### ISSUE TITLE
Content: copyedits

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1002]
- [x] a typo in the glossary entry for “Abandoned Mine Lands Fee” - the glossary currently reads “Abandoned Mind Land Fee”
- [x] On the Data Downloads page, for the Federal revenue by company "Download full dataset" file, in the actual Excel file the heading in column D (see screenshot below) that currently reads "Sum of Sum Of Revenue" should be changed to "CY2013 Revenues." 
- [x] “Role of State Governments” heading in the "State Laws and Regulations” section, the bullet titled “Enforce regulations and rules” needs a tweak. The bullet currently reads: "States with surface mining operations have agencies devoted to mitigating the environmental impact of such activities and restoring surface mine lands after mining operations are complete” .The way this sentence is worded implies that the state agency actually engages in restoring/reclaiming the land, which is not the case. To be clear, this sentence should be re-worded to something like “ and ensuring that companies adequately restore surface mine lands”
- [x] Portal states 567 Indian Tribes, the BIA website states that there are 566 tribes, and I just spoke with their PR officer who confirmed that the correct number is 566 pending the outcome of the Pamunkey appeal.

* From ONRR feedback

**Comment by coreycaitlin** [comment]
Once PR #1009 is merged, we can close this.
