### ISSUE TITLE
Main nav: consider simplifying "ABOUT USEITI" to "ABOUT"

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1012]
@meiqimichelle, @rtwell is trying to convince me that the top nav for this section should read simply, "ABOUT", and he is a very persuasive soul.

What do you think?
I wish we had time to test.

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/11659938/4ecb7560-9d90-11e5-8134-98ea748b8aa7.png)

## OR ##

![image](https://cloud.githubusercontent.com/assets/9259185/11659967/704252cc-9d90-11e5-8c81-da1780ecac96.png)

**Comment by meiqimichelle** [comment]
We did test it :) 'About' confused people as they weren't sure if it was about the data or about natural resources. 'About USEITI' was spot-on; people knew that that section was about the organization/process rather than site content.

**Comment by ericronne** [comment]
Ah. I must've forgotten :)
