### ISSUE TITLE
Documentation: All Lands Production > Coal refuse recovery data

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1020]
@Isabelle1512 @mentastc 

For all lands coal, each year there are entries that have a `Mine State` value of `Refuse Recovery`. [Example in the data here](https://github.com/18F/doi-extractives-data/blob/dev/data/_input/eia/commodity/coal-2004.tsv#L1824). Do you know what I should do with this data? Currently I'm filtering it out, but it should probably be visible.

for personal reference –>> [code that needs to be changed](https://github.com/18F/doi-extractives-data/blob/dev/data/bin/group-all-production.js#L243)

**Comment by Isabelle1512** [comment]
@gemfarmer @mentastc : I remember this came up when we were picking the counties way back when. I think at this stage to match the refuse recovery counties/mines to states would take a lot of work. If I remember correctly, refuse recovery is going back to old mines and successfully producing additional coal. For the Dec 11 stop date, I would suggest we leave these fields/data out, but note the data doesn't include refuse recovery for the time being.

**Comment by gemfarmer** [comment]
@Isabelle1512 that sounds reasonable. The data has the a `Mine County` column, but because the `Refuse Recovery is substituted for the `Mine State`, you would have to determine the state based on address. Either a lot of manual work or not so friendly parsing.

**Comment by meiqimichelle** [comment]
Reassigning to me to make a note in the documentation/content that we're not including that category.

**Comment by gemfarmer** [comment]
Not done, but not an important issue for now.

Taking out of sprint.

**Comment by meiqimichelle** [comment]
Added to note to data catalog for all-lands production. Closing!
