### ISSUE TITLE
Onshore federal production documentation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1024]
@mentastc It looks like we only have documentation for offshore federal production. See:
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/downloads/federal-production/

I see a heading for 'offshore data dictionary' but nothing for onshore. Or is that info for both onshore and offshore?

**Comment by mentastc** [comment]
I would actually change it to data dictionary since FIPS Codes are onshore, my bad

**Comment by meiqimichelle** [comment]
Ah, ok, got it! Easy fix. ON IT. Thank you!

**Comment by meiqimichelle** [comment]
Done with #1038 merges.
