### ISSUE TITLE
All Lands Production Documentation

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1028]
Add a documentation page, using [federal production](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/downloads/federal-production/) as a guide

**Comment by meiqimichelle** [comment]
We weren't planning on writing documentation for datasets that aren't ours. But, you make a good point -- maybe we should have things like scope and more details on how we're pulling the data, even for our non-ONRR/DOI data. This can wait till after launch -- what do you think?

**Comment by meiqimichelle** [comment]
OBE
