### ISSUE TITLE
Graphic Production: Home page explore callout charts

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1030]

**Comment by ericronne** [comment]
Here's how the revenues map might work if we changed the scale. Advantage is that most users should be able to differentiate between colors for all of the states.

NOTE: I don't know which states are zero and which are non-reporting, so some of this coloring is wrong. If we want to go with this approach, i'll need that info. If not, we can just screen grab the map on [this page] (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/federal-revenue-by-location/).

![image](https://cloud.githubusercontent.com/assets/9259185/11729266/0967146e-9f54-11e5-9676-947ac5bc4ab9.png)

**Comment by meiqimichelle** [comment]
Dupe. Closing in favor of #1056.
