### ISSUE TITLE
Visual Tweak (not a bug!): Make all select menus outline medium/light gray

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1031]
Currently dark gray (which matches the design), let's lighten a bit to #CCCCCC thx!...

![image](https://cloud.githubusercontent.com/assets/9259185/11693053/4cd4d03e-9e68-11e5-9b45-7706f5a6c299.png)

## change to ... ##
![image](https://cloud.githubusercontent.com/assets/9259185/11693105/a38bbc80-9e68-11e5-8e40-6cc37b453852.png)

**Comment by meiqimichelle** [comment]
OBE
