### ISSUE TITLE
Explore > Federal Production: show regions that have withheld

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1032]
Question from @mentastc:

For Federal production, would it be possible to show the regions and subregions (as bars) that have withheld data? 

For example, in [this view](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/federal-production/#product=Coal+(tons)&year=2013), there are a few states that have withheld data that aren't shown in the chart area. Could they be listed with a `(Withheld)` production value?

**Comment by meiqimichelle** [comment]
Dupe. Closing in favor of #935 .
