### ISSUE TITLE
Explore > all intro sentences: make underlined terms clickable

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1047]
Right now, our underlined terms that switch out depending on our selection look like they should be clickable, and if I remember right, we intended them to be. When a user clicks on a term, I believe we decided that the filter modal should open.

<img width="713" alt="screenshot 2015-12-09 20 52 54" src="https://cloud.githubusercontent.com/assets/4827522/11706564/018dbaf6-9eb7-11e5-9137-77a6ca6744b4.png">

**Comment by meiqimichelle** [comment]
For now, perhaps we remove the indication that these are clickable and add a toggle/focus later.

**Comment by gemfarmer** [comment]
Opened this issue #1134 to fix remaining issues
