### ISSUE TITLE
One more tax reporting company

### ISSUE THREAD

**Issue by Isabelle1512** [18F/doi-extractives-data#1048]
We got an update from statoil regarding their tax reporting. The number of companies that reported corporate income taxes is now 12, not 11. The total they reported is $0, so the total $ will not change. There are likely a couple of places on this site where micro copy changes will be needed - the "coverage or scope images," any time we say 11 companies reported taxes, etc. We will also need an updated Excel file for download for the reporting and reconciliation data, and updated Exec Sum and Appendix for download. I'll share with Corey via Slack today. I'm hoping Corey can help make sure this last minute change gets reflected throughout. Good news is one more company reported taxes. @coreycaitlin thanks in advance!

**Comment by meiqimichelle** [comment]
Also cc @ericronne because the 'egg' graphic with the 'total universe' number changes from 11 companies reporting taxes to 12.

**Comment by ericronne** [comment]
the universe is expanding.

**Comment by meiqimichelle** [comment]
Truth. Always.
