### ISSUE TITLE
Text-edit suggestion: use "Explore Data" in bread crumb, rather than "Explore"

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1055]
@coreycaitlin  @meiqimichelle?

my bad here, thinking it might be better to use the full section title, for consistency.
probably no big usability hit with it as is, tho.

**Comment by coreycaitlin** [comment]
I can probably tackle this as I keep reviewing this section.

**Comment by meiqimichelle** [comment]
Note: should be sentence case to match how it works breadcrumbs. "Explore data"

**Comment by meiqimichelle** [comment]
Done with #1102
