### ISSUE TITLE
Graphic Production: Home > Explore data intro charts

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1056]
Due to time constraints, these need to be static images for our initial launch.

I'll generate these, based on my designs from #743

**Comment by ericronne** [comment]
@meiqimichelle if these look good, you can use [these here pngs] (https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaVmNXbkxkYlRrejg&usp=sharing) ...

![home - explore callout - revenue copy](https://cloud.githubusercontent.com/assets/9259185/11734032/2a702676-9f79-11e5-8749-1ba10831aaef.png)

![02-home - explore callout - production](https://cloud.githubusercontent.com/assets/9259185/11733678/964a7076-9f75-11e5-8533-ad2ba3a872e8.png)

![03-home - explore callout - impact](https://cloud.githubusercontent.com/assets/9259185/11733677/9649e1f6-9f75-11e5-84cf-934991267f5e.png)

**Comment by meiqimichelle** [comment]
Woo! Moving to code. Closing.
