### ISSUE TITLE
Explore > remove pennies

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1059]
We removed rounding. But, we don't need pennies. We can round to the nearest dollar.

**Comment by usEITI** [comment]
👍

On Thu, Dec 10, 2015 at 3:40 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> We removed rounding. But, we don't need pennies. We can round to the
> nearest dollar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1059>.
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
@gemfarmer Is this one done with #1306 ?

**Comment by gemfarmer** [comment]
Yes!
