### ISSUE TITLE
Explore > all-lands production > renewables

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1060]
Totals seem awfully low for renewables data. Are these perhaps in the billions of kilowatt hours? Check with original data.

/cc @gemfarmer

**Comment by gemfarmer** [comment]
Yup. You are right. Good catch. They should be a scaled by a million. the numbers are right, but the units are supposed to be Thousand Megawatt Hours not Kilawatt hours. I'll make it Mwh and scale the numbers by 1000
