### ISSUE TITLE
Explore > %/$ switcher broken in FFx

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1072]
<img width="869" alt="screenshot 2015-12-10 19 02 35" src="https://cloud.githubusercontent.com/assets/4827522/11734113/225d6398-9f71-11e5-9078-b7e6a392dca3.png">

/cc @gemfarmer @shawnbot

**Comment by gemfarmer** [comment]
Lol that looks terrible. Fortunately this looks like it is exclusively a style fix. I ran it in firefox and didn't see any funcitonality issues. @meiqimichelle are you seeing functionality issues?

**Comment by meiqimichelle** [comment]
Ha, I didn't try, honestly -- I saw the styles and ran. If you're getting functionality, then we're good there.

**Comment by gemfarmer** [comment]
Ok! Even so, it is pretty nasty!
