### ISSUE TITLE
Visual Design: Top-of-page images for How It Works and Explore landing pp

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1081]
@meiqimichelle does this work for explore for now?

![image](https://cloud.githubusercontent.com/assets/9259185/11746544/35b0449c-9fe4-11e5-9430-9631d79de082.png)

**Comment by mentastc** [comment]
Is there any way to use the on planning area maps if we say this and shade it this way.... The eastern gulf actually doesn't have any production, and very little revenue but is shaded the dark color... I guess I could be ok with it, I'll wait and see ehat others on the theam think.

**Comment by ericronne** [comment]
Yes, good catch @mentastc, i'll merge the offshore subregions

**Comment by ericronne** [comment]
Revised @mentastc & @meiqimichelle ...
![image](https://cloud.githubusercontent.com/assets/9259185/11750676/2ea417b2-9ffa-11e5-92cf-68490ae86905.png)

**Comment by ericronne** [comment]
[Here's the png] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaZG05Zkd1WmpXaEU/view?usp=sharing)

**Comment by ericronne** [comment]
@meiqimichelle ^^

**Comment by ericronne** [comment]
@meiqimichelle et al, notion for the how it works top-of-page callout.
More lorem ipsum, sorry @coreycaitlin! ...

![image](https://cloud.githubusercontent.com/assets/9259185/11752373/d61aac2c-a004-11e5-892c-1da7acbf6ad6.png)

**Comment by ericronne** [comment]
@meiqimichelle here's a [png for that] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaUDBIZEs2al93SWM/view?usp=sharing), if copy changes, i'll tweak

![image](https://cloud.githubusercontent.com/assets/9259185/11752831/4e753366-a007-11e5-94fc-599cfea29fa1.png)

**Comment by meiqimichelle** [comment]
This will be done with #1094 merges. Closing.
