### ISSUE TITLE
Explore > All Lands Production: Pacific/Alaska region

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1098]
* [ ] `Pacific alaska` region needs to display data in bar chart and/OR
* [ ] needs to be clickable and display on map
* [ ] update TopoJSON to match #1108

@shawnbot I closed the PR ( #963 ) and put the remaining issues here

**Comment by meiqimichelle** [comment]
Overtaken by events. We restructured the way the explore data sections look and are coded, so this is no longer relevant.
