### ISSUE TITLE
Add more terms to the glossary

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1127]
Splitting this off from #908. Terms to add:

More words to add:

- [x] Independent Administrator (should be able to pull from Exec Summ)
- [ ] ~~ad valorem~~
- [x] GDP (see p. 61 of the Executive Summary)
- [x] locatable?
- [x] Fiscal year

From @gemfarmer:

Federal Production and All Lands production have some units that should be defined for a variety of products.

* [x] tons (also short tons)
* [x] metric tons
* [x] barrels (any certain number of barrels e.g. bbl, thousand barrels could fall under this)
* [ ] ~~cubic feet (will be either Mcf or MMcf. thousand and million, respectively)~~
* [x] megawatt hours (Mwh)
* [ ] ~~gallons (any variation on)? too basic?~~
* [ ] ~~pounds? too basic?~~
* [ ] ~~tickets (to measure quartz crystal)~~

**Comment by meiqimichelle** [comment]
re: the units, are we defining other units in the glossary? We could define those sorts of things in data documentation instead.

**Comment by gemfarmer** [comment]
@meiqimichelle Units seem like perfect a candidate for the glossary. Especially for the abbreviated ones. I could see someone wanting to quickly reference what a `Mwh` or `bbl` without having to check out and sift through all the documentation. 

That being said, I think it should be in the data documentation as well.

**Comment by coreycaitlin** [comment]
For "locatable minerals," most definitions are pretty circular, but even a slightly circular version might be better than nothing. @meiqimichelle, how's this?

> Locatable minerals are minerals that may be “located” and obtained by filing a mining claim. Locatable minerals include gold, silver, copper, lead, and many other metallic and nonmetallic minerals.

**Comment by meiqimichelle** [comment]
@coreycaitlin That makes sense to me, and I feel like it explains the point. I don't mind that its is semi-circular ;)

@gemfarmer yeah, good point

**Comment by coreycaitlin** [comment]
Closing this out. Let's create a new issue if we come up with more terms that need defining.
