### ISSUE TITLE
Bug: Explore > underline toggles not focusing

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1134]

**Comment by meiqimichelle** [comment]
The latest here is that @ericronne suggests updating the underline toggles to be *not* toggles, and have no underline, as per:

![image](https://cloud.githubusercontent.com/assets/9259185/12890492/7f361216-ce49-11e5-9771-eb2d5a9c6c52.png)

**Comment by meiqimichelle** [comment]
For reference, there is some discussion on this change in #1243 .

**Comment by ericronne** [comment]
and #1253 (where i noted three options)

**Comment by meiqimichelle** [comment]
@ericronne I assumed that option C of the choices in #1253 was 'chosen', I guess because of the image provided. Is that not the case? Do we still need to decide which one Brian should implement?

**Comment by ericronne** [comment]
There was no discussion, so 'chosen' means 'eric preferred this.'
If y'all dig, cool. Implement and test!
