### ISSUE TITLE
Content: Find home for "fair market value" sidebars

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1165]
Moving this out from #905: On p.41 of the Executive Summary, see coal lease sales info and GAO report. These two sidebars don't fit neatly on any page of the website. They might make the most sense on the coal diving graphic, but they fall outside of the main narrative and don't quite belong in the "fun fact" sidebar box.

**Comment by meiqimichelle** [comment]
@coreycaitlin is this still relevant?

**Comment by coreycaitlin** [comment]
Let's try putting this in the current `Did you know?` sidebar, and moving the current facts in that space to the intro of the page. The link can go in the "learn more" box at the bottom.
