### ISSUE TITLE
Content: Schedule C info

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1167]
Moved over from #905: p.74 of the Executive Summary includes bea schedule c info; where does this belong on the site?

**Comment by meiqimichelle** [comment]
@coreycaitlin is this still relevant?

**Comment by coreycaitlin** [comment]
This should go two places:

1. In a glossary item for `GDP`
2. In the data documentation for the BEA dataset

**Comment by meiqimichelle** [comment]
Closed with #2089.
