### ISSUE TITLE
Explore data microcopy: Lands or waters

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1168]
For the sentences that reflect filter selections, it would be nice if they could reflect whether the selected region is land or water. Examples:

<img width="468" alt="screen shot 2015-12-21 at 3 57 02 pm" src="https://cloud.githubusercontent.com/assets/1450354/11944524/b2768bc0-a7fb-11e5-85f3-4fff588882b6.png">

...should read "Revenue from all commodities on federal lands in Kansas (2013)"

<img width="443" alt="screen shot 2015-12-21 at 3 57 18 pm" src="https://cloud.githubusercontent.com/assets/1450354/11944525/b437929c-a7fb-11e5-8f8a-d396c7d6e3e4.png">

...should read something like "Revenue from all commodities on federal waters in the Atlantic (2013)"

The "waters" version may need more revising to get the variables right.

**Comment by meiqimichelle** [comment]
Overtaken by events. We've completely restructured the look and code of the explore data pages.
