### ISSUE TITLE
Add pagination to curated search

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1172]
Currently, we're arbitrarily cutting off the number of [search results](https://useiti.doi.gov/search-results/?q=oil) since we don't have pagination. We should fix this.

**Comment by gemfarmer** [comment]
This will likely mean making changes to the [search.js](https://github.com/18F/doi-extractives-data/blob/dev/js/components/search.js) file to limit the number of pages shown at a given time. I would suggest limiting the display to 10 results/page.
