### ISSUE TITLE
Content: curated search edit

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1173]
From feedback:

a document listed as this:
`DOI, Budget Justifications and Performance Information Fiscal Year 2016`
is only OSMRE's , not all DOI

**Comment by meiqimichelle** [comment]
@coreycaitlin I'm sorry, I did not document this well 😬 Any chance you know whether this is still relevant or not? Thank you!

**Comment by coreycaitlin** [comment]
Fixed it! We can close this issue as soon as #1827 is merged.

**Comment by meiqimichelle** [comment]
Closed with #1827
