### ISSUE TITLE
Design: Update favicon

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1176]
*note: click the images to see them at actual size, github enlarges them*

The current favicon uses the EITI "E" ...
![image](https://cloud.githubusercontent.com/assets/9259185/12056161/4d00385e-aef9-11e5-8c80-751adf00cca2.png)

That's definitely a viable option. Another option is to use one of the resource icons, as seen below. Oil seems an obvious choice, given its dominance. Thoughts, @meiqimichelle?
![image](https://cloud.githubusercontent.com/assets/9259185/12056242/e9126762-aef9-11e5-87e3-edfbc3ada321.png)

**Comment by meiqimichelle** [comment]
I'm partial to the "E" since it doesn't give preference to one resource over any other. But, reinforcing the point of the site (extractives) is also good. I don't have strong feelings -- I think we should show this around to non-project folks and see how they react.

**Comment by gemfarmer** [comment]
The icon representing the USEITI site on mobile browsers is a generic 'U'. I'm not sure if this is controlled by the favicon or by other means, but is worth looking into.

**Comment by meiqimichelle** [comment]
Following up on this:

@ericronne did you still want to explore updating the favicon?

Either way, we likely still need to create different sized favicons for various browsers and devices and link those properly in the `<head>` so that they display correctly.

**Comment by ericronne** [comment]
I don't mind a blue E, like i created for slack (![image](https://cloud.githubusercontent.com/assets/9259185/17065559/185bed0e-5008-11e6-9c1e-2b662eb5ccc2.png)), but technically that breaks the rules (since the E in our logo is black)

For now, bigger fish to fry.
