### ISSUE TITLE
Update and confirm art attribution list

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1177]
I'm updating this list and adding links ...

ICONS

[Airplane] (https://thenounproject.com/term/airplane/75353/) by Katie Wright from The Noun Project 
[Book] (https://thenounproject.com/term/book/8372/) by Danilo Gusmão Silveira from The Noun Project 
[Coal] (https://thenounproject.com/term/coal-trolley/13384/) Trolley by David Chapman from The Noun Project 
[Dam] (https://thenounproject.com/term/dam/69333/) by iconsmind from The Noun Project 
[Gas] (https://thenounproject.com/term/flame/57314/) by the2ne from The Noun Project 
Geothermal by Michelle Hertzfeld
[Hospital] (https://thenounproject.com/search/?q=hospital&creator=438738&i=69829) by iconmind from The Noun Project 
[Microphone] (https://thenounproject.com/search/?q=microphone&creator=186508&i=22278) by matthew hall from The Noun Project 
[Mountain] (https://thenounproject.com/search/?q=mountain&creator=276876&i=31123) by Chris Evans from The Noun Project 
[Oil Rig] (https://thenounproject.com/search/?q=oil&creator=318968&i=42474) by hunotika from The Noun Project 
[More] (https://thenounproject.com/search/?q=more&creator=15340&i=8557) by Jardson A. from The Noun Project 
[school] (https://thenounproject.com/search/?q=school&creator=21070&i=80797) by iconoci from The Noun Project 
[Swamp] (https://thenounproject.com/search/?q=swamp&creator=481804&i=75357) by Katie Wright from The Noun Project 
[Swings] (https://thenounproject.com/search/?q=swings&creator=16899&i=37924) by Rafael Farias Leão from The Noun Project 
[Wheat] (https://thenounproject.com/search/?q=wheat&creator=40467&i=17766) by Andrea Caldarelli from The Noun Project 
[Wind Turbine] (https://thenounproject.com/search/?q=turbine&creator=438738&i=68926) by iconsmind from The Noun Project 
[Gold Bullion] (https://thenounproject.com/search/?q=gold+bars&i=229933) by niedzwiedz from The Noun Project
[Excavator] (https://thenounproject.com/search/?q=excavation&i=60617) by Bruno Gatjens Gonzalez from The Noun Project
[Fish] (https://thenounproject.com/search/?q=fish&i=153358) by Mario Bieh from The Noun Project

#### @meiqimichelle Can't find this truck, so i think it may be a dramatically modified illustration (which thus needs no attribution) ...
![image](https://cloud.githubusercontent.com/assets/9259185/12068247/60c87776-afcf-11e5-8d73-c332a294c5aa.png)

#### @meiqimichelle What is this image? ...
Buildings by Stefan Parnarov from The Noun Project (??)

    IMAGES

    "Alaskan Pipeline" by U.S. Geological Survey.
    Available: https://www.flickr.com/photos/usgeologicalsurvey/16204180932

**Comment by meiqimichelle** [comment]
@ericronne It is the door to another dimension!
https://thenounproject.com/search/?q=Buildings&creator=31590&i=47227

**Comment by meiqimichelle** [comment]
Ok, I made these changes [here](https://github.com/18F/doi-extractives-data/pull/1197/files). We can merge that PR and close this issue if all looks good to you!

**Comment by ericronne** [comment]
Cool. Still stumped re the truck. It's a stump truck. Otherwise we can close.

**Comment by meiqimichelle** [comment]
Ah well! Merged the rest and closing.
