### ISSUE TITLE
Create research assets for upcoming work

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1178]
- [x] email templates: on the share drive [here](https://docs.google.com/document/d/1eNQzLYISPSdPmCZXb-GfV-QdCyFsuUqsZXsE9zPhmeA/edit)
- [x] spreadsheet for tracking contacts: on the share drive [here](https://docs.google.com/spreadsheets/d/1sbtwDMnic3EY9OFVOxPIQAbahlsrpH5NRJri8wgC9Yw/edit)

/cc @coreycaitlin

**Comment by meiqimichelle** [comment]
Reassigning to @coreycaitlin for review.

**Comment by coreycaitlin** [comment]
:+1: looks good! I left minor edits on the email templates, but nothing major.

**Comment by meiqimichelle** [comment]
Yay!
