### ISSUE TITLE
Make sure google analytics is doing what it is supposed to

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1181]
Or, consider another analytics source (but $$$)

**Comment by usEITI** [comment]
I would like to test what google analytics is telling us now after all the
urls have been revised and are now more systematic.

On Thu, Dec 31, 2015 at 2:33 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> Or, consider another analytics source (but $$$)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1181>.
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
Overtaken by events.
