### ISSUE TITLE
Research plan :D

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1182]
We need a plan for our next bit o' research. It will live on our [research branch here](https://github.com/18F/doi-extractives-data/tree/research/research/sprint-hautyhagfish).

**Comment by meiqimichelle** [comment]
This is going to take a bit of time because we should review all the research that we've done up till now and write up a summary as @coreycaitlin suggested in #1188. Corey, perhaps we should join forces there.

**Comment by coreycaitlin** [comment]
Sounds good! I'm hoping to tackle this summary today/tomorrow.

**Comment by coreycaitlin** [comment]
And I created an empty file for us to work in!

**Comment by meiqimichelle** [comment]
Ok! There's a summary [here](https://github.com/18F/doi-extractives-data/blob/research/research/summary-jan2016.md), a research plan [here](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-hautyhagfish/sprint-hautyhagfish_interview-script.md), and a draft interview script [here](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-hautyhagfish/sprint-hautyhagfish_interview-script.md). Sending over to @coreycaitlin for review and comments (in particular the interview script -- there's some notes in that doc).

**Comment by usEITI** [comment]
A comment on the following statement:

"One of the remaining sticky wickets to international EITI approval of the
USEITI report is around reconciliation data."

The concern expressed is tax reporting by Companies,  the low level of
companies that reported is 12 of 41 companies and that 5 of those 12
authorized the IRS to release their tax payment to the IA for reconciling.

There is not concern revolving around the non-tax revenue reporting and
subsequent reconciliation.

On Wed, Jan 13, 2016 at 12:45 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> Ok! There's a summary here
> <https://github.com/18F/doi-extractives-data/blob/research/research/summary-jan2016.md>,
> a research plan here
> <https://github.com/18F/doi-extractives-data/blob/research/research/sprint-hautyhagfish/sprint-hautyhagfish_interview-script.md>,
> and a draft interview script here
> <https://github.com/18F/doi-extractives-data/blob/research/research/sprint-hautyhagfish/sprint-hautyhagfish_interview-script.md>.
> Sending over to @coreycaitlin <https://github.com/coreycaitlin> for
> review and comments (in particular the interview script -- there's some
> notes in that doc).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1182#issuecomment-171411490>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by coreycaitlin** [comment]
I revised the research summary to clarify that the concern is about corporate tax reconciliation, not reconciliation in general. Closing this out now!
