### ISSUE TITLE
Content guide: natural resource

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1189]
The content guide states:

> **natural resource**, not commodity, resource, or sector
> 
> * the three broad categories of natural resources are: fossil fuels, renewables, and nonenergy minerals
> * nonenergy minerals may refer to hardrock mining or locatable hardrock mining for specificity

This doesn't seem entirely accurate, given that we wound up using "commodity" a number of places, especially in Explore Data. Is there a way we could clarify when/where to use each term?

**Comment by Isabelle1512** [comment]
@coreycaitlin: Hey Corey - good catch. In thinking about this, it felt like natural resource was the most intuitive. I know Michelle and I also discussed "extractive resource" at one point in time. Is this something we could test with users to make sure? If we do use "sector," I would think that would apply to oil and gas, mining, and renewables. In other words, there would be three sectors. If we do use commodity, I think it would be interchangeable with natural resource.

**Comment by meiqimichelle** [comment]
@coreycaitlin is this still relevant?

**Comment by coreycaitlin** [comment]
Just clarified in the content guide!
