### ISSUE TITLE
Content guide: header capitalization

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1190]
We seem to be using title case for h1s / page titles, but sentence case for h2 and below. How do folks feel about this? Leave as-is and update the content guide, or change all h1s to sentence case?

**Comment by meiqimichelle** [comment]
I think this is OBE -- @coreycaitlin , close this issue if you agree.

**Comment by coreycaitlin** [comment]
Added to [content guide](https://github.com/18F/doi-extractives-data/wiki/Content-guide#capitalization)
