### ISSUE TITLE
Wireframe: Explore > Reconciliation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1192]
![wire-reconciliation](https://cloud.githubusercontent.com/assets/4827522/12102761/56d85ee2-b2fa-11e5-9b3f-2b0bdc9551f2.png)

**Comment by meiqimichelle** [comment]
Version one: :heavy_check_mark: . Over to you @gemfarmer in #1193 to see how this feels with real data.

**Comment by Isabelle1512** [comment]
@meiqimichelle @gemfarmer : have no idea if it's helpful, but here is a screen shot of an interim dashboard that we made. I think the interesting thing is that for variances that exceeded the margin of variance for each revenue stream, you can click on them and read the explanation for why.

![image](https://cloud.githubusercontent.com/assets/15008153/12182914/52ce8bda-b559-11e5-8eb7-80648b68ba7d.png)

**Comment by gemfarmer** [comment]
@ericronne where is that wireframe that you made? Did you post it somewhere else?

**Comment by ericronne** [comment]
Hey folks! (esp @meiqimichelle @Isabelle1512 @gemfarmer)
Here are a few variants, based on chats w/Brian and my own meandering ruminations. Too much (or too lazy?) to explain here, but hopefully there's some fodder for fruitful discussion in these.

A few points:
- I may be totally missing the story these numbers are telling, but it seems to me that for the most part, company and gov reporting are fairly well matched. And thus the companies are being honest, in general. And users may visit this page with a fairly simple question in their mind: "Can i trust the numbers that companies report?" If that's the case, then a simple, aggregated bar chart like the one near the top of B may be enough to answer that question for them. Or not. I'm just guessing!
- I'm toying with a persistent $/% toggle filter, which i thought might be useful and fun. If it's deemed handy, it could be applied regardless of the selected option.
- If the percentage differences are meaningful and not too severely divergent, we thought it might be nice to show a split horizontal bar (see B). If negative variances are generally bad, we could even make them red, as i've done.

I guess i explained a little after all. :P Let's chat! Thx.


![explore-reconciliation-default-a](https://cloud.githubusercontent.com/assets/9259185/12211879/f1193076-b629-11e5-8f66-77885c340f4b.png)


![explore-reconciliation-default-b](https://cloud.githubusercontent.com/assets/9259185/12211878/f118febc-b629-11e5-8de9-3cdd674f83b9.png)


![explore-reconciliation-default-c](https://cloud.githubusercontent.com/assets/9259185/12211881/f11d3fc2-b629-11e5-8ec2-82acaa2f477c.png)


![explore-reconciliation-default-d](https://cloud.githubusercontent.com/assets/9259185/12211880/f11cea5e-b629-11e5-8c70-14426f8b32c3.png)

**Comment by gemfarmer** [comment]
@ericronne I think I like C/D the most. I like the stacked reported values. The horizontal bars are visually compelling, but I think they might be misleading.

**Comment by Isabelle1512** [comment]
@ericronne @meiqimichelle @gemfarmer :+1: Looking good! On the story these numbers are telling, I think you are right for most users. However, for super users, there is a next level. Here are two more questions you may want to answer: What's a "material" (one I should raise my eyebrows at) variance? For "material" variances, what caused them? The data for both of these questions exists and is already either on the site or in the Exec Sum Appendix. Maybe you just want to point there, or incorporate it here. Let me know if you want to chat more. Given the desire to show this at Lima, probably worth checking with ONRR about which questions the audience there is likely to have. I'm guessing it includes the two I've listed here. I know there's a tight timeline though. We can talk more if helpful.

**Comment by gemfarmer** [comment]
@Isabelle1512 Hmm is the data for what caused the variances only available in instances where reporting variances exceeded the Margin of Variance? Or for all cases?
This is also making me think that we should have a filter option for instances that exceeded the margin of variance. We could do this pretty easily using [the table on Margin of Variance on this page](http://localhost:4000/downloads/reconciliation/)

**Comment by Isabelle1512** [comment]
@gemfarmer : only where it exceeded the Margin of Variance. In those instances, the Independent Administrator went back to companies and the government to understand why the numbers didn't match. Where the variance is below the Margin of Variance, the difference wasn't considered meaningful enough to investigate further.

**Comment by ericronne** [comment]
@Isabelle1512 
Here's a new version, which (hopefully faithfully) incorporates thoughts from today's hangout with @gemfarmer and @meiqimichelle....
 - Revenue Type would be the only filter, since A - simple dollar amounts don't always tell the story as well as percentages do, and B - the user is able to deduce the variance in dollars anyway (by noting the difference between the "gov" and "co" amounts)
 - Top bar chart would change to reflect the Grand Total of whichever revenue type is selected in the filter (defaulting to all, as seen here)
 - Percentage variances deemed "material" are flagged in red, as the column header notes. We also hope to add a glossary link here.

![explore-reconciliation-default](https://cloud.githubusercontent.com/assets/9259185/12276802/6cf5a376-b93d-11e5-9775-50f60f663a2d.png)

**Comment by gemfarmer** [comment]
@ericronne  In `/federal-revenue-by-company` we have the heading repeated for each company. If we aren't doing that, was your vision to have one heading and make it sticky?

<img width="267" alt="screen shot 2016-01-14 at 5 10 54 pm" src="https://cloud.githubusercontent.com/assets/4803473/12341844/d72b30b2-bae1-11e5-85cc-1ac1b3f83867.png">

**Comment by ericronne** [comment]
We do? I don't see a repeated header. Can you show me a screen grab? I doubt it would be necessary here.
