### ISSUE TITLE
Simpler way of adding glossary links

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1198]
Right now, adding a link to the glossary requires pasting in the html: `<span class="term term-p" data-term="sample term" title="Click to define" tabindex="0">sample term<i class="icon-book"></i></span>`

Is there a way to make these simpler and more Markdown-flavored, ala footnotes in the case studies, where we use: `[^17]`?

One tricky thing about this is that the term doesn't always match the glossary term perfectly (singular v. plural, acronym v. full term, and so on), so we may need a way to connect them semi-manually.

**Comment by gemfarmer** [comment]
@coreycaitlin as far as I know there isn't an easy, pre-baked way to do this.

I could imagine something that would look more or less like this being useful:
`A lot of people are talking about [extractive industries](^extractive industries) right now...`
which would allow for variations like
`Every [extractive industry](^extractive industries) needs to comply with...`

**Comment by gemfarmer** [comment]
For my reference on making markdown extensions: 
* https://www.npmjs.com/package/markdown-flavor-maker

**Comment by gemfarmer** [comment]
@coreycaitlin I think the time has come for me to work on this. What are your thoughts about the proposed alternative syntaxes mentioned above.

In your opinion, is `{% include term.html id="extractive industries" val="extractive industry" %}` much worse than [extractive industry](^extractive industries) ?

**Comment by coreycaitlin** [comment]
Sorry, this didn't make sense until I clicked through to see it on GitHub!

Hm, that syntax is definitely trickier (I'd still need it stashed for copy-pasting), but slightly easier than straight HTML. I'm kind of ambivalent on whether it's easier _enough_ to be worth implementing.

**Comment by coreycaitlin** [comment]
I like that there's an easier default one for when the term does match up with the glossary, though. That seems compelling.

**Comment by gemfarmer** [comment]
With #1368 this syntax has changed. There are 4 different variations:
1. The displayed text is exactly the same as the glossary term text. The looks like this: 

`{{ "text" | term }}`

2. The displayed text is different than the glossary term. This looks like: 

`{{ "text" | term:"different text" }}`

3. The displayed text is exactly the same as the glossary term text, AND is directly followed by punctuation. This looks like:

`{{ "text" | term_end }}`.

4.  The displayed text is different than the glossary term, AND is directly followed by punctuation . This looks like: 

`{{ "text" | term_end:"different text" }}`

**Comment by meiqimichelle** [comment]
We did this! Closing.
