### ISSUE TITLE
Findability: Audit current terms against search trends

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1201]
Improve SEO for site. 
More to come.

**Comment by coreycaitlin** [comment]
One thing that needs to happen here: some background research on what terms people are actually looking for. Assigning to myself to tackle this.

**Comment by coreycaitlin** [comment]
Changing the title of this issue to be more specific about the research we need here.

**Comment by coreycaitlin** [comment]
We need more information about what terms people search for before we can explore which terms we should be working into our titles and headers. Terms to explore include:

- [] Oil and gas
- [] Coal
- [] Renewable energy
- [] Nonenergy minerals
- [] Natural resource policy
- [] Natural resource data
- [] Extractives industries
- [] Federal revenues
- [] Production
