### ISSUE TITLE
Page-specific metadata (for social media)

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1202]
Improve share-ability of site by adding page-specific meta data.
- unique image
- unique keywords???

**Comment by meiqimichelle** [comment]
For example, this would make it so an image of say, federal revenues shows up when that specific page is shared, rather than having the same image show up for the entire site.

**Comment by coreycaitlin** [comment]
Closing this issue — will reopen if this emerges as a user need.
