### ISSUE TITLE
Visual bugs: misc mobile

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1205]
### Global
 - [x] Lower the hamburger menu a few pixels, to align with the top of the USEITI logo
 - [x] This may require testing: Would like to see if moving the hamburger to the right margin would create any usability issues.
 - [x] In order to reduce the overall height of the menu, remove some vertical spacing from between hamburger menu items, like so...
![image](https://cloud.githubusercontent.com/assets/9259185/12248815/7a201f48-b881-11e5-8ff6-66b91562f4a6.png)
 - [x] Change the magnifying glass to blue, and indent it from the right end of the search box

### Home
 - [x] @gemfarmer maybe we should do a hangout to look at puzzle thru some home-page formatting, size normalizing, etc. (may impact other pp)
 - [ ] Bottom-of-page teaser link: is it possible to push the bottom line to the right so the text is centered (the caret pushes everything to the left)?

(Filter-related mobile issues noted in #1152)

**Comment by gemfarmer** [comment]
@ericronne would you want to rope this into a live-edit session? I'll send you a calendar invite

**Comment by gemfarmer** [comment]
>Bottom-of-page teaser link: is it possible to push the bottom line to the right so the text is centered (the caret pushes everything to the left)?

@ericronne what did you mean by this? Has it been fixed?

**Comment by meiqimichelle** [comment]
Moved remaining issue to #1283. Closing.
