### ISSUE TITLE
Bug: Explore > Empty parentheses

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1214]
On Explore > Exports, the parentheses that usually hold the year occasionally lose their contents. I also spotted this on Federal Revenue. This seems to happen mainly when I change _other_ filters several times.

![screen shot 2016-01-19 at 11 11 35 am](https://cloud.githubusercontent.com/assets/1450354/12429211/dfc71bb8-be9d-11e5-9de3-5757c0b1de5e.png)

![screen shot 2016-01-19 at 11 11 45 am](https://cloud.githubusercontent.com/assets/1450354/12429213/e36dd482-be9d-11e5-82ac-f75c0578e353.png)

![screen shot 2016-01-19 at 11 01 29 am](https://cloud.githubusercontent.com/assets/1450354/12429219/e6846e4c-be9d-11e5-8445-2a0359ed58bb.png)

**Comment by coreycaitlin** [comment]
This might show up only when I select a state/filter, then go back to the starting map using the back button.

**Comment by meiqimichelle** [comment]
Overtaken by events.
