### ISSUE TITLE
Bug(?): Jobs title reads "Percentage" even when the "#" option is selected in filter

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1215]
![image](https://cloud.githubusercontent.com/assets/9259185/12429576/b58e5204-beb0-11e5-8534-c9fa19ee6715.png)

**Comment by gemfarmer** [comment]
Yes, this is definitely a bug. I'll take a look!

**Comment by meiqimichelle** [comment]
Overtaken by events.
