### ISSUE TITLE
Formatting on Corporate Income Tax chart

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1230]
The formatting on [this chart](https://useiti.doi.gov/explore/corporate-income-tax/#fnref:2) needs to be updated.

UPDATE: after talking with @splatts, we are going to add [this link](https://www.irs.gov/uac/SOI-Tax-Stats-Returns-of-Active-Corporations-Table-1) to the footnotes, explaining where we got the data and why `Asphalt paving, roofing, other petroleum and coal products` was omitted (because it is out of scope for EITI)

![pasted image at 2016_01_27 01_38 pm](https://cloud.githubusercontent.com/assets/4803473/12624184/519a2d92-c4f3-11e5-951d-7758fd126e6e.png)

![pasted image at 2016_01_27 01_38 pm-1](https://cloud.githubusercontent.com/assets/4803473/12624185/519b48e4-c4f3-11e5-861f-bda57f4623b1.png)

**Comment by gemfarmer** [comment]
@mentastc on Slack: "I don't know why the second bold item doesn't have a second subset to make it whole, but that's not your problem. @isabelle @splatts any thoughts?"

**Comment by ericronne** [comment]
Just discovered this issue; a few suggestions...
 - Reduce the topmost green rule to 1-px thick
 - Right-align numbers
 - Possibly remove all $ signs except for top row
 - Center year labels in their columns
 - Perhaps make this table as wide as the text column

**Comment by gemfarmer** [comment]
Todo list of your suggestions:
 - [x] Reduce the topmost green rule to 1-px thick __this will apply site wide__
 - [ ] Right-align numbers
 - [ ] Possibly remove all $ signs except for top row
 - [ ] Center year labels in their columns
 - [ ] Perhaps make this table as wide as the text column

**Comment by gemfarmer** [comment]
@ericronne I think it is looking good!
![screen shot 2016-02-03 at 5 39 46 pm](https://cloud.githubusercontent.com/assets/4803473/12800769/2afcefd0-ca9d-11e5-8d10-bb3a81fec7e8.png)

**Comment by ericronne** [comment]
Way better, nice.

3 minor nits ('cuz me) ...
 - I would make the rule below "Industry" thick, like before. (The one between "Total receipts..." and the years was the one that needed thinning.)
 - The "Industry" label should be more prominent than "Mining" and "Petroleum..." (which previously were the light font weight). We can see how it looks when notched up to the next H level, or just boldface.
 - Did you try widening the whole table to match the text column? The "Petroleum..." label, eg, is getting pretty close to its '09 number

thx!

**Comment by gemfarmer** [comment]
More like this? I did widen the table to match the text column, btw.
<img width="599" alt="screen shot 2016-02-04 at 10 15 08 am" src="https://cloud.githubusercontent.com/assets/4803473/12821258/363ba07c-cb28-11e5-8d25-58ea4131cfd7.png">

**Comment by ericronne** [comment]
Sorry for the confusion, only meant for you to enlarge "Industry," not "Total receipts..." or the years

**Comment by gemfarmer** [comment]
But other than that it looks good?

**Comment by ericronne** [comment]
:+1: :+1:

**Comment by gemfarmer** [comment]
Closed with #1240
