### ISSUE TITLE
Update language on Explore > Exports

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1231]
The language on [Exports](https://useiti.doi.gov/explore/exports/) isn't quite correct. In the left column it states that:

`Because the data only lists the top 25 exports for each state, some states show as ‘no data’ on our map because extractive industries don't rank among their 25 top exports.`

It is actually drawing from 3 commodities, but only for the top 25 states (by export). @mentastc, I'm pretty sure this is actually the reason why we didn't want to total $ or %. The total for dollars would have been a total of the exports from the top 25 states, but would likely be interpreted as being a total for the *entire* US.

The language in the exploration heading, should also be changed to reflect the nature of this data.
`Exports from all commodities in the top 25 export states (2014)`? @coreycaitlin @meiqimichelle ideas for something better?

![screen shot 2016-01-27 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/4803473/12626549/d64078c0-c4fe-11e5-82b2-d75c736cbaae.png)

**Comment by coreycaitlin** [comment]
Wait what? This has thoroughly scrambled my brain. @gemfarmer: can we pair on this so I can get unconfused and come up with a clear solution?

**Comment by gemfarmer** [comment]
@coreycaitlin haha yes. yes we can pair on this – I think a short conversation would clarify things quite a bit.

**Comment by gemfarmer** [comment]
For my ref: https://www.census.gov/foreign-trade/statistics/state/data/index.html

**Comment by gemfarmer** [comment]
@coreycaitlin Well the good news is that I was wrong – there doesn't appear to be anything wrong with Exports! So no video chat needed :)
