### ISSUE TITLE
Visual bugs: Explore > reconciliation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1234]
- Add space above "Median payment…" header, to match similar pp, eg [this one] (https://useiti.doi.gov/explore/federal-revenue-by-company/)
- Center "payments reported by…" header

**Comment by gemfarmer** [comment]
@meiqimichelle as the design for this page has been changed, is this issue still relavent?

**Comment by meiqimichelle** [comment]
The `Add space above "Median payment…" header, to match similar pp, eg this one ` is still relavent,  but @ericronne may have caught that in a different issue by now. If yes, then we can close this one yays!

**Comment by meiqimichelle** [comment]
This should be done with #1261 .
