### ISSUE TITLE
Explore > Reconciliation: DNP / DNR

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1235]
These seem like unhelpful acronyms! But we should chat with Judy, et. al. to figure out the right words to put here.

**Comment by meiqimichelle** [comment]
Judy suggested that we leave them as-is for now (or, perhaps write out the acronym) and then test with users. @coreycaitlin correct me if I captured that inaccurately.

**Comment by meiqimichelle** [comment]
Also, assigning to @coreycaitlin to record next steps here (not sure where we landed).

**Comment by coreycaitlin** [comment]
I think we can just expand them for now — at least it'll be a little clearer, and didn't hear any major concerns about that solution. I'm not super clear on how to do that, though (I'm a little skittish about messing with the js and/or data).

**Comment by meiqimichelle** [comment]
Ok! We'll work that out -- and by we, I mean...reassigning to @gemfarmer :trollface: :P

**Comment by meiqimichelle** [comment]
To be specific -- this means that "DNP" would display as "did not participate" and "DNR" would display as "did not report". This is a sad design problem, too -- those words are long!

**Comment by usEITI** [comment]
correct

On Mon, Feb 1, 2016 at 1:11 PM, Michelle Hertzfeld <notifications@github.com
> wrote:

> Judy suggested that we leave them as-is for now (or, perhaps write out the
> acronym) and then test with users. @coreycaitlin
> <https://github.com/coreycaitlin> correct me if I captured that
> inaccurately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1235#issuecomment-178105045>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
Closed with #1244
