### ISSUE TITLE
Explore > Reconciliation: Add material variance amounts to the summary table

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1241]
We heard from the advisory group on Friday that the 1% bar in this summary chart registers as needlessly alarming, and could use some context to help people understand that 1% is an _unalarming_ number here.

![screen shot 2016-01-29 at 5 09 54 pm](https://cloud.githubusercontent.com/assets/1450354/12692378/036250a0-c6ab-11e5-8c72-ac876d34346d.png)

Also, material variances are confusing because they're different for each type of revenue (which is currently only captured in the glossary and data documentation).

Could we revise the summary chart so that each bar shows (maybe as a gray background bar?) what the material variance is for that revenue type?

Here's a list attempting to map this summary chart to the [table of MSG-approved material variances](https://useiti.doi.gov/downloads/reconciliation/):

- Rents : ONRR rents - 2%
- Other Revenue : ONRR other revenue - 3%
- Permit Fees : BLM permit fees - 3%
- Bonus & 1st Year Rental : BLM bonus and first year rentals - 2%
- Offshore Inspection Fees : Offshore inspection fees - 2%
- ONRR Civil Penalties : Civil penalties - 1%
- Bonus : ONRR bonuses - 2%
- Royalties : ONRR royalties - 1%
- Renewables : N/A
- AML Fees : OSMRE AML fees including audits and late charges - 2%
- OSMRE Civil Penalties : OSMRE civil penalties including late charges - 3%
- Corporate Income Tax : Taxes - 1%

**Comment by coreycaitlin** [comment]
Writing this issue also made clear that we need to edit the payment-type titles in that summary chart, so I'm assigning this to myself first.

**Comment by coreycaitlin** [comment]
First, could someone check that mapping? @meiqimichelle or @gemfarmer: does that seem correct?

**Comment by gemfarmer** [comment]
@coreycaitlin The mapping is at least consistent with what is on the downloads page and what I am using to flag Margin of Variance on the reconciliation page.

**Comment by gemfarmer** [comment]
@coreycaitlin I really like the idea of including the margin of variance threshold for context. Do you think
A: normalized bars:
![reconciliation](https://cloud.githubusercontent.com/assets/4803473/12722245/a0888bcc-c8c9-11e5-8018-0ebc379bf1a5.jpg)

**Comment by gemfarmer** [comment]
Or B: varied width bars? 
![recon-odd](https://cloud.githubusercontent.com/assets/4803473/12722305/e9481436-c8c9-11e5-9621-2d8fc522e44b.jpg)

**Comment by coreycaitlin** [comment]
I think I like B, but could be convinced otherwise?

**Comment by gemfarmer** [comment]
I think I do too, even if it isn't as visually tidy.

**Comment by ericronne** [comment]
B seems to communicate much more clearly to me, with labeling and such.

**Comment by usEITI** [comment]
Seems like B has the popular vote.  I like the context.

On Mon, Feb 1, 2016 at 10:55 AM, Brian Hedberg <notifications@github.com>
wrote:

> Or B: varied width bars?
> [image: recon-odd]
> <https://cloud.githubusercontent.com/assets/4803473/12722305/e9481436-c8c9-11e5-9621-2d8fc522e44b.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1241#issuecomment-178040357>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
So should I start on B then? @meiqimichelle

**Comment by meiqimichelle** [comment]
Yeah, let's do it @gemfarmer !

**Comment by coreycaitlin** [comment]
Revised names for the revenue types:

- ONRR rents - 2%
- ONRR other revenue - 3%
- BLM permit fees - 3%
- BLM bonuses & first year rentals - 2%
- Offshore inspection fees - 2%
- ONRR civil penalties - 1%
- ONRR bonuses - 2%
- ONRR royalties - 1%
- OSMRE AML fees - 2%
- OSMRE civil penalties - 3%
- Corporate Income Taxes - 1%

**Comment by coreycaitlin** [comment]
Alternate option! (After talking with @ericronne):

- Rents - 2%
- ONRR other revenue - 3%
- Permit fees - 3%
- BLM bonuses & first year rentals - 2%
- Offshore inspection fees - 2%
- ONRR civil penalties - 1%
- ONRR bonuses - 2%
- Royalties - 1%
- AML fees - 2%
- OSMRE civil penalties - 3%
- Corporate Income Taxes - 1%

This still disambiguates the confusing ones, but drops the org name from the ones that don't strictly need it to be clear (and of course the longer version is still in the Docs).

**Comment by ericronne** [comment]
Here's the mock i did this am, for reference, in case it's useful. Corey will supply final col header.

![image](https://cloud.githubusercontent.com/assets/9259185/12792292/c7512c16-ca70-11e5-9983-cfcc222d95d5.png)

**Comment by gemfarmer** [comment]
Closed with #1244
