### ISSUE TITLE
Explore > Reconciliation: Material variance floors

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1242]
In the reconciliation by company tables, there are some variances that are _over_ the material variance threshold, but the payments are _under_ the [variance floor](http://localhost:4000/downloads/reconciliation/). (I.e. ANKOR > Other > 60.8%) These probably shouldn't be ~~red~~ whatever color material variances are going to be.

**Comment by meiqimichelle** [comment]
How does this interact with the "17 material variances" ? As in -- we have too many things red, and scoping to this meaning will result in 17 red things? (or, whatever bold/indication we use instead of red. you get the idea ;) )

**Comment by gemfarmer** [comment]
@coreycaitlin do you know if the variance floor applies to companies or government? For an example of where this might matter, look at Peabody Energy Corporation > Permit Fees. Gov reports under the floor, company reports under.

**Comment by usEITI** [comment]
The variance is the difference between the two reported values, so it
applies to the difference.


Note there is a typo below on the website
https://useiti.doi.gov/downloads/reconciliation/

The MSG and the IA scoped out the potential causes of differences between
amounts reported by in-scope reporting companies and government entities
for each revenue stream included in the USEITI reconciliation process.

Three anticipates reasons for variance were:

Attributing payment information to different revenue streams
Recording a payment and a receipt of payment in different reporting periods
Reporting based on different sets of company payor entities
Based upon the type, magnitude, and likelihood of variances for in-scope
revenue streams, a variance percentage threshold and a variance floor
threshold were assigned to each revenue stream.

Variance percentage threshold: *If the variance amount when divided by the
amount reported by the government *was greater than the variance percentage
for that revenue stream, the IA considered the variance to exceed the
threshold, and then assessed whether the variance floor threshold applied.

Variance floor threshold: This was the minimum dollar threshold for a
variance and only applied if a variance exceeded the variance percentage
threshold. If the variance exceeded the variance percentage threshold and
exceeded the variance floor threshold, the IA performed further evaluation
of the variance.

On Wed, Feb 3, 2016 at 2:16 AM, Brian Hedberg <notifications@github.com>
wrote:

> @coreycaitlin <https://github.com/coreycaitlin> do you know if the
> variance floor applies to companies or government? For an example of where
> this might matter, look at Peabody Energy Corporation > Permit Fees. Gov
> reports under the floor, company reports under.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1242#issuecomment-179058895>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
Closed with #1244

**Comment by meiqimichelle** [comment]
@gemfarmer I don't see how this was closed. If it is truly closed, can we write an explanation of what we did here? Or why what we have displaying in the interaction is correct?

**Comment by gemfarmer** [comment]
@meiqimichelle Of course. I should have made sure that the values were consistent with the explanations that @coreycaitlin has been writing. 

As to how, [this method here](https://github.com/18F/doi-extractives-data/blob/dev/js/pages/reconciliation.js#L97) determines if the variance is material. I added a conditional to check if the value is greater than the floor for that particular revenue type.

**Comment by meiqimichelle** [comment]
Ah, got it! Thank you @gemfarmer . Who would be the right person to check and make sure everything is displaying as expected? (and then that person should close out this issue)

**Comment by gemfarmer** [comment]
@coreycaitlin would be. As part of #1233 she was going to validate them and replace my dummy footnotes with real ones.

**Comment by coreycaitlin** [comment]
Okay! Two material variances are missing the bold styling / footnotes:

- Ultra Resources Inc. > ONRR Royalties (1%): $1,086,317 was paid by Ultra Resources in 2012 and recorded in 2013; $47,724 was paid in 2013 and recorded in 2014.
- BP America > ONRR Rents (2%): $711,360 was paid by BP America in 2012 but recorded in 2013.

**Comment by coreycaitlin** [comment]
...also, we need a better explanation of the variance floors, so I'm going to try to figure out where to put that.

**Comment by gemfarmer** [comment]
I'm going to start looking into why those two weren't displayed. My guess is that it is because those two are exactly at the variance threshold.

**Comment by meiqimichelle** [comment]
@coreycaitlin I think the explanation itself will be taken care of in #1252 -- @ericronne 's design has a place for a glossary item on variance floor, and we're explicitly listing it in the new chart design. (tho we do need words for that -- I can take a first crack)

Re-assigning this to @gemfarmer for the remaining issue on why two of the footnotes are off.

**Comment by gemfarmer** [comment]
@meiqimichelle #1274 fixed the "two footnotes being off" issue. Is this good to close then?

**Comment by meiqimichelle** [comment]
Yep! WOOOO!
