### ISSUE TITLE
Bug: Explore > reconciliation doesn't keep filter summary sentence

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1245]
When you first open the filter on the reconciliation page, the summary sentence doesn't appear in the filter box. However, if you click on the underlined word, it opens the filter box and the sentence stays. I believe the expected interaction is that the sentence is always in the filter box.

<img width="1112" alt="screenshot 2016-02-03 23 00 25" src="https://cloud.githubusercontent.com/assets/4827522/12807161/035a477a-caca-11e5-8c85-be93bda92dc7.png">

<img width="1158" alt="screenshot 2016-02-03 23 00 32" src="https://cloud.githubusercontent.com/assets/4827522/12807164/075c5af2-caca-11e5-8b37-eb55bea7483c.png">

**Comment by gemfarmer** [comment]
@meiqimichelle this should be fixed with the new bug hunt branch >> https://federalist.18f.gov/preview/18F/doi-extractives-data/bh-bugs-2/explore/reconciliation/

**Comment by gemfarmer** [comment]
Update: this is currently not an issue on https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/reconciliation/

**Comment by meiqimichelle** [comment]
Huh. Ok, looks good to me! :tada:
