### ISSUE TITLE
Palette tweaks

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1247]
@gemfarmer A few minor adjustments to the colors, which will primarily impact the "hero" spaces atop the home page, and the landing pp for About, How it works, and Explore data...

 - [x] Update the blues:

   - $blue stays the same (#157bac)
   - [x] $light-blue (currently #e6f9ff): change to #e3f8ff
   - [x] $pale-blue (currently #f2fcff): change to #f0fcff
   - [x] $mid-blue (currently #c6e9ff): change to #c9eeff

 - [ ] Two other color issues:
   - [ ] $light-gray (#f7f7f7): are we using anywhere?
   - [x] $shock-green (#acb626): this should go away altogether. I see it in some icons at the bottom of diving graphics pp. (Those can all be changed to $blue.) Is it anywhere else that you know of?

thx!

**Comment by ericronne** [comment]
Visual reference...

![image](https://cloud.githubusercontent.com/assets/9259185/12827843/492d9342-cb47-11e5-9a68-7f93c4e6c5e6.png)

**Comment by gemfarmer** [comment]
@ericronne we are using $light-gray on the [how it works diving graphics pages](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/offshore-oil-gas/):
<img width="150" alt="screen shot 2016-02-04 at 2 23 02 pm" src="https://cloud.githubusercontent.com/assets/4803473/12828512/f07c8182-cb4a-11e5-9909-df57f937b625.png">

**Comment by gemfarmer** [comment]
There are some instances of $shock-green that are not styled with css, but exist as icons. Those will also need to be updated to truly rid the site of the color.
