### ISSUE TITLE
Top banner on mobile: should we keep the flag?

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1250]
Currently the flag and "official" text aren't included in the mobile view. Should we consider bringing it back, since it's our Seal of Approval? Could we put the other messages in the footer?

@meiqimichelle @gemfarmer

**Comment by meiqimichelle** [comment]
If we bring it back, can we keep the other note as well? I'm loath to move anything to the footer that we care about since so few people scroll that far.

**Comment by ericronne** [comment]
Do you loathe both of these options, loathy lady?

## A
![mobile banner option a](https://cloud.githubusercontent.com/assets/9259185/12851491/c2877bec-cbef-11e5-9071-2f02f012029a.png)

## B
![mobile banner option b](https://cloud.githubusercontent.com/assets/9259185/12851492/c289b9a2-cbef-11e5-9408-1d2e682eefbd.png)

**Comment by ericronne** [comment]
@meiqimichelle thoughts?
I like A a lot. Light years better than B, IMO.
Do we need to highlight what's new in a site that's basically 100% new?

**Comment by gemfarmer** [comment]
I like where this is going @ericronne. I also like A. Has the stamp of approval and is much cleaner.

**Comment by meiqimichelle** [comment]
@ericronne is this something that is still in play, or shall we close?

**Comment by ericronne** [comment]
It'd be nice to implement A and see how that tests, imo, if others concur and it's not too time consuming.

**Comment by coreycaitlin** [comment]
OBE
