### ISSUE TITLE
Glossary: clicking on item doesn't open definition

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1251]
When you click on a glossary icon, the glossary window opens, and filters the glossary definitions, but does not open that definition.

Previously the glossary did this, was this an active or an incidental change, @meiqimichelle ?

**Comment by meiqimichelle** [comment]
I think accidental :( It should load opened, as you suggest.

**Comment by meiqimichelle** [comment]
This came up in [usability testing](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-splashysunfish/sprint-splashysunfish_results.md). Moving up in the queue, since this is a lately-introduced bug anyways. Eep! :mans_shoe: :bug:
