### ISSUE TITLE
Refine: Explore > Reconciliation, summary chart

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1252]
Our summary chart did not test well with [usability test](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-splashysunfish/sprint-splashysunfish_results.md) participants. In particular, no one was able to figure out what we were trying to communicate with the material variances on the right of the intro chart.

- _[Referring to the summary bars] I guess this means that this is the direction of the discrepancy, but I don't really know._

- _So now I have a sense of what the percentages [in the chart] mean [after reading the intro paragraphs]. But what are these? [the 1%, 2%, 3%] They line up, so I guess these are tick marks -- it looks like -- I don’t know. [pause] I’m gonna start scrolling._

- _I’m not entirely sure what’s going on with the bar charts. This part is clear -- I get that the bar goes with the 1%, but these tick marks -- these are separate? A different column? Oh, wait. These are all one chart. Something about these threw me off. It wasn’t clear that those marks are part of the bar._

- _[Looking at the tick marks] I wonder why the threshold is considered different for different types?_

/cc @coreycaitlin

**Comment by ericronne** [comment]
We should discuss. I think the variance column header could go a ways toward explaining it. 

Super Special Favor Request: could we link to pages in issues? I often have trouble finding which branch i'm supposed to be viewing :/

**Comment by ericronne** [comment]
Quick copy tweak plus color addition ...

![image](https://cloud.githubusercontent.com/assets/9259185/12867482/b45a7c16-ccb4-11e5-86f8-792a19778499.png)

**Comment by meiqimichelle** [comment]
Yes, def. on the linking to a page! I think you found this one, but it is refers to [this page](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/reconciliation/#).

As for the quick tweak -- I'm not sure that will address the issue that people weren't understanding that the median payment discrepancies were "below" the theshold. They tended to read the chart as information in separate columns. Could we move what is now in column-header position to more like a subhead for the chart title? Maybe this will keep the eye focused on reading the lines as connected pieces of information.

 ie -->

**Median payment discrepancies by revenue type**
_material variance threshold blah blah and I'm smaller and sub-heady_

CHART CHART CHART as per the design above

**Comment by gemfarmer** [comment]
Could we have a key – basically just an example bar and material variance tick mark? It could exist below or to the right of the _subhead that @meiqimichelle is proposing_.

**Comment by ericronne** [comment]
Maybe, if we can't land on a solution where it's all sufficiently clear in the table itself. Here's a draft based on @meiqimichelle's notes...

![image](https://cloud.githubusercontent.com/assets/9259185/12890492/7f361216-ce49-11e5-9771-eb2d5a9c6c52.png)

**Comment by gemfarmer** [comment]
@ericronne @meiqimichelle Looks good, but I have a few Qs about the "material variance threshold" explanatory text:

- How will this work in mobile? There is barely enough room for the bar charts and tickmark
- Are we imaginging that explanatory text will always be on the first summary item?

**Comment by meiqimichelle** [comment]
that's for @ericronne -- can something be in that summary line that links it to the material variance tick mark without calling it out in the line?

**Comment by meiqimichelle** [comment]
ie, kinda like using color and/or bold from your previous design. or similar. or something. :)

**Comment by ericronne** [comment]
Yep mobile is a nut in need of cracking. We didn't plan on long labels like "BLM bonus & first year rentals" either. I smell a hangout. Tomoro am?

**Comment by gemfarmer** [comment]
I would take a crack at this around 10:30.

@ericronne @meiqimichelle

**Comment by gemfarmer** [comment]
@meiqimichelle @ericronne: 

@coreycaitlin and I just discussed what to do with the Reconciliation summary section and our thoughts are _roughly_ as follows:
* The summary section doesn't add clarity to a subject that is already a little unclear for most people.
* The story is that there is no story and the odd mix of precise bar charts and oddly-placed tick marks is confusing, even for people who understand the data to some degree.
* The hope for the summary section is that it could provide context and support the data that exists below it.
* Enter Margin of variance thresholds (Threshold/Floor) chart on /downloads/reconciliation. This chart provides meaningful context for what it takes for a margin of variance to become a material variance, broken down by revenue type.
* If this chart could become filterable by revenue type, it could have even more utility. Thoughts?

**Comment by gemfarmer** [comment]
Chart is here: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/downloads/reconciliation/

**Comment by meiqimichelle** [comment]
<img width="678" alt="screenshot 2016-02-09 12 02 13" src="https://cloud.githubusercontent.com/assets/4827522/12927369/1414f9ac-cf25-11e5-9482-d868216dc26e.png">

**Comment by meiqimichelle** [comment]
As per our discussion earlier -- @ericronne might take a crack at incorporating the above chart, and making info more contextual throughout the page (perhaps a drawer or modal that can provide more in-depth extra info than a glossary would).

In the meantime, I'll talk with Judy about using the current version as 'good enough for now and the Peru meeting.'

**Comment by ericronne** [comment]
@meiqimichelle @coreycaitlin @gemfarmer 

Sooo a couple notions which could maybe perhaps who knows work in conjunction with a version of the table posted above ...

### A - Simpler intro chart
Might the median chart might still be useful, if we just stripped out the variance floor references from it altogether? At a glance, a chart like the one below seems to be telling me the simple message which is a key point of the whole topic, namely: "You can trust the numbers on this site."...
![image](https://cloud.githubusercontent.com/assets/9259185/12992695/88102b94-d0db-11e5-8943-ecd5b50b1b4b.png)

### B - A friendly visual explanation of the process
An easily digested visualization along these lines (except better than this)...
![image](https://cloud.githubusercontent.com/assets/9259185/12992811/3774cfc2-d0dc-11e5-9918-3553cd3597e0.png)

**Comment by gemfarmer** [comment]
@ericronne I really like the flow chart idea. As much as we all like bar charts, I think this flow simplifies and clarifies things quite a bit.

In the above example, we could even use the different "Yes" instances as filters, where clicking on it would filter the company listing below to the set of instances that met that criteria.

**Comment by ericronne** [comment]
@gemfarmer <3 the filter notion!

**Comment by ericronne** [comment]
I'm not a huge fan of how big this chart is, but might be cool to let them re-sort by %, floor, or type.

![image](https://cloud.githubusercontent.com/assets/9259185/13014475/9ade8eb6-d179-11e5-85be-68c19addb193.png)

**Comment by meiqimichelle** [comment]
Talking to @usEITI right now -- how about we switch out the first intro chart for something like the simple version @ericronne has in the comment right above, and then also do a version non-interactive flow chart infographic kinda thing?

Would that work?

**Comment by ericronne** [comment]
wfm

**Comment by usEITI** [comment]
Where
Telecom - 1-877-984-1404 Passcode 2973393# (Leader Code:1923766#)
Greg Gould
Description
USEITI Implementation Subcommittee,



Telecom - 1-877-984-1404 Passcode 2973393# (Leader Code:1923766#)

On Tue, Feb 16, 2016 at 12:19 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> Talking to @usEITI <https://github.com/usEITI> right now -- how about we
> switch out the first intro chart for something like the simple version
> @ericronne <https://github.com/ericronne> has in the comment right above,
> and then also do a version non-interactive flow chart infographic kinda
> thing?
>
> Would that work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1252#issuecomment-184782425>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
@meiqimichelle I like the non-interactive flow chart as a good place to start on the rework

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer @coreycaitlin Thoughts on this??
(needs words, Corey :)

I've broken the paradigm re the chart header, but seemed necessary.
![explore - reconciliation](https://cloud.githubusercontent.com/assets/9259185/13094615/6efcb7cc-d4d1-11e5-87ca-20f771573688.png)

**Comment by meiqimichelle** [comment]
Splitting implementation into two issues, since this one is getting reeealllyyy big. Implementation of the simpler summary chart is now in #1278, and we can continue refining the flow chart here.

@ericronne , I think that flow chart looks really good! I'm not sure if I want to worry about what it would look like on mobile yet :-/ I think perhaps the next step needs to be me getting you real content, eh?

**Comment by ericronne** [comment]
Thx. And yep mobile is next nut to crack

**Comment by gemfarmer** [comment]
Thanks @meiqimichelle I was getting a little confused about where reconciliation was supposed to be going, but this clears it up! I'll get going on the new summary chart.

**Comment by ericronne** [comment]
Here's roughly how the flow chart might work in mobile…
![explore-reconciliation-mobile](https://cloud.githubusercontent.com/assets/9259185/13113810/5ae61f8c-d556-11e5-93da-3c0915806857.png)

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer @coreycaitlin ^^

**Comment by meiqimichelle** [comment]
Feedback from USEITI folks: want to make sure the content makes it clear that both sides of the flow really end in a "all good", just in different ways.

Also, more very good noises about the possibility of a flow chart, and focusing more on process and less on numbers.

**Comment by meiqimichelle** [comment]
First draft words for @ericronne --

**Left-side paragraph**

During the USEITI process, companies report payments to the government (such as rents, taxes, and royalties), and those reports are compared with government records of revenue received. This is to review U.S. accounting processes.

The 2015 report looked at calendar year data for 2013. The 45 companies invited to participate are listed here, along with a description of the reconciliation process, reported payments and reconciliation results for each revenue type.


**Flowchart**

H1: How are the numbers verified?

Intro: Every country that participates in <a>EITI</a> reconciles its data. An independent administrator compares company-reported payments (such as rents, taxes, and royalties) to government records of revenue received. Here's how it works.

Did the amount reported by the government differ from what was reported by the company?
--------------------------------------YES path---------------------------------------
Y: Is the percentage difference greater than the <a>variance percentage threshold</a>?
Y: Is the dollar amount of the discrepancy greater than the <a>variance floor threshold</a>?
Y: Then we have a <a>material variance</a> that warrants a second look, so the independent administrator reviews extra details about these transactions to understand what happened.

In the 2015 USEITI Report, out of the 555 transactions reviewed, the independent administrator identified and investigated only 17 material variances. It turned out that all of these were due to one of the following reasons, and were not significant errors:
* Differences in accounting systems. For example, some companies record transactions in their accounting systems differently than government does and so revenue categories (such as rents, taxes, and royalties) get lumped differently.
* Differences in accounting years. For example, companies and government sometimes run on different accounting years, resulting in payments getting recorded in different years.

--------------------------------------NO path---------------------------------------
If the amounts don't differ, then the transactions show that our accounting is correct and is no reason to further investigate. 

--------------------------------------BOTH end here with the 'so what' ?? ---------------------------------------
This means that our accounting systems in the United States are doing their jobs and we don't have issues with fees and taxes getting to where they're supposed to go.

**Comment by gemfarmer** [comment]
@ericronne @meiqimichelle were you expecting the flow chart to be an image or html?

**Comment by ericronne** [comment]
I pictured it as mostly html. Here's the revision @meiqimichelle @gemfarmer. This look pretty simple? ....

![explore - recon - desktop copy 2](https://cloud.githubusercontent.com/assets/9259185/13156495/5783bbcc-d648-11e5-8fc1-9aff88ae948e.png)

**Comment by meiqimichelle** [comment]
@gemfarmer I'm not sure, actually. I originally thought @ericronne wanted an image, but then we put in the glossary links. This would be an interesting HTML/CSS challenge, no? :smiling_imp:

**Comment by gemfarmer** [comment]
@meiqimichelle I keep missing these notifications. Yes, it would be an interesting challenge. Let's find a time next week.
