### ISSUE TITLE
Refine: Explore > Reconciliation, use of acronyms

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1253]
Almost everyone commented on the first line of data on the summary chart -- the fact that it says "ONRR" and they don't know what that is. It seems to put a bad taste in everyone's mouth.

- _Ummm -- the first place my eyes go is to the charts here, they draw me in, but I don’t understand what’s going on. I’m reading the title of the chart, Median …, I don’t really know what that means. Then I’m looking down at ONRR, and I don’t know what that means._

- _This would be really cool if this had one of those glossary plugins so I could hover and see what ONRR is. All the acronyms._

- _I think I don’t know what ONRR is so I think this is for insiders._

- _[Finds the filters] Oh! Filters! [YAY] Oh. [sad] [The only thing here is] these words I don't understand again._

With regard to this problem in the filters section, this is a problem on all site interactions, not just the ones on the reconciliation page.

- People do not like seeing words they don't understand or acronyms in the filter options.
  - _Let’s look at oil and gas [chooses that, sees the next drop-down appear]. Then -- NGL? Natural...gas….um….nevermind. [chooses something else]_

/cc @coreycaitlin

**Comment by meiqimichelle** [comment]
Related, we also had a lot of confusion on how to use the underlined words in the summary sentence in the filter area. Participants expected the underlined summary sentence words to open the glossary, likely because the dashed underline motif there is similar to the one we use for the glossary, and they didn't understand the revenue type and commodity words. It seemed like a hope for a lifeline on those difficult acronyms and words. At the very least, those underlined words need to close the filters (right now, you can click to open the filters but not click to close even though they still look clickable). That's a separate issue, but I'm copying it here because it informs the thoughts about how to deal with acronyms in the filters.

- _[Clicks Filter] Oh. [Pause] [Clicks revenue type drop-down]. Yeah, I don’t know what these are. but I could click on this to find out [tries to click on underlined word for definition, but it doesn’t do anything, participant looks deflated]._

**Comment by ericronne** [comment]
Yeah, looks like merely including or excluding the book icon isn't enough to indicate glossary vs. filter term. Also clicking on a filter word in the summary sentence doesn't put the focus on the corresponding filter widget, so clicking when the filter is open has no effect.

Options:
 - **A:** Simply remove the underscores from the summary sentences. The filter button is very prominent, so people are filtering.
 - **B:** Emphasize the filter words by changing to our link blue and losing that blue once the filter is open
 - **C:** Emphasize the filter words in another—non-link—manner. See below! :)

![image](https://cloud.githubusercontent.com/assets/9259185/12867432/30a52ec6-ccb3-11e5-98a2-e85346ebb996.png)

^^ This also reflects tweaks i've suggested over in #1243

**Comment by meiqimichelle** [comment]
This is done :tada:
