### ISSUE TITLE
Refine: Explore > Reconciliation, sort by location or industry?

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1255]
Searching by company name didn't resonate with usability test participants. Instead, they wanted to search by industry or location. This was either because they didn't know enough about the companies to know them by name, or because they were savvy enough to know that companies buy and sell each other a lot and often change names.

- _[Tries to search for a company] Oh gosh, I can't remember the name of the taconite companies [near me], and they keep renaming themselves anyways [implying that even if I did, searching by name wouldn’t be very useful]. It would be cool if I could search by industry, since I know there's an industry by me, but I can't find my personal interest here._

- _I also don’t know what these companies do. ["I don't know company names, but I know what's being mined near me"]_

- _Oh my gosh, this is [Company X]. They’re evil. They would keep changing names and buying other companies._

- _Oh! [finds the option to sort by tax] By taxes, does this mean taxes to federal? local? I want to know what's coming to my county, and if I'm getting the amount they should._

I know we don't have location data for the reconciliation dataset, and we don't have commodity, however -- don't the revenue types align with industry sometimes? Could we provide another filter that extrapolates industry from revenue type?

We probably don't have time to implement this right now, but it might be a good future feature.

/cc @mentastc @splatts @usEITI

**Comment by coreycaitlin** [comment]
I move to close this issue out — I think much of the state profile work we're doing solves the user interest here, and there's not much of a reconciliation story at the local level (though at some point if we have Federal Revenue by Company data that's more location-based, that might also be good).
