### ISSUE TITLE
Enhancement: data filters, people don't know how to close the filters

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1258]
People don't know how to close the filters. We might consider making the filters close if you click anywhere outside the blue area.

Potentially related, participants expected the underlined summary sentence words to open the glossary, likely because the dashed underline motif there is similar to the one we use for the glossary, and they didn't understand the revenue type and commodity words. It seemed like a hope for a lifeline on those difficult acronyms and words. At the very least, those underlined words need to close the filters as they were originally intended. Right now, you can click to open the filters but not click to close even though they still look clickable.

**Comment by ericronne** [comment]
Re summary sentences, i proposed options over in #1253 
C gets my vote

**Comment by meiqimichelle** [comment]
Overtaken by events.
