### ISSUE TITLE
Content: review how we talk about money throughout site

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1260]
Usability tests are showing that people don't understand the intracacies of where money is comine from and going to. For example, on the reconciliation page, people assume that $$ amount there mean payments, or how much the company is making. We need to review the entire site for how we're talking about these different things, and making clear that something is "Money paid to government from company because fee" or "Money redistributed to state from government for extraction" or whatever the situation is.

**Comment by meiqimichelle** [comment]
I think I made a related issue, that I just closed in favor of this one. The content from that issue:



Usability research participants weren't always clear on who was making the money. This is a problem common to many of our datasets.

_Ooo, they’re making so much money! [referring to the top entries on reconciliation, when really those numbers are amounts paid to government]_

**Comment by coreycaitlin** [comment]
Several ways we've worked to fix this on state pages:

> When companies want to extract natural resources on federal land, they pay fees depending on where they are in the process of using the land.

> In 2013, companies paid the federal government a total of $318,875,836 to extract natural resources on federal land (or lease federal land for that purpose).

We'll also build this into our usability testing plan to make sure this is working.

**Comment by coreycaitlin** [comment]
Closing this out for now! It's in the research plan, and we'll reopen if need be.
