### ISSUE TITLE
Content: Homepage, framing, and intro

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1265]
@coreycaitlin suggested that we might need a different way of introducing people to what our site (and USEITI and its data) is all about since our usability tests are showing that people are pretty overwhelmed by the amount and breath of information that we have available. And/or, they will focus on one specific piece of the site without a way to understand the linkages throughout.

I'm writing this issue as a placeholder -- we should come back to this after #1264 is finished and talk as a group on next steps/ideas.

Corey, feel free to update this description with the more articulate things you mentioned earlier today :)

**Comment by coreycaitlin** [comment]
We want to make sure the data portal is doing the rhetorical and navigational work that the executive summary did well, and that visitors can figure out what the most interesting and important parts of the site are if they arrive on the homepage.

**Comment by coreycaitlin** [comment]
I think this is mostly displaced by general reorganization, as well as #1742

**Comment by coreycaitlin** [comment]
We have other issues that cover this, so I'm closing this one out.
