### ISSUE TITLE
Visual bugssaging: mobile home (get it?) and footer

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1273]
@gemfarmer (& @meiqimichelle)
A few items to discuss, perhaps in a live session ...

General thoughts…
### A few suggestions for the hero unit…
- [ ] Shift the intro text up to reduce the amount of empty space above it
- [ ] End the blue background after the “Learn more…” link, so the “See how it works” unit runs over white
### Explore data…

I don’t want to get too far in the weeds with this now, in case we redesign this entire unit in the wake of testing. But here’s one or two quick suggestions:
- [ ] Move the big button to run below the main header, and center it like the “See how it works” button above
- [ ] Enlarge the “Federal rev…” text link to match the size of the links on the cards below

Q: Do we need an arrow by this link? If so, can we use the chevron style? I’d rather not use the current arrow at all on the site, for consistency/style
### Card area…
- [ ] Use the darker #F2F2F2 gray for the background
- [ ] Shift everything up a little to reduce the amount of background gray that runs at the top
- [ ] Time permitting, i may want to redesign the mobile view of the cards, too.
- [ ] The text is really small, perhaps enlarge?
- [ ] Use my new image which has no hairlines
- [ ] Center the second line of the link as best as possible. I think we found extra space on the right.
### Footer…

I think/hope we can make  this a lot shorter overall!
- [ ] Applies to desktop, too: If all agree, let’s make the  blue button the same height as the other two blue buttons on the page (45px, i think)
- [ ] Do we have enough real estate to go 2 cols like this?
- [ ] I moved the social bits up and added a divider rule

![image](https://cloud.githubusercontent.com/assets/9259185/13019542/beceeaf2-d195-11e5-9f09-2edcbf065d26.png)

**Comment by gemfarmer** [comment]
@ericronne much of this looks like another live session!

**Comment by gemfarmer** [comment]
Should we put something on the cal?

**Comment by gemfarmer** [comment]
Pulled from [this comment](https://github.com/18F/doi-extractives-data/pull/1248#issuecomment-183414270)
* [ ] add this image to homepage
![](https://cloud.githubusercontent.com/assets/9259185/13014195/47db2ec8-d178-11e5-97b5-00f654a8ff12.png)

**Comment by ericronne** [comment]
@gemfarmer that was just a screenshot :)
i need to update the color myself, i think.

**Comment by gemfarmer** [comment]
Ah ok.

**Comment by coreycaitlin** [comment]
I think much of this has solved itself in the process of other changes...is there anything particularly glaring that still needs fixing @ericronne?

**Comment by ericronne** [comment]
Some spacing issues, perhaps, but we can deal with later. Much of this is moot, due to new design.
