### ISSUE TITLE
Resolve required links footer issue

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1275]
Add gov site required links to site. Likely this will be in the footer.

**Comment by coreycaitlin** [comment]
Looks like this might be the breakdown of what's needed: http://www.digitalgov.gov/resources/required-web-content-and-links/

**Comment by mentastc** [comment]
Here is the link larry sent https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/

Corey's link is in ^^ also

**Comment by meiqimichelle** [comment]
Thank you, @coreycaitlin  and @mentastc !

**Comment by meiqimichelle** [comment]
Looks like we need:
- Privacy policy https://www.doi.gov/privacy
- FOIA https://www.doi.gov/foia
- About Department of the Interior https://www.doi.gov/
- USA.gov https://www.usa.gov/

I'm going to create a first version with these links and then send it to DOI for review. This is based on info on the link Larry sent over, which itself has a link to 'required content' (which is the link that Corey provided), and on the table on THAT page, some of the things are required on ALL gov pages, and some seem like they're only relevant to department or agency homepages. _whew_ These are the ones that seem required on ALL pages.

**Comment by meiqimichelle** [comment]
Looks like:
![screenshot 2016-03-21 10 21 16](https://cloud.githubusercontent.com/assets/4827522/13927527/456d9b2c-ef4f-11e5-936d-a89ab4c8aabd.png)

**Comment by meiqimichelle** [comment]
Sent an email to DOI for review (to see if this resolves their concerns over footer links, or if they'd prefer something more).

**Comment by gemfarmer** [comment]
@meiqimichelle is this resolved with your PR (#1333)?

**Comment by meiqimichelle** [comment]
Heck yeah! :tada:
