### ISSUE TITLE
Abandoned Mine Lands (AML) Visualization

### ISSUE THREAD

**Issue by splatts** [18F/doi-extractives-data#1279]
@meiqimichelle @coreycaitlin cc: @Isabelle1512 As part of our first visualization update, we've got a mock-up in the works on the AML program. For context, this issue (along with Coal Excise) were raised by the MSG as priority areas for contextual this year. On AML specifically, there have been lots of questions about what are abandoned mines, what is the government doing about them, and how they relate to extractives revenues. Likewise, the MSG has raised questions on how the fees have been collected and spent to date, the current status of the fund, as well as how the program and fund has functioned in the past. 

The attached mock-up is our first attempt at addressing those questions. It's currently being reviewed by members of the MSG and we'll be sending an updated wireframe around once we collect all those comments next week. For now, though, I wanted to share so we can all start thinking about where this might fit into the information architecture of the site, as well as how we can hit on elements of distribution and revenues that are relevant to what currently exists on the site, but are also specific to a given program.

[2016Feb15_USEITI AML DRAFT Mock Ups_v1.pptx](https://github.com/18F/doi-extractives-data/files/134883/2016Feb15_USEITI.AML.DRAFT.Mock.Ups_v1.pptx)

**Comment by meiqimichelle** [comment]
Test to see if @lukehawbaker sees this and can comment!

**Comment by lukehawbaker** [comment]
@meiqimichelle Looks like I'm good to go!

**Comment by meiqimichelle** [comment]
This work continues as separate tasks in #1571 and #1618. Closing.
