### ISSUE TITLE
Visual bug: homepage bottom teaser link isn't algined correctly on mobile

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1283]
Left over from #1205 : Bottom-of-page teaser link: is it possible to push the bottom line to the right so the text is centered (the caret pushes everything to the left)?

**Comment by meiqimichelle** [comment]
<img width="381" alt="screenshot 2016-07-21 16 26 07" src="https://cloud.githubusercontent.com/assets/4827522/17042105/df3bdcb2-4f5f-11e6-90a8-17dbe1859b4e.png">

**Comment by gemfarmer** [comment]
@ericronne could we solve this by left aligning the teaser instead?

**Comment by ericronne** [comment]
If that can be a mobile-only change, sure. If it would mean left-aligning for desktop, too, let's just keep it and close this out...

**Comment by coreycaitlin** [comment]
We removed this link 🎉
