### ISSUE TITLE
Global Nav: Users should be able to easily grasp the site structure, and fluidly navigate

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1286]
This invision mockup shows one way we could enhance the site's navigation. Just a first crack at it, for discussion. Click anywhere on the screen to advance thru, and click the logo to circle back to the home page.....

https://invis.io/8R64D4WQP

**Comment by meiqimichelle** [comment]
@coreycaitlin @gemfarmer @shawnbot -- Eric asked us to provide comments on the InVision as the next step for this task. Whenever you have a chance -- go nuts!

**Comment by ericronne** [comment]
Okay i don't think that invision design will work with our new structure :/

A meganav like this might work, though. Discuss! ...

![image](https://cloud.githubusercontent.com/assets/9259185/16991823/90371eae-4e62-11e6-900d-b2b91fe61845.png)

**Comment by coreycaitlin** [comment]
That is a VERY large nav. I'm not sure we need to use the nav to get people directly to states —especially if we're making that possible from the homepage, which might be more predictable for users. Could `Explore data` be a simple link, with no subnav?

**Comment by ericronne** [comment]
Large navs can be handy! (cf beta.fec.gov eg)
But yes, a global-nav redux may be less useful now, given the improved access we're designing into things.

@meiqimichelle ???

**Comment by meiqimichelle** [comment]
Agree! Let's not change the global nav right now, as we hopefully have addressed some of the core navigation problems on the site in other ways.
