### ISSUE TITLE
as a public safety professional, I would like to know about transport risks

### ISSUE THREAD

**Issue by techieshark** [18F/doi-extractives-data#1288]
Hey y'all, the site looks great.

Would it be possible to include information that members of the public and public safety professionals are  interested in related to the transport of flammable and toxic extracted resources? This seems to be an especially [pressing issue for low-income and minority populations](http://www.forestethics.org/sites/forestethics.huang.radicaldesigns.org/files/OilTrainPAEJReport.pdf).

For example, pipeline routes throughout the United States showing where fluid resources are shipped (ideally with source, destination, and volume information, as well as information about fluids [accidentally](http://www.biologicaldiversity.org/campaigns/americas_dangerous_pipelines/) [lost](https://en.wikipedia.org/wiki/List_of_pipeline_accidents_in_the_United_States_in_the_21st_century)). 

The pipeline route data would help connect the dots (literally):

[![Fluid resource losses](https://cloud.githubusercontent.com/assets/1072292/13267540/b7e9e4a2-dae2-11e5-99fc-930991e299f3.png)](http://www.youtube.com/watch?v=3rxqUXqPzog)

Information about the [routes transporting oil](http://explosive-crude-by-rail.org/) would also be of interest (ideally it would include where the extracted resource is being shipped from and where to, as well as information about volumes shipped and number or frequency of trips made).

Information about inefficiencies in the transport would also help communities along oil routes better plan, as well as provide useful risk information to potential investors in these projects.

For example, a dataset detailing information about locations and quantities of resources inefficiently let go of (some of which is discussed in this [Sightline timeline article](http://www.sightline.org/2015/05/06/oil-train-explosions-a-timeline-in-pictures/)). An example of one such inefficient and unfortunate loss to the industry is visualized below:

![image](https://cloud.githubusercontent.com/assets/1072292/13267120/78b63e04-dae0-11e5-84ce-8f81d063e15b.png)

In addition to residents and public safety professionals who are interested in the data, some mayors are as well.

> WHETHER IT’S FIVE OR THREE TRAINS, OUR CITY WOULD BE PLACED AT UNIQUE RISK TO THIS PROJECT. – [San Luis Obispo Mayor Jan Marx](http://www.sanluisobispo.com/news/local/article58417963.html#storylink=cpy)

The more information you could provide to them in regards to these concerns, the better.

Just a thought. But the site looks good so far. Nice work.

**Comment by coreycaitlin** [comment]
This is an interesting question, and it would be fruitful to explore someday how the site might better address the whole picture of where extractive industries go, and how they get there.

Right now, addressing this question is likely out-of-scope for the site, as many pipelines and transport channels are privately owned; DOI doesn't have much of this data.

**Comment by techieshark** [comment]
Thanks for the update. For consideration someday in the future then: 

Surely the construction of both pipelines and rail lines requires obtaining numerous permits from the government. Similarly, there must be permits for the operation of transport equipment. I would imagine the information could be pieced together from there. Notably, on the page for California, this site has pointers to further information -- perhaps there are other sources of information related to the _costs to society_ that the extractive industries website could point to, at least.
