### ISSUE TITLE
Refinements: reconciliation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1292]
- [x] Bring the 'conclusion' of the flow chart higher up in the flow of the page
- [x] Edit the entire page, now that we have more words
- [x] Add definitions for missing flow chart glossary links
- [x] Perhaps move filter on top of page? It doesn't make sense to have this here above the static charts (but maybe this will stay until we resolve the general filter issues as per #1285 )

**Comment by coreycaitlin** [comment]
- revise summary content on the parent page (Explore Data)

**Comment by ericronne** [comment]
[P R E V I E W] (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/reconciliation/) (for my own reference)

**Comment by ericronne** [comment]
Ok i'm not sure if y'all arrived at a solution yet, but here's one way we could consider surfacing the "yes you can trust this site" content. TTYL @meiqimichelle @coreycaitlin!

### Default
![explore - recon - desktop - alt](https://cloud.githubusercontent.com/assets/9259185/13608504/b28f3f2e-e51a-11e5-92f2-1618b9075790.png)

### Flowchart expanded
![explore - recon - desktop - alt - expanded](https://cloud.githubusercontent.com/assets/9259185/13608524/c6d18258-e51a-11e5-82e5-f92a4823e107.png)

**Comment by meiqimichelle** [comment]
As per @usEITI , this is not a priority right now. Moving it out of sprint for the moment.

**Comment by coreycaitlin** [comment]
Updated [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/reconciliation-new-summary/explore/reconciliation/), which resolves the outstanding content issues above.
