### ISSUE TITLE
508 Issues from pa11y-rails

### ISSUE THREAD

**Issue by nickbristow** [18F/doi-extractives-data#1296]
Results can be recreated using [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/)

## Results for https://useiti.doi.gov:
* __Error:__ Duplicate id attribute value "q" found on the web page.
 * WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
 * #q
 * `<input class="glossary__search drawer-search_field" type="search" name="q" id="q">`

## Summary:
* 1 Errors

**Comment by gemfarmer** [comment]
Closing in favor of #888
