### ISSUE TITLE
Content: State/county summary pages

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1334]
This is the first step of creating a wireframe from the work in #1267 .

**Comment by meiqimichelle** [comment]
We met today to talk on this. Here are some notes. Next step: @RyanSibley will synthesize and work on an outline of what content on a state profile page would look like.

- It is important to show which commodities exist in a state/county/whatever, and let people orient via this.
  - We should probably 'start' with commodities since that's how people think of things. ie, maybe start at location, and then the next 'choice' is commodities. 
- We need to show a layer or something about what land we’re talking about.
  - Explaining land types, and which land we're talking about (federal, state, etc), is probably pretty important.
- We need to contextualize, between states, and percentage of industry in states.
  - Is this state important to extractive industries, and are extractive industries important to this state?
  - Comparing across states might be important. "Where does Texas rank compared to other states?" Otherwise, there's no context into whether a value on the Texas page is big, small, whatever.
- We need to make sure people are able to scan the page for info (don’t hide things) Not modal.
  - Stronger navigation on page, narrative
  - If the story is more interesting or useful over time, then maybe we don’t need a time selector
  - Sections might be: revenue/production; laws; revenue/disbursements; impact (this is how the new opt-in state stuff is being organized at the moment, and might work well for these sections overall). We can also look at how the county info subsections work.
- People should be able to see at a glance what's available in each state. "Wyoming at a glance" at the top, for example.
  - Which commodities
  - This could help with findability/SEO
  - Ranking, if relevant (2nd most gas!)
  - Any outstanding impact
- People should be able to understand the key take-aways without knowing what they should be looking for on the page.
- We need to be able to direct people to the states and counties that have more info. ie, we should highlight those places where we have extra contextual and in-depth info.
- We need to be able to pull in the case studies, where relevant.

Let’s use Arizona for a sample state. We don’t want to be designing for like a list of all commodities if most states only have a sub-set so it will be useful to design with real data.

**Comment by RyanSibley** [comment]
Link to doc with summary of what we're working on: https://docs.google.com/document/d/15Kqu609u2XeR1orfOjPHpoZ7SbXaz_4y62IH0hQrmoA/edit?pli=1
