### ISSUE TITLE
508 Accessibility – Deeper dive

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1342]
As of the completion of #888, most of the major accessibility issues have been addressed.

This ticket calls for a more in-depth accessibility audit, that includes a manual audit (possibly call in @nickbristow ).

There is also one major issue (heading order) on the homepage that needs to be addressed. 

- [x] Img alt tags
- [x] `<h>` order
- [ ] is everything tab-able
- [x] confirm form HTML
- [x] confirm method for `title` on buttons (accordions)
- [ ] manual audit

**Comment by nickbristow** [comment]
For the glossary link in the nav add `aria-controls='glossaary'` to it. 

For the close button on the glossary either `value='close glossary'` or `aria-label='close glossary'` something like that. Screen reader not reading it currently

## Interactive maps

Years not keyboard accessible, numerous pa11y issues

## https://useiti.doi.gov/
The images in the bottom that are links should have the same text as the links below them. The images themselves don't seem to be anything specific

## https://useiti.doi.gov/case-studies/

Choose community page doesn't appear to be keyboard accessible.
