### ISSUE TITLE
Content: EIA = Energy Information Administration

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1346]
Make sure all instances on our site are Administration, not Agency.

**Comment by mentastc** [comment]
I was recently directing our contact at EIA to production data on the portal.  She noticed a small change that needs to be made to the EITI website.  EIA actually stands for the "Energy Information Administration", not "Energy Information Agency".

The following screenshot came from the downloads page: https://useiti.doi.gov/downloads/
Inline image 1

**Comment by mentastc** [comment]
^^email from nathan
