### ISSUE TITLE
Typo: Disbursements graphic

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1354]
The bubble chart has "Reclaimation" instead of "Reclamation." @ericronne could you update this image when you get a chance?

**Comment by ericronne** [comment]
Good catch @coreycaitlin ! Fixed...
![fund-disbursement-chart](https://cloud.githubusercontent.com/assets/9259185/14208348/86c4931c-f7e4-11e5-87eb-dac05374e0b5.png)

**Comment by gemfarmer** [comment]
Done here: #1360
