### ISSUE TITLE
Content: document taxonomy for federal revenues by location data

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1364]
On our live site, we've grouped commodities and products in a certain way. We should document this, and decide if it is still the appropriate groupings for the new state profile pages. We think we might need to adjust this slightly for the new layout.

**Comment by coreycaitlin** [comment]
This is the Google Sheets doc for the taxonomy: https://docs.google.com/spreadsheets/d/1umElxf9BJnmXkIYXr0EIdD6MXBwdgW9_wfcJR0h12P4/edit

**Comment by coreycaitlin** [comment]
Next step: Making sure that taxonomy doc ^^ represents the groupings that are currently on the site. @shawnbot, you probably know this best, if you have some time.

**Comment by meiqimichelle** [comment]
ONRR is doing this already! YES! They are working on finalizing, and will be built in to the data files they send us. @coreycaitlin do we need this pulled out of the data files into something so we can work with it as content documentation, or is the fact that @shawnbot will be able to use the categorization from the data files good enough, and we can close this issue?

**Comment by meiqimichelle** [comment]
@coreycaitlin sez: close!
