### ISSUE TITLE
508 issues

### ISSUE THREAD

**Issue by nickbristow** [18F/doi-extractives-data#1366]
https://useiti.doi.gov/how-it-works/

There appears to be a lot of buttons on the page with no value. They don't display on the page, but they are showing in this tool. http://wave.webaim.org/extension/

Either give the buttons values, or remove them from the page as they don't appear to be used?

@meiqimichelle

**Comment by meiqimichelle** [comment]
@gemfarmer any thoughts on this one? off the top of my head, perhaps this is related to the accordions on mobile, but I haven't looked at the code, as you know, in a veeerrrryyyy long time :(

**Comment by nickbristow** [comment]
@meiqimichelle @gemfarmer I think it is mobile buttons, so they need `<button value="blah">` or `<button aria-label="blah">`

**Comment by gemfarmer** [comment]
@nickbristow are you referring to these? If so, yes these are mobile only buttons. Those accordions do need aria attributes (`aria-label`), but if they are hidden (`display: none;`) on desktop, why would that be an accessibility issue on desktop? Shouldn't they only _need_ labelling on mobile? 
<img width="822" alt="screen shot 2016-04-08 at 12 22 28 pm" src="https://cloud.githubusercontent.com/assets/4803473/14391963/979fc468-fd84-11e5-9b83-752383c0c6ba.png">

**Comment by nickbristow** [comment]
@gemfarmer technically, yes. I just assume they aren't labeled in mobile atm?

**Comment by gemfarmer** [comment]
@nickbristow They are not.

**Comment by gemfarmer** [comment]
They do have a title though ```<button class="accordion-button" accordion-button title="Toggle for ownership"></button>```

**Comment by nickbristow** [comment]
@gemfarmer title isn't great for compatibility among screen readers, especially on mobile.

**Comment by gemfarmer** [comment]
:+1: ok. Good to know.
