### ISSUE TITLE
Markdownify pages

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1367]
It would be lovely, both for the site's reusability, maintenance to make as many pages as possible 100% markdown. 

@coreycaitlin and I will pair to assemble a list of content pain points in the site. For now:

- [x] #1198 Glossary items
- [x] How it works pages
- [x] Narrative pages

**Comment by gemfarmer** [comment]
* [ ] `about/report`
* [ ] `about/whats-new/`

**Comment by meiqimichelle** [comment]
Starting review, lookin' good in general! Here's a few edits:
![markdownify-edits-1](https://cloud.githubusercontent.com/assets/4827522/14546629/9c0c5350-025b-11e6-9b49-4cd7fc10d709.png)

**Comment by meiqimichelle** [comment]
Missed a list:
![screenshot 2016-04-14 16 17 07](https://cloud.githubusercontent.com/assets/4827522/14546733/61c0e476-025c-11e6-9025-bc475f66aaf7.png)

**Comment by meiqimichelle** [comment]
Boldify sentence starters (I don't know what to call those, haha) :)
![screenshot 2016-04-14 16 18 42](https://cloud.githubusercontent.com/assets/4827522/14546769/92b31fea-025c-11e6-8ef4-c608eda3c009.png)

**Comment by gemfarmer** [comment]
@meiqimichelle I think I've addressed all of these concerns!
