### ISSUE TITLE
State Trust Fund Error in Text

### ISSUE THREAD

**Issue by lukehawbaker** [18F/doi-extractives-data#1372]
Heyo! One of our contacts in Montana noted an error on the state laws and regulations page (https://useiti.doi.gov/how-it-works/state-laws-and-regulations/) The chart on trust funds has duplicate information for Alaska in the Montana slot and Montana information in the New Mexico slot. I've attached a mock-up of what it should look like. The Montana information isn't new, the New Mexico information I pulled together from some quick research. Let me know if you have questions!
[Updated State Trust Chart.pptx](https://github.com/18F/doi-extractives-data/files/224004/Updated.State.Trust.Chart.pptx)

**Comment by gemfarmer** [comment]
@lukehawbaker 
Could you verify that the changes made to the State Laws and Regulations page are correct?

https://federalist.18f.gov/preview/18F/doi-extractives-data/lukes-edit/how-it-works/state-laws-and-regulations/#natural-resource-trust-funds

**Comment by meiqimichelle** [comment]
Luke took a look and found one copy edit. That has been fixed, so now merging.
