### ISSUE TITLE
Prepare for outreach webinar

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1377]
Not sure what this means, but we should ask Judy.

**Comment by coreycaitlin** [comment]
Sounds like we should mainly be ready to answer questions about user research, usability testing, feedback, and how we iterate based on those things. (Probably with a healthy shout-out about how people can send us feedback!)

Closing this out, cause I think that's all we needed.

**Comment by gemfarmer** [comment]
👍

**Comment by usEITI** [comment]
Absolutely 100%yes.

On Fri, Apr 29, 2016 at 3:08 PM, Corey Mahoney <notifications@github.com>
wrote:

> Sounds like we should mainly be ready to answer questions about user
> research, usability testing, feedback, and how we iterate based on those
> things. (Probably with a healthy shout-out about how people can send us
> feedback!)
>
> Closing this out, cause I think that's all we needed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1377#issuecomment-215851134>
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*
