### ISSUE TITLE
Usability testing: state profile pages

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1388]
The state profile pages are nearing enough maturity to be able to test. We need to prep the research plan and people to reach out to.

**Comment by coreycaitlin** [comment]
[Research plan drafted](https://github.com/18F/doi-extractives-data/blob/research/research/9_sprint-nefariousnumbat/sprint-nefariousnumbat_research-plan.md)!

@meiqimichelle, how do you usually track who you're hoping to recruit for usability testing?

**Comment by coreycaitlin** [comment]
New plan: Split this into two research plans, and tackle one per sprint.

**Comment by coreycaitlin** [comment]
We have draft plans for both research sprints ([one mini-sprint for webinar follow-up](https://github.com/18F/doi-extractives-data/tree/research/research/9_sprint-nefariousnumbat), and [one full usability sprint to look at state pages](https://github.com/18F/doi-extractives-data/tree/research/research/10_sprint-elegantechidna)). The usability sprint testing script still needs some work, but the framework is there — the big question for me is how we'll get users oriented to the state page.

The main thing I think we should tackle before showing these pages to users is removing the sheer number of numbers on the page (probably by removing percentages and rankings).

**Comment by coreycaitlin** [comment]
We finished 4 full usability tests, in addition to Eric's ad-hoc tests of the revenue process chart. I think that's a wrap on this round of usability tests: next step is summarizing ( #1508 ).
