### ISSUE TITLE
Story map

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1389]
What I mean is: we have a pretty good start now on explaining states. We probably have content that does this for revenues and other 'process' stuff as well, and we're getting more content from Team Deloitte soon. /cc @coreycaitlin 

_more to come soon_

**Comment by meiqimichelle** [comment]
Related to #1265

**Comment by coreycaitlin** [comment]
One commenter at the webinar mentioned really loving the executive summary, and as part of our next user research phase, we should ask her about that!

**Comment by meiqimichelle** [comment]
@usEITI to review and let @meiqimichelle know if all the tasks, as we know them today, are represented.

**Comment by meiqimichelle** [comment]
We got feedback from Judy, and so now update!

**Comment by meiqimichelle** [comment]
The first version of this is done (there was some delay because the tool we use briefly blocked access) (18F + the tool worked it out, we're good now).
