### ISSUE TITLE
State profile pages into sharable form

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1390]
We're pretty close. We should probably just need to move the rest of the content work from the doc to the live page. Goal: finish by Wednesday, May 9.

**Comment by coreycaitlin** [comment]
✈️  [Preview link for reference](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/UT/) ✈️ 

Okay! Updates:

- I've pulled in most of the framing content from [this doc](https://docs.google.com/document/d/1_l5WbEQZAOfO-oUD3P1t06G1OjA7jeYMvf2DLqm9ZYs/edit#).
- Things that still need more work:
   - Disbursements content, which I haven't pulled in yet
   - The distinction between the two kinds of jobs data
   - Links to the datasets/documentation pages, and any notes about the scope/source of data that should be on this page (if we can keep that all on the docs pages, I'm 👍  for that)
   - The chart that shows fee rates per commodity by stage isn't in the prototype yet — not sure how we'll break this down to show only the relevant info
  - KEY FACTS: I think we can make this much, much shorter, and we'll need a contextual narrative. Hopefully usability testing can help inform what we need here!

I've been focused on building this page for non opt-in states with no offshore revenue. We'll need to do a bit more thinking about how to handle states with significantly more state data and how to talk about offshore revenue (not to mention which states that'll apply to, other than CA and AK).

With a little bit of styling and some stripped-back tables/charts, this should be ready to show to users. 🎉

**Comment by meiqimichelle** [comment]
Let's break this out into separate issues and close this one.

**Comment by coreycaitlin** [comment]
- Disbursements content, which I haven't pulled in yet --> #1461 
- The distinction between the two kinds of jobs data --> #1462 
- Links to the datasets/documentation pages, and any notes about the scope/source of data that should be on this page (if we can keep that all on the docs pages, I'm 👍 for that) --> #1463 
- The chart that shows fee rates per commodity by stage isn't in the prototype yet — not sure how we'll break this down to show only the relevant info --> #1464 
- KEY FACTS: I think we can make this much, much shorter, and we'll need a contextual narrative. Hopefully usability testing can help inform what we need here! --> #1465

**Comment by coreycaitlin** [comment]
And:

- how to handle states with significantly more state data --> #1467
- how to talk about offshore revenue --> #1466

**Comment by coreycaitlin** [comment]
Closing out this issue now that we have smaller issues to cover all the parts!
