### ISSUE TITLE
Glossary accordion bug

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1393]
This bug showed up on @mentastc's PC in Chrome.

- accordion chevron icons were misaligned
- filter functionality didn't work properly when the glossary search input was cleared.

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/16203406/b6d33948-36df-11e6-88d0-2b6c492aa811.png)

![image](https://cloud.githubusercontent.com/assets/9259185/16203413/c1e8125e-36df-11e6-9966-d8997cd1c76e.png)

**Comment by coreycaitlin** [comment]
Seeing wackiness in both chrome and safari on my machine:

![screen shot 2016-06-20 at 10 08 54 am](https://cloud.githubusercontent.com/assets/1450354/16203419/0ef2b164-36cf-11e6-8a31-3312a3887a1f.png)

<img width="669" alt="screen shot 2016-06-20 at 10 07 31 am" src="https://cloud.githubusercontent.com/assets/1450354/16203424/13551e5e-36cf-11e6-8021-f6eba414da50.png">

**Comment by gemfarmer** [comment]
I'm going to schedule some time to pair on this with one of you @meiqimichelle @coreycaitlin @ericronne 

'cuz my browser is working 👌

**Comment by gemfarmer** [comment]
Scheduled for this friday. Make it if you can! I just need one of you :)

**Comment by gemfarmer** [comment]
Closes with #1526
