### ISSUE TITLE
Write tests for data

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1399]
This is a bit of an epic and ongoing process. To start, we need to write tests to: 
* confirm the data in its **raw form** is the same as it is **in the db** as it is in **the yml** that we are using for templating
* make sure that all our $ figures are being parsed properly, etc.
* unit test utility functions

#1440 started adding tests for revenue, but we still have more to do:
---
- [x] Reinstate Circle CI
- [ ] Add tests for other data types
  - [x] Disbursements #1455
  - [x] Revenues #1440
  - [x] Production #1500 
  - [ ] Jobs #1501
  - [ ] GDP #1502 
  - [ ] Exports #1503

**Comment by meiqimichelle** [comment]
@gemfarmer to reach out to @shawnbot to schedule pairing on this.

**Comment by gemfarmer** [comment]
@shawnbot could we set aside some time later in the week to discuss this? I think it would be good to get this started sooner than later.

**Comment by gemfarmer** [comment]
@shawnbot just sent you an invite for Thursday afternoon. Let me know if that works for you

**Comment by gemfarmer** [comment]
We need to break this up in to sub issues! Doing this now!

**Comment by meiqimichelle** [comment]
Thanks for making those issues! I'll make an epic label and assign all those to it, and then close this issue.

**Comment by meiqimichelle** [comment]
These are all labeled now, so closing this larger issue in favor of the smaller issues.
