### ISSUE TITLE
Make state profile pages "sharable"

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1425]
Feedback that we have received on multiple occasions is that people want the page to be printable. I think it would be useful to expand this into the realm of "shareable". This could mean that the state pages should/could be:

- [x] printable
- [ ] good display (state specific) for social media
- [ ] (potentially) embeddable iframe?
- [ ] GIS ready datasets?

**Comment by meiqimichelle** [comment]
Oh cool! I was just looking for (what I thought was) an issue we had on print style sheets, but can't find it :( If it exists, plz link here @gemfarmer

**Comment by gemfarmer** [comment]
@meiqimichelle Judy was really excited about printable/social media sharable.

I'll be on the look out for the missing ticket!
