### ISSUE TITLE
Standardize OpenListNav data attributes

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1427]
Currently, OpenListNav.js requires certain hooks to exist on the page to generate its updating navigation panel.

It currently accepts two kinds of syntax

```
<a id="foo" data-nav-header="foo">
```

OR

```
<a name="foo" data-nav-header="foo">
```

This should be refactored to simply accept

```
<a id="foo">
```

Other advantages: IDs can be generated in markdown simply by using a header (`#`), which can then be referenced in a list of nav_items

```
## Header
```

generates

```
<h2 id="header">Header</h2>
``` 

Other alternatives include using [Waypoints](http://imakewebthings.com/waypoints/), but I think that this implementation is simpler, and already there :)

**Comment by meiqimichelle** [comment]
Done!
