### ISSUE TITLE
Sidenav with submenu

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1432]
Like this! 
Design: #1348 
Code: #1431 

![screen shot 2016-05-25 at 4 36 54 pm](https://cloud.githubusercontent.com/assets/4803473/15557127/ee13704c-2296-11e6-8013-4d321d6c3953.png)

**Comment by gemfarmer** [comment]
@ericronne are we still planning on using this approach?

**Comment by ericronne** [comment]
We may want to test it first, but i still think it's a useful solution. We just need to watch the length.

**Comment by gemfarmer** [comment]
A few to-dos here:
- [ ] add sub menu to jekyll templates (including changes to yaml frontmatter)
- [ ] style submenu
- [ ] make it so that all IDs that match `nav_items` in the front matter become navigable links
