### ISSUE TITLE
Commodity Revenue Tables

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1433]
Design: #1348 
Code: #1431 

Like this!

![screen shot 2016-05-25 at 4 40 49 pm](https://cloud.githubusercontent.com/assets/4803473/15557218/7d394bca-2297-11e6-9911-982068514ed4.png)

**Comment by gemfarmer** [comment]
Alternative header arrow box method: http://codepen.io/gemfarmer/pen/MeYGYN

**Comment by meiqimichelle** [comment]
I think this is covered by #1459. Closing.
