### ISSUE TITLE
Create tile view for sparklines/bar charts

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1435]
## Refs
Design: #1348 
Code: #1431

Like this! 

![screen shot 2016-05-25 at 4 44 19 pm](https://cloud.githubusercontent.com/assets/4803473/15557347/14dd70b4-2298-11e6-9f15-b96011a98bf1.png)

**Comment by meiqimichelle** [comment]
@ericronne How should we show scale on these? y-axis, other?

**Comment by gemfarmer** [comment]
Closed with #1448
