### ISSUE TITLE
Update chart styles for county level data

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1436]
## Refs
Design: #1348 
Code: #1431

Example: 

![screen shot 2016-05-25 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/4803473/15557388/4869964c-2298-11e6-9ea4-e5bc3f57a058.png)

**Comment by meiqimichelle** [comment]
@ericronne This was the notion from a few weeks back on how to display employment data by county. Perhaps your thinking has moved on since then. Should this wait on #1462 ?

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer yes if there's something else we can focus on now front end wise, it might be better to wait on this one. Design pattern will probably be influenced by #1462 and #1492, eg

**Comment by meiqimichelle** [comment]
Cool cool. I'll move this out of this sprint. Thx!

**Comment by meiqimichelle** [comment]
Done!
