### ISSUE TITLE
Layout adjustments

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1437]
## Refs
Design: #1348 
Code: #1431

Proposed adjustments:

- [x] make grid max-width 960px instead of 1024px
- [x] make state pages grid 9 (left) / 3 (right)

cc @ericronne

**Comment by ericronne** [comment]
Thanks @gemfarmer! Let's try to find a minute to discuss live before proceeding...

**Comment by gemfarmer** [comment]
Chatted with @ericronne yesterday. Pushing forward with this specified todos above
