### ISSUE TITLE
State pages: Dynamic Process Table

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1450]
The "Story" part of the process table (below, and [here on production](https://useiti.doi.gov/how-it-works/revenues/)) currently only exists as an image. Because each state has a different story, it makes sense to filter out resource types. This will else help keep the look similar to the newly styled revenues table (#1449).

<img width="341" alt="screen shot 2016-06-02 at 10 49 04 am" src="https://cloud.githubusercontent.com/assets/4803473/15751428/af398bbc-28af-11e6-81cd-f4d307aa7c0d.png">

**Comment by meiqimichelle** [comment]
This is working. Next step: pair with @meiqimichelle or @ericronne to clean up the styles.
