### ISSUE TITLE
State pages: Disbursements content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1461]
We need to write through the disbursements segment of the state profile pages. This will draw on what we started back in #660.

**Comment by gemfarmer** [comment]
@coreycaitlin @meiqimichelle 

So I did a little more looking into the data, and as far as I can tell the disbursements data that we have available in the three datasets listed on the current [disbursements download page](https://useiti.doi.gov/downloads/disbursements/) 
- disbursements_FY2012-2015_2016-03-04.xlsx
- land_water_conservation_fund_incl-documentation_2015-07.xlsx
- historic_preservation_fund_2011-2014_2015-10-30.xlsx

can be broken down as follows data available by state for onshore and offshore:

#### Offshore
- states (2012-2015)
- land and water conservation fund (some allocations are split between states, so this could be difficult to do cleanly) (2011-2014)
- historic preservation fund  (2011-2014)

#### Onshore
- states (2012-2015)

**Comment by gemfarmer** [comment]
And the data that we are currently using in the state pages prototype is only using the states fund

**Comment by coreycaitlin** [comment]
Closing for now — let's reopen or start a new issue when we have all the data.
