### ISSUE TITLE
Usability: Revise usability testing plan for state pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1468]
We should take another look at the initial [draft of the usability testing plan](https://github.com/18F/doi-extractives-data/tree/research/research/10_sprint-elegantechidna) for state profile pages, and probably revise it to make sure we know what we want to find out and what questions we'll be asking.

**Comment by coreycaitlin** [comment]
Related to #1388

**Comment by coreycaitlin** [comment]
Revised [plan](https://github.com/18F/doi-extractives-data/blob/research/research/11_sprint-randyroo/sprint-randyroo_research-plan.md) and [script](https://github.com/18F/doi-extractives-data/blob/research/research/11_sprint-randyroo/sprint-randyroo_research-script.md)! 🎉

**Comment by ericronne** [comment]
## [Eric's armchair testing notes](https://docs.google.com/a/gsa.gov/document/d/1IO1pYisQ6G7rk2iKQif-k8Cy52-OvWWPXGPkEiFODn4/edit?usp=sharing)

**Comment by meiqimichelle** [comment]
@coreycaitlin Can this be closed?

**Comment by coreycaitlin** [comment]
Yep!


On Jun 22, 2016, at 8:17 AM, Michelle Hertzfeld <notifications@github.com>
wrote:

@coreycaitlin <https://github.com/coreycaitlin> Can this be closed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/doi-extractives-data/issues/1468#issuecomment-227777365>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABYhcpCICxbEacCPC392UTZOlVCchVoGks5qOVIAgaJpZM4IwPTZ>
.
