### ISSUE TITLE
State pages: production with county data

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1492]
I'm chatting with @coreycaitlin now, and we're working on how to display production with county data.

<img width="468" alt="screenshot 2016-06-10 15 48 33" src="https://cloud.githubusercontent.com/assets/4827522/15980778/d1fc3f22-2f22-11e6-9d95-cb85f1ba993e.png">

We should get the information hierarchy clearer. Perhaps this is:
1. Here's how much coal was produced this year (the sentence)
2. Here's where it was (map)
3. Here's how it looks over time (line chart)
...and then some way to display the county-level data, something like the county break down that @ericronne designed further down in his mock in #1348.

ie, we should probably not lead with the line chart because then it makes the group of information together harder to parse.

Other:
- the line chart needs a title

**Comment by ericronne** [comment]
Let's talk live on this!

**Comment by ericronne** [comment]
## Latest, but refining further ...
![image](https://cloud.githubusercontent.com/assets/9259185/16203738/4f4e6908-36e1-11e6-89bf-e6a79d37eb2e.png)

**Comment by meiqimichelle** [comment]
@ericronne What is your latest version on this? Close enough for MVP?

**Comment by meiqimichelle** [comment]
And I should clarify @ericronne : for now, whatever version you have without the expand-a-county part is fine! Thx!

**Comment by ericronne** [comment]
@meiqimichelle @coreycaitlin this look good enough for this sprint?...
![image](https://cloud.githubusercontent.com/assets/9259185/16310008/5da71ed6-3930-11e6-92be-1aa37ed6b3b9.png)

**Comment by ericronne** [comment]
and @gemfarmer ^^

**Comment by meiqimichelle** [comment]
Looks great to me! Feel free to keep working on the county expansion stuff, but if @coreycaitlin and @gemfarmer  agree with my 👍 , @gemfarmer can use that mock for the MVP.

**Comment by ericronne** [comment]
Cool. We may need to have a version for wider states, too, where the legend runs horizontally under the map. I can paste a mockup here.

**Comment by ericronne** [comment]
The above is totally cool for this sprint. Here's an alt which is more flexible, tho, and i was able to align more closely with the bar chart design i was refining previously.

![image](https://cloud.githubusercontent.com/assets/9259185/16316753/879d9ba8-394d-11e6-97b4-068ec9609cc1.png)

**Comment by ericronne** [comment]
### [Sketch file] (https://drive.google.com/open?id=0BwWYNZcEDfwaTmgxVU9nUjVrWTQ)

**Comment by ericronne** [comment]
@gemfarmer @meiqimichelle 
Added horizontal state design (and added a little vertical spacing at the top) ....

![image](https://cloud.githubusercontent.com/assets/9259185/16321155/fc11eba2-3960-11e6-8747-50a59a3d57d0.png)


### [Sketch file with horizontal map] (https://drive.google.com/open?id=0BwWYNZcEDfwaV0pwS1gzU2pKZ0E)

**Comment by ericronne** [comment]
Here's a **[version 3 sketch file](https://drive.google.com/open?id=0BwWYNZcEDfwaVWROZDFHOWN6ZkE)** with parenthetical unit labeling, per [my comment in #1518](https://github.com/18F/doi-extractives-data/issues/1518#issuecomment-228350283). NOTE: also shifted the year indicator one col over. Consequently the intro line can be the same number of columns as the other text on the page (9)...

![image](https://cloud.githubusercontent.com/assets/9259185/16339746/fa891718-39e9-11e6-8a17-79c46f74d4f2.png)

**Comment by coreycaitlin** [comment]
I think we'll want to use this design for any dataset with county data — namely:

- Production: Federal land
- Revenue: Federal land
- Economic impact: Jobs — Wage & Salary

**Comment by coreycaitlin** [comment]
Dropdown design is in #1462

**Comment by meiqimichelle** [comment]
This is ready for implementation. @ericronne will drop in the latest, with expando.

**Comment by ericronne** [comment]
So it is written, so it shall be done ...

### Default (incl horiz states)
![production](https://cloud.githubusercontent.com/assets/9259185/16533968/040c9298-3fa2-11e6-95d4-55d02488f559.png)

### Expando (using Texas data as a "counties galore" edge case)
![production - expanded](https://cloud.githubusercontent.com/assets/9259185/16533986/2b6fa514-3fa2-11e6-9c65-6e54f52fca11.png)


## [Sketch file w-expando design] (https://drive.google.com/open?id=0BwWYNZcEDfwaOVVDM3pxRk1EZWc)

**Comment by ericronne** [comment]
Here's a mod based on the modded bar charts in issue #1556 

@coreycaitlin @gemfarmer note the unit positioning. Pulling it out of the key area also serves to simplify that part of the layout (esp for wide states, where the key will be on the bottom)
cc @meiqimichelle 

![production](https://cloud.githubusercontent.com/assets/9259185/16630616/bd2e0b80-4380-11e6-9ad7-3baf9467857d.png)

**Comment by ericronne** [comment]
### [Updated Sketch File!] (https://drive.google.com/open?id=0BwWYNZcEDfwaTG04M0V4UnNxdGs)

**Comment by gemfarmer** [comment]
Closed. Remaining issues in #1597
