### ISSUE TITLE
Data Tests: Exports

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1503]
Part of  #1399 
## TODO

Create pivot tables for the following
- Exports by state 

Pivot tables should match outputted yml files for the following datasets
## Steps to reproduce the behavior
- [ ] make pivot table for each dataset
-  [ ] write tests

**Comment by coreycaitlin** [comment]
I think the exports numbers are getting some extra zeroes (3, to be specific).

**Comment by gemfarmer** [comment]
This looks good to me!
