### ISSUE TITLE
Content: Add glossary terms

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1504]
Starting another list of glossary terms to add, based on usability testing.

- [x] Biomass
- [x] Acquired lands
- [x] Public domain lands
- [x] mcf
- [x] bbl
- [x] direct use (for geothermal)
- [x] disbursement
- [x] kilowatt hours

**Comment by coreycaitlin** [comment]
Notes on direct use:

> Hot water near the surface of Earth can be used directly for heat. Direct-use applications include heating buildings, growing plants in greenhouses, drying crops, heating water at fish farms, and several industrial processes such as pasteurizing milk.

**Comment by coreycaitlin** [comment]
Notes from EIA glossary on biomass:

> Biomass:  Organic nonfossil material of biological origin constituting a renewable energy source.

> Biomass gas:  A medium Btu gas containing methane and carbon dioxide, resulting from the action of microorganisms on organic materials such as a landfill.

> Biomass waste:  Organic non-fossil material of biological origin that is a byproduct or a discarded product. Biomass waste includes municipal solid waste from biogenic sources, landfill gas, sludge waste, agricultural crop byproducts, straw, and other biomass solids, liquids, and gases; but excludes wood and wood-derived fuels (including black liquor), biofuels feedstock, biodiesel, and fuel ethanol. Note: EIA biomass waste data also include energy crops grown specifically for energy production, which would not normally constitute waste.

> Biomass-based diesel fuel:  Biodiesel and other renewable diesel fuel or diesel fuel blending components derived from biomass, but excluding renewable diesel fuel coprocessed with petroleum feedstocks.

**Comment by coreycaitlin** [comment]
See #1198 for syntax.

**Comment by gemfarmer** [comment]
Per the units discussion, add `megawatt hours` to the list of terms :)

**Comment by coreycaitlin** [comment]
We can (finally 🎉) close this out once #1987 is merged.
