### ISSUE TITLE
Mobile visual formatting: Page margin inconsistent

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#1505]
Hi EITI folks! I've been perusing your work on mobile graphics to get some ideas for FEC. Good stuff! In the course, I noticed a weird little layout glitch.

## Expected Behavior
- Pages will have consistent margin patterns between the main copy and the edge of the device. (Ideally, with some white space in there)

## Actual Behavior
- On some pages, the copy goes full-width, and hits the edge of the device screen.

https://useiti.doi.gov/explore/reconciliation/
<img width="401" alt="screen shot 2016-06-17 at 11 04 45 am" src="https://cloud.githubusercontent.com/assets/11636908/16154994/54937f42-347b-11e6-8cfb-8b78d8817698.png">

https://useiti.doi.gov/about/
<img width="417" alt="screen shot 2016-06-17 at 11 04 33 am" src="https://cloud.githubusercontent.com/assets/11636908/16155001/590892ce-347b-11e6-9be3-03f829ed5f00.png">

## Steps to reproduce the behavior
- I observed this through the mobile view on Chrome's desktop inspector, and on an iPhone 6, Safari.

**Comment by gemfarmer** [comment]
Thanks for reporting @jenniferthibault !

**Comment by ericronne** [comment]
Pretty sure the new work fixes this 👍
