### ISSUE TITLE
Usability: Summarize findings for state profile pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1508]
Once we do one our last usability test tomorrow, we need to collect findings so far and decide what changes to make.

**Comment by coreycaitlin** [comment]
[Research results drafted!](https://github.com/18F/doi-extractives-data/blob/research/research/11_sprint-randyroo/sprint-randyroo_research-results.md) 🎉 

@meiqimichelle over to you for review!

**Comment by meiqimichelle** [comment]
So great!
