### ISSUE TITLE
Create print stylesheet

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1509]
Sub task of #1425 

Make a print style sheet for the site that enhances the styling in print format.

**Comment by gemfarmer** [comment]
@meiqimichelle do you think we should branch this off `dev` or `state-pages`? Do we want to get this released asap is what I'm really asking.

**Comment by meiqimichelle** [comment]
This doesn't have to go ASAP, `state-pages` is fine!

**Comment by gemfarmer** [comment]
👍

**Comment by gemfarmer** [comment]
Closed with #1633
