### ISSUE TITLE
State pages: make special cases available in template

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1513]
## Expected Behavior
We should be able to reference whether or not a state is an opt-in state, has case-studies, etc. like so:
```
{% if state_is_opt_in %}
```
or 
```
{% if state_has_case_studies %}
```
## Actual Behavior
This doesn't exist yet!
## Steps to reproduce the behavior
- add statuses to the front matter in a page's markdown file.

@coreycaitlin I can start this and hand off to you!

**Comment by gemfarmer** [comment]
@coreycaitlin, which would you prefer:  
- to have one file that has all the special cases information? like so:

```
AK:
  - case_study
    opt_in
    priority
AZ:
  - case_study
CA:
  - case_study
    opt_in
    priority
LA:
  - case_study
MI:
  - case_study
MN:
  - case_study
NV:
  - case_study
TX:
  - case_study
WV:
  - case_study
WY:
  - case_study

```

- or to edit each state's file? Either works, ready to do whatever is more straightforward on your end.

**Comment by coreycaitlin** [comment]
Hmm, my hunch is that one file per state will be more intuitive to maintain in the long run.

**Comment by gemfarmer** [comment]
Are you thinking it would be more intuitive because when you want to know something about that state you go to that file and you can see the relevant statuses for that state?

Because it does seem to be nice having all of the "special" info in one place.

That being said, if you think that one file per state will be easier to maintain, we already have one file per state, so it really isn't too difficult to just tack on a few extra data for that state.

**Comment by coreycaitlin** [comment]
🎉  All set!
