### ISSUE TITLE
State pages: production with county data, code layout

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1518]
After #1492 is done, we should code the layout and make it look like the mock.

**Comment by meiqimichelle** [comment]
Looks like this is ready to go here: https://github.com/18F/doi-extractives-data/issues/1492#issuecomment-228094983

**Comment by meiqimichelle** [comment]
If you haven't started yet, you can use @ericronne 's latest latest: https://github.com/18F/doi-extractives-data/issues/1492#issuecomment-228156116

**Comment by gemfarmer** [comment]
@meiqimichelle I'm going to wait on this until #1495 gets merged

**Comment by gemfarmer** [comment]
@ericronne what is the grid here?

**Comment by gemfarmer** [comment]
Within the primary column is it 4, 5, 3 on a 12 column grid? Or still 3, 3, 2 on a 8 column grid?

**Comment by ericronne** [comment]
### 12 for the content area...
![image](https://cloud.githubusercontent.com/assets/9259185/16338801/7c0f1608-39e4-11e6-8116-6ce70e02b6a1.png)

**Comment by ericronne** [comment]
Note: @gemfarmer 
We can keep the units as parentheticals in the chart titles for now, if that's quicker. That would align with how the charts are already designed...

![image](https://cloud.githubusercontent.com/assets/9259185/16339195/ff4b27a8-39e6-11e6-8db8-561e6aa210c0.png)

That would make for a simpler legend layout for horizontals, too. Win win...
![image](https://cloud.githubusercontent.com/assets/9259185/16339273/532ba4ec-39e7-11e6-9977-d3b5fd9b5cc5.png)

**This makes the titles longer, natch.**
I changed the bar chart to merely "coal production (tons) to keep it on one line. Not sure what all of the final titles will be, so i took the liberty. @coreycaitlin can answer all questions, i'm sure! 🔮 

We should root out the longest non-shortenable title and test the design. If we do have some breakers, it would be great if they were coded to ensure that the horizontal rules were always vertically aligned, like so (hopefully no nasty widows like this, tho!)...

![image](https://cloud.githubusercontent.com/assets/9259185/16339446/48774456-39e8-11e6-9298-3bbe427f125b.png)

**Comment by gemfarmer** [comment]
Split part of this off into #1585 (handling wider states)

**Comment by ericronne** [comment]
@gemfarmer here's the latest, reflective of the updated styles...

### [Sketch file] (https://drive.google.com/open?id=0BwWYNZcEDfwaTG04M0V4UnNxdGs)
