### ISSUE TITLE
National profile: content

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1519]
Based on our design studio, let's write a doc with content for a national profile page.

**Comment by coreycaitlin** [comment]
Started two documents (both in Google drive, so limited access):

- [Summary of images and ideas from the design studio](https://docs.google.com/document/d/1jvB3ofHxEEW6m8PquX3jZXSFOSRjFY236MMOt_LuOpA/edit)
- [National profile wireframe / content outline](https://docs.google.com/document/d/1uLoIBLRVYqnY4VNF9Z_KvReCtiG7rCkUTbfMdgHs9_E/edit)

**Comment by coreycaitlin** [comment]
Focus on:

1. Onshore/offshore
2. Disbursements

**Comment by coreycaitlin** [comment]
Next step: rewrite disbursements content so it fits the national context.
