### ISSUE TITLE
State pages: mobile view

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1523]
No explanation necessary, methinks :)

**Comment by ericronne** [comment]
Here's a first take, to chew and chat upon.

### [Very simple Invision prototype, for that "phone feel"] (https://invis.io/Y682AV8BK#/176399112_Mobile-x2)


### Sticky top nav ...
The sticky side nav from the desktop view could take the form of a header, and be expandable and sticky, updating as you scroll ...
![image](https://cloud.githubusercontent.com/assets/9259185/17106844/7afcebc4-5252-11e6-8864-b539999844bf.png)

### Megachart
The megachart could include a horizontally swipe-able feature ("more" would expand the explanations tab) ...

![image](https://cloud.githubusercontent.com/assets/9259185/17106942/da8169a8-5252-11e6-9de3-9f46102afd2c.png)

### Full page (more or less) ...

![image](https://cloud.githubusercontent.com/assets/9259185/17106886/9f046aa6-5252-11e6-929a-62389fc30904.png)

**Comment by meiqimichelle** [comment]
Nice! At first kick-the-tires, that makes sense to me!  That's a good idea, the swipe left-right for the mobile table ;)

**Comment by ericronne** [comment]
Ha. Here's the prototype which inspired it, courtesy @meiqimichelle ...
http://filamentgroup.github.io/tablesaw/demo/swipe.html

**Comment by coreycaitlin** [comment]
@ericronne 😻  this makes lots of sense, I like it!

**Comment by ericronne** [comment]
Further megachart revision. Concerns? Eg re implementation, @gemfarmer @shawnbot  @meiqimichelle?

### Default...

![image](https://cloud.githubusercontent.com/assets/9259185/17154847/5318046c-5348-11e6-9fc9-28557a74375d.png)


### Swiped to col 3

![image](https://cloud.githubusercontent.com/assets/9259185/17154535/0e07df60-5347-11e6-9fb1-c2d83eb0eb77.png)

**Comment by ericronne** [comment]
### Here's a starter [Sketch file] (https://drive.google.com/open?id=0BwWYNZcEDfwac1pMSFBLNXRvNEE). Not complete, but hopefully enough to get things rolling.

![mobile](https://cloud.githubusercontent.com/assets/9259185/17156322/cd40c23c-534e-11e6-926e-87b52be4db80.png)
