### ISSUE TITLE
State pages: Add county maps for federal revenue

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1524]
Federal revenue has county-level data, much like federal production. We should implement @ericronne's [lovely new layout](https://github.com/18F/doi-extractives-data/issues/1492) for county details in this section, too.

**Comment by coreycaitlin** [comment]
Moving notes from another conversation into here:

We have county-level federal revenue data for all commodities, and should make that available to some extent on this page.

The mega-process-chart is already showing revenue by commodity for one year, and it's broken up in a sensible way (for instance, it handles `Oil & gas (non-royalty)` beautifully). This is because revenue types map to commodities pretty neatly.

So! We are already showing revenue by commodity in the mega-process-chart, AND we're already showing what's being produced where up in Production on Federal Land. The one layer that would be nice to add is: "Total federal revenue by county for the last 10 years"

**Comment by coreycaitlin** [comment]
I believe the next steps here are:

- Add map and county-level info for `All commodities`
- Remove everything else under that

**Comment by gemfarmer** [comment]
@coreycaitlin to clarify, by
> Add map and county-level info for `All commodities`
you mean add `10 year bar chart | county map | county-level chart` layout, correct?
