### ISSUE TITLE
State pages: Design sticky-nav icon / interaction

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1538]
An icon which shows the currently active state or region, and serves as a secondary way to get back to the Explore main page.

**Comment by ericronne** [comment]
@meiqimichelle @coreycaitlin @gemfarmer @shawnbot 

Team! Here's a take at using an iconic map in the side nav. It presents some issues, and would be a pain to generate all 53(?) permutations ... but it's worth considering imo.

 - Alaska and hawaii would be infinitesimally small in the usual projection size, so i've enlarged them. 
 - The entire icon would also function as a button leading back to explore main

![sidenav icon button](https://cloud.githubusercontent.com/assets/9259185/16434012/c8479f10-3d52-11e6-84fe-92f5978fbe93.png)

**Comment by meiqimichelle** [comment]
LIKE!

**Comment by meiqimichelle** [comment]
Let's test this with Alaska, California and Arizona.

**Comment by ericronne** [comment]
I'll mock em up :thumbsup:

**Comment by ericronne** [comment]
Mocks, mocked...

![sidenav icon button style](https://cloud.githubusercontent.com/assets/9259185/16534880/af1dc34a-3fa8-11e6-94f5-8879c8e7c63f.png)

### [Icon PNGs] (https://drive.google.com/open?id=0BwWYNZcEDfwaaENWZkwxVTlVYWs)

### [Sketch file, if needed] (https://drive.google.com/open?id=0BwWYNZcEDfwaaldqeVYzdENkVTg)

**Comment by ericronne** [comment]
In response to some chatter over in the slack, our graphics team has shifted around the positions of Alaska and Hawaii. Pls opine, thx! @meiqimichelle @coreycaitlin @gemfarmer @shawnbot 

Also shows how we would treat longer state names

![image](https://cloud.githubusercontent.com/assets/9259185/16589875/c4547c32-429a-11e6-91db-a35d3e8d52b3.png)

**Comment by ericronne** [comment]
[Here are PNGs](https://drive.google.com/open?id=0BwWYNZcEDfwaaENWZkwxVTlVYWs) with the positions of AK and HI shifted. Implement for testing, @meiqimichelle?

![image](https://cloud.githubusercontent.com/assets/9259185/16633287/26982814-438e-11e6-8268-165173f5d5d3.png)

**Comment by usEITI** [comment]
The folks from Alaska will be glad to see the placement of their beloved
state.

On Wed, Jul 6, 2016 at 4:27 PM, Eric Ronne <notifications@github.com> wrote:

> Here are PNGs
> <https://drive.google.com/open?id=0BwWYNZcEDfwaaENWZkwxVTlVYWs> with the
> positions of AK and HI shifted. Implement for testing, @meiqimichelle
> <https://github.com/meiqimichelle>?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9259185/16633287/26982814-438e-11e6-8268-165173f5d5d3.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1538#issuecomment-230895942>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANnOZGOs_5sLIThLvVxfz45OONjEyd1Wks5qTA-4gaJpZM4JAXnb>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*
