### ISSUE TITLE
Add adjustable scale to megachart

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1541]
Let's discuss, and then possibly test, and then maybe actually create a tool enabling users to adjust the scale of the megachart. This will enable them to visually compare differences between smaller numbers, in cases where an outlier (such as oil and gas) completely throws off the scale.

(Just making a backlog issue for this, so it doesn't get forgotten.)

**Comment by ericronne** [comment]
If it's deemed useful, it might be handy on other charts, as well.

Perhaps similar to this design, which was concepted for revenues (but never implemented)...

![image](https://cloud.githubusercontent.com/assets/9259185/16459170/8e83dc86-3de7-11e6-9450-e7cff0dce98d.png)

Eric note to self: see "EITI Explore Data - Desktop v2.sketch"

@coreycaitlin @meiqimichelle @gemfarmer @shawnbot

**Comment by ericronne** [comment]
First envisioned in #962

**Comment by ericronne** [comment]
One simple(?) solve(?) would be to offer the option to hide the largest commodity, like so ...

![image](https://cloud.githubusercontent.com/assets/9259185/17453589/0baed48c-5b33-11e6-8bd3-1165dc68d115.png)

**Comment by coreycaitlin** [comment]
Noted this idea for posterity; closing this issue — will reopen if this emerges as a user need.
