### ISSUE TITLE
Meta: taskify process documentation work

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1546]
We have a plan for what we'd like to document more thoroughly to make the site easier to re-use. It is [here](https://docs.google.com/document/d/1HCZLVGx1cc3X1wXqytbsUXkqn5ApuGlsgak97Df6kj4/edit#heading=h.sy4tarfa6gv8) . This needs to be broken into tasks and made into discrete issues.

**Comment by coreycaitlin** [comment]
ALL THE ISSUES:

#640 
#1549 
#1550 
#1551 
#1552 

This could use a look-over by @gemfarmer when he's back to make sure I caught all the technical parts.
