### ISSUE TITLE
Meta: Document site/data relationships

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1550]
Documentation of the relationships between the site and the data, as well as how the data is organized. We’ve done a good job of separating the geographical (TopoJSON files that describe the shapes of states, counties, and offshore areas) from the tabular, but other countries would need to tailor the tabular data carefully to fit their needs.

**Comment by meiqimichelle** [comment]
Did we do this? I feel like we have a lot of documentation on how we're using data on this site. What do you think @coreycaitlin ?
