### ISSUE TITLE
Meta: Process and team documentation

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1552]
Clear, high-level writing about the big picture of the process will help other countries understand who they need, how much time it might take, and how to structure the process. Writing about how our process fit in with international EITI processes (such as the Multi-Stakeholder Group and Independent Administrator) will also help make this more plausible for other countries.

Team, resources, and process documentation could live in one place or work in conjunction with a collection of blog posts. We may also be able to create documentation that supports trainings or workshops and functions in a standalone way.

Documentation would need to include the following:
- Skills and abilities the 18F team brought to the project
- Step-by-step, hands-on documentation of the user-centered design process, including research
- How we (the website team) worked with the MSG, IA, and agency partners

**Comment by coreycaitlin** [comment]
@meiqimichelle wrote up [Little rules for designing with data](https://github.com/18F/doi-extractives-data/wiki/Little-rules-for-designing-with-data), which is a big step in the right direction!

**Comment by alexpandel** [comment]
closing out for now in favor of more granular tasks moving forward
