### ISSUE TITLE
Design: State profile intro

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1553]
Design for page intros! Example content to look at:

- [Wyoming](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/WY/#overview)
- [California](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/CA/#overview)
- [Texas](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/TX/#overview)
- [North Carolina](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/NC/#overview)
- [Washington, DC](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/DC/#overview)

**Comment by ericronne** [comment]
OBE(?) - see #1612
