### ISSUE TITLE
Glossary - Visual glitch on search canceling "x"

### ISSUE THREAD

**Issue by dmsnell** [18F/doi-extractives-data#1564]
When using the site glossary, which is awesome how it pops in from the side, I discovered that the "x" icon used to clear out the existing search terms was showing up improperly. Some quick testing revealed that it's a bit funky across browsers:

**Safari 9.1.1 OSX**
The icon is partially masked
<img width="277" alt="screen shot 2016-07-03 at 5 35 29 pm" src="https://cloud.githubusercontent.com/assets/5431237/16548491/c611e796-4144-11e6-87b9-f8edec1b8d27.png">

**Chrome 51.0.2704.103 OSX**
The icon appears to look as expected
<img width="280" alt="screen shot 2016-07-03 at 5 37 42 pm" src="https://cloud.githubusercontent.com/assets/5431237/16548504/ee9a9488-4144-11e6-9c0d-00d900799500.png">

**Firefox 47.0.1 OSX**
The icon is missing altogether.
<img width="276" alt="screen shot 2016-07-03 at 5 38 27 pm" src="https://cloud.githubusercontent.com/assets/5431237/16548522/40e1c018-4145-11e6-89f5-8fc44f31f47a.png">

**Comment by gemfarmer** [comment]
Hi @dmsnell. Thanks for noticing and taking the time to file this bug thoroughly! We will take a look asap and try to fix the bug in our next site update!

**Comment by coreycaitlin** [comment]
This is still broken, at least in Firefox.

**Comment by gemfarmer** [comment]
@toolness this might be a more straightforward one to get started with.

**Comment by msecret** [comment]
I researched this a little, and this is at the browser level. We're not directly creating that image, the browser is because it's specified as a `type="search"` input. I'm trying to figure out if there's something about our styling thats causing the issue.

**Comment by msecret** [comment]
On further research, I found Safari's most recent version does work for me.

I don't think firefox implements the close button. It can be implemented manually with JavaScript, but that seems like a messy, unmaintainable, error-prone solution. My suggestion here is to close this issue, as I don't think we have enough control to fix anything.
