### ISSUE TITLE
Refactor: accordion header click-ness

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1568]
## Expected Behavior

The entire accordion header should be clickable. Header = Title text + chevron icon
## Actual Behavior

Currently, accordions can only be toggled by clicking on the chevron to the right of the accordion title.
After [this PR](https://github.com/18F/doi-extractives-data/pull/1565), the glossary header is clickable, but it is doing so by making adjustments to `glossary.js` instead of `accordion.js`. This means that the rest of the accordions throughout the site still toggle the _old_ way.
## Steps to reproduce the behavior
- Adjust how the accordion is generated, ideally including options for it to make a button toggle with text in it AND a button toggle with non-clickable text beside it (like it is now)
- Adjust styles to accomodate these options

**Comment by meiqimichelle** [comment]
This is working on `dev`. This issue is to bring the code more into line with other work on the site. An enhancement.

**Comment by meiqimichelle** [comment]
@gemfarmer I changed the title to better reflect the issue here. Is this still a thing that needs to happen?

**Comment by coreycaitlin** [comment]
Looks like the main place this is still relevant is on the "How it works" (diving graphic) pages, and only on mobile.

**Comment by gemfarmer** [comment]
As @coreycaitlin mentioned earlier this year, this still is relevant on the "diving graphics page". 

These are the diving graphics pages:
- https://useiti.doi.gov/how-it-works/coal/
- https://useiti.doi.gov/how-it-works/offshore-oil-gas/
- https://useiti.doi.gov/how-it-works/onshore-oil-gas/
- https://useiti.doi.gov/how-it-works/minerals/
- https://useiti.doi.gov/how-it-works/offshore-renewables/
- https://useiti.doi.gov/how-it-works/onshore-renewables/

**Comment by coreycaitlin** [comment]
This is not a priority right now.
