### ISSUE TITLE
Content: Budget and audit visualization

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1573]
Pull content from the IA's Budget & Audit visualization into a Markdown page.

**Comment by meiqimichelle** [comment]
Pinging @avarnum so he can see how notification work :)

**Comment by coreycaitlin** [comment]
Started pulling in content here: https://github.com/18F/doi-extractives-data/tree/budget-audit-content

**Comment by coreycaitlin** [comment]
Notes from the PR:

Sidenote: We're using the how-it-works-ia branch to collect the new content that will go into a reorg of the How it Works section.

This PR includes content from the budget and audit visualization, which we've renamed "Oversight" to be parallel with other How it Works pages/sections. There are a few principles I kept in mind in revising this content for web:

- We always want to avoid duplicative content, both for usability reasons (finding similar or parallel information in two places can undermine user trust, because they aren't sure which is correct) and for maintainability. Whenever possible, we link to existing content, rather than re-creating it. This goes for content within the USEITI site (like disbursements), deeper agency pages (like ONRR's list of relevant laws), and agency home pages (for general info).
- To avoid confusion, I tried to make sure the scope of each section was internally consistent, and that all information about a topic lives in one place (rather than having content in multiple places on the same page.
- Each link should be clearly contextualized, so that users understand the scope of the link and what to expect if they click. For both usability and accessibility reasons, we never want to have different links with identical anchor text — and all anchor text should be as descriptive as possible. As part of this, I've moved more arcane links and most PDF links to footnotes.

**Comment by coreycaitlin** [comment]
Some of the text hierarchy and sidenav work we've been doing is stuck over in `state-pages`, so it's a little tricky to grok the outline of the page by looking at the [preview](https://federalist.18f.gov/preview/18F/doi-extractives-data/how-it-works-ia/how-it-works/oversight/).

Here's the outline, in case it's tricky to see:

- Data validation and auditing
  - Company standards and oversight (includes public and private company standards)
    - Federal audits of company records and systems
  - Federal standards and oversight
- Data publication
  - Company payment reporting
  - Federal revenue reporting
- Agencies that manage revenue payments
  - Non-tax payments
    - Understanding how ONRR manages revenue (includes enforcement mechanisms and disbursements)
  - Corporate income taxes
- Notes

**Comment by coreycaitlin** [comment]
Current outstanding questions for you, @avarnum:

- Your content mentions a "latest GAO audit", but I couldn't find the link for that in the link table. We *do* have the link to the latest DOI OIG report. Is there also a GAO audit I'm missing?
- Does Sarbanes-Oxley change the self-regulatory nature of accounting/auditing for privately-held companies as well as publicly owned companies?

**Comment by avarnum** [comment]
Answer to your first question: 
1. http://www.gao.gov/products/GAO-16-357R this is the report to the GAO audit of the US government's consolidated financial statements
2. You can say "a number of provisions affect privately held companies". here's non-official link on it: http://www.boylancode.com/news-knowledge/articles/62-yes-sarbanes-oxley-applies-to-private-companies. Both private and public companies were required to have internal controls, CEO and CFO sign-off on financials, etc.

**Comment by coreycaitlin** [comment]
Our new plan is to keep the visualization in PDF format, and let this page focus on overview + links. At this point, we're waiting for final-final content from the IA before we add that link.

**Comment by meiqimichelle** [comment]
Update from @splatts : the Implementation Subcommittee is getting one more week to review the content, and they were OK with having a downloadable PDF factsheet and we can provide a summary or whatever is useful on the website itself.

**Comment by coreycaitlin** [comment]
Closing this issue and opening #1691 to reflect our new plan.

**Comment by splatts** [comment]
Hi all - just a note that since the Implementation Subcommittee requested another week to review this and comment, and will (hopefully) be formally recommending it to the Co-Chairs this Wednesday (8/3), for approval by Co-Chairs next week. Heads up to you all that in this review process there were some slight changes to wording and sentences per the request of the MSG members on the Subcommittee. Might not impact your intro section too much, but just a heads up. @avarnum and I can help point these out for you all in reviews.
