### ISSUE TITLE
State pages: All-lands production resource groupings

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1574]
On the state pages, in the all-lands production section, we're showing both groupings and individual resources:

![screen shot 2016-07-05 at 5 07 38 pm](https://cloud.githubusercontent.com/assets/1450354/16603690/effe7c92-42d2-11e6-8a6d-9cf1fc1726bd.png)

This has a couple issues:

- It's confusing (what does "all other renewables" mean?! other than what?)
- It might be misleading, because we don't show which resources roll up into which groupings

Based on our [prior data notes](https://github.com/18F/doi-extractives-data/wiki/Data-Catalog#all-production) and some post-it math, it looks like this is how the products roll up:

![img_0063](https://cloud.githubusercontent.com/assets/1450354/16603759/94c22a26-42d3-11e6-973e-b1b4c4bde40c.JPG)

Given all that, I think the simplest solution is simply to remove some of the duplicative resources. Here's what I think we should do about each resource we're currently listing separately:

- ~~All other renwewables~~
- Wood and wood-derived fuels — keep
- Other biomass — keep but find a definition
- ~~Biomass (total)~~
- Wind
- Solar
- Geothermal

Alternately, we could solve this by showing stacked bars instead of separate bar charts. That seems awfully complicated, though.

**Comment by gemfarmer** [comment]
@coreycaitlin interesting! I didn't realize that `Wood and wood-derived fuels + Other biomass = Biomass (total)`.

Beyond consolidating some of the commodities, is this issue also to form commodity groupings in the bar chart grid area?

**Comment by coreycaitlin** [comment]
New thought!

- ~~All other renwewables~~
- ~~Wood and wood-derived fuels~~
- ~~Other biomass~~
- Biomass
- Wind
- Solar
- Geothermal

**Comment by coreycaitlin** [comment]
Note: Bob also mentioned this in his feedback, and this will help address a bunch of confusion/weirdness around biomass/renewables titles.
