### ISSUE TITLE
Natural Gas bar chart

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1579]
Bar chart should be easy to interpret. Currently natural gas has data stretching back to the 60s, but _likely_ with different collection methods than earlier years. 

## Expected Behavior

Somehow, we want to make this look better. Two options that I can see are 
* clipping the years to 2004-2013
* formatting the bar chart so that it doesn't look wonky. This could maybe include culling the year labels (every 5 years?)

## Actual Behavior
Here is the all production national data:
<img width="260" alt="screen shot 2016-07-07 at 3 47 17 pm" src="https://cloud.githubusercontent.com/assets/4803473/16669264/2a502584-445a-11e6-8cd4-d9ad4dd15302.png">

## Steps to reproduce the behavior
@ericronne to the rescue! Do you have any ideas for what to do about this?

**Comment by ericronne** [comment]
While you were away ...
We landed on trying ten years for all bars. See #1548

**Comment by meiqimichelle** [comment]
Done!
