### ISSUE TITLE
Bug: stray </li>s on the live site

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1581]
There are stray `</li>`s on the bullets on this page: https://useiti.doi.gov/how-it-works/revenues/ 

<img width="628" alt="screenshot 2016-07-07 15 49 52" src="https://cloud.githubusercontent.com/assets/4827522/16672360/8cdfe9d2-445a-11e6-8eb8-48663d3c4e3d.png">

**Comment by coreycaitlin** [comment]
@meiqimichelle I think I fixed this in #1499, but we haven't pushed it live yet.
