### ISSUE TITLE
State page year selector design

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1582]
The current design of interactive-data modules on the states page includes a selector, which defaults to the most-recent year for which we have data (2013 in the example below). Since the year is always different from the current year (2016), this has caused some confusion in our [armchair usability testing](https://docs.google.com/a/gsa.gov/document/d/1IO1pYisQ6G7rk2iKQif-k8Cy52-OvWWPXGPkEiFODn4/edit?usp=sharing) sessions. 

![image](https://cloud.githubusercontent.com/assets/9259185/16697605/17cc0a3e-4510-11e6-9cf4-c322c3a2a330.png)

One potential solution is to include the non-data years in the selector, but treat them differently....
![image](https://cloud.githubusercontent.com/assets/9259185/16697697/8d104e90-4510-11e6-82e4-bbd1b90aa7c9.png)

These non-data years could perhaps be clickable. If one was selected, an explanation of why we have no data could appear in the chart area.

 

- [x] Create a prototype
- [x] Test it

**Comment by ericronne** [comment]
@meiqimichelle @coreycaitlin @gemfarmer fyi

**Comment by ericronne** [comment]
![selector](https://cloud.githubusercontent.com/assets/9259185/16701462/920368dc-4525-11e6-9615-f9a5ab69696a.gif)

**Comment by ericronne** [comment]
@coreycaitlin @meiqimichelle 

Will this design for the "no data" years give us problems with some categories, since we may have 2012 data for federal coal in Utah, eg, but not have any 2012 data for federal biomass in Utah?

hrumph.

**Comment by ericronne** [comment]
Ok after chatting with @meiqimichelle, this "no data" approach may work after all (but we will have to explain some of the oddball situations in the copy, @coreycaitlin). Here's a modified gif, where i've instead grayed out the charts for non-data years. That way we won't have to worry about the page getting longer and shorter. NOTE: this design is old, but updating for the prototype would be time consuming.

Will do a quick test or two...

cc @gemfarmer 

![selector](https://cloud.githubusercontent.com/assets/9259185/16739744/341d6e96-4761-11e6-95c3-8e1911ec9dc1.gif)

**Comment by ericronne** [comment]
Did two quick tests on the selector; both people grokked it immediately. Also tested the bar chart interaction and a couple other state-page elements with one of the users. All in the [ever-growing test-notes doc] (https://docs.google.com/a/gsa.gov/document/d/1IO1pYisQ6G7rk2iKQif-k8Cy52-OvWWPXGPkEiFODn4/edit?usp=sharing)

Implement-able @meiqimichelle?

**Comment by meiqimichelle** [comment]
I believe @shawnbot and @gemfarmer may have started working on the selector yesterday, yays -- tracked in #1588
