### ISSUE TITLE
Style: adjust bar chart

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1587]
## Expected Behavior
<img width="196" alt="screen shot 2016-07-11 at 12 40 01 pm" src="https://cloud.githubusercontent.com/assets/4803473/16740416/a0bd68f0-4764-11e6-8dda-8b1b93d19b06.png">

## Actual Behavior

![pasted image at 2016_07_11 12_51 pm](https://cloud.githubusercontent.com/assets/4803473/16741214/f11de25e-4767-11e6-92c3-1f6d5033637f.png)

## Steps to reproduce the behavior
- [x] always show full breadth of years
- [x] years with no data should be grayed out
- [x] add bottom line to bars
- [x] change x axis label
- [x] change summary text

cc @ericronne

**Comment by ericronne** [comment]
Design is tracked in #1556 

Based on **[testing] (https://docs.google.com/a/gsa.gov/document/d/1IO1pYisQ6G7rk2iKQif-k8Cy52-OvWWPXGPkEiFODn4/edit?usp=sharing), it may be good to test a couple of variations for potential future iterations, eg...
 - Adding a Y-axis label
 - Sentence-embedded display vs numbers plus sentence display vs no sentence just numbers

**Comment by meiqimichelle** [comment]
_the infamous y-axis strikes again_

**Comment by ericronne** [comment]
one quick noodle, just pasting for ref and moving on for now...

![image](https://cloud.githubusercontent.com/assets/9259185/16773251/d6d4ca92-481c-11e6-8d9f-b57ca54bedc5.png)

**Comment by meiqimichelle** [comment]
Moved to the scale challenge to its own issue #1650

**Comment by gemfarmer** [comment]
@ericronne is this issue complete?

**Comment by ericronne** [comment]
Sure. Remaining changes can be tracked in #1700
