### ISSUE TITLE
Code: State page year selector

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1588]
Extension of #1582 

## Expected Behavior
Should be able to select a year from a year range and change _all_ bar charts in a given section to the selected year. All the years across all the sections will have the same year range available in the selector. However, if there is no data in that section for a given year (say, we don't have datayet for 2016), the year should be visible in the selector, and a new view will load that 'grays out' the bars and provides a different intro sentence that explains the situation.
## Actual Behavior
The year selector does not have any functionality
## Steps to reproduce the behavior
TBD

**Comment by meiqimichelle** [comment]
Looks like

![selector](https://cloud.githubusercontent.com/assets/9259185/16739744/341d6e96-4761-11e6-95c3-8e1911ec9dc1.gif)
