### ISSUE TITLE
Update county case studies for new year

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1601]
We have edits and additional info to add to the county case studies for this year. The original Word docs are [here](https://drive.google.com/drive/folders/0B2CjDILjK8_jNGVfZGloTWdUMUE) . This work is started on the `case-study-updates` branch.

**Content**
- [x] North Slope Borough — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/north-slope/)
- [x] DeSoto Parish — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/desoto/)
    - includes Mcf definition — see also #1504 
- [x] Elko and Eureka Counties — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/elko-and-eureka/)
- [x] Greenlee County — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/greenlee/)
- [x] Campbell County —[PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/campbell/)
- [x] Boone, Logan, and Mingo Counties — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/boone-logan-and-mingo/)
- [x] Humboldt and Lander Counties— [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/humboldt-and-lander/)
- [x] Kern County— [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/kern/)
- [x] St. Louis County — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/st-louis/)
- [x] Marquette County— [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/marquette/)
- [x] Pima County — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/pima/)
- [x] Tarrant and Johnson Counties — [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/case-study-updates/case-studies/tarrant-and-johnson/)

**Charts**
For design review and proofing in #1603 . This list is for implemetation (getting 'em on the page)
- [x] North Slope
- [x] DeSoto
- [x] Elko
- [x] Greenlee
- [x] Campbell
- [x] Boone
- [x] Humboldt
- [x] Kern
- [x] St. Louis
- [x] Marquette
- [x] Pima
- [x] Tarrant

**Comment by avarnum** [comment]
Great news! tagging myself @avarnum

**Comment by coreycaitlin** [comment]
@avarnum DeSoto is ready for your review here: https://federalist.18f.gov/preview/18F/doi-extractives-data/desoto-update/case-studies/desoto/

**Comment by coreycaitlin** [comment]
@avarnum All text and footnotes are ready for your proofreading pleasure! Just hit those "PREVIEW" links above to see each case study.

Images are still separate, but we could use your eyes on a few questions over in #1603 👀

**Comment by avarnum** [comment]
Hi @coreycaitlin @meiqimichelle i'll do my best to review some of these today. I'll follow up on #1603 first and if I don't get to these, @splatts will review and provide feedback in time for next week's OAG call on Friday.

**Comment by coreycaitlin** [comment]
Okay! All images are implemented (except Elko & Eureka employment, which I seem to have misplaced, as I mentioned in #1603). Remaining steps:

Final-final-final review and implementation of any further edits from Deloitte:

- [ ] North Slope Borough
- [ ] DeSoto Parish
- [ ] Elko and Eureka Counties
- [ ] Greenlee County
- [ ] Campbell County
- [ ] Boone, Logan, and Mingo Counties
- [ ] Humboldt and Lander Counties
- [ ] Kern County
- [ ] St. Louis County
- [ ] Marquette County
- [ ] Pima County
- [ ] Tarrant and Johnson Counties

Miscellaneous other things:

- [ ] Fixing fonts in all the images (Lato isn't loading in the SVGs, for some reason)
- [ ] Add image 19

**Comment by coreycaitlin** [comment]
Here's the full list of changes for the first three (which you can also see highlighted [here](https://github.com/18F/doi-extractives-data/pull/1686/files)):

## St. Louis County

- Change the word "chart" to "graph" in the first paragraph under "Production"
- Add footnote 4 citing the USGS 2013 Minerals Yearbook: Iron Ore
- Change this sentence: "The eight mines in St. Louis County operated by these and other companies provided 3,283 jobs in 2014, comprising 4% of the county's total 81,236 employment." to "The seven mines in St. Louis County operated by these and other companies provided 4,202 jobs in 2014, comprising 5% of the county’s total 81,236 employment." and added a footnote citing the 2014 Annual Report of the Inspector of Mines. 
- Change the final number in this sentence: "The tax rate for taconite production increased in 2013 from $2.46 per taxable long ton of concentrates to $2.56, an increase of 4.1%" from 3.8% to 4.1%
- In the last paragraph of "Revenue," changed the year for the data point about tax on unmined taconite ($227,126) from 2013 to 2014.
- Added a footnote reading "Ibid." in the middle of the second paragraph under "Costs."
- In the data availability table, changed "The Bureau of Labor Statistics (BLS) published total St. Louis County employment data for 2012. NAICS codes used were: 212 (Mining except oil and gas); 21221 (Iron Ore Mining); 213115 (Support Activities for nonmetallic minerals)" to "The Bureau of Labor Statistics (BLS) published total St. Louis County employment data for 2014. Iron mining employment figures are taken from the Annual Report of the Inspector of Mines of Minnesota."
- Under "Data gaps," changed a year range from 2004-2013 to 2004-2014.

## DeSoto Parish

- Change "27,052 residents" to "approximately 27,000 people"
- Change "Production in the region fell from 2.5 trillion cubic feet in 2011 to 1.3 trillion cubic feet in 2015." to "Production in the region fell from 2.8 trillion cubic feet in 2011 to 1.87 trillion cubic feet in 2014."
- Changed the paragraph about employment from "Out of DeSoto’s 27,000 residents, 548 people (or about 2%) were employed in mining-support activities in 2013, which included oil and gas extraction. Of this group, about half (271 people) were employed specifically in support activities for oil and gas extraction. More recent employment data for the complete oil and gas industry in the parish is unavailable. The chart below shows the increase in employment in broader extractive industries — specifically mining, quarrying, and oil and gas extraction — in DeSoto Parish between 2005 and 2014." ...to... "Employment data for the complete oil and gas industry in DeSoto Parish is unavailable. The data that does exist shows that 271 people, about 1% of DeSoto’s 27,000 residents, work in support activities for oil and gas extraction. That figure does not include those working directly in oil and gas extraction itself. Data also exists for employment in the broader extractive industries—which includes oil and gas extraction but also mining and quarrying. The chart below shows the increase in employment in the broader extractive industries in DeSoto Parish between 2005 and 2014."
- In the second paragraph under "Revenue," change "In 2015, Louisiana received $190 million from gas severance taxes across the state, as well as $358 million from gas royalties for production on state-owned lands, up from $99.45 million and $158.82 million respectively in 2013." to "In 2015, Louisiana received $190 million from gas severance taxes across the state, up from $99.45 million in 2013.  It also received $85 million from gas royalties for production on state-owned lands and water bottoms, down from $159 million in 2013."
- Changed the sentence "From 2008 to 2015, the taxable value of property within the parish increased by 125%, or from $291.7 million to $750 million." to "From FY2009 to FY2015, the taxable value of property within the parish increased by 160%, or from $292 million to $750 million."
- Changed the year range in the next paragraph to FY 2005 - FY 2011, and added "FY" to "2014" at the end of the paragraph.
- Added missing footnote one, which cites the Census for population numbers.
- Various footnote fixes

## Greenlee County

- Change 2015 Morenci Mine production number from 901 to 902 million pounds

-------

Things from these three that still need attention:

- [ ] Make sure DeSoto production chart matches updates from Luke
- [ ] Verify that the DeSoto tax trends chart specifies that the x-axis refers to fiscal years

**Comment by splatts** [comment]
Thanks @coreycaitlin ! A few updates that weren't noted in there:

St. Louis - I think you got this previously, but we need to make sure the Iron Ore Production graph says St. Louis and not Minnesota. We explain this in the contextual.

De Soto - 1) Note the updated graph for Louisiana Natural Gas Production. I think the migration of the graph caused an extra "Natural" to be in there before Louisiana (but can't tell if that's just a glitch on my screen because it's not in my source doc?). 2) Note the update to the labeling of the Sales & Use graph: we need to specify that these are Fiscal Years by adding "(FY)" in the title.

**Comment by splatts** [comment]
@coreycaitlin and by "updates that weren't noted in there" - I mean in your above updates :) We noted these in the docs, but marked them in red or track changes since they were graphs and we couldn't highlight.

**Comment by coreycaitlin** [comment]
@ericronne Moving this here — could you send over the chart for Elko/Eureka employment?

**Comment by ericronne** [comment]
### [Elko/Eureka employment chart] (https://drive.google.com/open?id=0BwWYNZcEDfwabUpxQ21SNVJ5NU0)

![image](https://cloud.githubusercontent.com/assets/9259185/17303768/bb55593c-57e7-11e6-9965-bbbf34ca88b9.png)

**Comment by splatts** [comment]
FYI on the graph from Tarrant and Johnson Counties from #1603 (which is now closed) - the reason it looks different from last year's is because we are using an updated data source which is different from last year's. Last year we used Censtat, and this year we are using BLS. When calling Censtat this winter to inquire about data availability to update the chart, they told us BLS data should be used as it was more current and accurate. Hence, the notable difference. We clarified this further in the data availability charts.

**Comment by coreycaitlin** [comment]
- [ ] Add notes to all case studies re: last-updated dates

**Comment by coreycaitlin** [comment]
A number of the marked chart updates indicated typos, title changes, or legend fixes that we'd already caught. As far as I can tell, here are the **charts that need updating because the data has changed noticeably:**

- [ ] Wage and salary employment in Boone, Logan, and Mingo counties: Mining industry vs. all other industries

![screen shot 2016-08-05 at 5 13 15 pm](https://cloud.githubusercontent.com/assets/1450354/17453360/d9c98168-5b2f-11e6-81fa-5d561cfd6ec8.png)

- [ ] Wage and salary employment in Pima County: Mining industry vs. all other industries

![screen shot 2016-08-05 at 5 19 13 pm](https://cloud.githubusercontent.com/assets/1450354/17453458/cdfa3f34-5b30-11e6-8fa4-294d9d22de8c.png)

- [ ] Humboldt & Lander: Wage and salary employment in the gold mining industry

![screen shot 2016-08-05 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/1450354/17453515/d6af2d32-5b31-11e6-8cf1-12102e9b774b.png)

- [ ] DeSoto: Sales and use taxes — add "Fiscal years" to x-axis, or otherwise make clear that the years shown are FY, not calendar years.

- [ ] Oil production in Kern County

![screen shot 2016-08-05 at 5 33 58 pm](https://cloud.githubusercontent.com/assets/1450354/17453570/c7538e72-5b32-11e6-8fa4-bbb10044dcb9.png)

- @splatts @avarnum — I don't think we should add a new line to indicate percentage to the Kern County assessed property valuation chart, because this would mean designing a new type of chart (we don't have any others that show quite the same set of things), and I think users can get the same information by reading the chart carefully.

**Comment by coreycaitlin** [comment]
Miscellaneous additional things to update:

- [ ] Fixing fonts in all the images (Lato isn't loading in the SVGs, for some reason) (see also: #1708)
- [ ] Need new source for footnote 34 in the North Slope case study — @splatts or @avarnum, can you let us know what you find?

Also, as an FYI to Team Deloitte — many of the Quarterly Census links go to a blank search page, so I updated the formatting of those footnotes to include instructions for finding the reference so users can duplicate results, rather than pretending to link to the filtered view (which results in a broken-feeling user experience).

**Comment by avarnum** [comment]
Hi @coreycaitlin . Thanks for filtering the charts.  Please send us the preview links when they're ready and we'll review the cases before they go live. In terms of your advice on Kern County, we agree that we should not introduce a new graphic style. Let's stick with the stacked bar charts and include the percentages in the chart itself like we do with Boone and many others. You have this data from the line chart in the existing format. Please let us know if you need any help with that data.

**Comment by splatts** [comment]
@coreycaitlin thanks for clarifying on the Quarterly Census links and for re-formatting them so it's a more pleasant (and accurate) user experience. Good for us to know these links go dead as we think about this process next year (and years forward). And we're dealing with the same thing on footnote 34 for North Slope - looks like they *just* updated that particular source as of July 27th as well with a new year of data. @avarnum is going to call them today to get the source for the 2014 data we are citing since we can't find it on their site now that the data was updated.

**Comment by avarnum** [comment]
Hi @coreycaitlin @meiqimichelle , as discussed on today's standup, I'm including the first batch of minor catches for the county case studies. Please let me know if you have trouble finding the reference or have any questions. See below: 

Kern County: The oil production graph needs to be updated based on the latest version the IA sent. 

Greenlee County: In the first paragraph, the number cited should be "9.7 billion"

More to come.

**Comment by avarnum** [comment]
@coreycaitlin I spoke to folks in Alaska for the citation that was broken in the North Slope Case Study and they have resolved the issue. The footnote you mentioned should function now--I just tested it.

**Comment by coreycaitlin** [comment]
@avarnum Thanks! Can you take one more look at Kern County (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/case-studies/kern/)? PR #1717 hopefully fixed that one.

**Comment by avarnum** [comment]
@coreycaitlin PR #1717  looks like it does the trick! thanks

**Comment by avarnum** [comment]
@coreycaitlin 

A few minor catches for Tarrant and Johnson Counties: 

- Footnote 12 contains a typo. It should read "Censtats Databases"

- In the Revenue section, we should introduce the PSF with the following sentence: "Texas earmarks some of these tax revenues for investment in the Permanent School Fund (PSF)." Let me know if you have questions for where that should go.

**Comment by avarnum** [comment]
@coreycaitlin A few catches for Pima County: 

Let's change the last sentence in "Employment" to "…from 2004 through 2014." to match the graph below which runs from 2005 to 2014

Let's say in the 2nd paragraph of Pima County Revenue, "state does not disclose what percentage of the $19.9 million distributed to all cities…" to match the number above ($19.9 million) which was updated based on more recent data. It currently reads "$19 million"

**Comment by avarnum** [comment]
Updates to Humboldt and Lander: 

The production graph needs to be updated with the new one from the Word documents sent by the IA. It still has an old version missing some data.

**Comment by avarnum** [comment]
Updates to Elko & Eureka

The production graph needs to be updated with the new one from the Word documents sent by the IA. It still has an old version missing some data.

**Comment by coreycaitlin** [comment]
@avarnum Hi Andrew! For those charts — if they aren't listed above, it means I couldn't spot the differences in the charts. Could you write up a clear description of what changed (perhaps with a table of what data the charts *should* be showing) for these two charts?

- Humboldt & Lander production
- Elko & Eureka production

**Comment by coreycaitlin** [comment]
Okay! @avarnum and I chatted, compared the charts, and it looks like all is well with those two charts.

I'll get on fixing Pima County now!

**Comment by coreycaitlin** [comment]
Okay! I think we're about ready to close this out — @avarnum, have you had a chance to look these all over?

**Comment by coreycaitlin** [comment]
Okay, not quite done — we finally have 2013 data for both NV production charts. @ericronne is creating new images for those two charts.

**Comment by ericronne** [comment]
### [AML charts with outlined fonts] (https://drive.google.com/open?id=0BwWYNZcEDfwaeWN0OEVlSVBZQzA) < are there now :)

**Comment by ericronne** [comment]
### [Elko gold with 2013 data] (https://drive.google.com/open?id=0BwWYNZcEDfwaSjFVd1VRNnA4X1E)

**Comment by ericronne** [comment]
@coreycaitlin fixed link ^^

**Comment by ericronne** [comment]
### [Elko gold production as a line chart] (https://drive.google.com/open?id=0BwWYNZcEDfwaWk5pdW1NSXhIVkE)
![image](https://cloud.githubusercontent.com/assets/9259185/17634086/74a938fc-6096-11e6-9605-9164ef090b85.png)

### [Humbolt gold production as a line chart] (https://drive.google.com/open?id=0BwWYNZcEDfwabzNQcEZrUGQwcmM)
![image](https://cloud.githubusercontent.com/assets/9259185/17634117/a378b068-6096-11e6-94fc-c69b2409c4fb.png)

**Comment by ericronne** [comment]
A few folks raised concerns about this AML chart, and wondered if another design might communicate more effectively....
![image](https://cloud.githubusercontent.com/assets/9259185/17671754/424c8ef0-62de-11e6-9822-c8a274f975fe.png)

Here's an alt design, which is hopefully more clear...
![image](https://cloud.githubusercontent.com/assets/9259185/17671783/5d0e56d8-62de-11e6-87cb-d90ea3cc4fa8.png)

This design leverages some of the approaches already in use on the site, such as the multiple line charts employed in "megacharts" on state pages. It's also simpler in terms of color (dark blue always refers to funds from collected fees, and light blue to interest-earnings funds).

Feedback coveted, per usual! :)

**Comment by meiqimichelle** [comment]
Moving the AML work over to #1682 .

**Comment by coreycaitlin** [comment]
- [ ] pull in line charts with 2013 data for NV gold production
- [ ] remove the phrase that says _how many fewer_ mines are in Boone, Logan, and Mingo counties
- [ ] clarify that the DeSoto parish school board attributed the increase in property values beginning in 2008 to the discovery of shale gas

**Comment by avarnum** [comment]
Hi @coreycaitlin I think this list looks good. However, I think we need to wait on the second point ("remove the phrase that says how many fewer mines are in Boone, Logan, and Mingo counties") until after the September Co-Chairs meeting. That was one that the Online Advisory Group felt needed to be resolved at Co-Chairs.

**Comment by meiqimichelle** [comment]
@avarnum My understanding from the online advisory group was that that we *should* make that change -- it was one that we introduced to clarify, but we were happy to change it back to the wording approved previously. I believe it was something else (perhaps the entire paragraph re-writes based on new data?) that needed to go back to the Co-Chairs. @usEITI do you remember on this point?

**Comment by avarnum** [comment]
Hi @meiqimichelle . You are right. Please return that phrase to what was approved previously.
