### ISSUE TITLE
State artwork rotation

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1605]
Users might prefer to see their states rotated in ways different than they appear in the projection we're using.

**EG, Utah is rotated like this…**
![image](https://cloud.githubusercontent.com/assets/9259185/16849857/01f6592e-49c2-11e6-8c64-bf0bca55b96f.png)

**But ideally would look like this...**
![image](https://cloud.githubusercontent.com/assets/9259185/16849878/193d7afe-49c2-11e6-9d3b-f7372f0113f5.png)

**Comment by coreycaitlin** [comment]
We haven't heard any further user feedback about this — the projections we're using seem to make sense to most folks (though AK would like to be larger). Seems like the slight rotation isn't causing issues, so closing this issue for now.
