### ISSUE TITLE
State page overview design: Make more interesting

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1612]
Currently the state-page "overview" (intro) sections are a little drab, consisting simply of text in a gray box...
![image](https://cloud.githubusercontent.com/assets/9259185/16887613/c3bca552-4aa0-11e6-98cc-5fdae7c2acfc.png)

Adding a very-simple map is one way to easily add interest and visually anchor the page. Perhaps it doesn't need to be anything more than a map of the state (at least for now). This will at least serve to instantly reinforce to users that they've arrived at the right place (since they may well have clicked on that state's shape on the national map in order to reach this page).
![image](https://cloud.githubusercontent.com/assets/9259185/16887578/98edc61c-4aa0-11e6-8125-40a715194818.png)

**Comment by ericronne** [comment]
@meiqimichelle @coreycaitlin @gemfarmer 👍 ?

**Comment by coreycaitlin** [comment]
👍

**Comment by meiqimichelle** [comment]
@ericronne Any thoughts on what this might look like for horizontal states?

**Comment by coreycaitlin** [comment]
Here's our new/improved/revised intro content for a few nice, meaty states:

> Natural resource extraction varies widely from state to state. In Texas, extractive industries accounted for 13.6% of gross domestic product (GDP) in 2013, and jobs in the extractive industries made up 3.8% of statewide employment.
> 
> Texas leads the nation in production of:
> 
> * Oil: 31% of U.S. production
> * Natural Gas: 28% of U.S. production
> * Wind: 21% of U.S. production
> 
> Natural resource ownership in the U.S. is closely tied to land ownership. Land can be owned by citizens, corporations, Indian tribes or individuals, or governments (for instance, federal, state, or local governments). Many USEITI datasets only cover natural resource extraction on federal land, which represents 1.8% of all land in Texas.
> 
> Texas also borders an offshore area with significant natural resource extraction, which may contribute to the state's economy. For production and revenue data about offshore extraction near Texas, see the [Western Gulf of Mexico]().
> 
> For a detailed view of how the extractive industries affect communities in Texas, read more about [Tarrant and Johnson Counties]().
> 
> -------
> 
> Natural resource extraction varies widely from state to state. In Montana, extractive industries accounted for 5.7% of gross domestic product (GDP) in 2013, and jobs in the extractive industries made up 12.4% of statewide employment.
> 
> Natural resource ownership in the U.S. is closely tied to land ownership. Land can be owned by citizens, corporations, Indian tribes or individuals, or governments (for instance, federal, state, or local governments). Many USEITI datasets only cover natural resource extraction on federal land, which represents 29% of all land in Montana.
> 
> The state of Montana chose to participate in an extended USEITI reporting process, so this page includes additional state revenue and disbursements data, as well as contextual information about state governance of natural resources.
> 
> -------
> 
> Natural resource extraction varies widely from state to state. In Wyoming, extractive industries accounted for 33% of gross domestic product (GDP) in 2013.
> 
> Wyoming leads the nation in production of:
> 
> * Coal: 39% of U.S. production
> 
> Natural resource ownership in the U.S. is closely tied to land ownership. Land can be owned by citizens, corporations, Indian tribes or individuals, or governments (for instance, federal, state, or local governments). Many USEITI datasets only cover natural resource extraction on federal land, which represents 48.1% of all land in Wyoming.
> 
> The state of Wyoming chose to participate in an extended USEITI reporting process, so this page includes additional state revenue and disbursements data, as well as contextual information about state governance of natural resources.
> 
> For a detailed view of how the extractive industries affect communities in Wyoming, read more about [Campbell County]().

We can also pull the land ownership map up to this section, as we'll be removing it below 🎉

**Comment by ericronne** [comment]
It might be nice to have a flexible design, where the image for taller states occupies fewer columns that the image for wider ones. The text would narrow or widen accordingly. Like so?...

![intro - az](https://cloud.githubusercontent.com/assets/9259185/17814267/af198f38-65f4-11e6-9171-4401fdcca5d1.png)
![intro - mt](https://cloud.githubusercontent.com/assets/9259185/17814266/af15ee46-65f4-11e6-97d0-bb644b2cc2b0.png)
![intro - tn](https://cloud.githubusercontent.com/assets/9259185/17814265/af132d8c-65f4-11e6-8083-0feca2d00594.png)
![intro - tx](https://cloud.githubusercontent.com/assets/9259185/17814264/af130122-65f4-11e6-8d4f-57bcee9dbe28.png)
![intro - wy](https://cloud.githubusercontent.com/assets/9259185/17814263/af12c6d0-65f4-11e6-84e2-bf4e195d6da4.png)

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/17909500/56addfb2-694a-11e6-9941-2e2864cb90f8.png)

**Comment by ericronne** [comment]
Here's how CA might look. I've reduced its size (otherwise HUGELY tall), and centered it in the space.

Even with this reduction, it will likely extend beyond the fold. So i've also **scooted this entire right-side unit upwards** so that the baselines of "California" and "Land ownership" align. (This would apply to all states.)

![image](https://cloud.githubusercontent.com/assets/9259185/17910330/ff1d5b66-694d-11e6-97f8-73553b33e262.png)

**Comment by meiqimichelle** [comment]
This is mostly implemented. @meiqimichelle will do one more check for some small changes. Also, @coreycaitlin found a usability issue here -- tester did not scroll. User was very excited about the side nav once she saw it though! @ericronne , how would you feel about moving the map down a bit so it is partially hidden? Or, something else.

**Comment by ericronne** [comment]
Should we add a scroll prompt?

**Comment by ericronne** [comment]
@coreycaitlin and @meiqimichelle chatted this am about how we might best encourage users to scroll on these pages. (This concern is based on anecdotal evidence that some users hesitate to do so.)

The solution below brings the much-touted sticky nav to the top. One potential gotcha here is that text wraps can sometimes result in widows. Worth a try?

cc @gemfarmer @shawnbot 

![image](https://cloud.githubusercontent.com/assets/9259185/18450566/34e61a02-78f9-11e6-9e00-27bb2af58608.png)

**Comment by meiqimichelle** [comment]
This is mostly done. Remaining issue might be a part of #1702 -- removing padding at the bottom of maps so stuff below those maps ends up in the right place.

**Comment by ericronne** [comment]
nitpix too ;)

... pairing is cairing.
