### ISSUE TITLE
Double-check hydroelectric unit

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1613]
Feedback from Bob and Chris: Hydroelectric should be MWh, not kWh — double-check this and implement.

**Comment by dmsnell** [comment]
kWh is a very granular unit rarely used outside of individual residential or industrial consumption. TWh is much more common for generation plants. For example, the Three-Gorges Dam and the Itaipu Dam both produce near 100 TWh each year, whereas typical large power-plants will be generating multiple or tens of TWh per year.

hope it helps! `¯\_(ツ)_/¯`

**Comment by gemfarmer** [comment]
@coreycaitlin, @dmsnell I'm not going to comment on the default units used for particular products, but I do think that it would be useful (maybe a later enhancement) for people to be able to toggle to units that make sense for them. 

I don't have an issue for this, but I did mention it [here](https://github.com/18F/doi-extractives-data/issues/1590#issuecomment-232562280) and would be interested in feedback as to whether or not this makes sense/would be as helpful as I'm imagining it would be.

**Comment by gemfarmer** [comment]
Just checked and the numbers are correct, but the units are not consistent with the data. They should be in MWh as @mentastc alluded to. 

Data:
https://github.com/18F/doi-extractives-data/blob/dev/data/production/all-production.tsv#L682

**Comment by coreycaitlin** [comment]
Sorry @dmsnell — I was trying to get some cryptic notes off of post-it notes and into GitHub on Friday afternoon so we could keep track of things, and this one definitely took a little bit more investigation before we knew what the next step was!

**Comment by dmsnell** [comment]
no worries @coreycaitlin! I just wanted to mention it because I've seen lots of issues here where I couldn't figure out how to get started because of a lack of information in the description (#1609 and #1605 for example). 

it's hard to write a comment like this without feeling like I'm barking at y'all - I'm not though 😺

**Comment by meiqimichelle** [comment]
@dmsnell For sure! We're going to see about getting some issues specifically fleshed out better for open source contributions, and tag them as such, to make it easier for folks outside the project to jump in. As you can tell, right now we're not managing issues with that use case in mind, and don't want to do with with *all* issues unnecessarily. Hopefully, we this will get a little clearer soon!

**Comment by meiqimichelle** [comment]
Done!
