### ISSUE TITLE
State pages: Explain geothermal differences

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1614]
On the state pages, for production on federal lands, we need to clarify why there are so many different sets of geothermal data, and update the titles accordingly.

**Comment by coreycaitlin** [comment]
Next step: pair with @gemfarmer on figuring out what's happening in the data.

**Comment by coreycaitlin** [comment]
We dug into this, and it looks like the standard unit of measurement for geothermal energy in the federal production dataset is kilowatt hours. There are a few counties that report it differently:

* Dona Ana County, NM reports `direct use, million gallons`
* Churchill County, NV reports `direct use, hundred gallons`
* Lassen County, CA reports `direct use, million BTUs`
* Lassen County, CA reports `electrical generation, other` (this is currently showing up as "units")
* Lake County, CA; Sonoma County, CA; and Beaver County, UT report `electrical generation, thousand pounds`
* Inyo County, CA reports `sulfur, sulfur` (no unit listed)

**Comment by gemfarmer** [comment]
To see what we are talking about in the source data:

[direct use, million gallons](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/federal-production.tsv#L4935)
[direct use, hundred gallons](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/federal-production.tsv#L391)
[electrical generation, other](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/federal-production.tsv#L4182)
[electrical generation, thousand pounds](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/federal-production.tsv#L401)
[sulfur, sulfur](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/federal-production.tsv#L3428)

**Comment by coreycaitlin** [comment]
Talked to Chris, and this is fine for now, because it accurately represents what's in the data. I'm adding a note in the documentation for the federal production dataset, and then we can close this out!

**Comment by meiqimichelle** [comment]
Closed with #2093.
