### ISSUE TITLE
Megachart tab interaction: don't make type bold on hover

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1620]
Currently the font turns bold and an underscore is added on mouseover. We should just add the underscore, without making the font bold....

![image](https://cloud.githubusercontent.com/assets/9259185/16929946/abed7c10-4cff-11e6-9acc-2efe16b063a3.png)

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer 

No rush, natch.

**Comment by gemfarmer** [comment]
@ericronne this was on my radar and was just fixed and merged as of [this PR](https://github.com/18F/doi-extractives-data/pull/1604)!
