### ISSUE TITLE
Case studies: Redesign main page

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1632]
It might help clarify site structure if we bring the [case studies main page](https://useiti.doi.gov/case-studies/) into line with all of the other "level two" pages stylistically (and navigationally), applying the wide blue bar design.

I'm onnit...

cc @meiqimichelle @coreycaitlin @gemfarmer @shawnbot @usEITI

**Comment by ericronne** [comment]
# Draft, inspired by the [explore data / national page](https://github.com/18F/doi-extractives-data/issues/1520)

![image](https://cloud.githubusercontent.com/assets/9259185/17026627/4fbc5f14-4f26-11e6-8c2b-d6162a499b98.png)

*If all think this is worth trying, i will design a mouseover state for the round buttons, showing the name of the case study and commodity.

**Comment by meiqimichelle** [comment]
@ericronne Nice! I like getting the case studies back in line with the 'blue bar' look on the other pages. Is there something that might distinguish the 'blue states that are clickable' on the 'explore data' section versus this page, which has the same blue states but I'm assuming only the round buttons are clickable? Or! Likely! You were getting there, but it didn't make sense to redesign the map until we'd had a chance to 👍 or 👎 to the idea generally.

**Comment by ericronne** [comment]
@meiqimichelle you mean this!...

![image](https://cloud.githubusercontent.com/assets/9259185/17027139/537e925a-4f28-11e6-875c-eeda0a799522.png)

**Comment by meiqimichelle** [comment]
💥

**Comment by ericronne** [comment]
Hovernotion...

![image](https://cloud.githubusercontent.com/assets/9259185/17030585/c30f511a-4f35-11e6-8995-cbaafe669395.png)

**Comment by ericronne** [comment]
@coreycaitlin &c note that i rearranged the name, to prioritize both the commodity and state. That work?

**Comment by meiqimichelle** [comment]
Over to me for implementation

**Comment by meiqimichelle** [comment]
@ericronne We needs icons! Any change you can make svgs for each one of those dots and link us up?

**Comment by gemfarmer** [comment]
- [ ] add ribbon layout to top of page
- [ ] create SVG layer for "points of interest" to add to map
- [ ] create tool tip

**Comment by ericronne** [comment]
@meiqimichelle yes.

**Comment by ericronne** [comment]
### SVG files for the circle icons [are right here] (https://drive.google.com/open?id=0BwWYNZcEDfwadEdFbVRKajVoZDQ).

Included reversed ones for hover (but may end up replacing those later if they don't look right, they were created with haste). I won't be surprised if some of these misbehave, so just let me know.

**Comment by meiqimichelle** [comment]
This is partially implemented already. Remaining: tooltips!

**Comment by ericronne** [comment]
### Here's a [simplified iron icon] (https://drive.google.com/open?id=0BwWYNZcEDfwaTm5nZzNYejlUZm8), which will hopefully fix the rendering issue.

**Comment by meiqimichelle** [comment]
@ericronne the simplified icon is coming through like this (not the gray and black, the cut-off icon:
![screenshot 2016-09-08 13 17 36](https://cloud.githubusercontent.com/assets/4827522/18365222/afdb03ca-75c6-11e6-88f8-0b7d85d4b157.png)

**Comment by ericronne** [comment]
@meiqimichelle hopefully [**this reversed-out iron icon svg**] (https://drive.google.com/open?id=0BwWYNZcEDfwaNTh3YVRfUDY4dG8) will work!

**Comment by ericronne** [comment]
@meiqimichelle and here is [another pass at the iron svg] (https://drive.google.com/open?id=0BwWYNZcEDfwaLTNLd0JBeDBfT1k) and [the reversed version] (https://drive.google.com/open?id=0BwWYNZcEDfwaTUxnYVZlX3dPWkE) to boot

**Comment by ericronne** [comment]
@meiqimichelle ok how about [**this** one] (https://drive.google.com/open?id=0BwWYNZcEDfwaZ3VXSG50M2NaWUk) and [**this** one] (https://drive.google.com/open?id=0BwWYNZcEDfwaWVRQNmF3SEp1ak0)?

**Comment by meiqimichelle** [comment]
@ericronne Better, still slightly slightly slightly off, but perhaps very much close enough:

<img width="1048" alt="screenshot 2016-09-09 14 35 47" src="https://cloud.githubusercontent.com/assets/4827522/18403631/cee9419e-769a-11e6-9b02-9e39834ca79c.png">
