### ISSUE TITLE
State page breadcrumb edit suggestion

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1634]
@coreycaitlin Thinking we should change the breadcrumb to read "Explore data," rather than "State Profiles." This will bring it into line with the IA. Cool?

cc @meiqimichelle

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/17031145/539f41f2-4f38-11e6-951f-a46abc8c2591.png)

**Comment by ericronne** [comment]
Yay! Who implements?

**Comment by coreycaitlin** [comment]
Fixed!
