### ISSUE TITLE
Visual bugs: Glossary

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1635]
A few issues with the glossary:
- There's an extra bar of space (the width of a scroll bar) to the right of the glossary when it's open.
- Too much space between the term title and the definition

**Comment by meiqimichelle** [comment]
@coreycaitlin @ericronne Which browser is this happening in? And which page? I'm not seeing it, but I know it is there.

**Comment by ericronne** [comment]
This is the ludicrously version numbered chrome 52.0.2743.116...

![image](https://cloud.githubusercontent.com/assets/9259185/18513136/c3ea350e-7a51-11e6-9944-6786948eacdb.png)

This is safari 9.1.2...

![image](https://cloud.githubusercontent.com/assets/9259185/18513189/1c95cbd2-7a52-11e6-88a8-a82cf568db8c.png)

**Comment by ericronne** [comment]
May want to explore #1564 when we deal with this

**Comment by coreycaitlin** [comment]
Half of this got fixed, and the scrollbar space issue seems to be particularly tricky to fix. We may need to live with that small gray bar on the right. Reopen if needed.
