### ISSUE TITLE
Prep documentation for impending major version bump

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1639]
We will be soon merging the work on `state-pages` to `dev`.

We should:

- [ ] Update the current README on `dev` so that people know a large change is coming, and
- [ ] Update the README on `state-pages` so that people know what is deprecated in that work, and how to orient themselves in the new structure.

**Comment by gemfarmer** [comment]
@meiqimichelle based on our conversation earlier today about the state-page merge, is it safe to say that we can close this issue?

**Comment by meiqimichelle** [comment]
Yup! Closing!
