### ISSUE TITLE
State pages: add scale reference to bar charts

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1650]
@ericronne 's latest notion for discussion:

![image](https://cloud.githubusercontent.com/assets/9259185/16773251/d6d4ca92-481c-11e6-8d9f-b57ca54bedc5.png)

**Comment by meiqimichelle** [comment]
@ericronne How final is this design? Should we try to implement, or shall we test in another way first?

**Comment by ericronne** [comment]
Implement away! But we should be mindful of vertical space. If it gets too generous, things could fall apart visually.
