### ISSUE TITLE
Implement (admittedly not quite final) mobile design for state page

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1670]
In the interest of getting mobile underway in earnest, and keeping @gemfarmer from getting too bored 😂  ...

**Comment by ericronne** [comment]
WIP design is in issue #1523 

### [Sketch file, woot] (https://drive.google.com/open?id=0BwWYNZcEDfwac1pMSFBLNXRvNEE)

**Comment by gemfarmer** [comment]
just waiting on a Sketch upgrade and then I'll feast my eyes on it.

**Comment by gemfarmer** [comment]
As always, looks great @ericronne . One question. For the megachart (below), were you imagining that the chart would be horizontally scrollable just within that section? 

<img width="399" alt="screen shot 2016-07-26 at 5 32 32 pm" src="https://cloud.githubusercontent.com/assets/4803473/17157728/fd33cf18-5356-11e6-9fab-8a057013da41.png">

**Comment by ericronne** [comment]
Yep. Like below. Little numbered buttons (see teal rectangles) would (ideally) slide into place at the top as you navigate through the columns, to represent the phases. Thoughts?...

![image](https://cloud.githubusercontent.com/assets/9259185/17175562/d6533196-53cd-11e6-820f-bd4840818302.png)

Ideally we'd have a sticky header...
![image](https://cloud.githubusercontent.com/assets/9259185/17175741/e050f178-53ce-11e6-9574-f8e9b637d821.png)


But we also have this sticky nav, so we have to watch out for crowding (and i don't know if this is a pain to do, either. If it takes too long, go sans sticky. Mobile not a primary aud)...

![image](https://cloud.githubusercontent.com/assets/9259185/17175898/bbd8b154-53cf-11e6-96d5-063c52e8a0dd.png)

**Comment by gemfarmer** [comment]
Nice. I like it!

**Comment by coreycaitlin** [comment]
@ericronne @gemfarmer What's remaining from this issue? Could you split any remaining bits of mobile-design implementation into new issues?

**Comment by ericronne** [comment]
I don't think any of the design has been implemented, but the chart is "usable" in it's current form, and a number of other issues are more pressing. So i don't know if we'll get to this :/
