### ISSUE TITLE
Content: Edit Budget & Audit intro

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1691]
We're ready to edit down the Budget and Audit introduction content, so it's focused on framing and links.

Once we have final content from the IA, we'll include that as a downloadable PDF.

**Comment by meiqimichelle** [comment]
This is blocked until we get the final version from Deloitte.

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] edit down the intro page
- [ ] upload the file
- [ ] put a button on the page

**Comment by coreycaitlin** [comment]
@meiqimichelle — let me know if you think we should include more/fewer links on the page. I've taken a stab at it, but could use your perspective.
