### ISSUE TITLE
Images for AML

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1696]
This is a continuation of #1618 to track only the necessary images. Preview of page [here](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/aml-fees/) .

We need:

1) Growth of AML fund over time
![screenshot 2016-08-01 10 45 03](https://cloud.githubusercontent.com/assets/4827522/17303326/0cbf7ad6-57d5-11e6-9b7d-fa509afe338d.png)

2) Allocation of unappropriated balance
![screenshot 2016-08-01 10 46 51](https://cloud.githubusercontent.com/assets/4827522/17303372/4604447a-57d5-11e6-9543-46e47545d6d2.png)

3) Largest grant recipients in FY2016
<img width="933" alt="screenshot 2016-08-01 10 49 30" src="https://cloud.githubusercontent.com/assets/4827522/17303473/b432d650-57d5-11e6-87d2-84195448a51f.png">

4) A waterfall/tree map
![image](https://cloud.githubusercontent.com/assets/9259185/17194102/f5121752-541b-11e6-9d7a-2310d7993b67.png)

**Comment by ericronne** [comment]
**This** is Indiana 😡 
![image](https://cloud.githubusercontent.com/assets/9259185/17311010/c3392130-580d-11e6-8ebb-d9c5592282d3.png)

sincerely, Eric
Chicago, IL

**Comment by coreycaitlin** [comment]
Notes from @lmhawbaker:

In the waterfall money graphic...

- The 4.3b bucket should be labelled "Construction of funded or complete reclamation projects"
- We should call the 2.5b bucket "Not yet disbursed", and the largest category within it (2.4b) should be called "Fees collected, not yet disbursed"

In the graph of unappropriated allocations, we should include the phrase "subject to congressional appropriation" after "Federal expenses"

**Comment by ericronne** [comment]
Updated tree map, with (i believe) *accurate proportions!*

Note: i changed "complete" to "completed" in the 4.3b note, because it seems more clear to me. Happy to change it back, if i'm off base: "Construction of funded or completed reclamation projects."

![image](https://cloud.githubusercontent.com/assets/9259185/17338694/09ab406c-58ae-11e6-932f-055fefd5dc24.png)

**Comment by coreycaitlin** [comment]
We also need to make a visual for the annual AML fees:

<img width="1154" alt="screen shot 2016-08-02 at 10 50 35 am" src="https://cloud.githubusercontent.com/assets/1450354/17339046/ef71e1d8-589e-11e6-8eb5-d458a3419bc9.png">

**Comment by ericronne** [comment]
# Moar AML Chartness, Woo!!!

### AML funding and spending
Here's the [original chart] (https://cloud.githubusercontent.com/assets/4827522/16970091/7f1b67ae-4dce-11e6-8614-9c508b21e929.png) for proofing.
![image](https://cloud.githubusercontent.com/assets/9259185/17350343/9b5db0e8-58eb-11e6-964a-b511742c9ac3.png)


### Allocation of unappropriated balance
Here's the [original chart] (https://cloud.githubusercontent.com/assets/4827522/16970122/c1967ea2-4dce-11e6-9466-7d28896cc61e.png) for proofing.
![image](https://cloud.githubusercontent.com/assets/9259185/17350385/dc590d36-58eb-11e6-9c81-d0777c8cd7ce.png)

### Growth of AML fund's unappropriated balance
Here's the [original chart] (https://cloud.githubusercontent.com/assets/4827522/16970114/ad12786e-4dce-11e6-8237-f8f8581ffbae.png) for proofing.
![image](https://cloud.githubusercontent.com/assets/9259185/17350400/02f7d896-58ec-11e6-8c3b-4b5ff05abaf2.png)

### Largest grant recipients in FY2016
Here's the [original chart] (https://cloud.githubusercontent.com/assets/4827522/17303473/b432d650-57d5-11e6-87d2-84195448a51f.png) for proofing.
![image](https://cloud.githubusercontent.com/assets/9259185/17350431/3bbc97e8-58ec-11e6-8df5-791d4a4ce694.png)


And totally tempting fate by doing this, but here are the ...
### [SVG versions] (https://drive.google.com/open?id=0BwWYNZcEDfwaeWN0OEVlSVBZQzA) for implemenation

**Comment by ericronne** [comment]
# And this one

### AML annual fees
The [original chart] (https://cloud.githubusercontent.com/assets/1450354/17339046/ef71e1d8-589e-11e6-8eb5-d458a3419bc9.png) for proofing.

![image](https://cloud.githubusercontent.com/assets/9259185/17370264/fd6fba36-5960-11e6-99cc-06a1b199fa10.png)

### I've added it to the [SVG collection] (https://drive.google.com/open?id=0BwWYNZcEDfwaeWN0OEVlSVBZQzA) for implementation

**Comment by lukehawbaker** [comment]
@ericronne these look great! Have gone through each and compared to the originals and they look good. The ups and downs in the line graphs are sharper and more severe in these than the originals, but I imagine that's from changing from one year increments to two year increments. They look accurate, so as long as they were built off of the data we provided, we're golden. 

Also my sincere apologies that the use of Indiana got past me. I can promise you it was Illinois when I sent it to get converted to an Illustrator file. (Still..as someone born in Chicago...I should have noticed that sooner)

**Comment by meiqimichelle** [comment]
@lukehawbaker thanks for the review! I'll get these up online on `dev` momentarily. Where momentarily means...likely within the hour.
