### ISSUE TITLE
Bar charts: flexible width text

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1700]
From #1676 
## Expected Behavior
Each row in a bar chart grid should have a normalized height, but the `.chart-description` text should be variable, adapting to the minimum allowable height for a given row.
## Actual Behavior
Currently, due to the flexbox styling, each bar chart in a grid of bar charts has a normalized height. We have standardized the height (`min-height: 100px;`) of the `.chart-description` text above the bar charts so that the title can be variable.
## Steps to reproduce the behavior
- [ ] make the height of the `.chart-description` variable by unsetting it.
- [ ] set a min-height for the bar chart svg. Because it is an svg, this height should be responsive.
- [ ] probably other unforeseeable things

cc @ericronne

**Comment by meiqimichelle** [comment]
This is pending a slight redesign from @ericronne on the bar charts. Maybe we end up implementing that redesign, which obviates this problem.

**Comment by ericronne** [comment]
To wit ...
![image](https://cloud.githubusercontent.com/assets/9259185/18073512/44c91a82-6e2c-11e6-88aa-4dd878fdcbf0.png)

(summary always visible, and we should discuss the fine pts live, @gemfarmer! ;)

**Comment by meiqimichelle** [comment]
We did the redesign. Closing!
