### ISSUE TITLE
State page without Javascript

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1710]
When a user doesn't have JS enabled, display content in a way that still delivers the primary focus of the page. For the state pages, this means 
- [ ] showing the informational bar chart text
- [ ] displaying the county map tables
- [ ] ensuring that all tabs work with CSS only
- [ ] hiding buttons that are only JS accessible
- [ ] hiding maps elegantly or displaying them in a way that demonstrates the need to turn on JS
- [ ] other things

**Comment by coreycaitlin** [comment]
Closing in favor of #2606
