### ISSUE TITLE
Visual bug: "Oil" and "Gas" in megachart should be recolored, and not links

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1713]
## Expected Behavior
The words shouldn't be links, and they should be colored to match their bar segments.
![image](https://cloud.githubusercontent.com/assets/9259185/17452952/ae94cd00-5b29-11e6-853a-525ed9ba96fd.png)
Oil - `#2E4E24`
Gas -`#587F4C`

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/17452947/95749602-5b29-11e6-8a63-11a31f8ac610.png)

**Comment by gemfarmer** [comment]
Totally agree!

**Comment by meiqimichelle** [comment]
This is fixed on `dev` with #1809. 🎉
