### ISSUE TITLE
Visual bug: Case study chart titles

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1722]
For the case study chart titles, I used the base h3 styling, but they're feeling a little bigger than they need to be. Let's make them smaller, either by targeting h3s on this page or by giving them different markup.

@ericronne could you add a screenshot of how it *should* look?

**Comment by ericronne** [comment]
I have these as 16px bold, which i think is our para-med +bold

![05-line chart - kern oil prod](https://cloud.githubusercontent.com/assets/9259185/17672615/d2ce23b8-62e2-11e6-8a08-8f0cb8bf0eff.png)

**Comment by meiqimichelle** [comment]
This is done! 🎉
