### ISSUE TITLE
Land and water conservation act data

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1730]
We should pull the more detailed land and water conservation act data that we have into the disbursements part of the national profile. It does *not* need to be in the same bar chart, unless that makes sense. We should investigate whether we can/should pull state data into related state pages (not sure if the data supports this).

**Comment by meiqimichelle** [comment]
This might be the latest file: 
[All LWCF Funding incl documentation_forEITI072015.xlsx](https://github.com/18F/doi-extractives-data/files/427555/All.LWCF.Funding.incl.documentation_forEITI072015.xlsx)

Info on this file:
`This file includes the data in several sheets. The data cover grant awards and approps for federal land acquisition projects from 2011-2014. Three grant programs are covered: NPS American Battlefield Protection Program (ABPP), FWS Cooperative Endangered Species Conservation Fund (CESCF) and the NPS Stateside Grants. I think you have write-ups on two of these programs already (if not, there are succinct descriptions at www.doi.gov/lwcf), but I probably need to get you something on the ABPP.`

**Comment by meiqimichelle** [comment]
Final data: [LWCF_incl-documentation_2016-update.xlsx](https://github.com/18F/doi-extractives-data/files/443352/LWCF_incl-documentation_2016-update.xlsx)

**Comment by meiqimichelle** [comment]
CESCF: Cooperative Endangered Species Conservation Fund
ABPP: American Battlefield Protection Program
LA: Land Acquisition

**Comment by coreycaitlin** [comment]
Note to self: The next step is to pull in a broad summary for all funds, link to the [deeper data](https://github.com/18F/doi-extractives-data/tree/lwcf-disbursements/data/disbursements/lwcf/) on the national page, then slightly revise the state content (since we now do have this data, but aren't showing it).
