### ISSUE TITLE
Offshore data regions/areas

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1740]
Dump existing data onto a layout that uses our state profiles pages as a start.

**Comment by gemfarmer** [comment]
@coreycaitlin @shawnbot @meiqimichelle to clarify, we left the conversation that we had last week with the resolution that we would (for now):
- treat offshore regions as "states" and offshore areas as "counties"
- add content on the offshore-region level
- remove offshore area pages
- _not_ cover protraction data?
- _not_ have a offshore landing page
