### ISSUE TITLE
Interactive chart map spillover

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1747]
Spillover from #1744 

Comments refer to **[this version of the map / table] (https://federalist.18f.gov/preview/18F/doi-extractives-data/interactive-chart-map/states/UT/#employment)**

- [x] Make SVGs not overlap. Suggested method [here](https://github.com/18F/doi-extractives-data/issues/1695)
- [ ] ~~add tooltip on map hover~~ This is tracked in #1804, which is now a general tooltip issue
- [x] @ericronne nit pics

**Comment by ericronne** [comment]
@gemfarmer (or @meiqimichelle) might it be more efficient to do this as a live bug squashing hangout?

**Comment by gemfarmer** [comment]
Work is in #1892

**Comment by meiqimichelle** [comment]
Tooltips are donezo!
