### ISSUE TITLE
Updates to How-it-Works/Revenue: Coal Excise Tax and AML Fees

### ISSUE THREAD

**Issue by avarnum** [18F/doi-extractives-data#1755]
@meiqimichelle 

We need to update the "Payments to extract natural resources from any land or water in the U.S." section to include information about Coal Excise Tax revenues and AML fees as these fees apply to non-Federal lands as well. 

See below for the screenshot of where they could go: 
![coal excise tax and aml fee additions](https://cloud.githubusercontent.com/assets/20306455/17747752/3b9fd06a-6484-11e6-985a-3beb6ca05a2e.JPG)

For Coal Excise: 

"In the United States, one of the taxes coal producers must pay is a federal excise tax when they mine coal. Producers pay the tax when the coal is first sold or used. (Footnote: A producer is any person or entity that owns the coal after it’s mined from the ground.) The tax does not apply to lignite or to coal mined in the U.S. for export. Learn more about the coal excise tax. (Link to page)"

For AML: 

"The Abandoned Mine Land (AML) Reclamation Program uses fees paid by present-day coal mining companies to reclaim coal mines abandoned before 1977. Learn more about the AML program. (Link to page)"

cc @splatts @lukehawbaker

**Comment by avarnum** [comment]
Sorry, the Coal Excise Tax and AML Information could go after all of the Corporate Income Tax info. 

![coal excise tax and aml fee additions](https://cloud.githubusercontent.com/assets/20306455/17747917/f63a65e8-6484-11e6-9085-fdc0483c8257.JPG)

**Comment by meiqimichelle** [comment]
Closed with #1832
