### ISSUE TITLE
Withheld data spillover

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1773]
Spillover issue from #1758 

- [ ] Decide how we are going to filter bar charts. Is it only when there is no data for every year? Or is it when there is no data or withheld data? Do we filter if every year is withheld?
- [ ] Select box show "no data" only when there is no data

New discovery:
- [ ] there is withheld data showing up in maps and charts outside of federal production. This is likely caused by `eiti-data-map.js` mistakenly defaulting values to `Withheld` instead of `no-data`, or in other words `null` instead of `undefined`. This will likely clear up many of the quirks I was noticing, primarily the select box no data bug mentioned above. Also, the `county-map.html` template _could_ be the culprit, setting `undefined` values to `null`

@coreycaitlin @ericronne we should set a time to decide which bar charts are filtered!

**Comment by ericronne** [comment]
I feel like we shouldn't ignore when data has been withheld, though it would be awkward to show an entire (blank) chart if that's all of the info we have. Sure, let's chat!

**Comment by gemfarmer** [comment]
@ericronne agreed. And that is why I left them unfiltered for now. It seemed a little strange to remove them, because `Withheld` data is interesting/important, but it also looks crummy at the moment.

**Comment by ericronne** [comment]
If it doesn't mess with the sorting logic, what if we ran such charts at the end, like Oil & Gas here?...

![image](https://cloud.githubusercontent.com/assets/9259185/17902840/934e4f90-692e-11e6-80c4-4cd48981fb21.png)

**Comment by gemfarmer** [comment]
Hmm yeah, I like that. We could also have those hidden in some kind of accordion?

**Comment by ericronne** [comment]
Do we know about how many we're talking about?

**Comment by ericronne** [comment]
Created a new issue to deal with no-data charts: #1851
