### ISSUE TITLE
Update 'how it works' landing page to reflect new IA

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1790]
We have a new information architecture as per [our wiki](https://github.com/18F/doi-extractives-data/wiki/Information-architecture). With #1788, our urls reflect that new reality, but we need to make the content on the how it works page match, too.

**Comment by ericronne** [comment]
### Draft!
![how it works main 9-2016](https://cloud.githubusercontent.com/assets/9259185/18284596/35f1a272-7430-11e6-9dc1-47a6a07162a7.png)

**Comment by ericronne** [comment]
### Here are the [4 big icons] (https://drive.google.com/open?id=0BwWYNZcEDfwaRmc4dkxNc1FJTmc)

**Comment by meiqimichelle** [comment]
Over to you, @coreycaitlin , for content :D See https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/
