### ISSUE TITLE
Double-check for 'type of land' in no data sentences

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1806]
User feedback:

> I think if there is no production on Federal land of a resource then it should explicitly state that in the heading, i.e. “There was no production from biomass, hydro or wind on Federal land in Montana.”  Same for state.  Or at least it has to somehow acknowledge that there is production of these sources within the border of the state, but they are not on Federal or state lands and produce no Federal or state revenue. 

I believe we intended to always call out the type of land ownership in the summary sentences, which we do in many places. We may has missed this in some of the withheld and/or no data sentences.

**Comment by coreycaitlin** [comment]
I think #1863 addresses this! 🎉
