### ISSUE TITLE
Data Check

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1820]
@meiqimichelle, @mentastc, Nathan, and I had a meeting to discuss the current state of data on EITI.

# State home

## Federal Production
- `NULL` commodity field in bar charts
- `Explore data` showing up as `state_name`. Should be something else.
- Inlet Scrubber (and other commodities that don't have '14 and '15 values) somehow made it into the yml output file. It isn't in the source data and isn't in the `federal_regional_production` database. Related to #1797

### Pulling in wrong dataset for offshore
[offshore.tsv](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/offshore.tsv) should not be used. [onshore.tsv](https://github.com/18F/doi-extractives-data/blob/dev/data/federal-production/onshore.tsv) is the only source of truth for federal production onshore AND offshore

- Add EITI Production CY06-15 Geothermal Update to GDrive

### Incorrect values
- Oil is significantly off.
- Salt is wrong for 2006-2013, correct for 2014-15

### Sentinel values (onshore)
Oil | 2013: 623,103,687.09 barrels
Salt | 2015: 764,801 tons
Salt | 2006: 512,832 tons
Gas | 2013: 4,941,408,110

## Federal Revenue
- The year be set to 2015 for the federal revenue by type chart and default for other fed rev data
- Nathan: NGL could be lumped into Oil & Gas (because NGL will always be done During Production).
- Add Other Revenues and Civil Penalties (not tied to a lease) to revenue by type breakdown. Should get added to All Commodities rollup. Maybe give them a caveat that these are revenues not tied to a  product or commodity. Note: this is not as high a priority as other data issues.

# State pages

## Montana – Federal Production
- Correct commodities: Coal, Gas, Oil
- County and state level data is correct

## Misc
- county dropdown tables list `County` in the rows for Production, but not for revenue.

# Offshore

### Sentinel stuff
- Should only have Oil, Gas and Salt for federal production
- Salt | 2015 | Central Gulf of Mexico | Withheld

# TODO
- make a list of links to the source datasets that we are using to populate the site for @mentastc and Nathan to double check.

**Comment by gemfarmer** [comment]
@meiqimichelle @mentastc As of now, all the sentinel values check out on dev!

**Comment by gemfarmer** [comment]
@mentastc should we be expecting `623,103,687.09` barrels of Oil in 2013 *nationwide*? Or  `623,103,681.09`?

**Comment by gemfarmer** [comment]
[Slack conversation about withheld satl](https://18f.slack.com/archives/eiti/p1473778977000011)

**Comment by gemfarmer** [comment]
Data tests are in place, but still need to update the data so that _all_ of them pass!

**Comment by meiqimichelle** [comment]
@gemfarmer is this still relevant, or can we close?

**Comment by gemfarmer** [comment]
This can be closed!

**Comment by meiqimichelle** [comment]
🎉
