### ISSUE TITLE
Opt-in states: Revenue sustainability charts

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1844]
The one new static visual that's especially important from the opt-in templates is the graph of revenue sustainability. Here are the three we'll need:

## Montana

![screen shot 2016-09-02 at 3 33 03 pm](https://cloud.githubusercontent.com/assets/1450354/18219940/718b5d48-7122-11e6-9af6-ffd86fd70b45.png)

## Wyoming

![screen shot 2016-09-02 at 3 36 20 pm](https://cloud.githubusercontent.com/assets/1450354/18220003/eb7226aa-7122-11e6-8caf-14ebc44c3657.png)

## Alaska

![screen shot 2016-09-07 at 1 10 27 pm](https://cloud.githubusercontent.com/assets/1450354/18326819/884e4616-74fc-11e6-802c-e5ef66fa1a77.png)

Happy to chat about this next week @ericronne!

**Comment by coreycaitlin** [comment]
@lukehawbaker: We have questions!

- For Montana, is `General Fund Revenue` or `Dept. of Revenue Collections` a better proxy for "total revenue"? Having all three bars makes the chart kind of confusing, because it seems like two of the bars should add up to the third one.
- For Wyoming, what message are we trying to get across by splitting out `Severance Tax` from `Total Natural Resources`? Could we just show the total?
- For Alaska, how can we simplify the number of bars so it's a bit easier to parse (especially at small sizes)?

**Comment by coreycaitlin** [comment]
Talked to @lukehawbaker, and he confirmed a few things:

- For Montana, if we want to have 2 bars, we should keep `Total General Fund Revenue`
- For Wyoming, if we want to have 2 bars, we should cut `Severance Tax`
- For Alaska, we want to make sure it shows the overall trend — and the price, interestingly. Let's talk about this one @ericronne ?

**Comment by ericronne** [comment]
Sure, let's talk about it during our scrollchat today, time permitting

**Comment by ericronne** [comment]
Three svg charts ahoy!...

### [Montana chart svg] (https://drive.google.com/open?id=0BwWYNZcEDfwaX2pYTWE0d3BmQmM)

### [Wyoming chart svg] (https://drive.google.com/open?id=0BwWYNZcEDfwaREVOLWFuS2NyNDg)

### [Alaska chart svg] (https://drive.google.com/open?id=0BwWYNZcEDfwaRUl5V3dGQ1NlVGs)


**Sneak peeks…**

![image](https://cloud.githubusercontent.com/assets/9259185/18493155/b1b92368-79d4-11e6-99e7-b292f9cb34e9.png)

![image](https://cloud.githubusercontent.com/assets/9259185/18493171/bccf6140-79d4-11e6-85d7-b073ece506ae.png)

![image](https://cloud.githubusercontent.com/assets/9259185/18493178/c955b1bc-79d4-11e6-9955-deb549d3e0dd.png)
