### ISSUE TITLE
Adjust language on "no federal production" states

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1854]
**Right now, we have three 'we don't have' statements**

`ONRR collects detailed data about natural resources produced on federal land. According to that data, there was no natural resource production on federal land in Maine in 2013.`

`In 2013, ONRR did not receive any payment for extraction of natural resources on federal land (or leasing of federal land for that purpose) in Maine.`

`In 2013, ONRR did not disburse any revenue from natural resource extraction on federal land to the state government of Maine.`

**Feedback**
The first sentence is pretty ok. There is concern that the second two sentences make it sound like there *was* extraction, but the government didn't receive payment for it, or didn't disburse it. Our state pages are approved pending an adjustment to the second two sentences to make that clear that the reason for the no-payment or no-disburse is that there wasn't production.

/cc @mentastc @usEITI

**Comment by coreycaitlin** [comment]
Here's what I recommend swapping in for those 2nd and 3rd sentences:

> There was no natural resource extraction on federal land in Maine in 2014, so ONRR did not collect any non-tax revenues.

and 

> The state government of Maine did not receive any disbursements from ONRR in 2014.

/cc @mentastc @usEITI

**Comment by coreycaitlin** [comment]
^^ edited those sentences again, still need to implement slightly revised version

**Comment by coreycaitlin** [comment]
@mentastc It still felt like burying the lede on that second sentence. What about this, or something like it?

> The state government of Maine did not receive any disbursements from ONRR in 2014. This is usually because there was no natural resource extraction on federal land in the state.

**Comment by meiqimichelle** [comment]
I think we did this! Closing for now. We can re-open if @mentastc has further feedback.
