### ISSUE TITLE
How it works: mobile

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1857]
Currently looks like:

![screen shot 2017-05-11 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/1450354/25974811/ce77bfee-365f-11e7-884b-4dcf4614f001.png)

Should look like [layout only; keep typography updates]:

![pasted image at 2016_09_07 01_27 pm](https://cloud.githubusercontent.com/assets/4827522/18323837/47191666-74ee-11e6-8224-d5e8e3d06f01.png)

**Comment by coreycaitlin** [comment]
Not a priority right now.
