### ISSUE TITLE
Animate scrolling when side-nav links are clicked

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1858]
For a more fluid user experience, create an eased animation for scrolls activated by clicks on the side nav, e.g. state pp ...
![image](https://cloud.githubusercontent.com/assets/9259185/18324179/bf5971ea-7500-11e6-8a6f-7ec9b60fc32d.png)

cc @meiqimichelle @gemfarmer @shawnbot

**Comment by coreycaitlin** [comment]
Closing this issue — will reopen if this emerges as a clearer user need, and potentially as a prototype to test.
