### ISSUE TITLE
Sticky-sidenav pp: Consider renaming "Overview" to "Top" (& bug fix)

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1868]
Since there is no "Overview" header — and this links back to the top of the page — I think "Top" might be more clear to users wherever we have the sticky sidenav. Agree?

Also, bug: the link doesn't currently take the user all the way back to the top of the page.

@coreycaitlin @meiqimichelle @gemfarmer

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/18351436/c9f5d978-759f-11e6-9f73-7f1c9a802e23.png)

**Comment by coreycaitlin** [comment]
I do like "Overview" because we actually have a distinct overview section with genuine summary/intro content — this isn't just a link to the top of the page, it's a link back to that chunk of content.

**Comment by ericronne** [comment]
Noted, but still lean toward "Top"! The other links all match their associated headers. Let's discuss. I also think it should link all of the way to the top of the page; better visual grounding that way. Test? Thanky

**Comment by meiqimichelle** [comment]
Either one is fine. However, we should make sure all the overview/top links go to the same place. Right now it is inconsistent.
