### ISSUE TITLE
Visual bug: Reconciliation

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1869]
Currently only the "no" path on this page ends with, "This means that our accounting systems in the United States are doing their jobs...," but **both** tracks should terminate with that affirmation, right? @coreycaitlin @meiqimichelle 

## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18353085/615261e6-75a6-11e6-87f1-036e4dff8d2f.png)

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18353135/8d88758e-75a6-11e6-86e2-f97b504a70b3.png)

## Steps to reproduce the behavior
open the page :D

**Comment by meiqimichelle** [comment]
Right. I remember I meant to fix this! Thx for issuing @ericronne .

**Comment by ericronne** [comment]
Handled with #1919
