### ISSUE TITLE
Visual bug: USEITI logo svg tagline looks bad

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1881]
## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18395608/bb5ba768-7684-11e6-9aaa-37ef35cfc7fc.png)

## Actual Behavior
Odd thinning of some characters...
![image](https://cloud.githubusercontent.com/assets/9259185/18395633/d7a4efec-7684-11e6-9b58-fd3b6bf2396f.png)

## Steps to Fix
[**Try this new svg**] (https://drive.google.com/open?id=0BwWYNZcEDfwaMHdTOFROZWlQNTg) 

cc @meiqimichelle

**Comment by ericronne** [comment]
@meiqimichelle lmk if we need a new png as well

**Comment by ericronne** [comment]
[White version of the logo] (https://drive.google.com/open?id=0BwWYNZcEDfwaTjMyZHdSckc1TDA) if you need it

**Comment by meiqimichelle** [comment]
This will be done when #1888 merges. Closing.
