### ISSUE TITLE
Change clickable overview map to show offshore regions instead of areas

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1895]
We changed our offshore pages to be at the area level instead of region, but didn't update the overview map, which still has regions. We should fix this.

**Comment by ericronne** [comment]
This is fixed, right @gemfarmer? Close?

**Comment by gemfarmer** [comment]
@ericronne I think this is actually reversed. We have now decided to organize things at the region level, but we are showing areas and clicking on an area takes you to a regional page. Title should read something like: 

> Change clickable overview map to show offshore regions instead of areas

**Comment by meiqimichelle** [comment]
IIII'mmm not sure this is a big deal. I'm ok with a `wontfix` here -- what do y'all think? Showing the 'state'-like offshore areas looks nice, and maybe isn't toooo confusing to users to, once clicked, end up on a region instead.

**Comment by coreycaitlin** [comment]
Reopen if this does seem to cause user confusion in the future.
