### ISSUE TITLE
Megachart: design for negative numbers

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1900]
I'm hesitant to run negative numbers in a new color. Red (eg) would communicate well, but it would add another color to the palette, and also draw inordinate attention to itself. A simpler solution is to italicize negative numbers, and not visually represent the "amount" at all. Instead, we could simply outline a blank rectangle with one pixel of $gray-light (#d3dfe6), like so …

![image](https://cloud.githubusercontent.com/assets/9259185/18451398/5561c1c0-78fc-11e6-8c0b-ad7732b500a4.png)

thoughts @gemfarmer @meiqimichelle @coreycaitlin?

**Comment by meiqimichelle** [comment]
_like_

**Comment by ericronne** [comment]
Changed this task to "implement"!

**Comment by gemfarmer** [comment]
Closed with #2238
