### ISSUE TITLE
Bug: Gulf of Mexico Revenue

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1903]
## Expected Behavior
Federal revenue map/chart should behave like other charts

## Actual Behavior
![screen shot 2016-09-12 at 4 44 16 pm](https://cloud.githubusercontent.com/assets/4803473/18454380/8ce822ee-7909-11e6-95fd-38def144f3df.png)

Clicking on the map opens the table, but doesn't highlight the rows.

Clicking on the rows does not highlight the map. 

cc @ericronne @coreycaitlin

**Comment by meiqimichelle** [comment]
This seems resolved, just checked.
