### ISSUE TITLE
Enhancement Proposal: Simplify land ownership legend labels

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1920]
The ownership maps currently say "lands" four times (title plus each legend label). @coreycaitlin do you think it would be confusing if we removed the word from federal and tribal, like so? ;) ...

![image](https://cloud.githubusercontent.com/assets/9259185/18515354/b4b8b82c-7a5a-11e6-9b99-d9b823b26f31.png)

cc @meiqimichelle

**Comment by ericronne** [comment]
@gemfarmer ...

As discussed in PR #1965, we'd like to create an exception for the legends two large maps (on home and explore main). The point is to change the wording on all of the state-page ownerships maps, removing "lands" from two spots. Like so ...
![image](https://cloud.githubusercontent.com/assets/9259185/18593221/0268fae0-7c00-11e6-961a-76101457a4a8.png)

The theory is that on those pages, the "Land ownership" title provides enough context for the user to get the point.

The large maps on the home and explore main pages don't have such a title, though. So for those two maps, could we keep the legend as is? I.e....
![image](https://cloud.githubusercontent.com/assets/9259185/18593282/586cf428-7c00-11e6-89fb-1035efd988b2.png)

**Comment by meiqimichelle** [comment]
We should also consider whether adding this will add unnecessary complexity to maintaining the site :-/

**Comment by ericronne** [comment]
Not a fan of complexity, but these two are super high-profile instances of the map. With fifty or so instances of above-the-fold redundancy. Your call

**Comment by gemfarmer** [comment]
@meiqimichelle @ericronne Is this done?

**Comment by ericronne** [comment]
done, but new bug introduced on home page map, where "land" was mistakenly deleted from the legend. made a new issue  #2020 👓
