### ISSUE TITLE
County chart interactions are defaulting to 2013 when they say 2015

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1925]
Right now, our pages say we're 2015, but the data that loads is for 2013. If you click another year in the bar charts (say, 2013) everything updates and when you return to 2015 things are correct. Probably as a result, there's some disconnect in the 2015 map/table views as seen in the image below.

This example is for production on federal land, but the same problem exists on federal revenue data, and wage and salary.

Current value:
Colorado - Gas - Cheyenne County - 2015 - 118103
Colorado - Gas - Cheyenne County - 2013 - 118103

Sentinel/correct values: 
Colorado - Gas - Cheyenne County - 2015 - 95825
Colorado - Gas - Cheyenne County - 2013 - 118103

![screenshot 2016-09-14 10 18 54](https://cloud.githubusercontent.com/assets/4827522/18522400/c45151c2-7a64-11e6-86dc-8e21cbdb91d7.png)

**Comment by gemfarmer** [comment]
Probably not a HUGE deal. My guess is that the map and chart are being defaulted to 2013 while the bar chart is getting defaulted to 2015. The solution that will help eliminate this problem in all cases is to make sure that the two different columns are being fed the same default year.

**Comment by meiqimichelle** [comment]
Chris gave us the :+1: !! Closing!
