### ISSUE TITLE
Visual bug: Sticky nav positioned too low on Explore main page

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1938]
## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18532261/b6167f42-7aa0-11e6-8716-d342c13f687f.png)

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18532256/a11e2630-7aa0-11e6-8756-1db7bdaf3960.png)

## Steps to reproduce the behavior
Visit page, scroll a bit...

@meiqimichelle @gemfarmer

**Comment by meiqimichelle** [comment]
Closed with #1951.
