### ISSUE TITLE
Bug: Withheld state rollup inconsistency

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1939]
In some cases, state-level info is showing up as "no data" when there is actually withheld data for a child county. This screenshot shows one instance in WY:

![screen shot 2016-09-14 at 4 20 24 pm](https://cloud.githubusercontent.com/assets/1450354/18533379/47ece820-7a97-11e6-8d75-a10667e4f0e8.png)

**Comment by meiqimichelle** [comment]
I believe this has been fixed (I just tried to re-create, and it seems fixed). Moving over to review for @coreycaitlin to check.
