### ISSUE TITLE
Bug: our megachart isn't including CO2 and Helium

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1948]
There are a few other products that don't seem to be pulling in to the megachart. This might be because we couldn't figure out where to categorize them. Perhaps we should re-name 'Hardrock Minerals' to 'Other products' and then add the few stragglers.

**Comment by gemfarmer** [comment]
We can solve this really quickly by adding them to the list of commodities. @meiqimichelle and @meiqimichelle proposed turning Hardrock Minerals into `Other Products`

**Comment by gemfarmer** [comment]
If we lump Hardrock Minerals into an Other category, we will need to change the copy in the process chart that specifies that that the acquired lands are Hardrock acquired lands.

**Comment by meiqimichelle** [comment]
Reviewed this with Chris, we've got a 👍 🎉
