### ISSUE TITLE
Megachart: Offshore revenue streams process explanation on national page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1955]
## Expected Behavior

The national explore page should have revenue stream process explanations for both onshore and offshore revenues.

## Actual Behavior

Because of how I set up the if-statement to show onshore/offshore explanations for oil and gas revenue streams when appropriate, the offshore oil and gas explanation is _not_ showing up on the national page.

## Steps to reproduce the behavior

Go to the national profile page and click on the "Revenue details by phase" tab:

<img width="824" alt="screen shot 2016-09-15 at 12 15 48 pm" src="https://cloud.githubusercontent.com/assets/1450354/18563996/88b92b82-7b3e-11e6-98a0-243228bd8979.png">

**Comment by meiqimichelle** [comment]
Closed with #2088.
