### ISSUE TITLE
Glossary links in markdown front matter

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1966]
## Expected Behavior

It would be lovely to include some glossary links in the opt-in content.

## Actual Behavior

The syntax we use elsewhere — for example, `{{ "word" | term:"words" }}` — seems to break if we put it in the front-matter markdown sections, like so:

![screen shot 2016-09-15 at 7 56 19 pm](https://cloud.githubusercontent.com/assets/1450354/18574100/73551d06-7b7e-11e6-8694-7fd853a08bcc.png)

## Steps to reproduce the behavior

I found this while attempting to link the phrase "material acres" to its glossary item in the MT.md and WY.md files.

**Comment by gemfarmer** [comment]
I agree that this would be pretty powerful. I think I _may_ have found our solution, but will need to test it. 

It looks like a person has created a `liquify` filter that will parse liquid! Check it out:
https://fettblog.eu/snippets/jekyll/liquid-in-frontmatter/
