### ISSUE TITLE
Visual bug: funky alignment on how it works main pg

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1970]
## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18589532/cbdf20d0-7bf0-11e6-8934-f288cc6a4f6d.png)

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/18589514/bb49d90e-7bf0-11e6-8f32-1af7b7552b46.png)

**Comment by meiqimichelle** [comment]
Whoa! That's exciting, and perhaps a recent change. Cool! Onnit.
