### ISSUE TITLE
Update unfurl image (still uses old map)

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1972]
Our social media share image is the map from the old homepage. We should update this. @ericronne what image do you think we should use there?

**Comment by ericronne** [comment]
For a quick swap in, the ownership map might be nice, sans legend.

Note: it seems that facebook doesn't pay attention to our prescribed image. Instead, it scrapes the page for images and lets you choose one. The default is this one, ew ...

![image](https://cloud.githubusercontent.com/assets/9259185/18592292/f173bc24-7bfb-11e6-987d-6ffad07bf06d.png)
