### ISSUE TITLE
Layout for words on megachart split bar isn't consistent

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1974]
Ideally, the words should stay to the left of the numbers, or move to two lines elegantly. The images here are from the Alaska page.

Sometimes, it does this:
![screenshot 2016-09-16 09 21 13](https://cloud.githubusercontent.com/assets/4827522/18593220/3d3cef02-7bef-11e6-941a-b058ec1f5d8a.png)

Sometimes, it does this:
![pasted image at 2016_09_16 12_21 pm](https://cloud.githubusercontent.com/assets/4827522/18593230/48ac83d4-7bef-11e6-8a18-98cb97c82bb7.png)

**Comment by ericronne** [comment]
If we're unable to get this layout consistently …
![image](https://cloud.githubusercontent.com/assets/9259185/18753763/f02f2c90-80ab-11e6-95e7-685b6f7c5e70.png)

then we can stack …
![image](https://cloud.githubusercontent.com/assets/9259185/18753831/243cf01c-80ac-11e6-988c-5ee6379b2799.png)

**Comment by meiqimichelle** [comment]
Done with #2222 🎉
