### ISSUE TITLE
Change name of case studies main page

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1979]
Now that we're using "Overview" only as a section label, we should change the <title> of the case studies landing page. May i suggest "Case studies," to align with other level-2 pp?

**Comment by coreycaitlin** [comment]
I'm pretty sure we already did this, unless you meant the meta page title — #1986 fixes that too. Let me know if I'm just missing this somehow...

**Comment by ericronne** [comment]
May not have yet been reflected in the branch i was browsing. Looks right on overview-eradication branch 👍
