### ISSUE TITLE
A few ribbon ironings

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1980]
For consistency / style ...

## [About USEITI] (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/about/)
~~- [ ] Looks like the bold intro line has a size exception. We can kill that, reducing the size to 1rem~~
 - [x] Add 10px of padding above the blue button
 - [x] Remove arrow icon from the exec summ link, add doc icon, underline text by default (making it the same style as how it works card, typographically)
![image](https://cloud.githubusercontent.com/assets/9259185/18602760/8baa1e2a-7c31-11e6-9ab9-33f02a90aaf7.png)

## [Case studies] (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/case-studies/)
 - [x] Slice 20 pixels off of the bottom of the ribbon, and scoot up the selector box accordingly
![image](https://cloud.githubusercontent.com/assets/9259185/18603179/fdcf0efe-7c34-11e6-9092-85b52720f52b.png)

## [Explore data] (https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/)
 - [x] Looks great! Pat self on back.

**Comment by meiqimichelle** [comment]
Should the bold header text on cast studies also be reduced to 1rem @ericronne ?

**Comment by ericronne** [comment]
@meiqimichelle yes pls
