### ISSUE TITLE
Formatting tool tips for county hovers

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1992]
@gemfarmer added handy tool tips to state-page maps (#1985). Since the tool tips were designed to complement high-profile, large maps, their current style is a little too much for these maps. Also the darkening of the selected area iinterferes with the user's ability to match up the fill color with the legend. Here's what they look like now...

![image](https://cloud.githubusercontent.com/assets/9259185/18640575/5dc3bac8-7e5e-11e6-8ccf-c600d9ff7aa3.png)

Here's a design for these county-map tips...
 - hovered county on map: alphaed-back green outline with no fill overlay (so that its color will still match the legend)
 - text: para-sm
 - tool tip box: white fill, outline 1px $gray-light

![image](https://cloud.githubusercontent.com/assets/9259185/18640636/92caec46-7e5e-11e6-98f9-f416a4f07616.png)

**Comment by gemfarmer** [comment]
@ericronne this should be a piece of 🍰 !! Maybe pair on this sometime tomorrow?

**Comment by ericronne** [comment]
sure. 🍐 🍰  is my fave.
