### ISSUE TITLE
Finish data tests on federal production

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1994]
Our sentinel data tests work. There are two or three tests out of six that aren't passing because the data isn't 100% correct. Once these are fixed, the data should be clean. As a more thorough test, we might test all of the rows after the sentinels are fixed. This issue is to complete the sentinel tests.

We're pretty sure the only problems left are issues with the offshore data, something to do with withheld data not parsing 100% correctly (ie, maybe we're leaving out a few rows of offshore).

**Comment by gemfarmer** [comment]
Comprehensive update: 

The current federal production test script tests key, "sentinel", values for national, state, county, and offshore. Of these tests, here is what is passing ( ✅ ) , and pending ( ⚠️ ):

national: 
- ⚠️ pending until discrepancy in Oil values is resolved 

state: 
- ⚠️ pending until discrepancy in Oil values is resolved 

county: 
- ⚠️ pending until discrepancy in Oil values is resolved 

offshore: 
- ✅ it('only has Oil, Gas, Salt')
- ✅ it('checks offshore areas')


So it looks like the Oil values are the culprit. More soon.

**Comment by gemfarmer** [comment]
This can also be closed!
