### ISSUE TITLE
Ethnio link is down on live site

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2000]
![image](https://cloud.githubusercontent.com/assets/9259185/18650734/40aadd1c-7e8c-11e6-86cc-60144898e8e5.png)

@meiqimichelle

**Comment by gemfarmer** [comment]
We had a brief discussion about this [on Slack](https://18f.slack.com/archives/eiti/p1473775287000004)

**Comment by meiqimichelle** [comment]
I fixed this for the bottom button...and realized that I didn't fix it for the link in the header! Adding to sprint.
