### ISSUE TITLE
Add icon to bar charts to indicate withheld & format wh product listing

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2008]
On bar charts, grayed-out years indicate a lack of data. However, you have to hover over or select the year in order to know whether or not that lack is because the number is withheld or not. So it might be helpful to drop a marker into the empty bar space for those years, like so...

![image](https://cloud.githubusercontent.com/assets/9259185/18682884/959a2696-7f33-11e6-9c6d-ae9531d75476.png)

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/18688168/c212605c-7f48-11e6-80fb-2cae2cd813fe.png)

[**Default icon**] (https://drive.google.com/open?id=0BwWYNZcEDfwaWEdMYWJySkRFNmM)

[**Selected icon**] (https://drive.google.com/open?id=0BwWYNZcEDfwaTjhGNnh0bUF6SkE)

**Comment by ericronne** [comment]
For consistency with other bar hovers, let's make the hover/selected color #587F4C (if we do implement this)

**Comment by ericronne** [comment]
## Design...

![image](https://cloud.githubusercontent.com/assets/9259185/18759674/2297ea2a-80c3-11e6-985a-763e5b2ef66b.png)

**Comment by coreycaitlin** [comment]
Closing in favor of #2023
