### ISSUE TITLE
Test these new choropleth blues

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2035]
Now that we've reduced the legend from 9 divisions down to 5 (yay), i think we can reduce our blues list as well (yay x2). Here's one to try. Need to see it in action (along with the texture layer) to tell (we can discuss further and handle naming in style guide issue: #1638 )...
- #dcf4fc (220 244 252)
- #b3def2 (r179 g222 b242)
- #5ca9cd (r92 g169 b205)
- #1478a6 (r20 g120 b66)
- #005078 (r0 g80 b20)

**Comment by gemfarmer** [comment]
@ericronne and I finalized colors in #2099 ! Closing!
