### ISSUE TITLE
Confirm state sizing and adjust as necessary

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2037]
Checkmark = 🆗 😋 👍 ⚡️ 👯 
Unchecked = consider additional tweaks as noted in parens ...
- [ ] AK (small, possibly go back to wide)
- [x] AZ
- [x] CA
- [x] CO
- [x] CT (go narrow?)
- [x] DE ( 😳 )
- [x] FL
- [x] GA
- [x] HI (maybe shrink it just a touch to pull it in from the edges)
- [x] ID
- [x] IL
- [x] IN
- [ ] IA
- [x] KS
- [x] KY
- [x] LA
- [x] ME
- [x] MD (a little big)
- [x] MA (go narrow?)
- [x] MI (feels small, enlarge state and make the frame taller to accommodate?)
- [x] MS
- [x] MO
- [ ] MT
- [ ] NE
- [x] NV (big)
- [x] NH (a little big)
- [x] NJ
- [ ] NM
- [x] NY (maybe a little bigger, and taller box to fit?)
- [x] NC (could it fit in narrow?? try?? discuss??)
- [ ] ND
- [x] OH (big)
- [ ] OK
- [x] OR
- [x] PA (just a little big)
- [x] RI (frame is really big, and state is off center)
- [x] SC (a little big)
- [ ] SD (a little big)
- [x] TN
- [ ] TX
- [ ] UT
- [x] VT
- [ ] VA
- [ ] WA
- [ ] WI
- [x] WV (a little big)
- [x] WY (a little big)
- [ ] Offshore Pacific (big)

**Comment by ericronne** [comment]
Getting close! A few final tweaks ...

Checkmark = 🆗 😋 👍 ⚡️ 👯 
Unchecked = consider additional tweaks as noted in parens ...

*Make map a little smaller (keep box the same size)*
 - [ ] IA
 - [ ] MT
 - [ ] NM
 - [ ] TX
 - [ ] UT
 - [ ] WI

*Make box taller*
 - [ ] NE
 - [ ] ND
 - [ ] OK
 - [ ] SD
 - [ ] VA
 - [ ] WA

*And...*
 - [ ] AK top map is small (big version is good)

**Comment by gemfarmer** [comment]
We fixed this with #2076. Can revisit particular maps if the need/want arrises. Closing
