### ISSUE TITLE
Modify year selectors to accommodate no-data years

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2048]
Currently any years lacking data have "no data" appended to the year label (eg "2008 no data"). These lines are also grayed out and italicized, to mark them as non-selectable. But when a no-data year has been selected, the "no data" label gets cropped by the right edge of the collapsed selector …

![slack-imgs com](https://cloud.githubusercontent.com/assets/9259185/19086806/462e5692-8a35-11e6-92aa-c9fb8ba14e97.png)

Ideally only the year would show in collapsed selectors; the "no data" label would only appear when the selector is expanded.

Note: there's a chance that we won't even require this design for now, but it would be good to have this design in place in case future data requires it. **BUT as such, it's a low priority.**

**Comment by coreycaitlin** [comment]
Closing in favor of #2378
