### ISSUE TITLE
Documentation: Geothermal rates

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2052]
In the documentation for the federal revenue dataset, we need to include the full explanation of geothermal rates and contextual links. We may also want to link to this explanation from the revenue megachart, within the geothermal rate summary.

**Comment by coreycaitlin** [comment]
From prior notes in #1560:

> For leases signed before the Energy Policy Act of 2005: The lessee’s reasonable actual transmission and generation costs are deducted from gross proceeds from electricity sales, and the resulting value is multiplied by the lease royalty rate (usually 10%); for direct use, the lessee pays the equivalent value of least expensive, reasonable alternative energy source. Thermal energy utilized must be measured by lessee at the inlet and outlet of facility. The resulting value is multiplied by the lease royalty rate of 10%.

**Comment by coreycaitlin** [comment]
I want to get #1614 sorted before I finalize these explanations.

**Comment by meiqimichelle** [comment]
Closed with #2093
