### ISSUE TITLE
Reposition some table headers

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2063]
Some table headers should be shifted to the left or right, so they better align with the content in their columns. We'll need to go through by hand in order to root out the offenders.

![image](https://cloud.githubusercontent.com/assets/9259185/19162209/8f68b22a-8bbc-11e6-95f0-dece043b4dc9.png)

**Comment by coreycaitlin** [comment]
@ericronne I think we did this in all the table-cleaning. Can we close this out?

**Comment by ericronne** [comment]
Looks like we missed this problem (grr), so we should leave it open.
![image](https://cloud.githubusercontent.com/assets/9259185/26063790/a32a7b0e-3954-11e7-90ca-a5ea72315e57.png)

**Comment by coreycaitlin** [comment]
Good example here: https://revenuedata.doi.gov/explore/MT/#federal-production

**Comment by master12** [comment]
There is no html/css solution to this issue. The best we can do is a hack that gets us an inconsistent look. The hack was bascially adding a hidden tbody tag attached to the thead and then collapsing it so it wouldnt show but still force the th cols to be the correct width. This was still off when the scrollbar showed by the width of the scollbar. Also long text pushed it beyond the right side as well. We decided the current solution was the most consistent and the value this hack add was minimal and inconsistent. The final decision was made on 2/21/2018 to leave it as is.
