### ISSUE TITLE
Remove superfluous line rules from some tables

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2064]
The [national disbursements chart](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/explore/#federal-disbursements) (and others?) shouldn't have outlines or dividers.

**Comment by gemfarmer** [comment]
@ericronne I can remove the dividers, but is there any additional style on those tables that you were hoping for?

**Comment by meiqimichelle** [comment]
Under way in PR #2147.

**Comment by ericronne** [comment]
👍 👍
