### ISSUE TITLE
Delete Isle Royale from large maps?

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2065]
I believe this little sliver of a thing near the upper-left corner is Isle Royale, which is folded in with Michigan …
![image](https://cloud.githubusercontent.com/assets/9259185/19166473/420fbf3a-8bcd-11e6-8774-f865c1bb0bff.png)

Sadly, the white stroke on the large maps (home and explore natl pg) seems to be choking it out …
![image](https://cloud.githubusercontent.com/assets/9259185/19165894/32f46b06-8bcb-11e6-8e77-e0c61c5f106f.png)

I'm guessing this might take a while to fix. What if we simply masked it out of those two maps?

@gemfarmer @meiqimichelle

**Comment by gboone** [comment]
FWIW, the entire island is a national park so it will [probably never have any extractives data](https://www.nps.gov/subjects/energyminerals/mining-claims.htm).

**Comment by coreycaitlin** [comment]
We probably shouldn't delete the island.

**Comment by ericronne** [comment]
Alaska and Hawaii have similar issues, right on the home page. @gemfarmer any rough idea of how long it would take to remedy?

![image](https://cloud.githubusercontent.com/assets/9259185/26063982/383dfa0e-3955-11e7-8cfb-e30ed87620f3.png)

**Comment by gemfarmer** [comment]
I don't think this is a quick fix. All of the map outlines are generated programmatically, and excluding certain parts of them could prove tricky, or buggy. I think I would opt for trying to style them in a way that accounts for the visual issues :man_shrugging:

**Comment by ericronne** [comment]
Maybe some of [these stroke properties](https://svgwg.org/specs/strokes/#ChangesSinceSVG2) can help.

For future pairing …

**Comment by coreycaitlin** [comment]
We're going to keep the island! Will open a new issue for addressing stroke weights on national maps if that comes up as a user need or product priority.
