### ISSUE TITLE
Reverse the order of years in selectors, so the most recent year is at the top

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2069]
Currently the most recent year resides at the bottom of selectors on state pages, and the furthest-back year at the top. This gives these drop downs a "drop up" effect! It also feels counter intuitive...

![image](https://cloud.githubusercontent.com/assets/9259185/19171844/6ce9cc16-8be4-11e6-826b-7b7b89310165.png)

cc @meiqimichelle @coreycaitlin @shawnbot

**Comment by gemfarmer** [comment]
Closed with Style cleanup #2077
