### ISSUE TITLE
Bug: "EXPLORE DATA" loses its boldness when navigating state pages

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2070]
## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/19172150/f4ff60a6-8be5-11e6-88d6-5849f7f336e7.png)

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9259185/19172161/ff402d84-8be5-11e6-90b8-b40745f862e4.png)

The main (ie national) explore page is good. All sub-pp seem to have this bug, tho.

**Comment by gemfarmer** [comment]
Closed with #2077
