### ISSUE TITLE
State pages: implement mobile sticky headers / nav

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2084]
## Collapsed sticky header, in context of page ...

![image](https://cloud.githubusercontent.com/assets/9259185/19396311/1d2b7de4-9208-11e6-9117-851ce193b137.png)
## "Stuck" header ...

![image](https://cloud.githubusercontent.com/assets/9259185/19396324/2becae16-9208-11e6-87ca-1de3ad7dbe6d.png)
## Stuck and scrolled …

![image](https://cloud.githubusercontent.com/assets/9259185/19396331/37a9395e-9208-11e6-9477-0ec2b88327ed.png)
## Expanded …

![image](https://cloud.githubusercontent.com/assets/9259185/19396336/4773fd38-9208-11e6-917d-e317536cd19c.png)

**Comment by gemfarmer** [comment]
This was implimented with #2090. Can someone say #sparkbars? Can I get a 🙌  🙌

**Comment by ericronne** [comment]
🌮 💃 🌮
