### ISSUE TITLE
Ownership maps: contrast between federal and tribal colors could be better

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2087]
## Contrast between fed and tribal is a little low

![image](https://cloud.githubusercontent.com/assets/9259185/19481680/64137d9c-9514-11e6-8b35-e1340fd7d196.png)

**Perhaps try reducing the opacity of the black overlay for tribal by 10% to 20%**

**Comment by meiqimichelle** [comment]
We did this!
