### ISSUE TITLE
Reduce number of steps in choropleth 

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2094]
@shawnbot, could you give your thoughts/input on the following idea:

@ericronne and I were throwing around the idea of reducing the number of steps
choropleth from 5 to 4. The benefit in our minds would be two-fold:

1.) Reduce overall space that the legend takes up (for mobile)
2.) Make maps more generally legible.

The potential drawback of doing this, in my mind, is that the choropleths will be less and less useful as standalone maps. Fortunately, we have the actual granule data readily available, so an upside of this might be that it more obviously demonstrates the intention of our maps: a quick, easy way to find big values and small values geographically. 

Another potential downside of consolidating steps is that it will likely push even more values into our bottom bracket in many instances. A solution to this might be to use a quantize scale? Do you have thoughts on the potential repercussions of this, @shawnbot?

cc @meiqimichelle

**Comment by ericronne** [comment]
Reducing the count to four would definitely improve the mobile layout, enabling us to go full width with the maps and run the legend beneath them, without shrinking the font by too much....

![image](https://cloud.githubusercontent.com/assets/9259185/19526198/48836cd8-95e9-11e6-8a0f-bcfb089a54a8.png)

I feel that most choropleths that i've seen don't have a table of data right there; the map *is* the data. In our case, though, the table does the heavy lifting of communicating the data specifics. So i don't know if we're losing much by sacrificing one level of color. My 2c.

**Comment by gemfarmer** [comment]
Done with #2099
