### ISSUE TITLE
Clarify non-commodity revenue chart on the national page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2115]
This chart — which represents all non-commodity revenue, so that the total in this section will match up with the total in the above megachart — is confusing: 

![screen shot 2016-11-01 at 10 21 53 am](https://cloud.githubusercontent.com/assets/1450354/19899328/f0e152fe-a01c-11e6-8e46-3fb16c1bffd2.png)

This issue is complete when we've come up with a way (probably through the magic of words) to make that chart a little clearer and less baffling.

**Comment by coreycaitlin** [comment]
I think a better sentence here would be something like:

> `Companies paid $60,621,570 in inspection fees, civil penalties, and other revenues in 2015.`

but this will involve adding a test in this section of the page in order to catch and rewrite the "none" instance. Also it would be nice if the title could be `Other revenue` instead of None.

**Comment by ericronne** [comment]
Yes, seems way more clear to me!

![image](https://cloud.githubusercontent.com/assets/9259185/24367982/495be590-12e4-11e7-86ad-ecb1e2ac5a14.png)

@gemfarmer easy to do?

**Comment by gemfarmer** [comment]
I'm pretty sure this will only require a text change, so yeah, I think we could take care of this pretty quickly!

**Comment by meiqimichelle** [comment]
@gemfarmer and I are working on this now, and realized that perhaps a better name for this is `Non-commodity revenue`. `Other revenue` is already defined above in the megachart (bottom right), and the thing we're defining here is the `*` part of that, which we've called `revenues not tied to specific commo­dities`.

<img width="762" alt="screenshot 2017-04-05 09 04 23" src="https://cloud.githubusercontent.com/assets/4827522/24714982/e6d8d11a-19de-11e7-9c22-4e7aa2d1bbfd.png">

Either way, the structure is in place to change this name whenever we want. 💥

**Comment by ericronne** [comment]
Closing for now, since "non-commodity revenue" in pr #2241 seems to be more clear and accurate than previous iterations. Opened a new issue to discuss this. #2242
