### ISSUE TITLE
Layout bug: First chart is slightly lower

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2117]
In a couple of sections, in at least some browsers (I'm using Chrome on a Macbook), the first trend chart is out of alignment with the others. This seems to show up in the federal revenue section on the national page:

![screen shot 2016-11-01 at 10 24 42 am](https://cloud.githubusercontent.com/assets/1450354/19899941/17740fb8-a01f-11e6-8130-32d5cc7dcc27.png)

And in state exports sections (this is Alabama):

![screen shot 2016-11-01 at 10 37 54 am](https://cloud.githubusercontent.com/assets/1450354/19899969/2f661bde-a01f-11e6-83aa-79b54ced9d92.png)

**Comment by gemfarmer** [comment]
This is fixed as of #2114!
