### ISSUE TITLE
Bug: How it works top ribbon

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2150]
## Expected Behavior
The How it works top banner layout should respond to mobile views. In mobile the image on the right should be full width and centered.

## Actual Behavior
It instead looks like this:
<img width="400" alt="screen shot 2016-11-23 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/4803473/20574599/eae53ef0-b17a-11e6-8b24-1b040e4e88e1.png">

**Comment by meiqimichelle** [comment]
Done with #2191
