### ISSUE TITLE
Replace older-style subnav with state profile subnav

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#2157]
Some pages still use an older version of subnav (see below right). This should be updated to match the newer (better!) subnav style that's on the state profile pages.

For example:
<img width="1050" alt="screenshot 2016-11-23 16 21 41" src="https://cloud.githubusercontent.com/assets/4827522/20581874/16547b6e-b199-11e6-8302-7598f02ee240.png">

**Comment by gemfarmer** [comment]
@meiqimichelle are we wanting the headings to also be sticky, like in the state profile pages? Or should I just fix the subnav itself?

**Comment by meiqimichelle** [comment]
@gemfarmer Good question! I was thinking about the subnav on the right as a first step. But, also, I'm not sure where this falls in terms of work priority -- wasn't sure how much else you had on your plate.

**Comment by gemfarmer** [comment]
@meiqimichelle I can make this initial change quickly, but making the sections sticky _might_ take longer. There are bigger fish to fry in EITI imho, so I'm going to focus on those things first. Namely:

- this issue (scoped narrowly)
- getting rid of unused images
- minifying css
- fixing megachart mobile view
- making maps unclickable in mobile
- fixing glossary search 'x' bug

If adding sticky subnavs to sections seems like a higher priority than any of these, please lemme know!

**Comment by meiqimichelle** [comment]
Definitely not higher priority than those other issues! You've got it!
