### ISSUE TITLE
Bug: Case studies map hover

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2192]
## Expected Behavior

The hover effects on the case studies maps should consistently work.

## Actual Behavior
Hovering over North Slope Alaska (this appears to be the only buggy icon) on the case studies map at https://useiti.doi.gov/case-studies/ does this:

![screen shot 2017-01-17 at 10 05 54 am](https://cloud.githubusercontent.com/assets/4803473/22028395/a9f8ec14-dc9c-11e6-9d18-05b6c2fc1244.png)

**Comment by coreycaitlin** [comment]
This is no longer happening!
