### ISSUE TITLE
Create new search index

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2193]
The search in the search bar should search the site as well as external resources that we curate.

Our search is currently via 18F/Beckley, which works well, but experiences a non-trivial number of service outages. 

To fix this, we can replace Beckley with the [`jekyll_pages_api_search`](https://github.com/18F/jekyll_pages_api_search) gem, which automatically generates a search index for our jekyll site. AND we can do this without removing our current functionality!

The search gem uses http://lunrjs.com/ under the hood to create an index that we can `add()` our existing curated list of external resources to. 

Steps to make this happen:
- [x] add the `jekyll_pages_api_search` gem
- [x] locate our [curated list of resources](https://github.com/18F/doi-extractives-data/blob/dev/_data/search.yml)
- [ ] replace our `/search-results/` page following the custom UI option allowed by the gem. On that page, we should be able to add JS that will add our curated index to the generated index

**Comment by gemfarmer** [comment]
So, after digging into this a bit more, it looks like we won't be able to integrate the index created by the `jekyll_pages_api_search` gem without editing that repo. We can do that, but I wonder if it would  faster and maybe _better_ to separate the two searches. One list for internal "hits", another for external resources??

Thoughts @meiqimichelle ?

**Comment by meiqimichelle** [comment]
Let's talk! Might grab @ericronne 's brain to think about what that might look like, if he has time.

**Comment by gemfarmer** [comment]
I think this is done with #2195?! @meiqimichelle
