### ISSUE TITLE
Clean the tables  (ノಠ益ಠ)ノ彡┻━┻

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2218]
Do a bit of restyling and consistency-izing.
Likely via @meiqimichelle and i 🍐-ing.  

## Tweaked megachart reference …
![image](https://cloud.githubusercontent.com/assets/9259185/23569113/52dca240-0023-11e7-92c8-045b653b0a2d.png)

**Comment by meiqimichelle** [comment]
Done with #2222
