### ISSUE TITLE
Visual bug: sticky headers have lost their year selectors

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2223]
![image](https://cloud.githubusercontent.com/assets/9259185/23682306/af22bc5a-0358-11e7-96b7-a87d587796c4.png)

e.g.http://127.0.0.1:4000/explore/#revenue

**Comment by ericronne** [comment]
Original design, formerly implemented but now <poof!> …
![image](https://cloud.githubusercontent.com/assets/9259185/23682369/08bbfe7a-0359-11e7-9535-05b07eaaecaa.png)

**Comment by gemfarmer** [comment]
Looks like they are there in mobile, so probably just a CSS media query (breakpoint) issue.

**Comment by gemfarmer** [comment]
sticky headers found sticky!
