### ISSUE TITLE
Update disbursement data on state pages

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#2225]
We have updated disbursement data as per #2184 and #2203. We might consider updating the federal disbursement total on state pages from 2015 information to 2016 information. For instance: [**In 2015, ONRR disbursed $496,043,426 to New Mexico.**](https://federalist.18f.gov/preview/18F/doi-extractives-data/add-2016-disbursements/explore/NM/#federal-disbursements)

**Comment by coreycaitlin** [comment]
This is done! [New Mexico example](https://useiti.doi.gov/explore/NM/#federal-disbursements)
