### ISSUE TITLE
Consider rewriting SEVERAL home-page-card headlines, for better wrapping and clarity

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2228]
### The current header text (A below) for the disbursements card on the home page breaks awkwardly. Perhaps we should rewrite?

**Here are some options, with a Hemingway pic for inspiration:

![image](https://cloud.githubusercontent.com/assets/9259185/23918884/b4b1d2e0-08c2-11e7-9ebd-fd968f471ae0.png)

**Comment by gemfarmer** [comment]
We can also also change the mininum height on those titles and then the content would start at the same spot.

**Comment by ericronne** [comment]
True, true, but the uniform heights make for nice gridding!

In fact, I just got inspired to make **everything** line up nicer, by ensuring that each of these headlines fit on exactly two lines on desktop. That meant editing the third and fifth card, too.

## Current text   >   Suggested edit
Where does the money go?   >   **How is the money from extractions spent?**
How do extractive industries affect communities?   >   **How do these industries affect communities?**
How does resource extraction result in federal revenue?   >   **How does extraction result in federal revenue?**

Here's how that lays out …
![image](https://cloud.githubusercontent.com/assets/9259185/24254189/42070716-0fb0-11e7-8cf8-360f68c1cd36.png)

cc @meiqimichelle

**Comment by ericronne** [comment]
Here's a rewrite of card 2's headline, which eliminates one of the How's:
"Where does the money from extraction go?"

@meiqimichelle either this or my previously posted one do the trick for you?

![image](https://cloud.githubusercontent.com/assets/9259185/24315194/aecb487c-10b3-11e7-817c-8088b8e9968c.png)
