### ISSUE TITLE
Whitehouse.gov links no longer work

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2237]
The links below now return this …

![image](https://cloud.githubusercontent.com/assets/9259185/24410935/fb889f82-1399-11e7-8f73-df08241d94d5.png)

https://www.whitehouse.gov/sites/default/files/us_national_action_plan_final_2.pdf

https://www.whitehouse.gov/sites/default/files/docs/us_national_action_plan_6p.pdf

https://www.whitehouse.gov/sites/default/files/omb/budget/fy2016/assets/16msr.pdf

http://www.whitehouse.gov/omb/budget/Historicals

https://www.whitehouse.gov/omb/circulars_a123_rev

https://www.whitehouse.gov/omb/circulars_a123_rev

https://www.whitehouse.gov/omb/financial_ffs_ffmia

https://www.whitehouse.gov/sites/default/files/omb/budget/fy2016/assets/16msr.pdf

https://www.whitehouse.gov/sites/default/files/us_national_action_plan_final_2.pdf

https://www.whitehouse.gov/sites/default/files/docs/us_national_action_plan_6p.pdf

http://www.whitehouse.gov/blog/2013/12/06/united-states-releases-its-second-open-government-national-action-plan

**Comment by ericronne** [comment]
cc @gemfarmer @shawnbot @coreycaitlin

**Comment by gemfarmer** [comment]
@ericronne it looks like all the Obama-era whitehouse pages have been re-routed to https://obamawhitehouse.archives.gov

[Related PR on the 18F site](https://github.com/18F/18f.gsa.gov/pull/2361/files)

**Comment by gemfarmer** [comment]
Testing out your links:
- https://obamawhitehouse.archives.gov/sites/default/files/us_national_action_plan_final_2.pdf
- https://obamawhitehouse.archives.gov/sites/default/files/docs/us_national_action_plan_6p.pdf
- https://obamawhitehouse.archives.gov/sites/default/files/omb/budget/fy2016/assets/16msr.pdf
- http://www.whitehouse.gov/omb/budget/Historicals
- https://obamawhitehouse.archives.gov/omb/circulars_a123_rev
- https://obamawhitehouse.archives.gov/omb/circulars_a123_rev
- https://obamawhitehouse.archives.gov/omb/financial_ffs_ffmia
- https://obamawhitehouse.archives.gov/sites/default/files/omb/budget/fy2016/assets/16msr.pdf
- https://obamawhitehouse.archives.gov/sites/default/files/us_national_action_plan_final_2.pdf
- https://obamawhitehouse.archives.gov/sites/default/files/docs/us_national_action_plan_6p.pdf
- https://obamawhitehouse.archives.gov/blog/2013/12/06/united-states-releases-its-second-open-government-national-action-plan

**Comment by ericronne** [comment]
Thanks! Should we update these on the site, @usEITI?

**Comment by gemfarmer** [comment]
I'm not sure where went:

```bash
curl -I https://www.whitehouse.gov/omb/budget/Historicals
```
Returns:
```
HTTP/1.1 404 Not Found
Server: Apache
ETag: "116c2317c81c0990ffe4f2b6ce1c164d:1485373624"
Last-Modified: Wed, 25 Jan 2017 19:47:04 GMT
Accept-Ranges: bytes
Content-Length: 65296
Content-Type: text/html
Expires: Tue, 28 Mar 2017 14:54:22 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 28 Mar 2017 14:54:22 GMT
Connection: keep-alive
```

**Comment by gemfarmer** [comment]
Also the `http` version

```
curl -I http://www.whitehouse.gov/omb/budget/Historicals
```
Returns the `https` version of the same link. And both are dead 😕 
```
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://www.whitehouse.gov/omb/budget/Historicals
Date: Tue, 28 Mar 2017 14:56:42 GMT
Connection: keep-alive
```

**Comment by ericronne** [comment]
This looks like the missing historicals …
https://obamawhitehouse.archives.gov/omb/budget/Historicals

**Comment by gemfarmer** [comment]
All accounted for!
