### ISSUE TITLE
Consider moving "non-commodity revenue" chart

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2242]
PR #2241 renamed the "none" revenue category to "non-commodity revenues."

## Old
![image](https://cloud.githubusercontent.com/assets/9259185/24716415/99c0cd4a-19f4-11e7-9e93-726c544fa0a7.png)

## New
![image](https://cloud.githubusercontent.com/assets/9259185/24716540/ff451518-19f4-11e7-889e-506215829e53.png)

But this chart is slotted in with the rest, alphabetically, which may make it difficult to find.

**Ideas to consider:**
- Shift it to the end of the section (after wind)
- Create a new section especially for this category. This would give us a chance to explain it more fully, but requires content generation.

*Note: there is only one instance of this, so it isn't a high-priority task*

**Comment by coreycaitlin** [comment]
Also related to #1608

**Comment by coreycaitlin** [comment]
Not an immediate priority — closing for now.
