### ISSUE TITLE
Table bugs

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2245]
- [x] Tables shouldn't have vertical lines
  - https://useiti.doi.gov/case-studies/humboldt-and-lander/#data-availability
  - http://localhost:4000/case-studies/humboldt-and-lander/#data-availability
<img width="558" alt="screen shot 2017-04-05 at 4 13 55 pm" src="https://cloud.githubusercontent.com/assets/4803473/24727228/e294f692-1a1a-11e7-9ffe-39e2c6eb1226.png">

  - should look more like this: https://useiti.doi.gov/how-it-works/reconciliation/2016/
  - http://localhost:4000/how-it-works/reconciliation/2016/
<img width="636" alt="screen shot 2017-04-05 at 4 14 04 pm" src="https://cloud.githubusercontent.com/assets/4803473/24727227/e2905600-1a1a-11e7-8510-64c5a7c3e1ff.png">

  - https://useiti.doi.gov/how-it-works/coal-excise-tax/#coal-excise-tax-rates
  - http://localhost:4000/how-it-works/coal-excise-tax/#coal-excise-tax-rates
<img width="559" alt="screen shot 2017-04-05 at 4 14 11 pm" src="https://cloud.githubusercontent.com/assets/4803473/24727225/e283032e-1a1a-11e7-8e53-ac29dae7d677.png">

  - https://useiti.doi.gov/how-it-works/corporate-income-tax/
  - http://localhost:4000/how-it-works/corporate-income-tax/
<img width="558" alt="screen shot 2017-04-05 at 4 16 40 pm" src="https://cloud.githubusercontent.com/assets/4803473/24727364/579391e2-1a1b-11e7-98bb-3e2174ed862b.png">

**Comment by ericronne** [comment]
Another style

 - https://useiti.doi.gov/how-it-works/reconciliation/2016/

![image](https://cloud.githubusercontent.com/assets/9259185/24727817/08c94424-1a1d-11e7-8a97-3afd3028b8fa.png)

**Comment by gemfarmer** [comment]
And another one!!!
<img width="477" alt="screen shot 2017-04-05 at 4 32 02 pm" src="https://cloud.githubusercontent.com/assets/4803473/24727903/5ce683dc-1a1d-11e7-9190-5764d9c3bf4e.png">

**Comment by ericronne** [comment]
The counties chart is pretty good, but for we may want to:
- [ ]  Shrink table font size from .9 rem (14.4px) down to .875 rem (14px), to match the associated vertical bars
- [ ]  Increase the top and bottom <tr> padding from 5px to 7px, to give the type more breathing room

## Current style
![image](https://cloud.githubusercontent.com/assets/9259185/25055358/ddcd201c-2127-11e7-9e9a-017d07ac83d1.png)

## Tweaked
![image](https://cloud.githubusercontent.com/assets/9259185/25055344/c7ca63a6-2127-11e7-9b09-cbf6c58cb29f.png)

**Comment by ericronne** [comment]
Opened new issue for county tables
