### ISSUE TITLE
Update federal revenues data

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#2247]
Chris will be sending updated Excel files shortly. Once they arrive, I will post them here. Then:

1. Upload new data files here, and edit text to say indicate 2016 as newest year: https://useiti.doi.gov/downloads/federal-revenue-by-location/

2. Update federal revenues data displays from 2015 to 2016: https://useiti.doi.gov/explore/#federal-revenue
- [x] The megacharts can default to 2016
- [x] The `Federal revenue trends by resource` can be a 10-year span, most recent span = 2016

Here are the excel files:
[federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_CY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930686/federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_CY06-16_2017-04-07.xlsx)
[federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_FY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930687/federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_FY06-16_2017-04-07.xlsx)
[federal_revenue_offshore_acct-year_CY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930688/federal_revenue_offshore_acct-year_CY06-16_2017-04-07.xlsx)
[federal_revenue_offshore_acct-year_FY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930689/federal_revenue_offshore_acct-year_FY06-16_2017-04-07.xlsx)
[federal_revenue_onshore_acct-year_CY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930690/federal_revenue_onshore_acct-year_CY06-16_2017-04-07.xlsx)
[federal_revenue_onshore_acct-year_FY06-16_2017-04-07.xlsx](https://github.com/18F/doi-extractives-data/files/930693/federal_revenue_onshore_acct-year_FY06-16_2017-04-07.xlsx)

**Comment by coreycaitlin** [comment]
🎉
