### ISSUE TITLE
Discuss trimming legends to only show colors that appear on their adjacent maps

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2248]
Legends for county production maps always show colors for all four possible ranges, even if a map has only one or two colors. Users might find map info easier to absorb if the legends showed only the colors which actually appear on the accompanying maps.

### Current approach
![image](https://cloud.githubusercontent.com/assets/9259185/24773562/4cb3b3e0-1adb-11e7-9446-d02ce08a203d.png)

### Proposed approach
![image](https://cloud.githubusercontent.com/assets/9259185/24773710/dbcc7454-1adb-11e7-9380-5c070e015f46.png)

**Comment by coreycaitlin** [comment]
We discussed this before in #1721, with related convo in #2094. I believe our conclusion was that we shouldn't filter out "unused" ranges, because it isn't a normal pattern and would complicate the legend component.

**Comment by ericronne** [comment]
I definitely see that logic. 👍 
Would also love to test this, to confirm.

**Comment by coreycaitlin** [comment]
Closing this out — not a priority for current product needs, and we aren't confident it will make things more usable.
