### ISSUE TITLE
How it works IA: consider merging federal and state law sections 

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2255]
### In the [**how it works**](https://useiti.doi.gov/how-it-works/) section, might it make sense to combine this section …

![image](https://cloud.githubusercontent.com/assets/9259185/24931466/00ba08bc-1ed3-11e7-9444-ae9a89990228.png)

### with this section …

![image](https://cloud.githubusercontent.com/assets/9259185/24931720/ee49914c-1ed3-11e7-9ed3-626796e1fa97.png)

### to give us this?

![image](https://cloud.githubusercontent.com/assets/9259185/24931779/2b6ef800-1ed4-11e7-84fb-e374f75ee8fd.png)

My gut feeling is that the same user may be interested in both federal and state laws, for example, but i could be wrong. Tossing it out there For Your Consideration @meiqimichelle @gemfarmer

**Comment by coreycaitlin** [comment]
Sure, this would be fine! I like `What laws and regulations govern natural resource extraction in the U.S.?`

**Comment by meiqimichelle** [comment]
Done with #2263.
