### ISSUE TITLE
Bug: Megachart Oil & gas text

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2262]
![screen shot 2017-04-18 at 11 19 31 am](https://cloud.githubusercontent.com/assets/4803473/25141355/efa627e4-2428-11e7-970c-ab216db0582e.png)

https://useiti.doi.gov/explore/OH/

Megachart oil & gas line looks wonky

**Comment by gemfarmer** [comment]
I think this is done. Right, @line47 ?

**Comment by line47** [comment]
Still looks wonky here - https://useiti.doi.gov/explore/OH/ I'm happy to fix it though. I can probably get to it next week.

**Comment by ericronne** [comment]
yep, wonky here, there, seems like ... everywhere :(

![image](https://user-images.githubusercontent.com/9259185/29478111-f280bba6-8430-11e7-9c79-407b40266f7a.png)

**Comment by line47** [comment]
Should it look like this?

<img width="153" alt="screen shot 2017-08-25 at 4 10 04 pm" src="https://user-images.githubusercontent.com/1449852/29733133-c9380f86-89b9-11e7-8f1a-4540d03a9a8c.png">


cc @ericronne

**Comment by line47** [comment]
This was also an issue with NGL so I'm adding that into this fix. 
![screen shot 2017-08-28 at 9 49 17 am](https://user-images.githubusercontent.com/1449852/29776286-27b98904-8bd6-11e7-854c-3d6bb4e507da.png)

**Comment by coreycaitlin** [comment]
This is finally fixed! 🎉
