### ISSUE TITLE
Phoenix style phixes pairing: Selectors

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2269]
- [x] **Make selectors more consistent with the overall site style**: kill outlines, use fills instead:
 - Dark gray (home-page state select, explore and case studies ribbon selectors)
 - Light gray (case study sub pages)
 - Dark green (data year selectors, already exist, consider resizing to bring into line with others, if not too bulky)

**Comment by gemfarmer** [comment]
Closing with #2273
