### ISSUE TITLE
Phoenix style phixes pairing: Case studies intro and right column

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2272]

**Comment by ericronne** [comment]
Consider stealing the state-page intro style, where the map is nested in the text. 


## Current
![image](https://cloud.githubusercontent.com/assets/9259185/25282192/5c6f596a-2675-11e7-8e80-766244a21c0c.png)

## Potential redo
![image](https://cloud.githubusercontent.com/assets/9259185/25282377/e516b998-2675-11e7-9277-f068fa17d3d3.png)

## Changes this would entail
 - [ ] Remove small commodity label/icon. It looks like a breadcrumb, but isn't really one
 - [ ] Add the commodity name to the front of the title
 - [ ] Restyle the selector (#2269) and narrow it
 - [ ] Shift sticky nav (#2271)
 - [ ] Nest the map image in the text
 - [ ] Remove the extra space which is embedded in the map svgs
 - [ ] Adjust intro type size (maybe)

**Comment by ericronne** [comment]
@gemfarmer if we could pair on enlarging the now-nested maps, that might be enough to close this out.

**Comment by ericronne** [comment]
@gemfarmer 🍐  would indeed rock here, whenever. Svg's, oh my. XO

**Comment by coreycaitlin** [comment]
Is this done with #2302?

**Comment by ericronne** [comment]
indeed.
