### ISSUE TITLE
Flickering sticky nav dropdown

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2274]
## Expected Behavior
The dropdown within the explore page stick navs should not flicker as the user is scrolling

![screen shot 2017-04-27 at 1 54 37 pm](https://cloud.githubusercontent.com/assets/4803473/25499347/bec96814-2b50-11e7-88de-67308ea9ff95.png)

## Actual Behavior
It is flickering

## Steps to reproduce the behavior
- change it in the JS or in the design.

If the design were to change, we could:
- make it so the year selector is always directly to the right of the nav 
- remove other year selector

Programmatically
Change the timeouts in `components/sticky.js` so that it doesn't flilcker

**Comment by ericronne** [comment]
Could we pair on this? Would love to adjust padding, too!

**Comment by coreycaitlin** [comment]
Is this fixed with #2282?

**Comment by gemfarmer** [comment]
I think this is fixed
