### ISSUE TITLE
Update text on one home card, and target link more specifically

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2275]
## This card on the home page links to the how page …
![image](https://cloud.githubusercontent.com/assets/9259185/25355905/ec53eab6-28fd-11e7-9e1d-87edb2ba65f0.png)

## Should it instead anchor link directly to the [#process tag](https://useiti.doi.gov/how-it-works/#process) on the page? …
![image](https://cloud.githubusercontent.com/assets/9259185/25355987/3de2f49e-28fe-11e7-8ca7-00aca329f8b0.png)

## And should we update the headline to match the card, like so?
![image](https://cloud.githubusercontent.com/assets/9259185/25356044/75735034-28fe-11e7-9f57-66ab0d795dd7.png)

**Comment by coreycaitlin** [comment]
I think this is done with #2285

**Comment by ericronne** [comment]
yep!
