### ISSUE TITLE
Link priority-states map to state legal page

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2276]
The u.s. map on the [state laws page](https://useiti.doi.gov/how-it-works/state-laws-and-regulations/) doesn't link anywhere. Since the other u.s. maps are clickable, perhaps this one should be, too …

![image](https://cloud.githubusercontent.com/assets/9259185/25359515/2a57f21e-290b-11e7-94f8-7a7f0675c535.png)

Could we borrow the home-page map behavior, and anchor-link to each priority state here? To wit:

![image](https://cloud.githubusercontent.com/assets/9259185/25359812/3c206016-290c-11e7-9bbe-9f92ad4b8c10.png)

**Comment by gemfarmer** [comment]
@ericronne Good idea. This shouldn't be that hard. It might be nice to create a standard for a clickable map without ownership as a backdrop. If we end up doing commodity pages (oil, gas, coal, etc.) that could be useful!

**Comment by coreycaitlin** [comment]
#2297 includes an initial solution for this by at least linking to all the state info

**Comment by coreycaitlin** [comment]
Priority states are a concept very tied to the 2015 EITI Annual Report, so this interaction is not a priority for improving the user experience going forward.
