### ISSUE TITLE
Bug: sticky date selector requires two clicks

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2283]
## Expected Behavior
Click once to open selector

## Actual Behavior
First click gives focus to selector; second click opens it

**Comment by gemfarmer** [comment]
https://gsa-tts.slack.com/archives/C02CZB4G5/p1493400390252656

**Comment by gemfarmer** [comment]
This seems to have gone away on its own. Does anyone else still experience this bug?

**Comment by ericronne** [comment]
☑️ Chrome
☑️ Safari (which still [ugh! typewise](https://github.com/18F/doi-extractives-data/issues/875))
☑️ Firefox

**Comment by gemfarmer** [comment]
is a check mark mean it is working, or not working?

**Comment by ericronne** [comment]
Working!! :)
