### ISSUE TITLE
Visual bug: funky coal link on how it works landing page 

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2299]
![image](https://cloud.githubusercontent.com/assets/9259185/26108093/07b1761a-3a11-11e7-8c51-61f87e9e8df2.png)

**Comment by ericronne** [comment]
Tablet breakpoint messes with these suckers.

**Comment by ericronne** [comment]
Tablet breakpoint messes with these suckers.

**Comment by coreycaitlin** [comment]
Related to #1857 — hopefully we can get both at the same time.

**Comment by gemfarmer** [comment]
How it works landing page is at https://useiti.doi.gov/how-it-works/
