### ISSUE TITLE
Jobs: Show breakdowns within each category

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2311]
There are some interesting breakdowns within each category of extractives jobs. For instance:

- Mining vs. mining support (for coal, oil, gas, and hardrock)
- Surface vs. underground-mined coal
- Phases of extraction: drilling vs. extraction

For most of these, **national-level breakdowns would probably be sufficient** for a first pass; we may not need to get this much detail on the state pages just yet.

**Comment by gemfarmer** [comment]
@coreycaitlin would this be a useful issue for @toolness to look at?

**Comment by coreycaitlin** [comment]
This isn't currently central to the NRRD product vision, and we're comfortable referring users to BLS for more advanced breakdowns if they need to explore the jobs data more fully.
