### ISSUE TITLE
Content: Nonenergy minerals information

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2314]
The IA has produced additional contextual information about nonenergy minerals. We'll need to figure out how much of this is new, where it belongs on the website, and how it should be connected to related data and context.

**Comment by coreycaitlin** [comment]
[Final source content is here (limited access)](https://drive.google.com/drive/folders/0B-tWFsKyyEsKYjAtV01KdEZMX0E).

The existing site covers [copper, gold, and iron](https://useiti.doi.gov/how-it-works/minerals/) within `How it works > How do natural resources result in federal revenue? > Production > Nonenergy minerals`. That page covers the 5 steps of production->revenue: Plan, Claim, Explore, Develop, and Decommission and reclaim. It also includes revenue rates.

The new addition includes information about lead, zinc, silver, and molybdenum, but is structured completely differently from the existing nonenergy minerals page. Each of these new metals has the following sections:

- Overview
- Production
- Industry overview
- Economic impact
  - Imports & exports
  - Jobs & wages
  - Costs
     - Water
     - Reclamation

The sources for much of this content are the USGS mineral overviews and other USGS publications. (Costs info comes from other sources.)

Each mineral has one bar chart, which compares the amount produced on all lands and waters to the amount produced on federal lands and waters. I don't think we have any other bar charts that do this elsewhere.

Questions to discuss as we incorporate this information:

- [ ] When should we manually copy USGS data, and when should we link to USGS resources? (For example, each state profile in "Explore data" links to the USGS Minerals Yearbook for that state, so that we don't need to hard-code that production data in order to show users how to find it.)
- [ ] Does the process & revenue information on the existing nonenergy minerals page also apply to these minerals?
- [ ] Should this information be incorporated into existing pages, or should we create 4 new pages?
- [ ] If we create 4 new pages, where should they go in the information architecture? They don't really fit under any of the existing headers in "How it works", though the summaries might belong on the [production summary page](https://useiti.doi.gov/how-it-works/production/).
- [ ] If we create 4 new pages, what page templates should we use? In many ways, the structure of these pages is similar to the case studies.

I think the next step is to *identify some potential user stories* — even if they're first-stab hypotheses — to help us think through where to put this content and how much to re-create from USGS.

**Comment by coreycaitlin** [comment]
After discussing with Luke, we've determined that this can fit into a new series of "How it works" pages.

**Comment by jamiealbrecht** [comment]
Hello! Adding a few notes and questions to this issue about the new how it works pages. I've pulled in the information on lead, zinc, silver and molybdenum on a new page currently titled "what resources are extracted in the United States?" 

A little bit about what I did (in the order of the powerpoint documents):

**Overview:** The overview is great and I used most of it! I linked to the USGS page for each new mineral once hoping to not duplicate too much of their content. The USGS overview page lets people drill down if they want more information about a specific mineral. 

**Production:** We have production data for lead, zinc, gold, and silver in the explore data section. Do we want to include data for molybdenum there, too? The production stats, as custom content, will be hard to maintain over time and that information is also available via USGS. So, I didn't include them here, but we can talk about that!

**Industry overview** (Same as production) This information is all provided by the USGS. For simplicity, we should link to USGS and if people want more information, they can find it all there.

**Economic impact** A few questions: 
1. Are we going to start including content about imports and exports for each commodity?
Per our past user research, users are more interested in regional data, not by commodity, so I imagine no. However, I thought I should put the question here.
2. In the explore data section, we currently show a figure of jobs and wages for nonenergy minerals. Do we need to break that down further?
3. Are we going to start having a costs (environmental and the like) section for each commodity?

**Comment by jamiealbrecht** [comment]
Here are the screenshots of the new nonenergy minerals: 
![30552400-a3a2240e-9c52-11e7-9d62-736086555ffe](https://user-images.githubusercontent.com/6954943/31458370-bab3b566-ae74-11e7-8758-e01d1f685727.png)
![30552404-a992d5de-9c52-11e7-9cc0-63befe29daa9](https://user-images.githubusercontent.com/6954943/31458372-bc40d29c-ae74-11e7-96e0-586524a0babd.png)

What do you think about this @coreycaitlin?

**Comment by jamiealbrecht** [comment]
The nonenergy minerals currently on the site (gold, copper, and iron) have 2014 and 2015 statistics that I think might be hard to maintain going forward. Should we keep them? Try writing them in a different way? Or get rid of them a la lead, zinc, silver, and molydbenum in the comment above?

**Comment by coreycaitlin** [comment]
@jamiealbrecht This looks great ([preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/nonenergy-minerals/))! A few notes:

- The last intro sentence ("We’ll talk about them and a few others here.") feels a little out-of-step with the voice/tone of much of the site; I think the intro would be okay without it.
- I agree that those inline stats are going to be a pain to maintain. Let's edit them out, as long as they're reasonable accessible from the USGS mineral overviews.
- Should we help users explore deeper on the site from this page? Maybe link to the Explore Data > Federal Production data? Case studies for counties with mineral production?

And to your questions from way back...

1. Are we going to start including content about imports and exports for each commodity?
Per our past user research, users are more interested in regional data, not by commodity, so I imagine no. However, I thought I should put the question here.
    - My instinct is that this data will be too hard to maintain, especially as it's not owned by ONRR/DOI.
2. In the explore data section, we currently show a figure of jobs and wages for nonenergy minerals. Do we need to break that down further?
    - I don't think so, but we might want to link to that, for folks who want to see the overall number.
3. Are we going to start having a costs (environmental and the like) section for each commodity?
    - Again, I think this'll be too hard to maintain, but we _could_ link to some representative case studies so people can understand the broad categories and issues involved. @brentryanjohnson Might also have insight on this.

**Comment by brentryanjohnson** [comment]
Nice work, @jamiealbrecht!

I agree with @coreycaitlin's general recommendations. I added a few minor edits and suggestions:

* The h2 and [h1](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/nonenergy-minerals/#nonenergy-minerals) are identical with a redundant sentence following the h2 (the headings also have the same id, so I can't link to it separately). Perhaps omit the h2 and combine the paragraphs under h1?
* Change "amongst" to "among" in the opening paragraph
* Typo in last sentence of the Copper section ("forth" to "fourth")
* Perhaps omit the last sentence in the Iron section. The regional information is nice context, but referring only to Minnesota's drilling trends after mentioning both Minnesota and Michigan leads to questions about the trends in Michigan as well without providing them (also, the [linked Minnesota site](http://www.dnr.state.mn.us/lands_minerals/exploration.html#2015) now contains information from 2016).

**Comment by jamiealbrecht** [comment]
Thank you both so much for your helpful feedback! Here are the changes I made:

1. Removed "we talk about a few of them here"
2. Removed many of the inline stats and linked to USGS where people can find the PDF summary sheets with these kinds of facts
3. Added links to case studies for copper and iron.
4. Fixed heading redundancy
5. Changed amongst to among
6. Fixed typo in copper section
7. Removed the last sentence in the iron section (part of # 2) 

Remaining questions that can be tackled later (I assume):
1. Should we add placer mines to the glossary?
2. Should we link to relevant case studies about costs?

Let me know what y'all think. <3

**Comment by coreycaitlin** [comment]
Thank you @jamiealbrecht!
