### ISSUE TITLE
A whole new flicker: side nav sub label

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2317]
"Federal land" flickers between different font weights as you scroll past charts, in Chrome. No flicker in Safari, eg.

![rop3eazhnn](https://user-images.githubusercontent.com/9259185/27346331-72878184-55b2-11e7-8971-a31b19bf4b24.gif)

**Comment by coreycaitlin** [comment]
I can't duplicate this, and it's currently a low priority.
