### ISSUE TITLE
On Explore page, some glossary links do not pull up term in glossary

### ISSUE THREAD

**Issue by onezerojeremy** [18F/doi-extractives-data#2319]
Some glossary-tied units on the "explore data" page do not actually have glossary entries. 

## Expected Behavior
Clicking on the glossary link for some links (seems like mostly units associated with Geothermal energy) should pull up the glossary definition for that unit. Very curious what a "sulfur" of geothermal energy is.  

## Actual Behavior
The glossary loads, but does not load a definition for the glossary. 

## Steps to reproduce the behavior
go to: https://useiti.doi.gov/explore/#federal-production
Scroll to find the Geothermal charts. 
Click on the units. 
look at the glossary, note the absence of a findable term.

**Comment by gemfarmer** [comment]
Thanks @onezerojeremy! 

I think this is because we don't have any of the gallons units in the [terms.yml](https://github.com/18F/doi-extractives-data/blob/dev/_data/terms.yml). We should probably make sure that other units didn't make it in for whatever reason.

**Comment by gemfarmer** [comment]
One other potential solution proposed by @coreycaitlin would be to only add glossary links to units that need them

**Comment by coreycaitlin** [comment]
🎉 This is fixed with #2328
