### ISSUE TITLE
On how it works page, the link to state and tribal lands is broken

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2334]
## Expected Behavior
When I click on "state and tribal lands" in the second paragraph on the page, I expect it to bring me down to a section on how those lands are managed

## Actual Behavior
Nothing happens

## Steps to reproduce the behavior
* Go to https://useiti.doi.gov/how-it-works/ 
* Click on the link to "state and tribal lands" in the second paragraph on the page. (It should also be here I presume: https://useiti.doi.gov/how-it-works/#state-tribal)

**Comment by coreycaitlin** [comment]
Let's fix this by rewriting this sentence and its links to better reflect the current organization of this page:

> Learn what the extraction process looks like, how state and tribal lands are managed, and what laws and governance relate to the industry.

**Comment by jamiealbrecht** [comment]
@coreycaitlin, how about something like this?

Learn what governs natural resource extraction in the U.S., how resources result in
federal revenue, and what processes ensure accuracy and accountability in this industry.

**Comment by coreycaitlin** [comment]
Fixed with #2344
