### ISSUE TITLE
Content: proofreading how it works, ownership, state and local lands

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2335]
On this page https://useiti.doi.gov/how-it-works/ownership/#state-and-local-lands: 

Is it worth defining three marine leagues or putting it in the glossary? Admittedly, I looked it up because I was curious if it's the same as three miles.

**Comment by coreycaitlin** [comment]
Yeah — I think we could either define it inline, add to the glossary, or link to a definition. Maybe we can decide which based on how handy a definition we can find and whether we use it elsewhere on the site.

**Comment by coreycaitlin** [comment]
@jamiealbrecht and I chatted about this the other day — turns out the term "marine leagues" only occurs twice on the site, so we think it's overkill to make a new glossary item.
