### ISSUE TITLE
Proofreading how it works, federal laws: Should we write out EISs acronym?

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2336]
In this section https://useiti.doi.gov/how-it-works/federal-laws/#regulations , we say "Environmental Assessments (EAs) and/or EISs," should we write out the acronym for EIS? It tripped me up a little bit until I got to the next sentence that mentions impact statements.

**Comment by coreycaitlin** [comment]
Yes, we should write it out or add it to glossary, depending on how much we use it. On this page, I'd vote for writing it out _and_ removing `(EAs)`, since we don't use that term again later in the page.

**Comment by jamiealbrecht** [comment]
Ha! On second review, EIS is in the glossary. 

In other places on the site we write out the full term and link to the glossary definition. We should follow that same convention here.
