### ISSUE TITLE
Use of and/or on the site

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2337]
We use and/or on the site consistently. Admittedly, I wasn't expecting that to be the convention. Should we add it to the content guide?

**Comment by coreycaitlin** [comment]
It would definitely be better to avoid `and/or`, but editing these out might require further research in some instances.

**Comment by coreycaitlin** [comment]
Much improved! @jamiealbrecht, did you get them all?

**Comment by jamiealbrecht** [comment]
Yes! Thank you for all your merging while I was gone. :)
