### ISSUE TITLE
Proofreading how it works, revenues: Punctuation in bulleted lists

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2338]
In the bulleted list in extractions from any land or water https://useiti.doi.gov/how-it-works/revenues/#all-lands-and-waters , should the second sentences in the list end in a period since they are all complete sentences?

**Comment by coreycaitlin** [comment]
Yes, probably! Let's clarify that list items should end with a full stop when they're a complete sentence.

**Comment by coreycaitlin** [comment]
🎉 all done!
