### ISSUE TITLE
Remove "Indian Trusts Act of 1882" link

### ISSUE THREAD

**Issue by lukehawbaker** [18F/doi-extractives-data#2339]
The link to the "Indian Trusts Act of 1882" at the bottom of the [Audit and Assurances page ](https://useiti.doi.gov/how-it-works/audits-and-assurances/) needs to be removed. It deals with the country of India, not tribes in the United States.

**Comment by lukehawbaker** [comment]
It turns out this was also in the factsheet from last year. I've updated it and have a new PDF. @coreycaitlin or @jamiealbrecht who would it be easiest to send that to?

**Comment by coreycaitlin** [comment]
Thanks @lukehawbaker and @jamiealbrecht!
