### ISSUE TITLE
Update Federal Production data

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2345]
We have federal production data for FY and CY 2007-2016 (limited access: [spreadsheets here](https://drive.google.com/drive/folders/0B4b900J0no9nRkQzMkZIQmJBbHM)).

This issues is done when:

- [x] The latest dataset is pulled into the site
- [x] New data is tested
- [x] New data is verified by @mentastc

**Comment by winzenburg** [comment]
Did our friend "brine barrels" get eliminated?

**Comment by coreycaitlin** [comment]
@winzenburg Not totally sure what you mean! Could you add a bit more detail?

**Comment by coreycaitlin** [comment]
@winzenburg I figured it out! Yes, it looks like 2006 was the only year for which we had _non-withheld_ `brine barrel` production data. With #2386, this section is now showing data for 2007-2016, so there is no graph for brine barrel production on federal land.

If you expand the "Data withheld" section below, it notes that production data for brine barrel production on federal land was withheld for 2007, 2008, and 2010.

**Comment by coreycaitlin** [comment]
Closing this out, because we've merged this data into dev, and it's been reviewed by @mentastc. Will reopen if we spot any data issues as we push to production.
