### ISSUE TITLE
Content: Revise "About USEITI" page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2347]
Working on the new about page [in this document ](https://docs.google.com/document/d/1tX63eOlIUKhkjUY00xE76ZdQWUgs-nzyQYgXrl6qiqw/edit). (limited access)

**Comment by coreycaitlin** [comment]
Next step: identify evergreen content and propose new page structure.

**Comment by jamiealbrecht** [comment]
Just updated the original comment with the google doc link.
