### ISSUE TITLE
Content: Homepage banner content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2348]

**Comment by coreycaitlin** [comment]
Next step: Draft partial revised homepage content, with placeholders for unknown elements.

**Comment by jamiealbrecht** [comment]
Started the draft homepage content v1 with "U.S. natural resources transparency" as the stand in name for the moment. 

![screen shot 2017-08-29 at 11 36 24 am](https://user-images.githubusercontent.com/6954943/29838424-094338aa-8cb0-11e7-8cfc-cd86d6a4fae3.png)

![screen shot 2017-08-29 at 11 36 48 am](https://user-images.githubusercontent.com/6954943/29838412-01da2ee8-8cb0-11e7-9dd2-2104bd89eeec.png)

**Comment by coreycaitlin** [comment]
Blocked by #2352

**Comment by ericronne** [comment]
@coreycaitlin @jamiealbrecht @winzenburg 

I wonder if this be developed _in tandem_ with #2352, as opposed to being blocked by it. Then we could test name ideas in the context of the home-header layout, along these lines …
![image](https://user-images.githubusercontent.com/9259185/30813643-9899f0ce-a1d3-11e7-848b-d7a9cbf053ec.png)

Thoughts?

**Comment by jamiealbrecht** [comment]
I think that's a good idea. 👍

**Comment by coreycaitlin** [comment]
Current draft banner copy:

> This site provides open data about natural resource management on federal lands and waters in the United States, including oil, gas, coal, and other extractive industries.

The header copy will depend on the final site name, in order to balance out keywords and make sure users can understand at a glance what the site is about.

We also found in [initial testing](https://github.com/18F/doi-extractives-data/blob/research/research/13_sprint-preposterous-puffin/sprint-preposterouspuffin_results.md) that the banner graphic (the oil rig + dollar sign) was helpful for helping people rapidly grasp the topic, and that the call to action "Explore data" was effective.

**Comment by coreycaitlin** [comment]
If we're moving forward with the title `Natural resources revenue data`, the remaining missing keywords/concepts might include:

- Energy and mineral extraction in the U.S. — I feel best about this one, I think
- Extraction on federal lands and waters — we hit "lands and waters" in the sentence, and "extraction" on its own is tricky

**Comment by coreycaitlin** [comment]
Closing this out — further work in #2395 🎉
