### ISSUE TITLE
Choose site name

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2352]
We started this in several workshops over the past few weeks, but need to settle on a few options and come to a decision.

**Comment by ericronne** [comment]
Working files and such …

 - [Background, etc.](https://docs.google.com/document/d/1ilYbFwii7vvVtZ0RRDxq4FxLng_BG3cAG10egDg_NIQ/edit#)
 - [Initial workshop Mural](https://app.mural.ly/t/gsa6/m/gsa6/1503083839726/5b889490ce4c25648af575d0b759113983126796)
 - [Mural zeroing in on words](https://app.mural.ly/t/gsa6/m/gsa6/1505399272414/0f4fbff389d3692a8160142453db0cba992a1d08)
 - [G-sheet to track and unpack words](https://docs.google.com/a/gsa.gov/spreadsheets/d/1ylBW4LyYAaQN9mvwOh89vLfYH7mOJ9XlCa3CLoAbA5o/edit?usp=sharing)

**Comment by coreycaitlin** [comment]
Next step: come up with 2 solid options to discuss and test.

**Comment by winzenburg** [comment]
Part-I co-working session on friday

**Comment by ericronne** [comment]
### [mural](https://app.mural.ly/t/gsa6/m/gsa6/1505399272414/0f4fbff389d3692a8160142453db0cba992a1d08)

**Comment by ericronne** [comment]
Branding "zones" we can play with for our test …
![home page branding zones](https://user-images.githubusercontent.com/9259185/30867989-0cf9511a-a2a3-11e7-9406-4e86b78ccc3c.png)


## WIP list of names and other branding elements to test.
We can suss out specific combinations next.
_Checked box = to be included._

### Name / URL
 - [ ] U.S. Resources Revenue / usresourcesrevenue
 - [ ] Resource revenue data / resourcerevenue (or resourcerevenuedata)
 - [ ] Resource revenue explorer / resourcerevenue
 - [ ] Energy resources data / energyresources
 - [ ] Energy and minerals data / energyandminerals (or energyandmineralsdata)
 - [ ] Energy and mineral revenues / energyandminerals
 - [ ] Energy and mineral revenue data / energyandmineralrevenue
 - [ ] (others)

### DOI branding
 - [ ] Top banner: "An official website of the U.S. Department of the Interior"
 - [ ] Top banner: "U.S. Department of the Interior"
 - [ ] Top banner: "An official website of the U.S. government" (the usual)
 - [ ] Atop logo: "U.S. Department of the Interior"

### Tagline
 - [ ] Data explorer
 - [ ] (others)

### Placeholder lead story
Q: What copy should we use? (#2348)

**Comment by ericronne** [comment]
updated "branding zones" graphic …

![artboard copy 3](https://user-images.githubusercontent.com/9259185/30929844-5fdf7962-a385-11e7-95fc-1a312efad135.png)

**Comment by ericronne** [comment]
Final mockups are over in the testing issue: #2384

**Comment by coreycaitlin** [comment]
Based on our [initial testing results](https://github.com/18F/doi-extractives-data/blob/research/research/13_sprint-preposterous-puffin/sprint-preposterouspuffin_results.md), we're going to move forward with variations on `Natural resources revenue data` (or a variation like "Natural resource revenue data" or "Natural resources revenue").

**Comment by ericronne** [comment]
Final name, typographic tweaks still in progress …

![image](https://user-images.githubusercontent.com/9259185/31558622-4e8963cc-b013-11e7-8280-de35908a6bcd.png)

**Comment by coreycaitlin** [comment]
Onward!
