### ISSUE TITLE
'make site-data' doesn't crash when errors occur

### ISSUE THREAD

**Issue by toolness** [18F/doi-extractives-data#2354]
I was able to discover #2353 because I ran `make site-data` immediately after running `make db` (as specified in the contributor instructions) and there was a splotch of red text that flew by. The command appeared to run successfully (the exit code was 0) but when I scrolled up to the splotch of red text, it was error output from some kind of command that was running a SQL query on the `tribal_revenue` table:

```
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: tribal_revenue
    at Query.formatError (/doi/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
    at afterExecute (/doi/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at replacement (/doi/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/doi/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

Ideally, I think this ought to make the Makefile exit with a non-zero error code, rather than simply printing the error to the console and moving on as though nothing bad had happened.

**Comment by coreycaitlin** [comment]
Keeping this, because it does reflect the desired behavior, and should be relatively manageable to achieve.

**Comment by jennmalcolm** [comment]
Closing and will reopen if error exists when we try updating tribal revenue data again.
