### ISSUE TITLE
Running "npm run watch-styleguide" fails because "watchy" can't be found

### ISSUE THREAD

**Issue by toolness** [18F/doi-extractives-data#2355]
Following the [instructions for running the styleguide](https://github.com/18F/doi-extractives-data/blob/dev/CONTRIBUTING.md#styleguide) results in the following error:

```
> @ watch-styleguide /doi
> watchy -w '_sass' -- npm run build-styleguide

sh: 1: watchy: not found
```

I talked to @gemfarmer about this and he recommends just removing the styleguide entirely, as it's quite out-of-date now. Apparently it was useful in the early stages of the project but has now outlived its usefulness.

**Comment by coreycaitlin** [comment]
@toolness That sounds good — if it's going to be easier to build a fresh styleguide than modify the old one, that's fine by me!

**Comment by coreycaitlin** [comment]
Overtaken by events — this is outdated with #2557
