### ISSUE TITLE
Broken link in how it works, production, gas

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2364]
On this page https://useiti.doi.gov/how-it-works/production/ in the gas section, the last link is broken. 

The link to "offshore exploration and development plans" is https://www.data.boem.gov/homepg/data_center/plans/plans/master.asp which 404s.

**Comment by coreycaitlin** [comment]
Closing for now — we're going to address this wave of broken links in a larger content audit.
