### ISSUE TITLE
Broken link in how it works, production, renewable energy, geothermal energy

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2365]
On this page https://useiti.doi.gov/how-it-works/production/#renewable-energy the second link in the geothermal section is broken. 

Where it says "40% of US geothermal energy capacity is on leased federal lands," it supposed to go to this link https://www.blm.gov/wo/st/en/prog/energy/geothermal.html but that page is not found.

**Comment by coreycaitlin** [comment]
Closing for now — we're going to address this wave of broken links in a larger content audit.
