### ISSUE TITLE
Broken link in how it works, production, solar energy

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2366]
In this section https://useiti.doi.gov/how-it-works/production/#solar-energy the link to "[70 pending applications to develop solar energy projects](https://www.blm.gov/wo/st/en/prog/energy/solar_energy.html)" leads to an error page.

**Comment by coreycaitlin** [comment]
Closing for now — we're going to address this wave of broken links in a larger content audit.
