### ISSUE TITLE
Upgrade to Jekyll 3.5.2

### ISSUE THREAD

**Issue by toolness** [18F/doi-extractives-data#2371]
One of the most time-consuming aspects of working on this project is the lengthy amount of time it takes for Jekyll to rebuild itself, even in incremental mode. According to the [Jekyll 3.5.2 release announcement](https://jekyllrb.com/news/2017/08/12/jekyll-3-5-2-released/), the latest version of Jekyll is much faster:

> 3.5.2 is out with 6 great bug fixes, most notably one which should dramatically speed up generation of your site! In testing #6266, jekyllrb.com generation when from 18 seconds down to 8.

**Comment by coreycaitlin** [comment]
Closing in favor of #2649
