### ISSUE TITLE
Broken Link: https://useiti.doi.gov/how-it-works/revenues/#tax-expenditures

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2372]
The three links under the [Tax Expenditures section on the How it Works / Revenue page](https://revenuedata.doi.gov/how-it-works/revenues/#tax-expenditures) are going to 404 pages.

See image

![screencapture-realtimeboard-app-board-o9j_k0ogcgi-1504714384222](https://user-images.githubusercontent.com/11579256/30122600-393d56ca-92ec-11e7-8f88-36623d505d05.png)

**Comment by coreycaitlin** [comment]
This is a great training issue — let's find time to pair on this!

**Comment by brentryanjohnson** [comment]
@mentastc Are you interested in tackling more broken links with me?

**Comment by coreycaitlin** [comment]
Next step: find the right links!

**Comment by coreycaitlin** [comment]
Issues in this section:

- "Defined in the law" link is broken (current destination: https://www.treasury.gov/resource-center/tax-policy/Documents/Tax-Expenditures-FY2017-Revised.pdf)
- PDFs aren't marked as PDFs

**Comment by coreycaitlin** [comment]
Closing in favor of #2540
