### ISSUE TITLE
Glossary glosses over basic terms

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2377]
Helper text seems to invite me to enter very basic terms, such as "solar"…

![image](https://user-images.githubusercontent.com/9259185/30564778-b28a46d4-9c8b-11e7-9783-3ad0ac8de0b0.png)

Users might benefit from the addition of terms such as "solar," "geothermal," etc. Let's discuss adding them.

**Comment by ericronne** [comment]
cc @jamiealbrecht @coreycaitlin

**Comment by ericronne** [comment]
Also "slang-y" terms like "fracking."…
![tyaq1dcmqv](https://user-images.githubusercontent.com/9259185/30720803-9ec38402-9eee-11e7-91ab-899e266dbf23.gif)

**Comment by coreycaitlin** [comment]
Larger glossary consistency and usage will be assessed in #2624
