### ISSUE TITLE
Year selectors can render dropdown items that are both "disabled" and "selected"

### ISSUE THREAD

**Issue by toolness** [18F/doi-extractives-data#2378]
This bug was originally mentioned in #2374.

Basically, `_includes/year-selector.html` is structured such that it can generate options that look like this:

```html
<option disabled value="2016" selected>2016 no data</option>
```

The problem here is that the option is *both* disabled *and* selected, which ends up rendering like this:

> ![2016-no-data](https://user-images.githubusercontent.com/124687/30717119-e69ba020-9ee9-11e7-8ce9-77e1d9d305fa.png)

We should probably edit the template to ensure that this can't happen, e.g. that an option can be disabled *or* selected, but not both.

**Comment by el-mapache** [comment]
I've taken a look at this, and I don't think we need to do anything further. It appears to have been fixed with Marco's PR last year!
