### ISSUE TITLE
Add a "suggest changes to this page" link to the footer

### ISSUE THREAD

**Issue by toolness** [18F/doi-extractives-data#2379]
Clicking on the link would take users to the GitHub edit view for the Markdown file for the current page's content.

We can either add such a link to every page as a normal feature that all visitors see, or we could only have it appear under certain circumstances. For example, in https://github.com/18F/pclob/pull/91 we made it so the link only shows up if `#devmode` is added to the end of the URL in the address bar.

This kind of thing can be really helpful for quick typo-fixing, and it can also be immensely helpful for developers who are unfamiliar with the structure of the site (or who have just come back from a long vacation) and aren't sure where the Markdown file corresponding to the page they're looking at is.

**Comment by coreycaitlin** [comment]
Closing — we don't think this is a user need right now.
