### ISSUE TITLE
Pull together resources on user research in government

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2383]
As a member of the ONRR innovation design team, I want to understand the guidelines around doing user research in government, including the nuances of the Paperwork Reduction Act and how to navigate it.

**Comment by coreycaitlin** [comment]
First step: pull together articles and memos to share with @winzenburg.

**Comment by jamiealbrecht** [comment]
@alexpandel and I have been collecting resources in this [document ](https://docs.google.com/document/d/19mOZWMvUndvVDkjgniVAiEzR2AOc0aW0g6LwT-ivRHw/edit)

Feel free to add, team!

**Comment by coreycaitlin** [comment]
Next step: training in remote research facilitation best-practices, further framing/refinement.

**Comment by alexpandel** [comment]
FYI @winzenburg, I started putting together [this big doc](https://docs.google.com/document/d/1pSGABUlHpedPnNo5vhepS0cjKX-4IL2S5Te0IHfJANA/edit) on PRA and how it applies to user research in gov. It's still superdrafty, but wanted to share at this point to help unblock you from the next research sprint!

**Comment by alexpandel** [comment]
Final step for Alex to take: include link from Jeremy

**Comment by alexpandel** [comment]
Alright, just added the link to TTS's draft "PRA Handbook" [here](https://docs.google.com/document/d/1pSGABUlHpedPnNo5vhepS0cjKX-4IL2S5Te0IHfJANA/edit#heading=h.10h2m6zeu54t) - that should be the last thing. @winzenburg if you could double-check that this is the right doc you had wanted and then close this issue, that would be great!
