### ISSUE TITLE
Test site names

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2384]
We should test potential site names #2352 (even simple hallway testing) to identify potential confusion or overlaps.

**Comment by coreycaitlin** [comment]
Next step: write a minimalist research plan for testing 2-3 options.

**Comment by ericronne** [comment]
Here are the home-page "zones" we can play with for our test …

![home page branding zones](https://user-images.githubusercontent.com/9259185/30866515-190d4c94-a29f-11e7-8220-6855dd5e4a55.png)

**Comment by coreycaitlin** [comment]
@jamiealbrecht started a [research plan draft here [limited access]](https://docs.google.com/document/d/1MJjXQByldyvX0hkJtyuZ-OtoIEuxilKeqwU1zR6Rirg/edit)

**Comment by ericronne** [comment]
Given security concerns, we will be sticking with a subdomain setup, at least for the time being....
![artboard copy 3](https://user-images.githubusercontent.com/9259185/30929686-cfa49d28-a384-11e7-86cf-0b4e4a20447f.png)

**Comment by ericronne** [comment]
To Be Tested! …

## A
![artboard](https://user-images.githubusercontent.com/9259185/30940693-817569a2-a3a7-11e7-8dab-7a2ffbb284e5.png)

## B
![artboard copy](https://user-images.githubusercontent.com/9259185/30940701-8d0edf96-a3a7-11e7-8678-62cb450c7ffe.png)

## C
![artboard](https://user-images.githubusercontent.com/9259185/30940705-94e867e6-a3a7-11e7-9f1f-8cb16d6c64a7.png)

**Comment by coreycaitlin** [comment]
@ericronne I think A and C are the same — pasting error?

**Comment by ericronne** [comment]
You passed the test! 😂 
(hold, pls...)

**Comment by ericronne** [comment]
fixed

**Comment by jamiealbrecht** [comment]
We have a [research plan](https://github.com/18F/doi-extractives-data/blob/research/research/13_sprint-preposterous-puffin/research-plan.md)! :)

**Comment by winzenburg** [comment]
Here's PDF of the screens for sharing/testing

[Data website screens.pdf](https://github.com/18F/doi-extractives-data/files/1349482/Data.website.screens.pdf)

**Comment by ericronne** [comment]
[Some notes from my tests.](https://docs.google.com/a/gsa.gov/document/d/1TLinfOJwjX9pJtfzXKjg3SyrA3OR72ArVl7DiZDYpRY/edit?usp=sharing)

**Comment by alexpandel** [comment]
FYI, working on a lightweight summary of findings this morning. Will post a draft shortly for y'all's feedback/edits!

**Comment by alexpandel** [comment]
We have a [research results summary](https://github.com/18F/doi-extractives-data/blob/research/research/13_sprint-preposterous-puffin/sprint-preposterouspuffin_results.md)! Please feel free to make any changes as you see fit before our standup tomorrow morning, when we'll share it with the wider ONRR crew.
