### ISSUE TITLE
Sticky heads still have one-pixel of horizontal space above them

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2385]
![x](https://user-images.githubusercontent.com/9259185/30832344-6443c74a-a210-11e7-97af-4d85d28e8af5.gif)

**Comment by ericronne** [comment]
Some content also bleeds _**ever so slightly**_ over the left edge, too …
![image](https://user-images.githubusercontent.com/9259185/30832572-25411c54-a211-11e7-8968-80c2b38ce7ed.png)

**Comment by jennmalcolm** [comment]
Not seeing the issue; may still exist, but hard to replicate. This is a low priority, so closing for now.
