### ISSUE TITLE
Content: Tribal addition

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2387]
We have the final tribal content! [[Limited access](https://drive.google.com/drive/u/1/folders/0B-bSXujqt5mZaGhiNzlOMEV0TG8)] Now, we need to add it to the site.

**Comment by coreycaitlin** [comment]
After reviewing this content, it looks like it will make the most sense to expand the existing "Tribal Laws and Regulations" page into a broader "Understanding natural resources on tribal land" page that can include all the new content.

**Comment by coreycaitlin** [comment]
This is now [ready for preview here](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/#tribal-overview) 🎉 

There are still some footnotes, TKs, and links to tidy.

**Comment by coreycaitlin** [comment]
Closing out with #2356
