### ISSUE TITLE
Plan in-person product vision workshop

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2392]
We should get together, talk about the vision for the site, and plan for the upcoming months of work.

- [x] Identify a time when most of the team can travel to the same location

**Comment by alexpandel** [comment]
Rough planning happening [in here](https://docs.google.com/document/d/1UyOoeb_TFZfb__NWKOIdzd-sfcAEDOQEpuy6mZriAhI/edit)!

**Comment by coreycaitlin** [comment]
Workshop successfully done!
