### ISSUE TITLE
Research: What do our target users need?

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2393]
It's time for another round of research into user needs for the target users of the site.

- [x] write up target user groups based on past personas and group exercises
- [x] recruiting strategy for target user groups
- [x] identify research questions

**Comment by coreycaitlin** [comment]
This is also related to #2383, on best practices for doing user research in government.

**Comment by alexpandel** [comment]
FYI @winzenburg, I'm getting started on a [research plan](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_plan.md) for this, filling out each section piece by piece. Let me know if you want to pair on this sometime today or tomorrow!

**Comment by alexpandel** [comment]
Hey @winzenburg - **any chance you'd be up for putting our heads together on the research plan for this sometime tomorrow?** I feel like it would be ideal if we could start doing some recruiting next week, so getting clear on goals and target groups we're trying to reach could give us a head start... (based on some of the brainstorming y'all already did here, of course!: https://app.mural.ly/t/gsa6/m/gsa6/1503083839726/5b889490ce4c25648af575d0b759113983126796)

**Comment by alexpandel** [comment]
After some coworking today with @winzenburg, we have a first pass at a [research plan here](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_plan.md)! Would love y'all's :eyes: on it to see if I'm missing anything or otherwise off the mark @coreycaitlin @ericronne @winzenburg et al (especially around the "goals & questions" and "methods & desired participants" sections)

**Comment by alexpandel** [comment]
FYI, @winzenburg & I got more granular with our recruitment strategy for this week, which we're keeping track of [in here](https://docs.google.com/document/d/1zYoOsIhQwOwlY78XG4mukz4Gz_U5gUbcoQ7oQETeDw8/edit) for now.

**Comment by alexpandel** [comment]
@winzenburg do you have a spreadsheet yet for [the folks we might want to contact](https://docs.google.com/document/d/1zYoOsIhQwOwlY78XG4mukz4Gz_U5gUbcoQ7oQETeDw8/edit?disco=AAAABRN9LUQ) so we could start triaging and emailing this afternoon? I'm working on that cold-email language now!

**Comment by alexpandel** [comment]
We have our first interview tomorrow afternoon (🎉), so we have [a draft discussion guide here](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/discussion_guide.md)!

**I could really use y'all's 👀/feedback on this before tomorrow mid-day**, especially @coreycaitlin & @winzenburg to make sure the general questions/flow makes sense and isn't too complicated or ambitious (which it very possibly is right now), and @ericronne to make sure we're targeting the right questions for the "general usability test" section (keeping in mind that we'll only have about 15 mins to spend on that section). Thanks, all!

**Comment by coreycaitlin** [comment]
Next step: lightweight write-up of research synthesis

**Comment by alexpandel** [comment]
Took a first pass of the [research summary here](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_results.md) - would love a second set of 👀s on it if you're game @coreycaitlin or @brentryanjohnson!

**Comment by brentryanjohnson** [comment]
- Is it worth noting the site name and URL changed partway through the research?
- If I recall correctly, the [participant who mentioned scrolling](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_results.md#participants-found-the-structure-of-some-of-the-information-to-be-cumbersome-and-unmanageable) specifically referenced the [Renewables dive-in page](https://revenuedata.doi.gov/how-it-works/onshore-renewables/)
-  One participant frequently works with raw data and recommended we take a look at [USDA Quick Stats](https://quickstats.nass.usda.gov/)

**Comment by alexpandel** [comment]
ah, good call on all of this @brentryanjohnson - just committed a change to address all three, and left some breadcrumbs about what I changed in [comments in the commit details].(https://github.com/18F/doi-extractives-data/commit/514fc9354be282944d851c293d3650efb3795232#diff-ad10025b1e157807dc9741764d4e860d). Realize I shoulda made this a pull request with you and @coreycaitlin as reviewers, apologies! Feel free to give any more feedback/make any more changes as you see fit 👍

**Comment by alexpandel** [comment]
@winzenburg, you game to take a look at this [research summary here](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_results.md) (and make any edits/changes as you see fit, of course) so we can close this one out?

**Comment by alexpandel** [comment]
I think this comment from @winzenburg on https://github.com/18F/doi-extractives-data/issues/2438 was meant for this issue, so adding it here for posterity and closing this one! 

From Ryan W: "Yes! I think where we are in the broader research effort, this is well done as a synthesis of our early effort."
