### ISSUE TITLE
Update federal disbursements data

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2397]
Update federal disbursements with 2017 data. [Data file is here (limited access)](https://drive.google.com/drive/folders/0B4b900J0no9nWUJDRkF6elVDX2s).

This data should be formally released Nov. 30 along with a press release.

**Comment by coreycaitlin** [comment]
Blocked until we get the data file, and until the press release goes out. We expect the data file in a couple of weeks.

**Comment by coreycaitlin** [comment]
Updated the issue description to link to the data file (limited access until it's released), and note timing.

**Comment by coreycaitlin** [comment]
This is likely to take a couple of sprints, but the next step is to update with a link to the source file in GDrive.

**Comment by jennmalcolm** [comment]
Just a reminder this data should be updated by Nov 30.

**Comment by coreycaitlin** [comment]
This is done with #2477 and being reviewed
