### ISSUE TITLE
Pick a url!

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2399]
After testing, we've named the site, "Natural Resources Revenue Data" (see #2352). But the url question remains open. Let's discuss the options here, and then test a few to see which is clear, and easy to remember. Here are some general considerations (from the [ONRR data site words mural](https://app.mural.ly/t/gsa6/m/gsa6/1505399272414/0f4fbff389d3692a8160142453db0cba992a1d08))

![image](https://user-images.githubusercontent.com/9259185/31837698-65aad37e-b59f-11e7-9f87-2addaf2ac298.png)
![image](https://user-images.githubusercontent.com/9259185/31837711-735ef626-b59f-11e7-9a9f-d661292192bb.png)

![image](https://user-images.githubusercontent.com/9259185/31837754-8fe76dfa-b59f-11e7-81ef-614f43a1201e.png)

**Comment by ericronne** [comment]
# _________ .doi.gov

###  naturalresourcesrevenuedata.doi.gov
### natural-resources-revenue-data.doi.gov
### naturalresourcesrevenue.doi.gov
### natural-resources-revenue.doi.gov
### resourcesdata.doi.gov
### resourcedata.doi.gov

_please edit this comment to add more ideas!_

**Comment by coreycaitlin** [comment]
We discussed the following options:

- naturalresourcesdata.doi.gov
- resourcesrevenue.doi.gov
- naturalresourcesrevenue.doi.gov
- resourcesrevenuedata.doi.gov
- revenuedata.doi.gov
- resourcedata.doi.gov

...and decided that length — and the word _data_ are paramount, bringing us to two final options:

- revenuedata.doi.gov
- resourcedata.doi.gov

**Comment by coreycaitlin** [comment]
Decision: new URL will be revenuedata.doi.gov 🎉
