### ISSUE TITLE
New favicon

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2411]
We'll need a new favicon in place of the tiny `E`. One option would be the DOI logo, though it gets pretty squished at that size.

**Comment by ericronne** [comment]
Yes the seal is very squint inducing …
![image](https://user-images.githubusercontent.com/9259185/32182331-62f6aeb0-bd64-11e7-937c-d4e2f7274624.png)

A simple, data-esque icon might be the way to go. It's on my list …
