### ISSUE TITLE
Screener formatting should complement the site design

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2414]
Here's what i'm thinking …

Gray background: my theory is that the stickiness should be sufficient to make it obvious to users, so we needn't rely on a bright color. If we find that people aren't clicking it, let's reconsider.

Full formatting suggestions …
![image](https://user-images.githubusercontent.com/9259185/32184834-86445a5a-bd6b-11e7-87d4-957b9fefad0a.png)

**Note**
Given the always-visible nature of this utility, we may want to consider adding a close function to the tab.

**Comment by ericronne** [comment]
@laurenancona i'd love to  🍐  on this, if you like!

**Comment by laurenancona** [comment]
@ericronne A close function on the tab is on the roadmap for Recruiter product, but not landed yet.

**Comment by laurenancona** [comment]
Tab styles updated, viewable here: https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-NCRF98R&gtm_auth=2n0LfCVrQs_AC4_0HYEFwA&gtm_preview=env-9&gtm_debug=&url=https://useiti.doi.gov/

**Comment by ericronne** [comment]
Bada- 💥  ! Thanks!
