### ISSUE TITLE
The footer should reflect the new site direction

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2415]
## Current footer
![image](https://user-images.githubusercontent.com/9259185/32183205-ac60fdce-bd66-11e7-9afc-f48725bd7292.png)

## Considerations

- EITI logo will now be moot, so it should go away
- In its place, DOI branding may help give users useful context. I'll play with a design which incorporates the seal, eg.
- Explicit EITI mentions here will need to be rewritten/nixed:
   - [ ] **Questions?** Contact the USEITI Secretariat at USEITI@ios.doi.gov.
   - [ ] **Built in the open** This site (v2.2.1) is powered by USEITI data and open source code. We welcome contributions and comments on GitHub.
   - [ ] Mail: USEITI Secretariat, 1849 C Street NW MS 4211, Washington, D.C. 20240
Department of the Interior Home | Privacy Policy | FOIA | USA.gov
   - [Twitter link](https://twitter.com/useiti_doi)
   - [Facebook link](https://www.facebook.com/USEITI)

**Comment by ericronne** [comment]
Related (to consider): #2379

**Comment by ericronne** [comment]
@coreycaitlin i'm holding off on design until we suss the content, lmk if you want to 🍐

**Comment by coreycaitlin** [comment]
@ericronne Let's start minimal, and work toward a more complex footer in future iterations. Any recommendations about where/how to fit the DOI logo in this spot?

<img width="1116" alt="screen shot 2017-10-31 at 3 13 28 pm" src="https://user-images.githubusercontent.com/1450354/32251376-fe9072f4-be4d-11e7-92fe-6a49ce5a291f.png">

**Comment by ericronne** [comment]
Assuming that's ☝️  the content, i'll make a new branch and noodle...

**Comment by coreycaitlin** [comment]
Yep, let's start there (though I think we'd like to remove the Twitter and Facebook links, as well). Can you make a branch off of the `name-change` branch?

**Comment by ericronne** [comment]
yep that's what i did.
twitter and fb should go away, though?
impacts layout, so we should make that call now-ish

**Comment by coreycaitlin** [comment]
@ericronne Yes, at least for now.

**Comment by ericronne** [comment]
@coreycaitlin g2g? …
![image](https://user-images.githubusercontent.com/9259185/32286069-4d02e2c6-befa-11e7-8c43-127a16f4c268.png)

cc @msecret

**Comment by coreycaitlin** [comment]
This looks great! Let's do it.

**Comment by ericronne** [comment]
Woo! @msecret do you want to start on this and hopefully i'll have chance to do a favicon? Then perhaps we can work on the header during pear time??

I made a [branch](https://github.com/18F/doi-extractives-data/tree/name-change-footer)

**Comment by ericronne** [comment]
@msecret here's the [DOI seal png](https://drive.google.com/open?id=0BwWYNZcEDfwaLUNDdzJONTRJZ2s) (svg file is twice the k load)

**Comment by msecret** [comment]
K starting on this
