### ISSUE TITLE
Test font on multiple browsers

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2417]
Ensure that our implementation of Lato Light (300), Normal (400), and Semibold (600) work across various browsers and on PCs

**Comment by ericronne** [comment]
@winzenburg or @brentryanjohnson, might i impose upon you to visit the following pages in Chrome and IE on your PCs at some point, and transfer screenshots to me? I have no such hardware, i'm (not at all) sorry to say.

- [home](https://revenuedata.doi.gov/)
- [how it works](https://revenuedata.doi.gov/how-it-works/)

Email is probably the most efficient route to get them to me. (Github and slack sometimes seem to mess with images.)

Thank You!

**Comment by brentryanjohnson** [comment]
I've emailed these to you, @ericronne. You'll see some issues, particularly with IE (no surprises there).

**Windows 7, Chrome**
![home_windows7_chrome](https://user-images.githubusercontent.com/32855580/34693615-3698219a-f479-11e7-864f-614f128b8acd.PNG)
![home2_windows7_chrome](https://user-images.githubusercontent.com/32855580/34693616-36a92a94-f479-11e7-88e4-1f73a403fc45.PNG)
![howitworks_windows7_chrome](https://user-images.githubusercontent.com/32855580/34693617-36c31a3a-f479-11e7-9d4a-54c1ab2372d9.PNG)
![howitworks2_windows7_chrome](https://user-images.githubusercontent.com/32855580/34693618-36d78a56-f479-11e7-9905-f1c074e14eae.PNG)

**Windows 7, IE11**
![home_windows7_ie](https://user-images.githubusercontent.com/32855580/34693628-450a7e4e-f479-11e7-8402-0accf14856e1.PNG)
![home2_windows7_ie](https://user-images.githubusercontent.com/32855580/34693629-45245bde-f479-11e7-9d92-b524397a751b.PNG)
![howitworks_windows7_ie](https://user-images.githubusercontent.com/32855580/34693630-4539c82a-f479-11e7-8b6c-f9ac7ce1a22d.PNG)
![howitworks2_windows7_ie](https://user-images.githubusercontent.com/32855580/34693631-454a9eca-f479-11e7-8c45-4222bc3af0b3.PNG)

**Comment by ericronne** [comment]
That logo is supposed to be svg 😠

**Comment by ericronne** [comment]
Thanks for the research, @brentryanjohnson!
Lots to unpack here, and sadly, it'll have to be executed by someone other than i. :(

Let's hang out this week to create a detailed issue, tho. Look for an invite...

**Comment by coreycaitlin** [comment]
After testing, the font doesn't seem to be the main issue — other cross-browser issues are captured in #2596.
