### ISSUE TITLE
Header style tightening

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2419]
A few style tweaks (in addition to those i made, see pr #2418), some of which require css chops which are beyond me atm :)

![image](https://user-images.githubusercontent.com/9259185/32234932-099fca9a-be2c-11e7-98df-af3ea6704ef1.png)

*Let's pair for smaller-viewport adjustments

**Comment by coreycaitlin** [comment]
Okay to close @ericronne?

**Comment by ericronne** [comment]
Good enough for now :)
