### ISSUE TITLE
Revise the what's new page 

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/doi-extractives-data#2424]
Tell us what's new!

**Comment by coreycaitlin** [comment]
Since we link to the current version and release notes in the footer, and this page consistently falls out of date, it seems like time to deprecate this page. Next step: remove it from the site.

**Comment by coreycaitlin** [comment]
@brentryanjohnson I think we talked about this one while you were out — any objections to removing this page? Users can still view release notes for the latest changes — and they're much more likely to be maintained consistently.

**Comment by brentryanjohnson** [comment]
@coreycaitlin I think we should remove it.
