### ISSUE TITLE
Name change follow-up bugs

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2427]
Remaining issues to fix:

- [x] version link in footer is broken
- [x] DOI logo in footer should link to DOI
- [x] audits and assurances link on About page should be a relative link
- [x] IA glossary link on About page is broken
- [x] robots.txt should be updated with new url
- [x] favicon could use a little more love
- [x] wordmark is a little large in mobile view (hits hamburger icon on small phones)

**Comment by ericronne** [comment]
favicon given a little extra ❤️  ☑️ 

![image](https://user-images.githubusercontent.com/9259185/32753672-6465bd6a-c893-11e7-8be7-c2d14665857e.png)

https://github.com/18F/doi-extractives-data/commit/2e6e8e83d1a983257d1f80f323880efd7fef28bb

**Comment by coreycaitlin** [comment]
Nice! Much more legible.
