### ISSUE TITLE
Scroll bar triggered on sticky h4s

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2432]
At least some sticky h4s are getting a scroll bar. It appears to be associated with "overflow: auto" property, but the other headings with the same attribute are not exhibiting the same behavior. Observed on Chrome 62.0.3202.62 on Windows 7.

![h4-scroll](https://user-images.githubusercontent.com/32855580/32383297-dd408e1c-c074-11e7-82e4-4e310cae1e8d.PNG)

**Comment by ericronne** [comment]
Tag @msecret ;)

**Comment by brentryanjohnson** [comment]
This is no longer appearing for me, either. It may have been resolved via a browser update. Closing!
