### ISSUE TITLE
Redirect from useiti.doi.gov to revenuedata.doi.gov

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2433]
We started setting up this redirect, but it's currently behaving not quite as hoped. Here's what we'll need to get this right:

- [x] Copy + design for super-minimal page to sit at useiti.doi.gov and alert users to redirect, in case the browser takes a moment
- [ ] Remove most content/assets from redirect repo

**Comment by ericronne** [comment]
Copy, courtesy @brentryanjohnson …

**Natural resources revenue data is now at revenuedata.doi.gov. We’re redirecting you there.**

**Didn’t work? [Go to the revenue data now](https://revenuedata.doi.gov/)**

**Comment by ericronne** [comment]
Lightweight design for above …

![image](https://user-images.githubusercontent.com/9259185/32390513-b314358a-c09c-11e7-8f31-134c1dfe6d5c.png)

**Comment by ericronne** [comment]
I made a quick dummy layout for reference
https://github.com/18F/useiti-redirect/commit/f79d928ee307e6c13631fc0db106419a70720742

@msecret

**Comment by ericronne** [comment]
@msecret is this all wrapped up?

**Comment by coreycaitlin** [comment]
I believe this is all squared away!
