### ISSUE TITLE
Add 2016 coal production data

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2436]
We're missing the [2016 data value for coal production](https://revenuedata.doi.gov/explore/#all-production). This data is available via the Energy Information Administration's ["Total Energy Data Browser"](https://www.eia.gov/totalenergy/data/browser/?tbl=T06.01#/?f=A). 

The 2016 value is: 728231912

**Comment by msecret** [comment]
Hmm, I wonder if this is why some of the tests are breaking for 2016 data

**Comment by coreycaitlin** [comment]
We should make sure to pull in the full updated data when we update this – I vaguely remember that sometimes other values get updated, as well!

**Comment by msecret** [comment]
So I understand: this data is missing for the total and all states?

**Comment by msecret** [comment]
I don't think I see anything about state data in that EIA link

**Comment by coreycaitlin** [comment]
Yep! The coal production data gets released later than all the other commodities, so our site doesn't have coal data for 2016. I think we should likely just pull a full 2016 update to this data from EIA. Notes and instructions should be here:

- [Downloads](https://revenuedata.doi.gov/downloads/#all-lands-and-waters)
- [Data notes](https://github.com/18F/doi-extractives-data/wiki/Data-Catalog#all-production)
- [README](https://github.com/18F/doi-extractives-data/tree/dev/data/all-production#readme)
- [Config file](https://github.com/18F/doi-extractives-data/blob/dev/data/all-production/config.yml)

Does that help? If not, let's chat and see if I can clarify.
