### ISSUE TITLE
Synthesize workshop findings and next steps

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2438]
After last week's workshops, we should figure out how to reflect the decisions, conversations, and learnings in our work going forward.

**Comment by alexpandel** [comment]
Links to all of our in-progress docs are here:
-  [synthesis plan](https://docs.google.com/document/d/1Aq8YmXAbPBwsANYxdGgYXPKUbX6gHcUXrK_XPHsMV88/edit)
- [in-progress synthesis docs](https://drive.google.com/drive/u/0/folders/1K3rbBqdet8jaSeuEeokkmP2R1EFPzlib)
- [working list of our next steps](https://docs.google.com/document/d/1Aq8YmXAbPBwsANYxdGgYXPKUbX6gHcUXrK_XPHsMV88/edit#heading=h.vyq6l14pgqlq)

To make our next steps more visible and track them more effectively, **let's try adding our "next steps" as issues in Waffle,** with the `non-code task` label so we can filter them when needed, and we can revisit in a sprint or two whether tracking all our work in one place works for us, or if we need to adjust. Sound good @winzenburg?

**Comment by winzenburg** [comment]
Yes! I think where we are in the broader research effort, this is well done as a synthesis of our early effort.

**Comment by alexpandel** [comment]
now that all of the next steps have been added into Waffle, I'm going to close this meta-issue in favor of the more granular tasks.
