### ISSUE TITLE
Style guide: Document and/or adjust grids and spacing

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2446]
Where needed.

Using #2444 for handy reference.

Baby steppin' toward that holy grail! (#2360)

**Comment by ericronne** [comment]
Consider addressing down the road, if a larger-scale css refactoring initiative is undertaken.

A systemic approach along the lines of the [cloud.gov grid](https://styleguide.fr.cloud.gov/components/detail/grid--column-fill-and-fit.html) might help make layout construction easier and more modular, e.g.

**Comment by coreycaitlin** [comment]
Keeping this open — worth documenting the column spacing.
