### ISSUE TITLE
Typo in lease section

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2454]
[Onshore dive-in graphic](https://revenuedata.doi.gov/how-it-works/onshore-oil-gas/) under "Lease" has "RPMs"; should be "RMPs" (for Resource Management Plans).

**Comment by coreycaitlin** [comment]
This is a great opportunity to pair on the content-updating process!

**Comment by coreycaitlin** [comment]
@jennmalcolm Now that this is merged into `dev`, you can go ahead and close this issue!
