### ISSUE TITLE
Update about.yml

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2460]
We need to update [`.about.yml`](https://github.com/18F/doi-extractives-data/blob/dev/.about.yml) with new site name , description, URL, contact, etc.

**Comment by coreycaitlin** [comment]
Next step: check with @wslack about whether the `about.yml` file is critical for our ATO status.

**Comment by coreycaitlin** [comment]
Update: it is not. [More about the Federalist ATO here](https://before-you-ship.18f.gov/infrastructure/federalist/)

Given this, I think we could likely deprecate this file! I _think_ it used to be used for some 18F internal project-tracking and aggregation tools, but I think those are no longer maintained.

**Comment by wslack** [comment]
I can confirm that it used to be used to aggregate data about our projects but isn't in use now.
