### ISSUE TITLE
Training: user research

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2464]
Laying a foundation for User Research with in the ONRR team

As an ONRR team member I want to know:
1. Why do you do user research
2. How do you write a research plan?
3. How do you find research participants
4. Why/how do you create a screener?
5. How do you create an interview script?
6. How do you conduct an interview?
7. How do you analyze the finding?

, so I can conduct user research to create human centered products.

**Comment by alexpandel** [comment]
Howdy @winzenburg! Not sure if you saw [this doc](https://docs.google.com/document/d/19mOZWMvUndvVDkjgniVAiEzR2AOc0aW0g6LwT-ivRHw/edit) that @jamiealbrecht & I started putting together a couple weeks ago for https://github.com/18F/doi-extractives-data/issues/2383, but it may have some good starting materials for many of the topics you mentioned!

**Comment by alexpandel** [comment]
@winzenburg if it's ok with you, I'm gonna rename this task "Training: user research" to put it more in line with the task definition you spelled out. I'm also gonna add a separate task to "plan next research sprint," since it'll be important to ground all this training in a real sprint!

**Comment by coreycaitlin** [comment]
This issue will be done when user research training is planned/scheduled.

**Comment by coreycaitlin** [comment]
I've opened up #2509 to cover this sprint's activities, and #2510 for the next step toward another training/learning session. @winzenburg do those cover the big next steps? Okay to close this issue out in favor of those two?

**Comment by alexpandel** [comment]
Closing this for now. We'll be heading into some more research training in February, so we'll create new, more clearly scoped issues for those sessions as we get closer. We'll also work on wrapping up our documentation around the research process next sprint (#2537).
