### ISSUE TITLE
Workshop synth: workshop summary

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2465]
Create/Send workshop summary to attendees

**Comment by alexpandel** [comment]
how is this one coming, @winzenburg? This should probably go out in the next day or two... do you have everything you need in the various [synthesis docs](https://drive.google.com/drive/u/0/folders/1K3rbBqdet8jaSeuEeokkmP2R1EFPzlib) to pull this together? If not, it might make sense to make some comments in the individual issues where you still need help to indicate what you need done so folks know how to help!

**Comment by alexpandel** [comment]
**@winzenburg @brentryanjohnson @coreycaitlin - would love y'all's eyes on [my draft of this](https://docs.google.com/document/d/1a0Q8MnhZCP8ROWdDo1myWatAGroZJQZcbcgS_ojOlo0/edit#heading=h.w1oanxrg2w7v) in the morning, as I'm hoping to send it out by EOD Monday.** 

Context:  I ended up framing this as the first of a weekly "transition update" email that 18F will send out to the wider team (vs a one-off email about the workshop). Please let me know if you think I missed or misrepresented anything, and I also left a couple comments in the doc with some targeted questions for y'all. Gracias!

**Comment by coreycaitlin** [comment]
Looks good! :shipit:
