### ISSUE TITLE
Take first pass at defining product vision

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2467]
As the ONRR Information and Data Management group, I want to understand the product vision of the revenuedata.doi.gov site as a document to 

- Help drive product decisions
- Provide a destination for the team to stay on-course
- Get the entire team on the same page
- Inspire and motive

**Comment by alexpandel** [comment]
I think we aligned on the next step here being us having a follow-up product vision session this week, starting with me leading the group through how 18F thinks about product framing and vision, and shooting to get us to at least a v1 of our product vision for the NRRD site. Working on the game plan for that today!

**Comment by alexpandel** [comment]
Next step: we'll be working on fleshing out [this doc](https://docs.google.com/document/d/1Pc2qdQHN6m268r9rJhP9OfZIq0dbkdWnGqHZEQYn4E0/edit#) during our session today!

**Comment by coreycaitlin** [comment]
Next steps:

- @brentryanjohnson to edit problem statement for length/clarity
- Revisit scenarios after research synthesis #2524 
- Break out value delivered for each scenario
- Prioritize scenarios
- Draft vision statement
- Spell out reasoning for things that are out of scope
- Identify and catalogue risks, mitigation paths
- Bring in other stakeholders

**Comment by alexpandel** [comment]
Marking this as done, as I've broken out the next steps into individual issues (#2547 #2548 #2550 #2551 #2549 and #2552).
