### ISSUE TITLE
Workshop synth: product vision workshop context

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2468]
At an ONRR team member, I want to know what happened at the product vision workshop, so I have context into how the product vision was created.

**Comment by alexpandel** [comment]
I linked to [this](https://docs.google.com/document/d/1IlzyLwOqHV3eBGEUuMhjG9vK64YlyWzrUWObL-poDNo/edit) in [the workshop summary email](https://docs.google.com/document/d/1a0Q8MnhZCP8ROWdDo1myWatAGroZJQZcbcgS_ojOlo0/edit#heading=h.w1oanxrg2w7v), so I'd consider this done enough for now! closing.
