### ISSUE TITLE
Workshop synth: measurement

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2471]
As an information and data management team member, I want to instrument the NRDD and stats page, so I get a baseline understanding of user behavior

**Comment by alexpandel** [comment]
I linked to [this](https://docs.google.com/document/d/1BvmFLYFbLm1lUumfS7ej9EEQ_X_Iv2v0gSXEEOvwnxY/edit) in [the workshop summary email](https://docs.google.com/document/d/1a0Q8MnhZCP8ROWdDo1myWatAGroZJQZcbcgS_ojOlo0/edit#heading=h.w1oanxrg2w7v), so I'd consider this done enough for now! closing.
