### ISSUE TITLE
Workshop synth: assumptions

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2473]
Synthesizing the assumptions exercise from the product vision workshop

**Comment by coreycaitlin** [comment]
I've recorded and summarized this session [here (limited access)](https://docs.google.com/document/d/1ZNPw5OLO2xh5a2SWi4I409tUqJAChoG--bnVbFtsnB8/edit#) — please feel free to add or edit as you see fit, @winzenburg or @alexpandel!

**Comment by alexpandel** [comment]
this is great, thank you @coreycaitlin! closing ✔️
