### ISSUE TITLE
Workshop synth: role/training synthesis

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2474]
Summary of the the role transition and training

**Comment by alexpandel** [comment]
I linked to [this](https://docs.google.com/document/d/16P8rLs1IeL5ab2gqKzt1YXB-eyJ0R7xIVq1jt793QNc/edit) in [the workshop summary email](https://docs.google.com/document/d/1a0Q8MnhZCP8ROWdDo1myWatAGroZJQZcbcgS_ojOlo0/edit#heading=h.w1oanxrg2w7v), so I'd consider this done enough for now! closing.
