### ISSUE TITLE
Plan next research sprint

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2476]
Get a research plan drafted up so we can get started on the next research sprint.
Some initial brainstorming in [this doc](https://docs.google.com/document/d/1QSSZF7QJfgVDtzo8oCHEtSnaPCNEROqD2TyuzLl2wUM/edit#heading=h.ylx6viky1t2v) related to this was as follows:

- **Possible research question:** How & why are people using the stats page today?
- **Underlying goal:** start to get a sense of what the end goal of an integrated stats & NRRD site might look like, to use as a north star for smaller, more immediate changes we might make to the NRRD site
- **Potential participants:** the users Nathan identified who use the stats site/make data requests

**Comment by alexpandel** [comment]
Hey @winzenburg,  can you either get the research plan posted in the research branch on Github, or drop a link to the Google Doc in this issue? Happy to help if you need help with either, just DM me on Slack!

**Comment by winzenburg** [comment]
Here is the Research Plan and Interview Script in Github https://github.com/18F/doi-extractives-data/blob/research/research/15_cheeseycheetah/research_plan.md

**Comment by coreycaitlin** [comment]
Closing this out now. Next step is #2509, then synthesis.
