### ISSUE TITLE
Case studies updates

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2480]
Add 2017 case studies updates
**This issue tracks the copy updates. I'll create a separate issue to track chart build updates.**
- [X] [Boone Logan and Mingo counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/boone-logan-and-mingo/)
- [X] [Campbell County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/campbell/)
- [X] [DeSoto Parish](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/desoto/) 
- [X] [Elko and Eureka counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/elko-and-eureka/)
- [X] [Greenlee County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/greenlee/)
- [X] [Humboldt and Lander counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/humboldt-and-lander/)
_"Humboldt" is spelled incorrectly in various places in the case studies (omits "d"), including the markdown file name. I fixed the incorrect spellings in the body text._
- [X] [Kern County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/kern/)
- [x] [Marquette County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/marquette/)
- [x] [North Slope Borough](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/north-slope/)
- [x] [Pima County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/pima/)
- [x] [St. Louis County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/st-louis/)
- [x] [Tarrant and Johnson counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/tarrant-and-johnson/)

**Comment by brentryanjohnson** [comment]
@jamiealbrecht Would you mind proof-reading these wonderful case studies?

**This issue tracks copy updates. #2496 tracks chart updates that accompany this content.**

- [ ] [Boone Logan and Mingo counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/boone-logan-and-mingo/)
- [ ] [Campbell County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/campbell/)
- [ ] [DeSoto Parish](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/desoto/) 
- [ ] [Elko and Eureka counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/elko-and-eureka/)
- [ ] [Greenlee County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/greenlee/)
- [ ] [Humboldt and Lander counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/humboldt-and-lander/)
- [ ] [Kern County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/kern/)
- [ ] [Marquette County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/marquette/)
- [ ] [North Slope Borough](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/north-slope/)
- [ ] [Pima County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/pima/)
- [ ] [St. Louis County](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/st-louis/)
- [ ] [Tarrant and Johnson counties](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/case-studies/case-studies/tarrant-and-johnson/)

**Comment by jamiealbrecht** [comment]
On it! Thank you!

**Comment by jamiealbrecht** [comment]
For Campbell County, footnote # 9, the link is broken. In a quick glance at the interwebs, I couldn't find a replacement BLM link. Does that sentence have to have a footnote?

**Comment by jamiealbrecht** [comment]
For Desoto Parish, footnotes 18,19, 34, and 35 links are broken. Not sure if the problem with 34+35 is just the LA DOT website being down. Anyways, for 18 + 19, I couldn't find replacement links quickly, but I figure we can tackle that a bit later. 

(I can separate issues for broken links later, but just keeping track of them here for now)

**Comment by jamiealbrecht** [comment]
For Greenlee County, footnote links # 6 and # 7 are broken.

**Comment by brentryanjohnson** [comment]
Thank you, @jamiealbrecht !

I had documented some of the broken links, and obviously I should have sent them over earlier! Here are at least some of them for the remaining case studies on your list:

**North Slope**
- Alaska Department of Environmental Conservation, Contaminated Sites Program, Division of Spill Prevention and Response, Annual Report (PDF)

**Tarrant and Johnson**
- State of Texas Legislative Budget Board, Overview of Natural Gas Tax Structures (PDF)
- Texas General Land Office, Permanent School Fund Overview

**Comment by jamiealbrecht** [comment]
All done proofreading! These look great. Awesome work, RJ! Made a few minor edits. Will follow up with a PR.

**Comment by brentryanjohnson** [comment]
I merged this, so I am closing the issue! :man_dancing:
