### ISSUE TITLE
Data: Colorado revenue and disbursements data

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2485]
Like Montana, Wyoming, and Alaska, we need to pull in Colorado state disbursements and revenue data. [Data is here (limited access)](https://drive.google.com/drive/folders/0B-bSXujqt5mZQUJnMTR5LUIxYXM)

**Comment by msecret** [comment]
The data form the source file is structured different and needs to be formatted. Work in progress is here: [google drive](https://docs.google.com/spreadsheets/d/1Oo091UQRRMVaLZxD37SdkDc-WbBsM6127uZzoAlbbOg/edit#gid=0).

**Comment by coreycaitlin** [comment]
We've determined that we need this data to be structured in roughly the same ways MT, WY, and AK were structured. Marking as blocked until the source data is sorted out.

**Comment by coreycaitlin** [comment]
[Newly better-structured data is here (limited access)](https://drive.google.com/drive/folders/0B-bSXujqt5mZQUJnMTR5LUIxYXM)

**Comment by coreycaitlin** [comment]
Let's treat this as an opportunity to test the process of updating data using Docker, from an ONRR machine.

**Comment by brentryanjohnson** [comment]
@msecret Can we pair on this one soon and cross it off the list?

**Comment by brentryanjohnson** [comment]
Should we scope the addition of Colorado to the [homepage opt-in blurb](https://revenuedata.doi.gov/), or do you think that should be a separate issue?

>Learn about extractive industries in each state
Explore production, revenue, and economic impact data for each state, as well as additional contextual information and data about three states that chose to participate in deeper reporting: **Alaska, Montana, and Wyoming.**

**Comment by jennmalcolm** [comment]
I created a separate issue for the home page blurb, so this is linked to #2671.
