### ISSUE TITLE
Data: Update state revenue and disbursements data for AK, MT, WY

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2486]
We have updated data for our three prior opt-in states. [Data here (limited access)](https://drive.google.com/drive/folders/1NMOZPvOR8tpgYHnEsfrkP_RuglvsH2Zb)

**Comment by coreycaitlin** [comment]
Next step: break down next steps and smaller tasks to complete this

**Comment by coreycaitlin** [comment]
Currently blocked by a data discrepancy in WY revenue/disbursements — it looks similar to something we [ran into last year](https://github.com/18F/doi-extractives-data/pull/1813#issuecomment-243847159). @brentryanjohnson is working with Deloitte to resolve.

**Comment by brentryanjohnson** [comment]
Deloitte responded with the following:

>So, given the disparity within the Excel, I am inclined to go with the highlighted number on the ‘Distributions by Revenue Stream’ tab (2,126,209,645). I say this because we can trace it back to the tally of the revenues streams which have corresponding sources. Without the sources for the other figure within the excel, I am hesitant to list that number

Since we updated the WY opt-in data with the figure above, I am unblocking this one.

**Comment by coreycaitlin** [comment]
Moving the full set of checklists here:

## Wyoming

- [ ] State revenue chart [🏇 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-local-revenue) - 2016 data, but needs validation
- [ ] State disbursements  [🏇 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-disbursements) - 2016 data, but needs validation
- [x] Content updates ([source; limited access](https://drive.google.com/drive/folders/13ZJPUWeZbUs7kFQzNEGVvUSyalwPiPLi))
- [ ] Static charts — update or remove

## Montana

- [ ] State revenue chart [🐻 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/MT/#state-local-revenue) - still showing 2014 data
- [ ] State disbursements  [🐻 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/MT/#state-disbursements) - still showing 2014 data
- [ ] Content updates ([source; limited access](https://drive.google.com/drive/folders/1pWiMDMIbSLsxv-tyRIVSiGRF8ETu9SRB)) - #2584 
- [ ] Static charts — update or remove

## Alaska

- [ ] State revenue chart [🐟 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/AK/#state-local-revenue) - showing 2015 data
- [ ] State disbursements  [🐟 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/AK/#state-disbursements) - showing 2015 data
- [ ] Content updates ([source; limited access](https://drive.google.com/drive/folders/1siHtT_1_rz4W4supWyYkPZuCzQooAGCu)) - #2585
- [ ] Static charts — update or remove

**Comment by brentryanjohnson** [comment]
Some of the opt-in state charts could use an update. @ericronne Here are the values to add:

## Montana
[Revenue sustainability](https://revenuedata.doi.gov/img/MT_revenue_sustainability.svg)

### 2015
- Total: $2,570,708,000
- Natural resources revenue: $234,144,422

### 2016
- Total: $2,572,730,000
- Natural resources revenue: $164,109,688

![image](https://user-images.githubusercontent.com/32855580/35464136-3bac7d82-02a9-11e8-954f-d44adff8459d.png)

## Alaska
[Revenue sustainability](https://revenuedata.doi.gov/img/AK_revenue_sustainability.svg)

### 2016
- Total: $5,800,000,000
- Petroleum: $1,600,000,000

### 2017
- Total: $9,900,000,000
- Petroleum: $1,600,000,000

### 2018
- Total: $9,700,000,000
- Petroleum: $1,500,000,000

![image](https://user-images.githubusercontent.com/32855580/35464281-f0794f4c-02a9-11e8-85c7-c7a7d816cad4.png)

**Comment by coreycaitlin** [comment]
Next steps:

- @msecret to dig into MT and AK data and why it didn't update to 2016
- ask @ericronne to update revenue sustainability charts (AK may take some coworking time to determine best ways to approach the differences between this year's and last year's)

**Comment by brentryanjohnson** [comment]
Wrapped this one up with the completion of the static charts; merged.
