### ISSUE TITLE
Case study charts: update

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2496]
It's time to update our case study charts again. 

- [x] **Boone, Logan, and Mingo Counties**
[Chart 1: Coal production](https://revenuedata.doi.gov/img/counties/wv-production.svg)
![boone1](https://user-images.githubusercontent.com/32855580/33439805-2c45ce30-d5a3-11e7-8437-4d3def2e2264.PNG)

2015 values:

- Total: 21,955
- Boone: 8481
- Logan: 9562
- Mingo: 3912

### Draft for proofing
![01-line chart - boone coal prod](https://user-images.githubusercontent.com/9259185/34310359-ce762a6c-e71c-11e7-8c7a-ef7f67faba70.png)

---

- [ ] **Boone, Logan, Mingo wage and salary chart** 
[Chart 2: Wage and salary employment...](https://revenuedata.doi.gov/img/counties/wv-wage.svg)
![boone2](https://user-images.githubusercontent.com/32855580/33439820-33e4cc7c-d5a3-11e7-9bd1-02762bfa8c56.PNG)

2015 values:

- All other industries: 16,816
- Mining industry: 3743

### Problem with this (and most employment charts)
![02-bar chart - boone wage](https://user-images.githubusercontent.com/9259185/34310367-e05f4a88-e71c-11e7-96dc-d5cab71337c9.png)

---

- [x] **Campbell County**
[Chart 1: Coal production](https://revenuedata.doi.gov/img/counties/wy-production.svg)
![campbell1](https://user-images.githubusercontent.com/32855580/33440034-c54f4cc8-d5a3-11e7-9e6d-0290899439d6.PNG)

2015 values:
- Total coal production: 328,221,901

### Draft for proofreading
![03-line chart - campbell coal prod](https://user-images.githubusercontent.com/9259185/34310415-1f3d7900-e71d-11e7-8693-9bd80b34438b.png)

---
- [ ] **Campbell County wage and salary employment chart**
[Chart 2: Wage and salary employment](https://revenuedata.doi.gov/img/counties/wy-wage.svg)
![campbell2](https://user-images.githubusercontent.com/32855580/33440041-c8893296-d5a3-11e7-9e54-1e3a6db6f12c.PNG)

2015 values:
- All other industries: 16,085
- Mining industry: 6802

### Problem
![04-bar chart - campbell wage](https://user-images.githubusercontent.com/9259185/34310456-4c020c12-e71d-11e7-9c15-67dbde3e0c2b.png)

---

- [x] **DeSoto Parish**
[Chart 1: Natural gas production](https://revenuedata.doi.gov/img/counties/la-production.svg)
![desoto1](https://user-images.githubusercontent.com/32855580/33440286-724be1de-d5a4-11e7-8b3f-570de0a9a130.PNG)

2015-16 values:
- 2015: 1.72018 e12
- 2016: 1.67466 e12

### Draft for proofing
![05-line chart - kern oil prod](https://user-images.githubusercontent.com/9259185/34310471-602b1dc8-e71d-11e7-902b-7783b998bbce.png)

---
-[ ] Desoto wage and salary employment chart
[Chart 2: Wage and salary employment](https://revenuedata.doi.gov/img/counties/la-wage.svg)
![desoto2](https://user-images.githubusercontent.com/32855580/33440409-bc28fbf2-d5a4-11e7-84ad-f538addac90c.PNG)

2015-16 values:

- 2015: 
     - all other industries: 4180
     - mining: 886

- 2016:
     - all other industries: 4062
     - mining: 836

### Problem
![13-bar chart - desoto wage](https://user-images.githubusercontent.com/9259185/34494988-bad26936-efb8-11e7-8601-f7c0e33ca760.png)

---

[Chart 3: Sales and use taxes](https://revenuedata.doi.gov/img/counties/la-tax.svg)
![desoto3](https://user-images.githubusercontent.com/32855580/33440448-dad676f6-d5a4-11e7-836c-ee95280f3fbf.PNG)

2015 values:

- 18 million

### Draft for proofing
![25-bar chart - sales and use tax trends](https://user-images.githubusercontent.com/9259185/34310659-63d4a79a-e71e-11e7-91d5-f8d594b6f77b.png)

---

- [ ] **Elko and Eureka Counties**
[Chart 1: Gold production](https://revenuedata.doi.gov/img/counties/nv-production.svg)
![elko1](https://user-images.githubusercontent.com/32855580/33440631-561b3fe0-d5a5-11e7-8e1c-c38af7e0e4b4.PNG)

2015 values:

- Elko: 607,524
- Eureka: 1,538,408
- Both: 2,145,932

### Draft for proofing
![17-line chart - elko gold](https://user-images.githubusercontent.com/9259185/34310674-7de29a66-e71e-11e7-99a3-7ab5dbf93af7.png)

---

[Chart 2: Gold mining employment](https://revenuedata.doi.gov/img/counties/nv-employment.svg)
![elko2](https://user-images.githubusercontent.com/32855580/33440667-6bb3e924-d5a5-11e7-9b1c-577fd0eec317.PNG)

2015 values:
- Elko: 1290
- Eureka: 3774
- Both: 5064

### Draft for proofing
![19-bar chart - elko eureka empl](https://user-images.githubusercontent.com/9259185/34310749-dd8ec8ae-e71e-11e7-8cf8-db067fa3e57e.png)

---

- [ ] **Greenlee County**
[Chart 1: Morenci mine copper production and average copper price](https://revenuedata.doi.gov/img/counties/az-production.svg)
![greenlee1](https://user-images.githubusercontent.com/32855580/33440783-bc2be424-d5a5-11e7-9356-3ade25e4e09f.PNG)

2016 values:
- Production: 848
- Price point: 220

### Draft for proofing
![15-combo chart - morenci copper](https://user-images.githubusercontent.com/9259185/34310756-ec929bd2-e71e-11e7-9ba3-be6401718fa6.png)

---

- [X] **Humboldt and Lander Counties**
_Inconsistent spelling of Humboldt/Humbolt throughout content and charts_

[Chart 1: Gold production](https://revenuedata.doi.gov/img/counties/nv-humboldt-production.svg)
![humbolt1](https://user-images.githubusercontent.com/32855580/33441070-9ec4a082-d5a6-11e7-8789-bc049ba4d3c7.PNG)

2015 values:
- Humboldt: 1,113,430
- Lander: 1,259,426
- Both: 2,372,856

### Draft for proofing
![09-line chart - humboldt gold](https://user-images.githubusercontent.com/9259185/34310771-082265bc-e71f-11e7-9f52-bb4f60ef191d.png)

---

[Chart 2: Gold mining employment](https://revenuedata.doi.gov/img/counties/nv-humboldt-wage.svg)
![humbolt2](https://user-images.githubusercontent.com/32855580/33441103-b3ac7b50-d5a6-11e7-885a-120787493f6d.PNG)

2015 values:
- Humboldt: 1979
- Lander: 2670
- Both: 4649

### Draft for proofing
![10-bar chart - humboldt lander empl](https://user-images.githubusercontent.com/9259185/34310784-1986cac8-e71f-11e7-962c-037fdb9443bd.png)

---

- [X] **Kern County**

[Chart 1: Oil production](https://revenuedata.doi.gov/img/counties/ca-production.svg)
![kern1](https://user-images.githubusercontent.com/32855580/33441342-4f3d3456-d5a7-11e7-976c-4479836c7a73.PNG)

2015, 2016 values
- 2015: 144,429.52
- 2016: 134,049.90

### Draft for proofing
![05-line chart - kern oil prod](https://user-images.githubusercontent.com/9259185/34311058-b15e7f48-e720-11e7-809f-a1611be3f128.png)

---
- [ ] Kern wage and salary employment chart
[Chart 2: Wage and salary employment](https://revenuedata.doi.gov/img/counties/ca-wage.svg)
![kern2](https://user-images.githubusercontent.com/32855580/33441380-634fb57c-d5a7-11e7-9448-3dfb20ee913e.PNG)

2015, 2016 values:
- 2015
     - Oil and gas: 3676
     - All other industries: 248,445
- 2016
     - Oil and gas: 7718
     - All other industries: 244,370

### Problem
![06-bar chart - kern oil](https://user-images.githubusercontent.com/9259185/34310802-2ee37b64-e71f-11e7-8ccf-18a2e6c99f32.png)

---
- [X]
[Chart 3: Assessed property valuation](https://revenuedata.doi.gov/img/counties/ca-valuation.svg)
![kern3](https://user-images.githubusercontent.com/32855580/33441411-7843fc54-d5a7-11e7-9a50-354f021bdf9f.PNG)

2015, 2016 values:
- 2015
     - Oil and gas: 28.7224
     - Non oil and gas: 69.7544
     - Total: 89.2
- 2016
     - Oil and gas: 19.4456
     - Non oil and gas: 72.60708
     - Total: 85.4

### Draft for proofing
![08-bar chart - kern assessment alt](https://user-images.githubusercontent.com/9259185/34310866-7a7dcd40-e71f-11e7-8429-2b0f3a859e22.png)

---

- [X] **Marquette County**

[Chart 1: Iron production](https://revenuedata.doi.gov/img/counties/mi-production.svg)
![marquette1](https://user-images.githubusercontent.com/32855580/33441572-d20eaebe-d5a7-11e7-9a81-582605e9c008.PNG)

2014 values:
- Crude iron: 35,700
- Usable iron: 12,100

### Draft for proofing
![16-line chart - marquette iron](https://user-images.githubusercontent.com/9259185/34310884-88b637bc-e71f-11e7-8dd1-e07338c34097.png)

---

- [ ] **North Slope Borough**

- [X] Oil production chart
[Chart 1: Oil production](https://revenuedata.doi.gov/img/counties/ak-production.svg)
![northslope1](https://user-images.githubusercontent.com/32855580/33441706-2bd33ece-d5a8-11e7-939b-7e56a8df3781.PNG)

2015 values:
- North Slope: 169,554
- Alaska: 176,241

### Draft for proofing
![20-line chart - north slope oil](https://user-images.githubusercontent.com/9259185/34310895-97d1e728-e71f-11e7-8308-968f5032f94b.png)

---
-[X] North Slope employment chart
[Chart 2: Employment](https://revenuedata.doi.gov/img/counties/ak-wage.svg)
![northslope2](https://user-images.githubusercontent.com/32855580/33441748-42d97642-d5a8-11e7-8652-5ac18967b836.PNG)

2015 values:
- Mining: 9290

-[X] **The existing chart is being replaced by this one:**
[Chart 3: Alaska production and gas tax](https://revenuedata.doi.gov/img/counties/ak-tax.svg)
![northslope3](https://user-images.githubusercontent.com/32855580/33441782-59a8fadc-d5a8-11e7-90f5-d607b6546f09.PNG)

**This is a completely revised chart to replace the current one. Here are the new values:**
- 2006: $4,400
- 2007: $5,100
- 2008: $11,300
- 2009: $6,100
- 2010: $6,200
- 2011: $8,100
- 2012: $9,900
- 2013: $7,400
- 2014: $5,700
- 2015: $2,400
- 2016: $1,600

### Not sure what's going on here
![22-bar chart - alaska quarterly severance tax copy](https://user-images.githubusercontent.com/9259185/34310957-032a53f2-e720-11e7-87c4-8bbc4e050c27.png)

---

- [X] **Pima County**

[Chart 1: Copper production](https://revenuedata.doi.gov/img/counties/az-pima-production.svg)
![pima1](https://user-images.githubusercontent.com/32855580/33441915-ba5150e6-d5a8-11e7-8db6-10e4092b03d3.PNG)

_No update_

---
- [X] Wage and salary employment chart
[Chart 2: Wage and salary employment](https://revenuedata.doi.gov/img/counties/az-wage.svg)
![pima2](https://user-images.githubusercontent.com/32855580/33441983-d8e984ba-d5a8-11e7-80e8-d3aa5743df5f.PNG)

2015 values:
- Percent: 0.8%
- Chart value: 285,383

### Draft for proofing
![24-bar chart - pima wage](https://user-images.githubusercontent.com/9259185/34310968-18afac22-e720-11e7-9e81-c5305c264f1a.png)

---

- [X] **St. Louis County**

[Chart 1: Iron ore production](https://revenuedata.doi.gov/img/counties/mn-production.svg)
![stlouis1](https://user-images.githubusercontent.com/32855580/33442117-31c11bde-d5a9-11e7-9f48-d88c214dd871.PNG)

2014 values:
- U.S.: 56,100
- St. Louis County: 43,200

### Draft for proofing
![23-line chart - st louis iron ore](https://user-images.githubusercontent.com/9259185/34310988-2fecdaf4-e720-11e7-904b-bd3f40b3526d.png)

---

- [X] **Tarrant and Johnson Counties**

[Chart 1: Natural gas production](https://revenuedata.doi.gov/img/counties/tx-production.svg)
![tarrant1](https://user-images.githubusercontent.com/32855580/33442304-b2e28c5c-d5a9-11e7-9b50-8b8dfeebbcfb.PNG)

2015, 2016 updates:
- 2015:
     - Tarrant: 610,410,810
     - Johnson: 265,051,033
     - Total: 875,461,843

- 2016:
     - Tarrant: 537,874,853
     - Johnson: 227,637,351
     - Total: 765,512,204

### Draft for proofing
![11-line chart - tarrant johnson gas](https://user-images.githubusercontent.com/9259185/34311005-47052282-e720-11e7-9832-c461841c4bf7.png)

---

[Chart 2: Wage and salary employment](https://revenuedata.doi.gov/img/counties/tx-employment.svg)
![tarrant2](https://user-images.githubusercontent.com/32855580/33442338-c7ed88a4-d5a9-11e7-9175-df3989d13e2c.PNG)

- 2015:
     - Johnson: 1186
     - Tarrant: 8285
     - Johnson + Tarrant: 9471

- 2016:
     - Johnson: 355
     - Tarrant: 6948
     - Johnson + Tarrant: 7303

### Draft for proofing
![12-bar chart - tarrant empl](https://user-images.githubusercontent.com/9259185/34311023-5d54ae18-e720-11e7-998f-b011e7818b66.png)

**Comment by ericronne** [comment]
FYI these are manually drawn ... in sketch. :/

#2497

**Comment by brentryanjohnson** [comment]
I know...we'll need to continue our discussions re: the maintainability of case studies as a whole.

**Comment by coreycaitlin** [comment]
Next step: Pull latest-year numbers from the charts, and identify whether we can get that data from the visuals within 1-2 hours. (If not, we'll request further data files.)

**Comment by brentryanjohnson** [comment]
@coreycaitlin and @ericronne I'm chipping away at adding the new data values (above).

**Comment by brentryanjohnson** [comment]
@coreycaitlin and @ericronne I finished pulling out the updated values (above). They should be ready to incorporate into the Sketch charts.

**Comment by ericronne** [comment]
Excellent! Now they're *my* problem :)
Stay tuned.

**Comment by ericronne** [comment]
Something seems fishy in boone county...

![image](https://user-images.githubusercontent.com/9259185/34277630-4583989e-e66c-11e7-9795-1680e28732cf.png)

My guess is that the old chart is a *stacked* bar. The [campbell](https://revenuedata.doi.gov/img/counties/wy-wage.svg) chart matches up fine, except for 2014...
![image](https://user-images.githubusercontent.com/9259185/34277931-76872edc-e66d-11e7-978f-7bc525a401e3.png)
 

Also there's no percentage figure for 2015. Something we can calculate?

**Comment by ericronne** [comment]
Dropped drafts (including images of problematic employment bars) into the mega-note atop this issue.

An early 🎁  for y'all, cuz i care.

**Comment by brentryanjohnson** [comment]
Hmmm...looking back at [#1603](https://github.com/18F/doi-extractives-data/issues/1603), It looks like the Boone numbers might have been accidentally exaggerated at some point. Last year's "other industries" values hovered around 20,000 (not over 25,000, as in the current chart). It seems the chart values we were given this year are more or less consistent with past years.

As for Campbell County, the percent value for 2015 is **29.7%**, rounded to **30%**.

**Comment by brentryanjohnson** [comment]
@ericronne and @coreycaitlin I checked the Boone, Logan, and Mingo data against the [census source data](https://data.bls.gov/cew/apps/data_views/data_views.htm#tab=Tables), and it appears the data as [_currently_ represented on the site](https://revenuedata.doi.gov/case-studies/boone-logan-and-mingo/#employment) is accurate (the chart we received this year **doesn't** appear to be accurate). I pulled the 2015 values from the source:
- Mining industry employment: **3,688**
- All industries: **21,732**
- Percent mining: **17%**

**Comment by coreycaitlin** [comment]
Still blocked by needing further data validation.

**Comment by coreycaitlin** [comment]
Next step: Identify and list outstanding charts that need updating or validation, and come up with a plan to move forward.

**Comment by brentryanjohnson** [comment]
It looks like the 2016 values were not added to this chart:

- [ ] **Greenlee County**
[Chart 1: Morenci mine copper production and average copper price](https://revenuedata.doi.gov/img/counties/az-production.svg)
![greenlee1](https://user-images.githubusercontent.com/32855580/33440783-bc2be424-d5a5-11e7-9356-3ade25e4e09f.PNG)

2016 values:
- Production: 848
- Price point: 220

### Draft for proofing
![15-combo chart - morenci copper](https://user-images.githubusercontent.com/9259185/34310756-ec929bd2-e71e-11e7-9ba3-be6401718fa6.png)

**Comment by brentryanjohnson** [comment]
- [ ] **Boone, Logan, Mingo wage and salary chart** 

2015 values:

- All other industries: 16,816
- Mining industry: 3743

### Problem with this (and most employment charts)
![02-bar chart - boone wage](https://user-images.githubusercontent.com/9259185/34310367-e05f4a88-e71c-11e7-96dc-d5cab71337c9.png)

---

- [ ] **Campbell County wage and salary employment chart**

2015 values:
- All other industries: 16,085
- Mining industry: 6802

### Problem
![04-bar chart - campbell wage](https://user-images.githubusercontent.com/9259185/34310456-4c020c12-e71d-11e7-9c15-67dbde3e0c2b.png)

---

- [ ] **Desoto wage and salary employment chart**

2015-16 values:

- 2015: 
     - all other industries: 4180
     - mining: 886

- 2016:
     - all other industries: 4062
     - mining: 836

### Problem
![13-bar chart - desoto wage](https://user-images.githubusercontent.com/9259185/34494988-bad26936-efb8-11e7-8601-f7c0e33ca760.png)

---

- [ ] **Greenlee County Morenci copper**

[_This one is missing the 2016 addition._](https://github.com/18F/doi-extractives-data/pull/2570/files?short_path=c8a4b89#diff-29dab03f88bce64779f6507caa19f232)

2016 values:
- Production: 848
- Price point: 220

### Draft for proofing
![15-combo chart - morenci copper](https://user-images.githubusercontent.com/9259185/34310756-ec929bd2-e71e-11e7-9ba3-be6401718fa6.png)

---

- [ ] **Kern wage and salary employment chart**

2015, 2016 values:
- 2015
     - Oil and gas: 3676
     - All other industries: 248,445
- 2016
     - Oil and gas: 7718
     - All other industries: 244,370

### Problem
![06-bar chart - kern oil](https://user-images.githubusercontent.com/9259185/34310802-2ee37b64-e71f-11e7-8ccf-18a2e6c99f32.png)

**Comment by coreycaitlin** [comment]
Next step: @brentryanjohnson to gather final numbers and clarify outstanding questions here.

**Comment by brentryanjohnson** [comment]
We received the origin data from Deloitte, but we're still awaiting explanations from them regarding some discrepancies in the data. For that reason, I've added the `workflow: blocked` label back.

![image](https://user-images.githubusercontent.com/32855580/35537592-9d4414f8-04ff-11e8-9b42-2abfe23c4e18.png)

Remaining questions:
- The Excel chart labels the y-axis as "Number of paid employees". How is that different than "Total Employment"? Does "Total Employment" include unpaid employment/volunteerism of some kind?

- If "Paid Employment" is derived from all industries that pay employees, why don't the "Mining Industry" and "All Other Industries" values add up to the "Total Employment" value (they add up to Total Employment only for 2004)? What figures in to "Total Employment" that is not captured in Mining + All Other Industries?

- The stacked bar chart style implies that the "percentage of Employment" value is the percentage of Mining compared to Mining plus All other industries, but that isn't the case. The percentage is calculated as the percentage of mining as a portion of total employment. This is an issue because Mining + All other industries doesn't equal Total Employment.

- In 2015, the value for "All Other Industries" is larger than Total Employment for the same year. How is that possible?

**Comment by brentryanjohnson** [comment]
So we've discovered that _Jobs in sector_ + _Jobs in all other industries_ ≠ _Total Employment_ in the Bureau of Labor Statistics data. The Deloitte data charted mining jobs and all other industry jobs, but presented the percentage as mining jobs as a portion of total employment (for Boone, Logan, Mingo).

To move this forward, we decided to omit the "All other industries" values and stack-chart mining and total employment. The chart [on the site now](https://revenuedata.doi.gov/img/counties/wv-wage.svg) uses the "Total Employment" figure instead of the "All other industries" value, even though the latter is represented as the difference of mining employment and total employment.

We have a path forward. I will circle back with @ericronne to move this forward.

**Comment by brentryanjohnson** [comment]
@ericronne The updated values and labels should be ready to chart; they are in the [comment above](https://github.com/18F/doi-extractives-data/issues/2496/#issuecomment-360909571).

Let me know if you have any questions or concerns.
