### ISSUE TITLE
Broken links in Tribal addition

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2499]
We have some broken links in [Natural resource production on tribal land](https://revenuedata.doi.gov/how-it-works/tribal-production/). Related to #2387.

- Sample minerals development agreement (PDF) 404
- Building Green Economies on Tribal Lands (PDF) 404
- broad overview of the process for developing renewable energy projects (PDF) 404

**Comment by coreycaitlin** [comment]
Also a great pairing opportunity 🐝

**Comment by brentryanjohnson** [comment]
- [ ] Sample minerals development agreement (PDF) 404
_Could be [this link](https://www.bia.gov/sites/bia.gov/files/assets/as-ia/ieed/ieed/pdf/idc010987.pdf)_
- [ ] Building Green Economies on Tribal Lands (PDF) 404
_Looks like [this is the correct link](https://www.bia.gov/sites/bia.gov/files/assets/as-ia/ieed/ieed/pdf/idc010168.pdf)_
- [ ] broad overview of the process for developing renewable energy projects (PDF) 404
_Looks like [this might be the one](https://www.bia.gov/sites/bia.gov/files/assets/as-ia/ieed/bia/pdf/idc1-031905.pdf)_

**Comment by mentastc** [comment]
Fixed links and there is a pull request to merge to dev
Pull request #2517

**Comment by coreycaitlin** [comment]
Whoops! This was accidentally rolled back by #2507, so I'm re-opening.
