### ISSUE TITLE
Broken GDP data value (percent)

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2504]
The percent value in the [GDP chart](https://revenuedata.doi.gov/explore/#gdp) isn't pulling in the data. We're also missing the 2016 data.

![broken_gdp](https://user-images.githubusercontent.com/32855580/33498555-a357ce22-d686-11e7-9261-0f06bd9bd26a.PNG)

**Comment by coreycaitlin** [comment]
🎈 This is now fixed!
