### ISSUE TITLE
Document disbursements data update process

### ISSUE THREAD

**Issue by msecret** [18F/doi-extractives-data#2505]
In order for contributors to easily update the disbursements data with new yearly data, there should be detailed instructions that provide users with clear steps and an understanding of the different data files.

Notes in progress:
https://docs.google.com/document/d/1Vyjh1oldslmoZSgvHm5OTq0rlQBzJiEBTph-MuHBiQU/edit

**Comment by coreycaitlin** [comment]
This is great @msecret! Assigning to myself to identify some next steps and sort your notes into how-to, questions, and next steps.

**Comment by msecret** [comment]
I started working on the documentation updates here: https://github.com/18F/doi-extractives-data/pull/2518.

**Comment by coreycaitlin** [comment]
Are there any other next actions you want to pull out of this @msecret? I think the notes you added in the README file cover the how-to, and you've already resolved some of the questions. 🎉

**Comment by coreycaitlin** [comment]
This documentation is improved [here](https://github.com/18F/doi-extractives-data/blob/dev/data/disbursements/README.md), and we opened #2529 to follow up on documenting the `years.yml` part of the process.
