### ISSUE TITLE
Document the role of Circle, Hound, federalist in workflow

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2514]
Can we talk about the role of Circle, Hound, and federalist checks in the GitHub workflow?

- What role does each play in merging/publishing?
- What are some common issues we might confront with each?
- How do we resolve issues with each when they arise?

**Comment by coreycaitlin** [comment]
Next step: draft this documentation in a Google Doc or wiki page.

**Comment by coreycaitlin** [comment]
[Started a draft of this here (limited access)](https://docs.google.com/document/d/1t2rfoKH8WD_ZiBFY_0VEh5IKw-Q7tzQuVsWIlCrn14U/edit#).

**Comment by alexpandel** [comment]
next step: @jeremiak to review what Corey started, make any changes/additions as needed, and get it added to the wiki.

**Comment by jeremiak** [comment]
Added to the [wiki](https://github.com/18F/doi-extractives-data/wiki/Continuous-integration-tools)

**Comment by alexpandel** [comment]
sweet, thank you! @brentryanjohnson, would you (or @jennmalcolm) want to give this a once-over and close this issue if it feels complete (or give some more direction on what you need if not)?

**Comment by brentryanjohnson** [comment]
This is looking great! I converted the subheadings from `p` tags to `h2`s for semantic purposes. 

I think we could use a little more information about CircleCI. @jeremiak What do you think about adding some documentation to that section that covers the purpose of CircleCI and summarizes the checks in a little more detail?

**Comment by jeremiak** [comment]
@brentryanjohnson I added [the following to the wiki page](https://github.com/18F/doi-extractives-data/wiki/Continuous-integration-tools/_compare/bf56527c8106d75bc7caa8b272ded36cc435ddae...6f32605e1a6842475cae3708ac677ee956a4a45a), let me know what you think and close if you think its sufficient for now.
