### ISSUE TITLE
Documentation: Review and improve wiki

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2519]
Our [wiki](https://github.com/18F/doi-extractives-data/wiki) is a great source of documentation about all kinds of things, including product decisions, hypotheses, content/editorial guide, and data notes. As we begin expanding our documentation, this seems like a good time to review what we've got, make sure it's organized usefully, clean out cruft, and make space for new stuff.

Some examples of documentation/wiki organization on other projects:

- For overall large-project docs structure: [Web Design Standards wiki](https://github.com/18F/web-design-standards/wiki)
- For Federalist and research documentation: [plainlanguage.gov wiki](https://github.com/GSA/plainlanguage.gov/wiki)
- For content update documentation and visuals: [worker.gov wiki](https://github.com/USDepartmentofLabor/worker-dol-gov/wiki/1.-Editing-guide:-Site-data-structure)

**Comment by brentryanjohnson** [comment]
I would really like to pair on this!

**Comment by alexpandel** [comment]
@brentryanjohnson yes plz! Let's discuss today in sprint planning!

**Comment by jennmalcolm** [comment]
Ryan has completed review and some restructuring, so we are closing this.
