### ISSUE TITLE
Style guide: Rig JS web components to fractal

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2522]
Bring JS web components for data-driven visualizations into the style guide:
- Bar charts
- Maps

**Comment by coreycaitlin** [comment]
@msecret What's the next step here? I think we still need to add the specific elements, right?

**Comment by coreycaitlin** [comment]
Next step: @msecret and @brentryanjohnson to meet and discuss what is most useful for documenting these elements. Pairs well with #2620

**Comment by coreycaitlin** [comment]
The styleguide now _has_ JS, but none of the actual JS elements/components are included. I believe the relevant components are tagged with "tech help needed."

**Comment by jeremiak** [comment]
Related pages on the style guide:
- [ ] Accordions
- [ ] Buttons
- [ ] Links
- [ ] Selectors
- [ ] Typography

**Comment by brentryanjohnson** [comment]
Closing in favor of #2771
