### ISSUE TITLE
Plan research synthesis

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2524]
We want to synthesize the research we've conducted for #2476 next week, while the insights are still fresh. Doing so will require planning how we use that time.

This issue is done when the following have occurred:
- [x] a rough synthesis plan is drafted (@winzenburg)
- [x] time is held on research team's calendar for group synthesis on Thursday 12/14 (@winzenburg)
- [x] individual prep sessions are scheduled with each of the interview teams (@alexpandel)
- [x] interview notes docs are copied into shared documents in [this folder](https://drive.google.com/drive/u/0/folders/1sSM6ElU9NL_FVXcF9atAEdg0MVi4J6di) so @alexpandel can access them for her prep sessions (@winzenburg)
- [ ] detailed facilitation plan for Thursday is drafted (@alexpandel)

**Comment by alexpandel** [comment]
for that last checklist item @winzenburg, I set up some time for us to pair on this mid-day Wednesday. Would you be up for taking a first pass at writing down a rough plan for how we might use the time on Thursday, that we can refine together in our Wed meeting?

**Comment by alexpandel** [comment]
first pass at [plan for session here](https://docs.google.com/document/d/1QSSZF7QJfgVDtzo8oCHEtSnaPCNEROqD2TyuzLl2wUM/edit#heading=h.peel5lvny1fx); we can discuss in our meeting in a bit @winzenburg!

**Comment by coreycaitlin** [comment]
Next step: conduct the synthesis! #2535
