### ISSUE TITLE
Scrub markdown files for proper header structure

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2531]
Search content .md files and replace "strong" markdown (`**Subtitle**`) instances with header styles, where appropriate. Like we just did with [this file](https://github.com/18F/doi-extractives-data/pull/2530/files#diff-0b4e2817b2c6508154383025afdd1e39).

**Comment by coreycaitlin** [comment]
I reviewed most markdown files, and I can't find any other instances where we're using `**strong**` but should be using a header. Calling this done!
