### ISSUE TITLE
Data: Update FY Revenue download data set for 2017 

### ISSUE THREAD

**Issue by mentastc** [18F/doi-extractives-data#2532]
Replace the current 3 download FY files with the new FY2017 download files. 

Flies should be located here on the portal:  https://revenuedata.doi.gov/downloads/federal-revenue-by-location/

![image](https://user-images.githubusercontent.com/15347998/33902481-1f967410-df43-11e7-8c54-1cf2e5e51332.png)

**Comment by mentastc** [comment]
@coreycaitlin can you please add links to the source files

**Comment by coreycaitlin** [comment]
Yep! The files are [here (limited access)](https://drive.google.com/drive/folders/0B4b900J0no9nQW8xc0tzN1d3eDg)

This is a great pairing issue, so I'm going to assign a few folks.

**Comment by coreycaitlin** [comment]
Now in final refinement by @brentryanjohnson!
