### ISSUE TITLE
Documentation: Remote collaboration and project management

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2536]
Let's write down what does/doesn't work to keep a remote team productive, since that's a pretty crucial part of building and maintaining momentum.

**Comment by coreycaitlin** [comment]
I've added an initial set of rules/tips/recommendations to the wiki here: [Basics for making distributed work work](https://github.com/18F/doi-extractives-data/wiki/Basics-for-making-distributed-work-work)

**Comment by brentryanjohnson** [comment]
@coreycaitlin I added some subheadings and elaborated in the "overcommunicate" section. If you think those additions add value and look good, we can close this!

**Comment by coreycaitlin** [comment]
@brentryanjohnson Your additions make it much better — thank you!
