### ISSUE TITLE
Documentation: Research process and norms

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2537]
We tend to follow a relatively consistent research process for most sprints, and rely on certain deliverables and documents to make that research consistent. We should have that documented for reference and posterity!

**Comment by alexpandel** [comment]
What's the definition of done here? How can I help? :)

**Comment by coreycaitlin** [comment]
Next step: I'll edit down my draft and put it in the research branch README.

**Comment by coreycaitlin** [comment]
Just posted a draft of this documentation here: [research/README.md](https://github.com/18F/doi-extractives-data/blob/research/research/README.md). Would love review and feedback from @jennmalcolm and @brentryanjohnson!

**Comment by jennmalcolm** [comment]
This looks good to me, and I think it will help very much as we transition the work to ONRR without having our UX person on board yet. Thank you.
