### ISSUE TITLE
How it works content updates

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2539]
We have stale content on How it works--> [Corporate income tax](https://revenuedata.doi.gov/how-it-works/corporate-income-tax/). 

For example, some statements need to be updated/corrected:

_The Securities and Exchange Commission is rewriting the rule and has stated that it will be proposed in the spring of 2016. Once finalized, publicly traded companies will report according to the law and the rule._

**Comment by coreycaitlin** [comment]
Closing in favor of #2624
