### ISSUE TITLE
Misc fractal tech tasks

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2545]
Many to be co-tackled by @msecret and @ericronne …

- [x] Confirm that our approach reflects / supports how content is currently added to the site
- [ ] ~~Set up connection to _variables.scss, in order to access colors, eg~~ (Effort required would outweigh the benefit.)
- [x] Colors: vertically align small icons with text
- [x] Colors: add map colors (which use RGBA and overlays)
- [x] Callout cards: background should cover full page
- [x] Selectors: how should we set widths?
- [x] Text links: suss out indenting issue

**Comment by ericronne** [comment]
## Second batch
- [ ] MS: linking between iframes (target="_blank" not working)
- [ ] Add vertical spacing between collated components
- [ ] Override the iframe margin when necessary (req's additional preview.hbs file, return to this later, time permitting)
- [ ] Set up a style (via javascript?) to add subtle border to white color swatch (which might in turn give us a leg up on applying other piecemeal styles)
- [ ] Accordions: rig them up, or figure out how to make them as useful as possible (code seems specific, and a little complicated)
- [ ] Filter toggle button: needs "+" icon (and preferably working sample)
- [ ] Glossary: i want to use this as the base for a "sliding-panel utility," which could be useful as a filter, eg. Need tech guidance
- [ ] Icon button panels: used on the case studies [map](https://revenuedata.doi.gov/case-studies/), these might be useful on future interactive maps. They are hand-positioned to specific pixel coordinates, though, so it might not be easy to make them into reusable components.

**Comment by coreycaitlin** [comment]
Closing — will open individual issues for remaining style guide needs as they arise.

**Comment by ericronne** [comment]
Looks like most of these are set to be covered by #2522, but mobile nav isn't. It' viewable on [this page of the style guide](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/build-styleguide-on-fed/styleguide/components/detail/global-header.html), but not functional.
