### ISSUE TITLE
Framing: articulate the problem NRRD is solving

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2547]
Working on this [here](https://docs.google.com/document/d/1Pc2qdQHN6m268r9rJhP9OfZIq0dbkdWnGqHZEQYn4E0/edit#heading=h.akxk5796axa4). 

This is done when:
- [x] pairing time with Jennifer/Ryan and Corey/Alex has been set up to work on this 
- [x] @brentryanjohnson has taken a pass at condensing the problem statement into 2-3 concise paragraphs
- [x] @jennmalcolm has reviewed
- [x] @alexpandel or @coreycaitlin has reviewed

**Comment by coreycaitlin** [comment]
This is in great shape — I think it'll be ready to close out as soon as @brentryanjohnson takes one more look at it (post-holidays!).

**Comment by coreycaitlin** [comment]
This is done! 🎉
