### ISSUE TITLE
Framing: identify & prioritize risks to NRRD

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2549]
Working on this [here](https://docs.google.com/document/d/1Pc2qdQHN6m268r9rJhP9OfZIq0dbkdWnGqHZEQYn4E0/edit#heading=h.5vmq1yuu08h8). 

This is done when:
- [x] pairing time with Jennifer/Ryan and Corey/Alex has been set up to work on this (~1 hour?)
- [x] we feel all known risks are captured accurately
- [x] we’ve captured any known mitigation approaches for each risk
- [x] we've assigned a status to each risk
- [x] @brentryanjohnson has assigned a criticality level to each risk (or gut-checked the existing ones)
- [x] @jennmalcolm has assigned a criticality level to each risk (or gut-checked the existing ones)

(Some good background info about identifying & mitigating product risk [here](https://docs.google.com/presentation/d/1uPRDMzIuKHMTlH39pXskqIsdQa4VEIX-ekaGgLBak1w/edit).)

**Comment by coreycaitlin** [comment]
This is in good shape to move forward!
