### ISSUE TITLE
Framing: articulate the NRRD vision

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2551]
Working on this [here](https://docs.google.com/document/d/1Pc2qdQHN6m268r9rJhP9OfZIq0dbkdWnGqHZEQYn4E0/edit#heading=h.mitxd1m45nm5). 

This is done when:
- [x] pairing time with Jennifer & Ryan and Corey/Alex has been set up to work on this (~1.5 hours?)
- [x] we have a clear, concise, 1-2 sentence statement that captures the vision for NRRD.
- [ ] we've made new issues for next steps around publishing our framing on the wiki and building awareness and support for it with project stakeholders.

(Some good background info about articulating the product vision [here](https://docs.google.com/presentation/d/1ZoghI89cQ5UhlgLhLfg07GdGSrEPkf3BIwgCDLIHfeg/edit).)

**Comment by alexpandel** [comment]
Note: this is blocked until #2547 #2548 and #2550 are complete.

**Comment by coreycaitlin** [comment]
Removed the `blocked` label, because the 3 other issues are done 🥇

**Comment by alexpandel** [comment]
👏👏👏 y'all, this looks great! Calling it ✨DONE!✨
