### ISSUE TITLE
Framing: socializing the product vision & framing with key stakeholders

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2552]
Some good background info about broadcasting your product narrative is [here](https://docs.google.com/presentation/d/15PkLZQF34U9QAwjrA5EL5szee5s1l8kDL7UxL0Kpw3g/edit).

This is done when:
- [x] pairing time with Jennifer, Ryan and Corey/Alex has been set up to decide what comms might be needed (~1 hour?)
- [x] we’ve identified any other communications might be needed and have captured next steps in Github issues

**Comment by alexpandel** [comment]
Note: this is blocked until #2551 is complete.

**Comment by alexpandel** [comment]
This is no longer blocked! @jennmalcolm @coreycaitlin does this count as done given our session in demo last week? Or do we want to plan for wider comms with OLT, etc?

**Comment by coreycaitlin** [comment]
This is done, and we'll track further work in new issues!
