### ISSUE TITLE
Broken link on Tribal Revenue

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2556]
On the [Tribal Revenue page](https://revenuedata.doi.gov/how-it-works/tribal-revenue), we have a broken link under the [Audits and assurances subheading](https://revenuedata.doi.gov/how-it-works/tribal-revenue/#audits-and-assurances). The link is "Onshore Energy and Mineral Lease Management Interagency Standard Operating Procudures (PDF)."

**Comment by coreycaitlin** [comment]
Closing in favor of #2624
