### ISSUE TITLE
Mothball the old styleguide, and deal with associated cruft

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2557]
Our current [style guide](https://revenuedata.doi.gov/styleguide/index.html) is incomplete, and will be obviated by the fractal one currently under way in #2360. Once that's complete, let's delete the old one, and clean up sass files which reference it.

**Comment by coreycaitlin** [comment]
@msecret to investigate whether this is done...stay tuned.

**Comment by jeremiak** [comment]
I'm calling this done since 2614 was merged
