### ISSUE TITLE
Proposal: Use webpack instead of Jekyll for many build tasks

### ISSUE THREAD

**Issue by jeremiak** [18F/doi-extractives-data#2563]
Currently, we leverage Jekyll as one of the main build tools. For example, it watches and compiles the SCSS directory for us. This is out of the box behavior for Jekyll but one of the problems is that we do things differently for JS and some other files and `jekyll` isn't available at the time we need it on Federalist. We use webpack to compile our Javascript, but perhaps we should use it to compile the CSS files and move other files like `images` or `fonts` to a distinct compilation folder for static assets (`/public`).

Our current set up presents a challenge for using Fractal because:
1. Federalist doesn't have `jekyll`/`bundle` available at the time it runs `npm run federalist`
2. To make Fractal changes requires waiting for Jekyll to rebuild the site

The goal would be to have Jekyll only do template/HTML compilation and have webpack do CSS/JS compilation and img/font asset moving. This would enable Fractal to work without Jekyll (ensuring that it works on Federalist and decreasing the amount of time it takes to do work on the styleguide itself).

@msecret and I came up with this list of tasks to get this done:
- [x] Set up webpack for building CSS
- [x] Set up webpack to dump compiled JS into public and not /js/lib (which is confusing to have both source and compiled files in the same place)
- [ ] Set up webpack for moving images and fonts around
- [x] Configure Jekyll to ignore all of those files (hopefully this has a nice secondary benefit of speeding up the build time)
- [x] Rename static paths to use `/public` if we can't figure out how to do this dynamically with Jekyll defaults
- [x] Configure Fractal to use `/public` and not rely on Jekyll at all

**Comment by jeremiak** [comment]
I have been doing much of this work on the `move-some-css-around` branch and have webpack building the CSS so that Jekyll need not worry about it and the Fractal app can get access to it without `ruby` or `jekyll` being present (which is what happens in the Federalist builder).

However, I have run into an issue where the site cannot build on Federalist because (the current theory goes) the dependencies and app take up too much memory ([slack link for convo in #federalist-support](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1514997464000239)). I might try updating the node version since npm v5 changes the way dependencies are installed so as to have a lower memory footprint.

**Comment by ericronne** [comment]
Thanks for the update, and for keeping up the fight! 💪

**Comment by coreycaitlin** [comment]
Closing this out, since this work has been merged in. Remaining troubleshooting will get new issues!
