### ISSUE TITLE
Right-align numerical values in disbursement tables

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2569]
## Expected Behavior
![image](https://user-images.githubusercontent.com/9259185/34492116-d25c097a-efab-11e7-9ee4-bca09e331073.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/9259185/34492157-f93238c6-efab-11e7-8097-72ecfebbb57c.png)

I've made the fix on the [national page](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/er-styling-jan/explore/#federal-disbursements), but need @msecret's help for opt-in pp.

For PR #2568

**Comment by coreycaitlin** [comment]
This is done with #2568
