### ISSUE TITLE
Audit plugins

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2574]
On other projects, auditing plugins has occasionally helped identify opportunities to speed up the build. Let's get a sense of what plugins we're using, what potential duplications we have, and so forth.

**Comment by coreycaitlin** [comment]
Part of this should include noting custom plugins and filters, and might help track down the issues with #2652

**Comment by jeremiak** [comment]
https://docs.google.com/spreadsheets/d/170oMFh1ESCBIzrbpvYdlPmAOkhfEj98EHJC4WDbfhSc/edit#gid=0

**Comment by master12** [comment]
@jeremiah Looks good to me

**Comment by jeremiak** [comment]
Closing this then!
