### ISSUE TITLE
Inconsistent column widths for horizontal charts

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2576]
Horizontal charts have inconsistent widths depending on their placement. For example, the Wyoming revenue and disbursement charts have different widths.

The presented width of the chart also affects the scale; the narrower chart below requires scaling that visually equates $0 and $13 million ([separate issue](https://github.com/18F/doi-extractives-data/issues/2575) for chart showing value for 0).

![image](https://user-images.githubusercontent.com/32855580/34546011-e39264a0-f0a5-11e7-96f3-91c353659df9.png)

![image](https://user-images.githubusercontent.com/32855580/34546017-f90511b6-f0a5-11e7-867d-ec0addddb462.png)

**Comment by coreycaitlin** [comment]
Closing this for now!
