### ISSUE TITLE
make sure everyone at ONRR who fields information requests is well informed about what data is available on NRRD, and how to use the site

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2579]
During our last research sprint, we heard that many folks turn to their own personal contacts within ONRR to get the info they need, but that in several cases, these folks' contacts within ONRR were not well-versed in what data was available on the NRRD site vs. what data required a custom data pull, which led to some confusion and wasted time on both sides.

It would be worth the NRRD team investing time in making sure everyone at ONRR who fields information requests, whether formal or informal, is well informed about what data is available on NRRD, and how to use the site, so that they can help direct people to the right place when the information they are asking about is in fact available on the site. 

This would likely entail some targeted demos, and potentially even developing some training materials or scripts that various ONRR staff can use to help direct data requestors either to relevant pages on the NRRD site or to the Data Services team for custom requests.

**This issue is done when:**

- [x] we've more clearly scoped what this work would entail, and have broken this task into smaller, more actionable issues.

**Comment by coreycaitlin** [comment]
Next step: open new issues or identify tasks to move this forward.

**Comment by coreycaitlin** [comment]
Let's pull this into the next sprint!

**Comment by jennmalcolm** [comment]
We have outlined audiences and messaging in communications plan and will create new more discrete issues for follow-on work.
