### ISSUE TITLE
Training: Review development workflow using Docker setup

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2583]
We've gone through several dev workflows, but have spent less time on the Docker-specific workflow, especially given the constraints of ONRR workstations. We need more pairing/training/documentation about this process, and should identify any blockers that make this slower or more difficult.

**Comment by coreycaitlin** [comment]
We have more pairing time on the calendar later today to get @mentastc set up with Docker. We also updated the documentation in this PR #2613 

This issue will be done once @mentastc has Docker running successfully on his machine, and once we've verified that the workflow is functional on the DOI network.

**Comment by jennmalcolm** [comment]
Chris reports that Docker is set up and working on his machine.
