### ISSUE TITLE
Content updates: Alaska opt-in state information

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2585]
There are a number of content updates that need to be made in the Alaska opt-in contextual narrative.

- [Source file is here (limited access)](https://drive.google.com/drive/folders/1siHtT_1_rz4W4supWyYkPZuCzQooAGCu) — all changes should be tracked/highlighted in the Word doc.
- Most of these changes (if not all) will be made in [this file](https://github.com/18F/doi-extractives-data/blob/update_optin_state_data/_states/AK.md), at the path: `_states/AK.md`.
- Ideally, these changes would be made on the working branch `update_optin_state_data` or a sub-branch off that one, so we can preview them alongside the related data updates.

This is a great pairing opportunity for content-maintenance training — reach out to either @brentryanjohnson or me if you want to start by looking at it together.

**Comment by coreycaitlin** [comment]
Three broken links remaining — let's get those fixed before releasing this content.

**Comment by brentryanjohnson** [comment]
### Broken links:

- To learn more, see the APF Dividend Division’s annual reports or **financial history and projections (PDF) 404.**

- The Bureau of Indian Affairs recently changed this by establishing **Rule 25 CFR Part 151 404**

- Decommissioning and restoration activities, including **Decommissioning, Removal, and Restoration Regulatory Review (PDF) 404**

**Comment by coreycaitlin** [comment]
This is done with #2622 🎉
