### ISSUE TITLE
Update self-employment data

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2587]
We need to update [self-employment data](https://revenuedata.doi.gov/explore/#federal-disbursements) for 2016. Currently, the site is displaying the 2015 value when selecting 2016, but we're not charting it (because it doesn't exist). This figure [originates from BEA and must be calculated](https://github.com/18F/doi-extractives-data/wiki/Data-Catalog#self-employment).

![image](https://user-images.githubusercontent.com/32855580/34697252-1a85bbe4-f487-11e7-9af0-a828d180798e.png)

**Comment by brentryanjohnson** [comment]
I've provisionally calculated 805,500, but I would appreciate a confirmation if someone else has time to run the numbers.

**Comment by brentryanjohnson** [comment]
The process for pulling these numbers seems to have changed since [our documentation](https://github.com/18F/doi-extractives-data/wiki/Data-Catalog#self-employment) was written. For example, there doesn't appear to be a category for "extractive industries (21)," but rather a category called "Mining, quarrying, and oil and gas extraction" with three subcategories:

**Mining, quarrying, and oil and gas extraction**
- 201 Oil and gas extraction
- 202 Mining (except oil and gas)
- 203 Support activities for mining

It's advisable to rewrite the documentation when we confirm the new process is correct.

**Comment by coreycaitlin** [comment]
It looks to me like the [2017 NAICS table](https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart=2017) still has `21` as `Mining, Quarrying, and Oil and Gas Extraction`.

The BEA data notes that:

> The estimates of wage and salary employment for 1998-2006 are based on the 2002 North American Industry Classification System (NAICS). The estimates for 2007-2010 are based on the 2007 NAICS. The estimates for 2011 forward are based on the 2012 NAICS.

...so they seem to be crosswalking changing NAICS codes behind the scenes.

In _really_ confusing news, though, the BEA tables don't seem to use NAICS codes, exactly — instead, there's a column called `LineCode`, which seems to sort-of map to specific NAICS codes. In this case, I'm pretty sure that *LineCode 200 in the BEA tables = [NAICS code 21](https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart_code=21&search=2017%20NAICS%20Search)*.

And I also got 805,500 when quickly grabbing the numbers for 2016 👍

**Comment by brentryanjohnson** [comment]
Thank you, @coreycaitlin.

It appears some of the state self-employment data is withheld, but we're presenting it numerically as "0" (e.g. [Delaware](https://revenuedata.doi.gov/explore/DE/#self-employment) and [Rhode Island](https://revenuedata.doi.gov/explore/RI/#self-employment)). In the data, these states have 2016 values of `(D)`, which is defined the following way:

> (D) Not shown to avoid disclosure of confidential information, but the estimates for this item are included in the total.

This is somewhat related to #2641, in which we document the need to present withheld data as other than 0.

**Comment by coreycaitlin** [comment]
@brentryanjohnson Yep! that's documented in #1870

**Comment by brentryanjohnson** [comment]
Thank you, @coreycaitlin! I searched the issues but didn't find that one. :+1:
