### ISSUE TITLE
Add right-pointing caret to secondary links on how it works landing

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2592]
## Design
![image](https://user-images.githubusercontent.com/9259185/34798120-65b94f82-f620-11e7-8bf5-d752f0a3329f.png)

## Actual
![image](https://user-images.githubusercontent.com/9259185/34798138-787f12f0-f620-11e7-8c6e-5541d9ec0e82.png)

**Comment by coreycaitlin** [comment]
Closing this out — we'll open a new issue to address accessibility issues with these links.
