### ISSUE TITLE
"What's new" content is...not new

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2593]
I discovered a "[what's new](https://revenuedata.doi.gov/about/whats-new/)" page that hasn't been updated in quite some time. I'm not sure whether or where this is linked, as I haven't audited for a link yet.

I'm curious about the origin of this page...e.g., did it come out of a user need identified in research? Any ideas @coreycaitlin?

**Comment by coreycaitlin** [comment]
Closing in favor of #2424
