### ISSUE TITLE
Define a list of browsers and versions to support

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2596]
User experience in browsers such as I.E. is Not Good. (cf #2594, #2595 e.g.).

Which browsers do we support? Ideally we would have a list (based in our analytics), and set up a scheme to maintain it!

:)

**Comment by ericronne** [comment]
(#2417 catalogs some issues)

**Comment by coreycaitlin** [comment]
Next step: look at analytics and conduct some browser testing to get a sense of our baseline.

**Comment by brentryanjohnson** [comment]
## Browser analytics 
I've pulled together our analytics for the period of Nov. 1, 2017 to April 2, 2018. Here's the browser-share breakdown by percent:

- **Chrome**: 62%
- **Safari**: 17%
- **Internet Explorer**: 9%
- **Firefox**: 7%
- **Edge**: 3%
- **Opera mini**: <1%
- **SeaMonkey**: <1%

## Browser versions
- **Chrome**: all users greater than or equal to version 62.0.3202.62
- **Safari**: over 75% of users greater than or equal to 11.0
- **Internet Explorer**: 85% using IE11; 15% using IE7
- **Firefox**: over 80% of users greater than or equal to version 57
- **Edge**: all users version 15.15063 or greater

## Desktop and mobile
- **Desktop**: 82%
- **Mobile**: 12%
- **Tablet**: 6%

**Comment by brentryanjohnson** [comment]
We should discuss which browsers we can/should support. 

Internet Explorer is still used by ~10% of site visitors. To me, that's a significant enough share that we should consider addressing style issues for those users.

**Comment by jennmalcolm** [comment]
This looks like good list to me. Can you tell me what percentage of the users we would be covering with this list?
