### ISSUE TITLE
Style guide: Content review of documentation

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2597]
Review initial documentation, edit, add as needed.

**Comment by coreycaitlin** [comment]
Started some of this review/revision in #2591, but haven't tackled a full content edit yet.

**Comment by coreycaitlin** [comment]
Next step: @brentryanjohnson to read through and identify specific gaps and areas for expansion.

**Comment by jenniferthibault** [comment]
Closing this in favor of https://github.com/18F/doi-extractives-data/issues/2771 which outlines more about the user story
