### ISSUE TITLE
Incorrect scale for commodity

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2600]
I noticed an incorrect scale for the Helium bar chart under [Revenue-->federal land](https://revenuedata.doi.gov/explore/#federal-revenue) (bar chart; not megachart).

There are at least two issues:
1. The 2015 value is negative, but shows a sliver of positive value (this bug is captured in #2575).
2. The **scale is significantly off**, resulting in (for example) $20 appearing to be nearly _half_ of $2,934.

![helium](https://user-images.githubusercontent.com/32855580/34898700-453eb74e-f7a9-11e7-90a2-838e9d55f349.gif)

**Comment by brentryanjohnson** [comment]
The only other national chart scale that looks off to me is Clay. I'm going to spot-check state charts, too.
![clay](https://user-images.githubusercontent.com/32855580/35018904-bcb0f4a4-fad8-11e7-9a0e-816fc6a68989.gif)

**Comment by coreycaitlin** [comment]
Yeah, this seems broken. I bet this is an effect of how rounding works, especially for low numbers or outliers.

**Comment by msecret** [comment]
We think this might be related to a negative value in the chart messing up the total range of the chart, which would effect how the bars render.

I think a next step is to confirm that this is the problem by creating a fake chart by hand modifying the yml data.

**Comment by coreycaitlin** [comment]
Previously: #2321, #2320, #2119

**Comment by brentryanjohnson** [comment]
It looks like our 2017 federal revenue update made this scale issue a little worse. We should consider rolling this into an upcoming sprint.

![Incorrect scale for helium animated chart](https://user-images.githubusercontent.com/32855580/37167539-0a465212-22b7-11e8-95c1-86d8ada6da66.gif)

**Comment by jennmalcolm** [comment]
Possible solutions per Jeremia: add another floating bar for zero or remove negative numbers entirely.

**Comment by master12** [comment]
code is merged
