### ISSUE TITLE
Training: running a successful sprint

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2603]
Let's prep for getting Jennifer in the driver's seat on running NRRD's sprints!

This issue is done when:
- [x] we have time scheduled for some basic scrum training with Jennifer.
- [x] we've prepped and sent any materials needed in advance of the session(s).
- [x] we come out of the session(s) with Jennifer feeling ready to begin leading standup starting next sprint.
- [x] we capture any next actions in subsequent issues.

**Comment by coreycaitlin** [comment]
Our draft documentation about [how to run meetings is here (limited access)](https://docs.google.com/document/d/1O_QrOH3zLO1KH2ILjYTteo4qQilN4Oe2cXq4eYR4hm0/edit).
