### ISSUE TITLE
Style guide: Improve the process of running the style guide locally, and document

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2620]
As discussed in #2614, we should make it easy to run the style guide locally, and document how to do so.

**Comment by brentryanjohnson** [comment]
@msecret and I paired on this today, but we weren't able to get Fractal served locally on the ONRR machines. Fractal indicated it was successfully served, but the browser couldn't find it at the supplied localhosts.
```
Fractal web UI server is running!

 Local URL:      http://localhost:3000
 Network URL:    http://172.18.0.4:3000
 BrowserSync UI: http://localhost:3002
```

**Comment by brentryanjohnson** [comment]
Fractal is now serving up (along with Jekyll) on my machine on the `docker-styleguide-command` branch. Ports 3000 and 4000, respectively.

**Comment by jeremiak** [comment]
With #2625 getting merged, I'd say this is done.

I'm not sure who closes out issues/accepts them but I am currently assigned to this issue so I'm giving my 👍 to closing it.
