### ISSUE TITLE
Content audit

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2624]
It's time to conduct a content audit! A content audit is the process of qualitatively assessing our existing content. We'll inventory and evaluate the content against multiple criteria:

### Inventory
- URL
- File type
- Title 
- Description

### Assessment
- Keywords
- Word count
- Reading grade level
- Quality
- Priority for update
- Maintenance requirements
- Notes

It's a great time to complete a content audit as the project transitions from 18F to a team within the Office of Natural Resources Revenue. Additionally, following the U.S. withdrawal from EITI, it's important to review the content in the context of the [product visioning work](https://github.com/18F/doi-extractives-data/issues/2551) happening concurrently.

During this content audit, I will also endeavor to fix broken links identified in #2256.

**Comment by jennmalcolm** [comment]
@mentastc to review laws on NRRD to spreadsheet to help out

**Comment by brentryanjohnson** [comment]
Here's the [content audit worksheet](https://docs.google.com/spreadsheets/d/1aAjbQuLds4Q75Iq8xfQ4lQGgL9XPy4xv6tiHVkDk8xw/edit?usp=sharing) (limited access).
