### ISSUE TITLE
County choropleth map bug

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2626]
## Expected Behavior

- County maps should have choropleth behavior, with darker blues representing larger values and lighter colors representing smaller values according to the d3 scale applied to map.

## Actual Behavior

County maps are not behaving properly as choropleths in `dev` branch (and those recently branched off it). Counties with values for each map are light grey, but they are not shading properly according to their values (as indicated in the tables below each map).

![county choropleth map comparison between dev branch and production](https://user-images.githubusercontent.com/32855580/35642784-1597b426-0679-11e8-81a2-abbe7ed8d615.png)

**Comment by brentryanjohnson** [comment]
This appears to be a problem with numerous, if not all county maps, in `dev`.

![Montana chroropleth map bug](https://user-images.githubusercontent.com/32855580/35635245-a0f3abcc-0662-11e8-82e6-b3a8c5178cb5.png)

![Illinois choropleth map bug](https://user-images.githubusercontent.com/32855580/35635308-d2bd0dba-0662-11e8-963a-9170e8e953fa.png)

**Comment by jennmalcolm** [comment]
Next step: @msecret verify fix.
