### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2639]
## Expected Behavior

- Data and documentation links should load in a "document" icon
![Data and documentation link with icon](https://user-images.githubusercontent.com/32855580/35872035-a1375ed2-0b1a-11e8-8f37-7aa96e39b5c7.png)

## Actual Behavior

- "Document" icon isn't appearing

![Data and documentation link with missing icon in Firefox](https://user-images.githubusercontent.com/32855580/35833204-10b05372-0a85-11e8-9721-e5b6ab136b64.png)

![Data and documentation link with missing icon in Chrome](https://user-images.githubusercontent.com/32855580/35833226-2a9d1a18-0a85-11e8-89da-2908251e17b1.png)

## Steps to reproduce the behavior

- Clear cache and load any data page that contains "Data and documentation" link.

**Comment by brentryanjohnson** [comment]
I noticed a few more missing icons related to missing fontawesome fonts. It looks like our [How it works pages](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/dev/how-it-works/coal/) reference them under the "Get involved" subheading.

![icons missing on how it works pages](https://user-images.githubusercontent.com/32855580/35888810-ed84f3d4-0b4d-11e8-8e15-65409af86e5e.png)

**Comment by coreycaitlin** [comment]
We're tackling this by doing #2284
