### ISSUE TITLE
Change how withheld data is represented in county tables

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2641]
Withheld data at the county level still shows a numeric value of zero in the accompanying table. I think this could be confusing for users, because it implies there was no production. (Related to #2394) 

It might be better to do one of the following:

- Change the table output from the number 0 to "Withheld".
- Remove the table value output altogether, since the data is shown as withheld in two other places (below bar chart; right side of map)

![Gilsonite data in Utah](https://user-images.githubusercontent.com/32855580/35946034-241d011a-0c17-11e8-982b-0a85da1f4d00.png)

**Comment by coreycaitlin** [comment]
We also need a design for how to display withheld county data on the map itself. Two options:

- use a different color for withheld data (like gray or orange)
- or get data on which _range_ the withheld number falls into and use that color

**Comment by jennmalcolm** [comment]
For the table, either of Ryan's options will work, so @master12, do whichever is easier please.  For Corey's suggestion, we could explore getting the data range in the future, but for now, if we could implement a different color for withheld, that would be an improvement.
