### ISSUE TITLE
Confirm that the Makefile will work within docker & document steps to run

### ISSUE THREAD

**Issue by jeremiak** [18F/doi-extractives-data#2654]
The Makefile predates our move to docker and it has not yet been tested (or at least it is not documented) to work within Docker. We should:

- [ ] Ensure that the Makefile can be run inside of docker and generates the output as expected
- [ ] Document how to run the Makefile inside of Docker

I imagine that this would also likely close #2553 as it would mean that we are all working on a single platform (docker) and rely on it to handle cross platform differences.

**Comment by master12** [comment]
The makefile works in docker but not on windows. We will continue investigate solutions in another ticket. #2679
