### ISSUE TITLE
Investigate if Windows 10 Pro will help with Docker process

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2655]
We've been through a couple of rounds of Docker improvements #2630 #2296 #2625 #2351, but are still struggling with Docker implementation on Windows 7 machines. We're hoping that Windows 10 Pro will give us a better path forward.

**Comment by jennmalcolm** [comment]
Next steps: We are moving forward with IT to try to get Windows 10; should improve some of the issues

Still have build problem - Jeff trying one thing today then will pair with Jeremia for more options

**Comment by master12** [comment]
Windows 10 is needed to overcome the 260 char limit of Win 7. Docker VM will not provide us a powerful enough environment to run builds during regular day to day development. Windows 10 direct installation is needed and local administrator rights or similar raised level of rights locally is needed to debug, test and develop applications.

**Comment by jennmalcolm** [comment]
Closing this since we have determined that Windows 10 and local administrator rights will improve process and will pursue these options with ONRR IT.
