### ISSUE TITLE
Pursue dev environment improvements through ONRR IT

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2672]
We have determined that the best way to improve the development environment will be to get Windows 10 machines with local admin rights. The Windows 10 machines are in process, and we now need to push for local admin rights for the Innovation Design Team:

- [x] Document justification for local admin rights for Innovation Design Team
- [x] 18-F review and give input into justification
- [x] Send justification to IT
- [ ] Arrange meetings with ONRR IT, Innovation Design Team, and 18F developers, as necessary, to discuss

**Comment by alexpandel** [comment]
Hey @jennmalcolm - @jeremiak & I are done taking a pass at [the doc (limited access)](https://docs.google.com/document/d/1Zz2I3WOTpeY_ERt4eT1cYMcgZauG6NS6gpb5BhAOLoM/edit#), feel free to make any changes you see fit and forward on!

**Comment by jennmalcolm** [comment]
Thanks

Sent from my iPhone

On Mar 13, 2018, at 10:39 AM, Alex Pandel <notifications@github.com> wrote:

Hey @jennmalcolm <https://github.com/jennmalcolm> - @jeremiak
<https://github.com/jeremiak> & I are done taking a pass at the doc
(limited access)
<https://docs.google.com/document/d/1Zz2I3WOTpeY_ERt4eT1cYMcgZauG6NS6gpb5BhAOLoM/edit#>,
feel free to make any changes you see fit and forward on!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/doi-extractives-data/issues/2672#issuecomment-372688118>,
or mute the thread
