### ISSUE TITLE
Change "Downloads" links to "Download data"

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2676]
## Consider changing link copy

We should consider changing the utility and footer link microcopy from "Downloads" to "Download data." 

While we offer more than just data to download, my hypothesis is that most users want to download data. The other "downloadables" are effectively support materials for the data. Additionally, "Downloads" does not (by itself) communicate anything at all to the user about what they can expect to find if they follow the link.

#### Now
![utility menu with glossary and downloads links](https://user-images.githubusercontent.com/32855580/36759632-e5256f5e-1bcc-11e8-953b-676eabec462b.png)
#### Proposed
![utility menu with glossary and download data links](https://user-images.githubusercontent.com/32855580/36759584-bd9bbede-1bcc-11e8-9349-9ecc45fd7d9a.png)

#### Now
![Footer downloads link](https://user-images.githubusercontent.com/32855580/36759804-771e6672-1bcd-11e8-8de3-e07abc42b913.png)
#### Proposed
![Footer download data link](https://user-images.githubusercontent.com/32855580/36759827-8fee0964-1bcd-11e8-8156-813882fe6fc2.png)

**Comment by jennmalcolm** [comment]
I like this change. I think it's clearer, and we have had some user feedback (especially with the Stats site consolidation), that it isn't easy to find where they can get the data.
