### ISSUE TITLE
Add PRA documentation to research guide

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2680]
Let's get some of the documentation we pulled together for #2383 related to working within PRA regulations out of Google Docs and into our research guide in the research branch.

**Comment by alexpandel** [comment]
Adding @jenniferthibault to this one too, since we're working on incorporating this into the onboarding guide!

**Comment by jenniferthibault** [comment]
We  pulled this out of Google docs and incorporated this into a new wiki page about [What you need to know about doing design and research in the federal government](https://github.com/18F/doi-extractives-data/wiki/What-you-need-to-know-about-doing-design-and-research-in-the-federal-government#research-with-members-of-the-public) This page  will also be cross-referenced from the onboarding docs.  Closing this issue
