### ISSUE TITLE
Blog: outline a post about the NRRD transition work for the 18F blog

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2683]
Let's get started framing out a blog about our work together!

This issue is done when:

- [x] we've figured out the audience & goal for the post
- [x] we've sketched out a rough outline
- [x] we've captured next steps in a new issue for next sprint

**Comment by alexpandel** [comment]
@brentryanjohnson we can collab on this [here!](https://docs.google.com/document/d/1I2MIw3Y97rmKc28ztCtjX-FnaK1BHHqrzJRgNkF4G3Y/edit) (limited access)

**Comment by brentryanjohnson** [comment]
:point_up: @alexpandel I think we've completed the tasks for this one; should we close?

**Comment by alexpandel** [comment]
yass, good call!
