### ISSUE TITLE
Add Oil Shale to Revenue Table

### ISSUE THREAD

**Issue by mentastc** [18F/doi-extractives-data#2687]
##2628 Issue is related, this is to fix two things. 

1. Add CY in front of 2017 where it appears on the visualized revenue data sets.

2.  Oil Shale is a commodity that should appear in the table but doesn't please add it to the needed tables (national and whatever states that have oil shale rents). I would add in the Oil and Gas Section of the table.

**Comment by brentryanjohnson** [comment]
@mentastc Let's chat this week about the CY addition. I'm not sure users will know what that abbreviation means, and it might cause confusion.

**Comment by jennmalcolm** [comment]
I agree with Chris that we need to just add the Oil Shale revenues into the Oil & Gas number.

**Comment by jennmalcolm** [comment]
Separate issue #2725  created to address suggestion to add CY to years. This one should just address number two in original description.

**Comment by master12** [comment]
Starting reviewing the code

**Comment by master12** [comment]
pull request created
