### ISSUE TITLE
Blog: get post published on 18F blog

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2689]
Building on #2688, let's get this sucker published!

This issue is done when:
- [x] we've gotten the draft to a place that we/18F feels 👍on
- [x] we've figured out whose approval we'll need from ONRR to get the post published
- [x] we've gotten approval from ONRR (Jennifer & Judy)
- [x] we've gotten approval from 18F
- [ ] post is released on blog!

**Comment by alexpandel** [comment]
@brentryanjohnson, updated draft back from the 18F blog team [here (limited access)](https://docs.google.com/document/d/1I2MIw3Y97rmKc28ztCtjX-FnaK1BHHqrzJRgNkF4G3Y/edit?pli=1#) — let me know what you think!

**Comment by alexpandel** [comment]
FYI @brentryanjohnson, I made some good progress on this today; still have about an hour's worth of editing I want to do tomorrow, but I'd welcome your eyes at any point, and feel free to jump on any of the TO-DO tasks I highlighted for myself throughout the post (especially taking a knife to the intro, I'm terrible at intros and conclusions 😬 )

**Comment by alexpandel** [comment]
This is now waiting on @jennmalcolm & @usEITI's feedback & approval 🎉 @jennmalcolm I assigned you to the card while we're waiting on your review, but once you feel good about the draft, feel free to assign this issue back to me and I'll move forward with getting it published 🚀

**Comment by jennmalcolm** [comment]
I like it. I added one word and one comment.

**Comment by alexpandel** [comment]
Awesome, thanks @jennmalcolm! Judy had also taken a look, so I just added this to 18F's blog queue, so now we're just waiting on their review/edits/approval, and then we should have a publication date set, woop woop!

**Comment by alexpandel** [comment]
@FYI @brentryanjohnson, we got edits back from Andre today — I'm happy to dig into them on Monday, but if you want to take a look before then, go for it!

**Comment by alexpandel** [comment]
We've got a date! This will be published on 18F's blog on 5/1  🎉! @jennmalcolm, would you prefer that we close this issue now, or wait until the post is actually published?

**Comment by jennmalcolm** [comment]
Let's close it now since we have a date.

**Comment by alexpandel** [comment]
woo hoo! I'll drop the link in here once it's live for posterity, but closing for now!

**Comment by alexpandel** [comment]
FYI, this is now live! https://18f.gsa.gov/2018/05/01/lessons-from-an-18f-product-transition/ 18F will tweet/promote it tomorrow 🎉
