### ISSUE TITLE
Define and create viable dev environment for Windows 10 government issued machine

### ISSUE THREAD

**Issue by master12** [18F/doi-extractives-data#2701]
Create dev env setup instructions
Clean up old or outdated files

**Comment by master12** [comment]
Write of dev environment options done:

https://docs.google.com/spreadsheets/d/1lRbiv3TteyBaL24Ay_P3iFh66ZzUtYGUEFZoDVVoX44/edit?usp=sharing

**Comment by jennmalcolm** [comment]
Thanks for the options document. I will close this issue as we have started to obtain the rights for the Innovation Specialists to be able to use the third option.
