### ISSUE TITLE
Define data management option for website

### ISSUE THREAD

**Issue by master12** [18F/doi-extractives-data#2702]
What tech do we use?
Plan to implement

**Comment by master12** [comment]
Was successful in getting the Makefile to run on Windows using the Windows Linux Distribution. So this can be an option  still for ONRR.

**Comment by master12** [comment]
Investigating the use of Google Sheets / App Script to be a more user friendly tool.

**Comment by master12** [comment]
Write up of options to review is done:


https://docs.google.com/spreadsheets/d/18zSGmTHYIzvDQmgofR3Ome4bKfmmw09cCaKA6QqJdoc/edit?usp=sharing

**Comment by jennmalcolm** [comment]
Thanks. We should pilot the Google Apps process with our new Disbursements design in the near future.
