### ISSUE TITLE
Define rough comms strategy for NRRD

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2703]
Let's start thinking about the audiences we need to reach to grow the site's impact (both in terms of stakeholders and users).

This issue is done when:
- [x] time is set aside for a discussion about comms strategy
- [x] we've defined the priority audiences for NRRD 
- [x] we've identified the key messages we want to convey to each priority audience, and via what channel
- [x] we've identified the next steps we'll need to take to reach those folks

**Comment by alexpandel** [comment]
Nice work today @jennmalcolm @mentastc @brentryanjohnson! I'm gonna remove myself from this task and leave it to you @jennmalcolm to decide who will take the next steps on this, but feel free to loop me back in if you need any help, have questions, etc!

**Comment by jennmalcolm** [comment]
Thanks, Alex. @mentastc has agreed to work on our next steps.
