### ISSUE TITLE
Change chart captions for negative values

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2732]
Let's rewrite the sentence based on conditional logic denoting a negative value. Here are some options:

## Draft options

- [ ] ONRR adjusted revenue for the production of `commodity` on federal land by `-$value` in `year`.
- [ ] Overpayment for the production of `commodity` on federal land led to an adjustment of `-$value` in `year`.
- [ ] Revenue for the production of `commodity` on federal land was adjusted by `-$value` in `year`.
- [ ] Revenue for `commodity` was adjusted by `-$value` in `year`. This is usually because of overpayment in a previous year.
- [ ] In `year`, `commodity` production on federal land yielded `-$value` in federal revenue.

## Examples

![revenue prototype one](https://user-images.githubusercontent.com/32855580/37986378-24e95314-31b0-11e8-85c7-8b2c83cbad6c.png)

![revenue prototype two](https://user-images.githubusercontent.com/32855580/37986247-cea6dd32-31af-11e8-9018-5aa91e1035f8.png)

**Comment by brentryanjohnson** [comment]
Thank you, @jennmalcolm.

We have limited space for these captions, so we may need to continue to work on it and see if we can edit it down a bit. Otherwise it breaks our layout to accommodate the additional text. 

I'll see if I can but it down a bit and still retain meaning and context.

![broken template due to amount of caption text](https://user-images.githubusercontent.com/32855580/37990165-4e3a149c-31ba-11e8-977c-c47606053fb0.png)

**Comment by brentryanjohnson** [comment]
Perhaps we can call out that the data is accounting year in the intro text (or somewhere else, since it applies to each chart in the series).

Here's another option, edited down a bit more:

> Likely due to overpayment in a previous year, `commodity` production on federal land yielded `-$value` in `year`.

![prototype chart of negative value and language for a commodity](https://user-images.githubusercontent.com/32855580/37990672-d521a29e-31bb-11e8-8b76-6c41bd457080.png)

Let me know if we're getting closer, @jennmalcolm.

**Comment by jennmalcolm** [comment]
Yes, I think that's better. I'm fine with the accounting year being in the intro. I just think that's important for truly understanding that this isn't just a reporting error. I'm wondering if we need the word revenue in the end of the sentence. Just an idea, and if it messes with the space too much, we can just go with your last suggestion.

**Comment by brentryanjohnson** [comment]
Adding "of revenue" breaks the layout again, even with a relatively short commodity name like "helium". I'll keep working with the language, @jennmalcolm.

![content prototype](https://user-images.githubusercontent.com/32855580/38054100-c821c3e2-328a-11e8-9441-0ad5f55a66b5.png)

**Comment by brentryanjohnson** [comment]
## Two more options

Here are two more options that fit the caption container.

- Revenue for helium was adjusted by -$784 in 2017, probably because of a previous overpayment.
- Production of hot springs yielded -$784 in 2017 revenue, probably due to a previous overpayment.

![helium chart](https://user-images.githubusercontent.com/32855580/38060962-004b3b06-32a2-11e8-8c40-526a766a60ce.png)

![helium chart](https://user-images.githubusercontent.com/32855580/38061059-632ce1fc-32a2-11e8-9d6b-0d1e6689a4c3.png)

## Longer names and values

We will run into layout problems if we have a large negative value for a commodity with a longer name, such as hardrock minerals.

![hardrock minerals chart](https://user-images.githubusercontent.com/32855580/38061175-23851cd0-32a3-11e8-963e-2bb33726626a.png)

![hardrock minerals chart](https://user-images.githubusercontent.com/32855580/38061120-d1ccd2de-32a2-11e8-9fd3-811dd9fdbd72.png)

## Explaining negative values somewhere else
I'd certainly prefer to explain the negative values in context, but we can consider explaining them elsewhere, perhaps in How it works. 

Or we could explain in context using the glossary. It gets a little messy, though, with the number of styles colliding in the caption. But it's the only option I've landed on so far that can handle the combination of long commodity names and large values.

![caption with adjusted as glossary item](https://user-images.githubusercontent.com/32855580/38061636-d76f2460-32a4-11e8-85f1-957a201b1848.png)

What do you think, @jennmalcolm and @mentastc?

**Comment by jennmalcolm** [comment]
I like the second option (Production of hot springs yielded -$784 in 2017 revenue, probably due to a previous overpayment), but I am wondering why it says hot springs under the helium chart. Aside from that, let's go with that wording if @mentastc thinks it's ok too.

**Comment by brentryanjohnson** [comment]
@jennmalcolm I was prototyping different commodity names in the same caption to see how the length of each affected the layout. I was just prototyping in the browser, so hot springs was never affiliated with the helium chart on the actual site.

**Comment by jennmalcolm** [comment]
Ok, thanks.

**Comment by brentryanjohnson** [comment]
@master12 Here is the winner:

> Production of `commodity` yielded `-$value` in `year` revenue, probably due to a previous overpayment.

I'll create a new issue for us to work this in.
