### ISSUE TITLE
Update production intro paragraph

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2735]
Our [production intro paragraph](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/calendar-year/explore/#production) includes specific year and data references. We should consider abstracting these references so they are either (1) data-driven references that will update when our data is updated or (2) omit specific data references and generalize the content.

> The United States produces more natural gas and oil than any other country, and ranks second in the world for production of coal. The U.S. also ranks second in the world for renewable energy production, with a total of 9.56 quadrillion BTUs of renewable energy production in 2015.
> 
> Among nonenergy minerals, the U.S. ranks fifth in the world for production of gold (200 metric tons) and copper (1.25 million metric tons), and ninth for iron (56 million metric tons). Learn more about natural resource production in the U.S.

**Comment by jennmalcolm** [comment]
Yes, we should update this, and data driven references would be nice. We should discuss removing the US's world-wide production rankings. Since we don't have other countries' production data on our site, I don't know that the ranking should be within the scope of our intro.
