### ISSUE TITLE
Plan for Design Studio 

### ISSUE THREAD

**Issue by qmanderson1** [18F/doi-extractives-data#2742]
Define Goals/Outcomes for the Design Studio. 

Flesh out an agenda for the Design Studio to be held on April 19th.

**Comment by bpdesigns** [comment]
- [ ] Define Goals/Outcomes for the Design Studio.
- [ ] Create timeline and list of activities for the day
- [ ] Flesh out an agenda for the Design Studio to be held on April 19th.

**Comment by bpdesigns** [comment]
Agenda completed and reviewed with @jennmalcolm
