### ISSUE TITLE
Review design onboarding documentation

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2744]
Prepare to onboard a new UX designer to the NRRD team by reviewing the existing onboarding resources, and making improvements where necessary.

This will help the new designer (and future team members) get up to speed, and feel prepared to start contributing to the project more quickly.

As a new team member myself, I'll use my experience as a starting point for finding the gaps. Process outline:
- [x] Review the existing onboarding docs & try out the process currently in use by the NRRD team
- [x] Make notes in this issue about observations from this process, potentially including changes to existing resources, adding new or different resources, or organizing resources in different formats.
- [x] Move findings to new issues to be addressed individually during this sprint

**Comment by jenniferthibault** [comment]
Here's a collection of questions and thoughts that came up as I've been onboarding this week:

## General
- **Is there a specific place to start?** Things I should definitely read vs things that are better for later? Would be nice to have a guided experience, like an outline or such to help me know where to start
- **The product framing document is super helpful., let's make sure folks find it first** I found that early in the wiki, but if I hadn’t tried to look in the wiki I may have found it later. Would be helpful to make sure folks find that first (very related to point 1)
- **ONRR + 18F background** There is some project background info in 18F internal team documents that I found helpful and not at all worthy of being hidden away. Might be helpful to pull out 
- **Who are the team members and what are their roles?** This was handled really well by a round of introductions at the first meeting I attended, which was a sprint planning meeting
- **What are the regular meetings for this project and how do they work?** Different teams have different practices, so even though I’ve been to a sprint planning before, I wasn’t sure how it works on this project. This could also potentially be covered in a few quick minutes at the beginning of each new meeting, but it would feel even better to get some sort of briefing _before_ that, so the new team member knows what to expect when showing up, and can prepare, if relevant/able. Maybe there’s a day 1 meeting between the PM and the new team member where this (+team roles, background) is all covered together, and then just a quick audible reminder at the beginning of the first sprint meetings.
- **What tools does the team use?** If some of the tools are new to me, where should I start learning about them?
- **What's on the horizon?** Is there a project road map? I did find [this one](https://app.mural.ly/t/gsa6/m/gsa6/1517848877792/f45f99f44093ff10a347988b4fbabff36221e315) linked from the shipping notes, I think.
- Maybe a bug:  On the wiki, the Information architecture page  listed in the nav doesn’t exist: https://github.com/18F/doi-extractives-data/wiki/Information-architecture

## Design-specific
- **Where is this style guide you speak of?** I found a few mentions of the style guide, but nothing that linked to it. That should be an easy fix :)
- **Design principles, FTW!!** The style guide also hold the site’s design principles on its home page, which could get called out specifically for design onboarding
- **An archived piece of content that's very useful** The “lLttle rules to designing with data” writeup is a super useful and very specific resource, but kind of buried. I’d pull this into a design-specific resource list
- **An intro to our research documentation** Finding the user research branch was easy because it was it’s own link in the wiki table of contents, but it took me a while to realize it was a GitHub branch, which I hadn’t seen before. If I was new to GitHub, I probably wouldn’t have understood entirely, but either way would have liked a bit of an intro to where it’s kept and how it’s organized, then a straight link to the README for the deep dive, which I nearly missed because I got caught on the folders of research.
- **Tools** Are there design-specific tools needed?
- **Design files** Are there high-fidelity design files, or design files used to build static prototypes? If so, where do they live, who has access to them, how is version control managed?

_______

@qmanderson1 and @bpdesigns , could you take a look and let me know if any of this squares up with your recent experiences, or if there's anything you experienced that I haven't hit here?

**Comment by jennmalcolm** [comment]
Yes, could you add this as a Wiki section please?

I think that is a good, workable format, and I have done a similar thing in other groups. I was planning on assigning her a buddy anyway. I would like @mentastc to be her NRRD-buddy as I will already be working with her on supervisor and DOI/ONRR-realted things, and I want to get her interacting with other team members more too. @mentastc are you up for that? If so, read through Jen's document and let us know if you have questions before next week.

**Comment by jenniferthibault** [comment]
Will do! @jennmalcolm should I split the work of adding it to the wiki into another issue, or keep it as part of this one? Not sure if this team has a preference for more smaller issues, or fewer issues overall, but glad to do either.

**Comment by jenniferthibault** [comment]
Sounds great, will do!

**Comment by jenniferthibault** [comment]
Breaking out to #2761
