### ISSUE TITLE
Get 18F travel approval for design studio

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2746]
In order for 18F folks to travel, we need explicit client approval. This task is done when:

- [x] we've figured out exactly who from 18F need to travel
- [x] anyone traveling has reserved (but not submitted for authorization) their travel in Concur
- [x] anyone traveling has filled out [this spreadsheet (limited access)](https://docs.google.com/spreadsheets/d/1zffo_i0bSIU8YzTDOO5pME71OYMyHK6o7MK4Yzgg2jk/edit#gid=1000729692)
- [x] we've gotten explicit approval from Jennifer (or Judy?) for folks' travel, and have forwarded it to the 18F travel team (according to [these instructions](https://handbook.18f.gov/travel-guide-1-authorization/#billable-travel-approval))
- [x] anyone traveling has submitted their travel for approval via Concur
- [x] tickets are successfully issued for anyone traveling

**Comment by alexpandel** [comment]
@bpdesigns you've got this all squared away for your travel coming up, yes? if so, feel free to close this one!

**Comment by bpdesigns** [comment]
All set! Was just waiting on getting my travel card
