### ISSUE TITLE
Reformat dollar variables

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2753]
Related to #2729 and #2749.

## Data values
I'm replacing manually curated data with variables that reference our `_data` values. This works fine, but some of the values are too verbose for efficient reading in context. For example:
![Full dollar value on tribal summary](https://user-images.githubusercontent.com/32855580/38379971-3dfd0a7c-38b7-11e8-98b1-1f39acb28c04.png)

## Current filter(s)
I resolved this issue in PR #2749 by applying a filter to divide the value by 1 million and then round the result. This achieves the desired readability outcome, but introduces two new issues:
- The unit of "million" is hard-coded. If the dollar amount next year is (hypothetically) $1 billion or more, the unit will still be correct, but it will be difficult to read and potentially confusing (e.g. $1,200 million).
- We now have a round integer, but there is a difference of $211,357 between the full value and our rounded value. This is a significant amount of money to round away, and it could be more in coming years depending on the origin value.

## Desired filter
Ideally, we'd have a custom filter that queries the length of the value, adds the appropriate scale unit (e.g. "million"), and produces a rounded float value at one decimal point if the value is $1 million or more.
 
Desired example result: $675,788,643 --> **$675.8 million**

**Comment by el-mapache** [comment]
Looking into this as I type!
