### ISSUE TITLE
Information architecture page of the wiki does not exist

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2758]
## Expected Behavior
When I click the link to the page titled "Information architecture" in the wiki table of contents, I will be taken to a page full of information

## Actual Behavior
I am prompted to create a new page called "Information architecture"
![screen shot 2018-04-09 at 9 44 03 am](https://user-images.githubusercontent.com/11636908/38501296-a03920f6-3bda-11e8-96cd-eefbb8b8fd19.png)

## Steps to reproduce the behavior
- View the wiki: https://github.com/18F/doi-extractives-data/wiki
- Click "Information architecture" in the table of contents on the right hand side

**Comment by brentryanjohnson** [comment]
Thanks for identifying this issue, @jenniferthibault. I believe this link is intended to go to the [Sitemap](https://github.com/18F/doi-extractives-data/wiki/Sitemap), which contains an archive of IA notes along with an updated sitemap. We should probably change the name of the link to reflect what this actually is.

I have changed the link to go to the sitemap for now.
