### ISSUE TITLE
Institute re-vamped GitHub labeling system

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2779]
We need to review our issues in GitHub and label them according to the new system documented here: https://github.com/18F/doi-extractives-data/wiki/Github-Labels

For this issue to be done, the following needs to be accomplished:

- [x] New labels created in GitHub

- [x] Old labels that will not be used any longer, deleted in GitHub

- [ ] All issues reviewed, and appropriate labels from new system applied

**Comment by brentryanjohnson** [comment]
This is ongoing, but I'm going to close since we'll be applying the new labels as we go.
