### ISSUE TITLE
Add withheld caption to county data tables

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2793]
@master12 has fixed our major county table bug in #2792, but we should look into another minor bug related to captions.

## County table data captions
Our county table rows have a caption revealed on a click event, but they're currently only working for counties for which there is data in the selected year.
![county table data caption](https://user-images.githubusercontent.com/32855580/38889654-376495d2-4234-11e8-98ea-f742a3e6853e.png)

## County table withheld captions
In [`display-federal-production-county.html`](https://github.com/18F/doi-extractives-data/blob/dev/_includes/location/display-federal-production-county.html), it appears there is an alternative caption available if the data is withheld. For some reason, this caption isn't revealed on click. We should look into why this caption isn't active on click.

```              data-witheld="false">
              <span class="withheld" aria-hidden="true">
                Data about {{ product_name | downcase }} extraction on federal land in {{ county[1].name }} in <span data-year='{{ year }}'>{{ year }}</span> is withheld.
              </span>
              <span class="has-data">
                <span data-value='{{ product_volume }}'>{{ product_volume | intcomma }}</span> {{ units }} of {{ product_name | downcase | suffix: units_suffix }} were produced in {{ county[1].name }} in <span data-year='{{ year }}'>{{ year }}</span>.
```
![county withheld row](https://user-images.githubusercontent.com/32855580/38889888-cff48348-4234-11e8-8bbc-b109e3d296d1.png)

**Comment by jennmalcolm** [comment]
Fixed by #2842
