### ISSUE TITLE
Integrate feedback into onboarding checklist

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2795]
So that the onboarding process can be even better for the next team member, integrate learnings and feedback from it's first round of use into the master template in the wiki: https://github.com/18F/doi-extractives-data/wiki/Onboarding-checklist

**Process observations**
- In order for the new team member to be able to check items off the task list, they need to be part of the GitHub group with permissions on repo. That information was provided later in the checklist, and should be moved up in the list to be an early step.

**Feedback from @mcharg via https://github.com/18F/doi-extractives-data/issues/2778#issuecomment-382426675** 
- I wouldn't separate out the design principles form the rest of the style guide. I read through the whole style guide when I got to the design principles task, so then I thought the second item for the style guide was a duplicate.
- I would group the items around NRRD research and conducting research in the government, since a lot of the questions that popped up in my head when I was reading through the NRRD research part were answered when I got to the government research part.

**Comment by mcharg** [comment]
The listserv instructions should also be updated.  This is what's in the instructions when you are added to the list.

"If you  know someone who  would be a good  addition to this  list, please
have   them   email   Jean    Fox   (fox.jean@bls.gov)   or   Jon   Rubin
(Jonathan.Rubin@cfpb.gov)."

**Comment by jenniferthibault** [comment]
Updated the checklist with all of this feedback, thanks @mcharg !
https://github.com/18F/doi-extractives-data/wiki/Onboarding-checklist

Closing this issue for now, but feel free to open a new issue for more changes in the future
