### ISSUE TITLE
Develop strategy for EITI content

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2799]
Related to #2722, #2774, and #2799

Develop a strategy for EITI-era content that will no longer be maintained.

- [X] Conduct content audit to inventory EITI-era content researched and developed by the USEITI Independent Administrator (Deloitte)

- [x] Determine which EITI-era content categories (e.g. case studies) are practical to maintain in the absence of the Independent Administrator

- [ ] Determine which EITI-era content categories provide demonstrable value to current and prospective NRRD users

- [ ] Create content calendar for content categories we will retain and actively curate

- [ ] Create archive for EITI content that will no longer be maintained and develop unobtrusive design pattern to surface this content for users that wish to access it

**Comment by brentryanjohnson** [comment]
@mcharg I tagged you in this issue with the hope you can pair with me on prototyping some ideas. :)

**Comment by mcharg** [comment]
@brentryanjohnson 
I took a look at the content that's flagged as Yes to be archived and came up with 3 levels where the note about archiving can happen.

1. Page Level https://hp1ins.axshare.com/#g=1&p=archived_page
2. Section Level  https://hp1ins.axshare.com/#g=1&p=archived_section
3. Document Level https://hp1ins.axshare.com/#g=1&p=archived_document

I added some columns to the spreadsheets to help track which level each piece of content should have notes at.

General rules
1. If everything on a page is archived, note at page level. (i.e. Executive Summaries)
2. If everything in a section is archived, note at section level.  (i.e. How It Working > Accountability)
3. If it's just one link in a section, only note at page level when going to that link. (i.e. Abandoned Mine Land Reclamation Program)
4. If it's only a document that's being archived, note at document level. (i.e. TBD, I thought we had an example of this and then found out the whole page is actually listed to archive)

**Comment by brentryanjohnson** [comment]
These are great, @mcharg!

Is there supposed to be a leading icon on these banners? If so, they're missing for me.
![archive banner](https://user-images.githubusercontent.com/32855580/39766816-0e4e7a20-529a-11e8-9c47-2f3e9eef78be.png)

**Comment by mcharg** [comment]
@brentryanjohnson The icon should show up now.

**Comment by brentryanjohnson** [comment]
EITI content archiving recommendations: [Google Doc](https://docs.google.com/document/d/1guEvQ2jTgASiG7c9nrvuR9oDsiu1xZayoE7RooqflXk/edit?usp=sharing) (limited access)

**Comment by jennmalcolm** [comment]
@brentryanjohnson the remaining three check boxes could each be their own issue. In order to facilitate sprint-sized issues, could you please make these into three separate issues and then reference and close this one?

**Comment by brentryanjohnson** [comment]
Closing in favor of #2862, #2863, and #2800.
