### ISSUE TITLE
Create (internal user focused) Disbursements Prototypes to Test 

### ISSUE THREAD

**Issue by qmanderson1** [18F/doi-extractives-data#2802]
Create 2-3 Prototypes to test that focus on the user needs of internal users by implementing the table and filtering features as discussed in the Design Studio. 

We'll know we're done when: 
* [ ] We have 2-3 prototypes that are ready to be tested on users

**Comment by mcharg** [comment]
Is this one done?  I pulled both of your prototypes into the Axure file.
https://m13r6x.axshare.com

**Comment by bpdesigns** [comment]
Yes. I think this good to close.
