### ISSUE TITLE
Create (external user focused) Disbursements Prototypes to Test

### ISSUE THREAD

**Issue by qmanderson1** [18F/doi-extractives-data#2803]
Create 2-3 Prototypes to test that focus on the user needs of external users by implementing the table and filtering features as discussed in the Design Studio.

We'll know we're done when: 

* [ ] We have 2-3 prototypes that are ready to be tested on users

**Comment by jennmalcolm** [comment]
@qmanderson1 and @mcharg, could you detail more about how this is different from #2802 since it references the same needs (table and filtering features)?

**Comment by qmanderson1** [comment]
@jennmalcolm Ben and I met with Shannon and decided we would create 2 sets of prototypes. One set will focus on internal user needs/stories and the other will focus on external user needs/stories. There's some overlap but Ben and I are taking on internal user focused prototypes and Shannon is taking on external user focused prototypes.

**Comment by qmanderson1** [comment]
@jennmalcolm No problem, sounds like a plan!

**Comment by mcharg** [comment]
Prototype link: https://m13r6x.axshare.com

**Comment by mcharg** [comment]
I think the prototypes are good for testing.
https://m13r6x.axshare.com
