### ISSUE TITLE
Add tab component to style guide

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2814]
## Expected Behavior
All interface patterns and components used (and re-used) on the website will be represented in the style guide, and patterns on the website will be used consistently.

## Actual Behavior
The Tab component exists on the website, but is not included in the style guide. Found on the following pages, with slightly different styles:
https://revenuedata.doi.gov/explore/#federal-revenue
https://revenuedata.doi.gov/how-it-works/offshore-oil-gas/

![screen shot 2018-04-20 at 7 32 19 pm](https://user-images.githubusercontent.com/11636908/39316924-5eb2eb32-4948-11e8-9805-1618189a1af3.png)
![screen shot 2018-04-20 at 7 32 55 pm](https://user-images.githubusercontent.com/11636908/39316925-5ec35652-4948-11e8-85ef-f5dc98e9c2f6.png)

There is also a third tab style seen on these pages:
https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2016/
![screen shot 2018-04-20 at 7 20 36 pm](https://user-images.githubusercontent.com/11636908/39370973-502aab2e-4a0e-11e8-95a4-1fb88f7b76d7.png)

Criteria for completion:
- [x] Add styles as a new component in the styleguide, with examples and documentation around when and how to use them

**Comment by jenniferthibault** [comment]
Related to #2768 and #2769

**Comment by jenniferthibault** [comment]
In #2819 I discovered that the toggle was actually another tab in disguise. Editing the original description to add it in.

**Comment by jennmalcolm** [comment]
Related to #2878. Determine if it should still be on site and then how to include tab that behaves as toggle in style guide.

**Comment by jenniferthibault** [comment]
We moved the master tab style into the style guide in #2885, and through discussion with @brentryanjohnson determined that the tab/toggle mystery component was actually functioning more as a subpage navigation. We separated that into a second PR, #2919 , and added it to the style guide as well.

One that PR is merged, this issue can be closed

**Comment by jenniferthibault** [comment]
Both PRs are merged, so closing this issue
