### ISSUE TITLE
Initial research and preparations for outreach efforts

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2816]
In the next two weeks, we can take the following actions to prepare to fully dive into our outreach efforts when Shawnique returns
- [x] Go through market map and see what would be useful.
- [x] Add any additional list of relevant interest groups,  etc to the market map
- [x] Start looking into potential opportunities to feature NRRD on DOI’s outreach channels (social media, etc) 
- [x] Check analytics to see where people are going, and what they’re looking for

**Comment by mcharg** [comment]
I pulled in the contacts from the user research participant pipeline spreadsheet and did a Google search and added a few new places that have cited https://revenuedata.doi.gov/.

**Comment by mcharg** [comment]
Got access to analytics.  Not sure we're going to learn anything relevant to this from them.  We don't have data about where users are coming from or going to off the site (at least that I can find) and, since most of the data is on the single explore page, we don't have a breakdown of what on that page users are looking for.

**Comment by jennmalcolm** [comment]
@mcharg, can you look into adding tag manager to hopefully provide us more useful information in the future?

**Comment by jennmalcolm** [comment]
Thanks @mcharg, if you look into it, and it seems difficult to implement, we have a contact at DOI who may be able to help. Let me know what you find.

**Comment by mcharg** [comment]
@jennmalcolm Just got to the part in the tag manager training video that says that each agency has to purchase Tag Manager and it's separate from DAP.

**Comment by jennmalcolm** [comment]
Ok @mcharg thanks for your research thus far. I will see what I can find out about how we could purchase tag manager. If you have other ideas on different analytics tools we should look at, we can do that too.

**Comment by brentryanjohnson** [comment]
@mcharg and @jennmalcolm, I've been able to create _some_ custom reports in DAP, without their consultation. This may still be too limiting, but I'm happy to walk through what I've configured, if you're interested.

![Natural Resources Revenue Data analytics](https://user-images.githubusercontent.com/32855580/39785544-6eb15928-52d1-11e8-9e99-e23bbe8c301e.png)

![Natural Resources Revenue Data analytics](https://user-images.githubusercontent.com/32855580/39785596-9b0d774a-52d1-11e8-9857-4ce61933344e.png)

**Comment by jennmalcolm** [comment]
@brentryanjohnson yes, I'm interested. Could you set up a time that will work? We can take that opportunity to discuss the options with tag manager.

**Comment by jennmalcolm** [comment]
yes @mcharg please create a separate issue for implementing tag manager. I think I've muddied this issue up enough. Thanks.

**Comment by mcharg** [comment]
Figured out how to look at the service provider.  Given that most of our users are accessing the site from work, it's a good indicator of where are users are coming from.
[Analytics DOI Agency Profile NRRD Portal 20171101-20180430.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46c99a9b2f9b97a08cfaff678b74b0b52e432970304493397f83ea24ba0255333d2b5ecc1e1a1b15a0e98b2ba7b13d718a5d16efd16c5774c23e11bea4905ffd5ee075d80b97bcae8f49c1bd6924b28edc496c16561d8cf65d35a6914e9e5ff559fd5f17f54d623cbb2f7c29058614672d6c6d27aefeda5e8e8165a7be182651daae.pdf)

**Comment by mcharg** [comment]
Here's a good snapshot of the segments for the service providers I'm easily able to put into a segment.
![Users by Segment.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46dd879f3191c3ab96a98c46a350f59a3d046b313916ac217586f76ae5002e545e0a1aad145d0c42aef1da2ea3bf3c708c540ebbd66e4d68d47f40f2ecdd42e64bef62994597b4bc804dc5ea382dee8d8b4c3d1606119bb2.PNG)

**Comment by mentastc** [comment]
I'm looking into the onrr.gov website to help align better with the NRRD site. I'll be writing up a list of edits for the group to review. 

I reviewed and added names to the market map as a future resource to contact

**Comment by jennmalcolm** [comment]
Thanks @mentastc. Do you know who manages DOI social media accounts? Could you check into that to see if there are opportunities there and what the process would be?

**Comment by mcharg** [comment]
@mentastc Did you get a chance to look into the social media accounts?  If not, should we move that checkbox to the outreach issue in the new sprint and close this one out?

**Comment by jennmalcolm** [comment]
@mentastc has reached out to ONRR's comms contact about DOI social media channels. We'll continue this work in #2870
