### ISSUE TITLE
Planning for usability testing

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2823]

**Comment by mcharg** [comment]
Study plan: https://docs.google.com/document/d/1USw8OVEM0Qu6_WYVAbEPXLnfX1xqOpNOxR2Awp4rnH0/edit?usp=sharing

**Comment by qmanderson1** [comment]
@mcharg Would you please put the study plan in the research folder so that we have access.

**Comment by mcharg** [comment]
@qmanderson1 It's in the folder, but it removed access for everyone who's not in DOI and won't let me add you back.  Can you create a blank document and I'll copy and paste the contents into it?

**Comment by qmanderson1** [comment]
@mcharg [Blank doc here!](https://docs.google.com/document/d/1eW4uOHPOCANLWVOenr82S8i9uxGLBUPeUqo6LEbeYT0/edit)

**Comment by mcharg** [comment]
@qmanderson1 Thanks!  Contents from other doc copied in.  Will delete the old doc.

**Comment by qmanderson1** [comment]
Awesome, thank you! @mcharg

**Comment by mcharg** [comment]
The plan is now on github. https://github.com/18F/doi-extractives-data/blob/research/research/18_BenevolentBats/ResearchPlan.md
