### ISSUE TITLE
Clarify color use guidance

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2829]
From #2769 

So that team members can find the most-used colors faster, and don't have to rely on visual comparisons between the site and the color spectrum, define a primary palette from the color swatches in use.

We've got all the pieces, we just need to re-organize so that people don't have to guess as much.

- [x] Define the most-used colors as the primary color palette
- [x] Since "blues" and "greens" doesn't say much about their use cases, collapse the separate color pages into one page (keep usage notes in the example viewer if helpful)
- [ ] Add "with white" to "Accessible" or "Not accessible"

**Comment by jenniferthibault** [comment]
This palette seems to be the most commonly used set of each color group. From here I'm going to work on how to re-organize the other color sections, and draft information for the Notes panel.

<img width="639" alt="screen shot 2018-05-16 at 10 09 33 am" src="https://user-images.githubusercontent.com/11636908/40122320-85a7ab34-58f1-11e8-876a-e3a9bc8af35f.png">

**Comment by jenniferthibault** [comment]
Working through this in #2881 I left out the third checkbox, adding "with white" in favor of keeping that information as the first note in the README for each collection. It was creating a text block larger than the color swatch, and leaving as is seemed like a fair balance instead of adding complexity to reduce the size of the type styles here. 

Glad to adjust if the team disagrees!

**Comment by mcharg** [comment]
@jenniferthibault Can you include details about what we commonly use the colors for in the notes?
