### ISSUE TITLE
Define highest value areas for visual design training & find resources

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2861]
One of our transition acceptance criteria is that the NRRD team has the resources they need to continue to develop skills in high-value areas to support iteration on the site.

And one of those high-value areas is visual design! 

To start approaching this, in this issue we should 
- [x] outline what the highest priority visual design skills and subjects are (in relation to the site) together
- [x] define the best approach to developing skills or knowledge in each area
   - Then the 18F team can find best resources for each area, and/or help the NRRD team develop them through training 
- [ ] schedule or carry out training or learning in each area

**Comment by jenniferthibault** [comment]
## Summary
There'll be a lot to catch up on with folks out this week, so I wanted to do a more thorough walkthrough of the exercise the team participated in last Friday:

## The workshop
First each team member brainstormed answers to the question: `In your work on the NRRD website, when are moments when you need to answer the question "What should this look like?"`

Then we grouped those into the following three areas:
- I feel confident in my ability to...
- I feel unsure while trying to...
- I have no idea how to...

At a high level, that looked like this, with each color representing a different team members (detail purposeful obscured at this stage in the overview):
![screen shot 2018-05-22 at 9 30 40 pm](https://user-images.githubusercontent.com/11636908/40398702-7aa02318-5e07-11e8-8a55-800d2aacaf8d.png)

**An important decision point**
We agreed that in order to prioritize subject based on most current needs, we should focus on skills needed to maintain the site and design system in place. Based on that, we divided the topics into `Skills needed to maintain the site` above the horizontal line, and `Skills needed to revisit decisions made about the site, or refactor it`, below the horizontal line, grouped responses by theme within each of the three sections, and drew lines between the different sections where different team mates had different comfort levels for the same skill.

At a high level, that looked like this:

![screen shot 2018-05-22 at 9 38 49 pm](https://user-images.githubusercontent.com/11636908/40398933-8eef19f4-5e08-11e8-9481-c45b60396f73.png)


Here are the detailed category themes from the `Skills needed to maintain the site` section. Overlapping cards show when team members placed their assessment in the same comfort level category.:

![screen shot 2018-05-22 at 9 41 49 pm](https://user-images.githubusercontent.com/11636908/40399015-05bfc0ce-5e09-11e8-80d1-fbe3653ef9d4.png)

![screen shot 2018-05-22 at 9 41 57 pm](https://user-images.githubusercontent.com/11636908/40399017-0a3c44ba-5e09-11e8-9072-7c73590420b6.png)

![screen shot 2018-05-22 at 9 42 05 pm](https://user-images.githubusercontent.com/11636908/40399020-0d02ce58-5e09-11e8-8ca9-e0d7a5736281.png)

### Next steps:
Identifying resources/approaches for the different priority categories (update part 2 coming next)

**Comment by jenniferthibault** [comment]
Here is my first go at identifying hypothesis for how the team might improve comfort levels in the following areas identified in the above exercise. In no particular order...

## Methods or action steps for improving comfort levels with...

![screen shot 2018-05-22 at 10 18 56 pm](https://user-images.githubusercontent.com/11636908/40400004-26d256be-5e0e-11e8-98da-77d2932c31d1.png)

- There are opportunities for the team to pair through activities to see how this plays out based on real tasks, like going from wireframing to production
- Since there are tons of outside resources and examples to look to for best practices and approaches for using design systems, we should absolutely spend time learning from those
- One of these resources we can look to are decision frameworks, or decision flows for how others decide when or if to add/change components in a system (since this was a big area of shared hesitancy)
- An actionable step for task-based work would be to integrate completion criteria for updating the style guide into any GitHub issue that builds new features, or makes changes to existing ones

![screen shot 2018-05-22 at 10 13 26 pm](https://user-images.githubusercontent.com/11636908/40399896-bb7aa6aa-5e0d-11e8-9304-b16e55667289.png)
- The first two are quick wins that I can help with, but I think ultimately a big way to improve confidence would be to pair through styling new elements with Shannon or Ryan here

![screen shot 2018-05-22 at 10 13 38 pm](https://user-images.githubusercontent.com/11636908/40399898-bba065e8-5e0d-11e8-893b-c1651b044df4.png)
- This feels a bit like a subcategory of either of the two theme above, and could be improved with some of the same methods 

![screen shot 2018-05-22 at 10 26 13 pm](https://user-images.githubusercontent.com/11636908/40400212-294b1de4-5e0f-11e8-8054-c356c495f545.png)
- There are lots of folks in government thinking and working around accessibility, we can help identify those communities and resources


![screen shot 2018-05-22 at 10 18 51 pm](https://user-images.githubusercontent.com/11636908/40400296-841fe628-5e0f-11e8-97c4-79af16e90ae6.png)
- This feels like an especially high-value area of skill development given the subject matter of the site. The team was pretty unanimously hesitant or uncertain in this area

![screen shot 2018-05-22 at 10 13 50 pm](https://user-images.githubusercontent.com/11636908/40399900-bbd2391a-5e0d-11e8-8ed0-e828b8b33b87.png)
- Good news here is that while some team members felt like they had no idea where to start, others are very skilled and comfortable in this area. Feels like we should start by trying to collaborate or pair through these scenarios first before going further

_____
@mcharg @master12 @brentryanjohnson I'd love your take on what's here so far (though I know 2/3's of you are out this week, so it's ok!)

Does this feel representative of our conversation? Synthesized in a way that feels accurate? Are there other ways you'd approach breaking this down? 

I feel comfortable enough (even pending the team's review) to start gathering some materials and links in these areas that call for outside resources.

**Comment by mcharg** [comment]
@jenniferthibault Looks like a good approach to me!  Great job synthesizing everything.

**Comment by jenniferthibault** [comment]
This is in progress, but I started listing out resources and training opportunities I know & trust in this [Google Doc](https://docs.google.com/document/d/1fiJI0t-70-gHfmdXsE9abQJ_hZ99DMDmwgWz8rtIywc/edit#heading=h.rtabtt8o3qpv), which was easier to use as a living editable place for the moment

**Comment by usEITI** [comment]
This is a really good resource list moving forward, thank you!

**Comment by jennmalcolm** [comment]
I agree. I like your approach @jenniferthibault, and this will be a very useful resource.

**Comment by jenniferthibault** [comment]
Closing in favor of pulling specific action steps and pairing opportunities into #2889 #2894 #2895 and #2898 . I'll keep updating the google doc above with external training and resources (and re-sharing to slack when I do)
