### ISSUE TITLE
Begin outreach planning

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2870]
Once initial outreach research (#2816) is complete, our next steps (per Shawnique) on our outreach project are:  

- [x] Define some concrete actions we can take to make sure DOI folks who field info requests (FOIA, Data Retrieval team, Public Affairs, etc) have enough knowledge about the site to point folks in the right direction.

- [x] Brainstorm ways to foster a two-way relationship with these folks - we give them resources to help them field requests; they give us info about the types of requests they’re getting so we can make the site better

- [x] Start looking into potential opportunities to feature NRRD on  outreach channels (social media, etc)

**Comment by mcharg** [comment]
@shawnique Can you add a link to the plan you started to this issue?

**Comment by shawnique** [comment]
[NRRD Communication Strategy](https://docs.google.com/document/d/1n3ZpVYLzanz99VJRb9zbagO1tV6YwoOfbV7F8r2veeI/edit#heading=h.so2y0c7jsg2n)

[DRAFT: NRRD Communication Strategy](https://docs.google.com/document/d/1AyEfd8UxVK81HjUujzjHoKmYPwNVRyBBexp9ygoYBIk/edit)

**Comment by shawnique** [comment]
@mcharg & @mentastc please check out the draft outreach and communications plan. Comment where necessary and we can discuss in our outreach meeting next week.

**Comment by mcharg** [comment]
@shawnique I put some comments in the plan.

**Comment by shawnique** [comment]
Check out the [Communication Outreach Plan](https://docs.google.com/document/d/1q4l6ZQuRtmcySvm87GBQGQkbXEVXb7A1xwEvTETV6c4/edit#heading=h.rhhtca4ytsaf)
