### ISSUE TITLE
Recruit Participants for User Research

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2891]

**Comment by mcharg** [comment]
@shawnique  Have you heard back from anyone you asked about an email template for recruiting for user research?

**Comment by mcharg** [comment]
@brentryanjohnson Would you mind taking a look at these templates for emails to send to potential participants?
https://docs.google.com/document/d/1HRLBy-IigoNGlcAD9eY7pQKq9T95HL1NTLfiGLwsDg4/edit?usp=sharing

**Comment by brentryanjohnson** [comment]
@mcharg Looks great! I made a few minor, suggested edits in a named version.

**Comment by mcharg** [comment]
@brentryanjohnson Thanks!

**Comment by mcharg** [comment]
@brentryanjohnson I added a template for the meeting invite to the doc, can you please take a look?

**Comment by brentryanjohnson** [comment]
Okay @mcharg; I've added some suggestions. Feel free to take or leave!

**Comment by mcharg** [comment]
I've contacted 27 people from the pipeline of participants over the last 3 days and have only heard back from 3 - 2 internal and 1 external.  I'm trying to avoid reaching out to people we've already talked to about disbursements and I want to talk to more external users than we have in the past.  We may need to think of other ways to recruit external participants.

**Comment by mcharg** [comment]
We're up to 5 participants - 2 internal ONRR, 3 external (2 journalists, 1 NGO) with one more (internal other gov't agency) who said she'll give me times next week.  It's a fairly good mix of the user types (2-3 Question Answerer, 2 Storyteller, 1 Agenda Supporter).  

Ryan and I already conducted one of the sessions with a journalist yesterday afternoon because he only had that time to talk.
