### ISSUE TITLE
Plan for User Research

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2892]
- [x] Write plan
- [x] Post plan to GitHub
- [x] Write script
- [x] Post script to GitHub

**Comment by mcharg** [comment]
Plan: https://docs.google.com/document/d/135kE0dqLJrGjTDpgGqoD4rzS7jU_06x4LXRST-XovlM/edit#heading=h.o14bekxg05lj
Script: https://docs.google.com/document/d/1Qg1KPw9gl28V_E6-ewHha1ySfQ1ldXrOinxQRjo78QE/edit#heading=h.kn6q64oyymqf

**Comment by mcharg** [comment]
@jennmalcolm Can you take a look at the plan and let me know if you have any feedback?

**Comment by jennmalcolm** [comment]
Sorry for my delay in responding. I looked at the plan, script, and prototypes. I made a couple very minor changes on the plan and script, and they look good to me. The prototypes look great. Thanks.

**Comment by mcharg** [comment]
@jennmalcolm Thanks!

@master12 I'm having trouble finding the Research branch in Atom to add a folder for the docs for this sprint.  Do you have time to show me how to do that today?

**Comment by mcharg** [comment]
Plan: https://github.com/18F/doi-extractives-data/blob/research/research/19_gratefulgopher/Guide

Guide: https://github.com/18F/doi-extractives-data/blob/research/research/19_gratefulgopher/Guide

@brentryanjohnson When you're back in the office, can you take a look at why the markdown isn't formatting in the plan and guide?  Jeff and I can't figure it out.

**Comment by mcharg** [comment]
@brentryanjohnson Nevermind, I figured out that it was because I didn't have .md on the file names.
