### ISSUE TITLE
Identify icon sets to use for future site needs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2894]
In order to make it easier and faster for the NRRD team to use new icons, we should identify icon sets that stylistically match the site that the team should try to pull from first.

**Comment by jenniferthibault** [comment]
Think I found a few good starter options! Here's what I'd add to the style guide under the [Icons](https://revenuedata.doi.gov/styleguide/components/detail/icons.html) note tab.

@brentryanjohnson I'd love your review on both content and the list of recommendations:

___

> Many of the site’s icons are from different contributors on the Noun Project, and are used under a Creative Commons license with attribution in the [humans.txt](https://github.com/18F/doi-extractives-data/blob/dev/humans.txt) file. Others are designed from scratch.
> 
> Even though they are from different sets and artists, they share common style attributes. When picking or building new icons, make sure to match these characteristics:
> - highly rounded corners
> - default style uses heavy outlines, unfilled solid interior spaces
> - if shapes overlap in space, lines leave a gap where they meet instead of intersecting (`.icon-cloud`, `.icon-wind`, `.icon-coal`, `.icon-copper` )
> 
> For finding new icons in the future, here are some open source icon resources that match icon characteristics used on the NRRD site. Each example is from an open source icon set, but specific licenses differ for each.
> 
> - Font Awesome: [Regular style, free collection](https://fontawesome.com/icons?d=gallery&s=regular&m=free). 
>     - Select an [individual icon](https://fontawesome.com/icons/address-book?style=regular) to download it as an SVG
>     - [License](https://fontawesome.com/license?from=io)
> - The [Consumer Financial Protection Bureau’s icons](https://thenounproject.com/cfpb_minicons/uploads/) on the Noun Project
> - [Feather icons](https://feathericons.com/)
>     - [MIT License](https://github.com/feathericons/feather/blob/master/LICENSE)
>     - [GitHib repository](https://github.com/feathericons/feather)
> 
> After you’ve picked new icons, add citations for it to [`humans.txt`](https://github.com/18F/doi-extractives-data/blob/humans-txt/humans.txt)

**Comment by jenniferthibault** [comment]
@mcharg & @brentryanjohnson  where's the most useful place for these options to live for future reference?

**Comment by mcharg** [comment]
Maybe under Design & Research on the wiki?

**Comment by jenniferthibault** [comment]
Yeah I'm torn between the wiki and the notes tab on the [icons page in the style guide](https://revenuedata.doi.gov/styleguide/components/detail/icons.html). 

Wiki because it feels like a list of optional resources, but style guide because it tells you how to style new elements consistently. I think that makes the style guide feel a little less like it would get forgotten there — does that make sense?

**Comment by mcharg** [comment]
I'm good with putting them in the style guide.
