### ISSUE TITLE
Identify scenarios for pairing on spacing questions

### ISSUE THREAD

**Issue by jenniferthibault** [18F/doi-extractives-data#2898]
In the workshop from #2861 , we identified decisions around how much margin/padding to use in visual styling was an area of low confidence on the team. If we flag those scenarios as they arise this spring, NRRD & 18F can pair through making decisions around that area in order to get more comfortable.

- [ ] Ryan and/or Jeff identify scenario needing a decision between spacing, margins, and padding
- [ ] Flag for Jen, who will coach through her process of making a decision around spacing in those instances

**Comment by jennmalcolm** [comment]
closing since we do not have visual design support from 18F now
