### ISSUE TITLE
Export All Sketch Files to Illustrator

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2912]
This is especially important for items not exported to Axure, like charts.

**Comment by jenniferthibault** [comment]
Glad to pick this up this sprint. @jennmalcolm ok to move this item into this milestone? I don't think it will compete with finishing my other tasks

**Comment by jennmalcolm** [comment]
Sure, thanks.

**Comment by jenniferthibault** [comment]
All the design files live on 📁 [Google Drive ](https://drive.google.com/drive/folders/10-NddNUSmWZz8NEymAXj6kgZknMMOMmG)

I created an Illustrator file copy of every Sketch file in the [00 style guide](https://drive.google.com/drive/folders/1smZkLLq-j-o1iNIignpx5ajmC5JWDFxZ) and[ 01 layouts](https://drive.google.com/drive/folders/1odMofhdlkRcq5hC_Exs0lfi2ZGFkxNFn) folders, which seem to be the most useful.

The charts and graphics files are in 01 layouts >> [static charts and graphics](https://drive.google.com/drive/folders/16uLo-Oz2qKpCOI6bof_i4RlGP4JQy44L). One thing that isn't ideal about these conversions is that in most instances, the text was outlined as vectors, so it won't be editable. 

Notes about other files:

- The files in [02 art production](https://drive.google.com/drive/folders/1UA3muLRGRFCHgAF0n0mqCKvU7B7TWUbx) are all already in Illustrator formats (or file formats that are able to be opened in Illustrator, like SVGs or PDSs)
- The files in [03 conceptual fodder and wish list](https://drive.google.com/drive/folders/11V0aIBxh0rJ2n6rqaAPvZ_UaugYCXqSV) all have Illustrator-compatible PDFs, and might not be useful for the future
- The files in [04 visual inventory](https://drive.google.com/drive/folders/1kOkla8oaKgsrx-qBmx8jboa-DvuXoq_x) also all have PDFs, and are process documents used in a previous audit, more than docs that are useful to production. So they're available, but also likely won't be used again.

**Comment by mcharg** [comment]
Looks good to me.

**Comment by jenniferthibault** [comment]
👍 closing
