### ISSUE TITLE
Figure out how to get Mural

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2913]

**Comment by mcharg** [comment]
@jennmalcolm When I figure out the cost, should I assume getting licenses for the whole team, including the data analysts?  That would be 7 licenses, I think.

**Comment by jenniferthibault** [comment]
Tagging in @MkathrynC for help here to work with our infrastructure team to find this info. 

For precedent: I was able to do this on a previous project for InVision and Sketch by finding GSA's security review, and sending screenshot of the approvals (and any conditions, if there were any) to our partner agency's CISO team, who was willing to accept GSA's evaluation for their agency.

**Comment by mcharg** [comment]
Looks like we got approval.
