### ISSUE TITLE
Change production data description under download data

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2970]
The years under Federal Lands and Waters on the download data page needs to be updated to reflect the new production data file on the site.

![image](https://user-images.githubusercontent.com/30806839/41554987-5daf622a-7304-11e8-9bbc-c52482b5d6eb.png)

**Comment by brentryanjohnson** [comment]
Great catch, @jennmalcolm. I've updated and clarified the year ranges on the downloads landing page in #2971.
