### ISSUE TITLE
Question about data pipeline for site?

### ISSUE THREAD

**Issue by anderspeders** [18F/doi-extractives-data#395]
Congratulations on the launch. The site looks really excellent. A big thank you for open sourcing this work. This will likely be a benefit to many other EITI countries!

A few questions about the data: 
1) Will you be publishing _Company ID_ and _State_ along with Company Name when available?

2) Will you be adding data on individual mining licenses and consessions (incl. i. License holder(s).
ii. Coordinates of the license area.
iii. Date of application, date of award and duration of the license.
iv. In the case of production licenses, the commodity being produced) as per 3.9 in the EITI standard?

Ref: https://eiti.org/files/English_EITI%20STANDARD_11July_0.pdf

**Comment by gemfarmer** [comment]
@coreycaitlin this was quite awhile ago. It appears that we never answered @anderspeders's question, but I'm not sure that it is still relevant. Should we close it?
