### ISSUE TITLE
Color Contrast Issues

### ISSUE THREAD

**Issue by nickbristow** [18F/doi-extractives-data#431]
## Home page
- [x] Paragraph text in header, background needs to be less transparent measured at 3.69:1
- [x] "Where do these revenues go?" background needs to be less transparent measured at 4.16:1
- [x] Unselected year on bubble graph is black on grey, should be white on grey or something else
- [x] Bubble graph, blue text that appears on rollover isn't light enough
- [x] Bubble graph, white text on green bubble fails with 2.61:1

## Global
- [x] Red link hover text fails with 3.72:1 
- [x] In collapsed nav menu, white link hover text on blue fails with 1.91:1

## Sectors page 
- [x] White text on light purple bar (all except the last bar)

## data page
- [x] Black unselected tab text on grey fails
- [x] Placeholder text fails
- [x] White on green bonus text fails
- [x] black on purple other text fails

**Comment by meiqimichelle** [comment]
@nickbristow 
For `Bubble graph, white text on green bubble fails with 2.61:1`, I was able to adjust to 3.8:1 (...I think...if I'm reading the scale right) without too much change to the color feel. Is that good enough, or do we need more?

**Comment by meiqimichelle** [comment]
Here's another @nickbristow 
I don't know how to test the transparencies. The sites I'm going to to test them are telling me the color and transparency is good to go.

**Comment by meiqimichelle** [comment]
And finally, @nickbristow , that placeholder text. I still can't find the controlling color BOOO. Am going to take a break, and if you have a sec, maybe a new set of eyes will find it.
