### ISSUE TITLE
Assumption/hypothesis testing for next EITI release

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#455]
Lean UX planning [here](https://docs.google.com/a/gsa.gov/document/d/14iYigu1cFd_SJrVt0rz3QvqIoGxQaTryDRCmUjmLS84/edit)

I believe the biggest product risk right now is our lack of outreach/communications. We should work on validating the following hypotheses as soon as we can:

-We believe that: we don’t know enough about our user base
Which will result in: creating a product that does not meet user needs
We will know we are right when: we interview more people in each user type about their interactions with extractive industries information and data

-We believe that: USEITI data is useful to a broad audience
We will know we are right when: more than just the few subject-specific non-profits use/reference our data

-We believe that: providing more location-based information
Will result in: meet a user need for the concerned citizen who wants to know what’s happening in his/her neighborhood
We will know we are right when we see increased interest from non-sector-specific civil society groups (local groups instead) pending more comms outreach

-We believe that: providing the 2015 USEITI Report online and in an easily-sharable way
Will result in: increased use of its data
We will know we are right when: we see USEITI datasets being used by many third parties, including non-specialists (ie, have have lowered the barrier to entry)

**Comment by nsinai** [comment]
+1

**Comment by meiqimichelle** [comment]
Overtaken by #470 and the roadmap in our [wiki](https://github.com/18F/doi-extractives-data/wiki).
