### ISSUE TITLE
Click-to-reveal more info on bubbles not working in Ffx 35.0.1 Mac

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#460]
Need to test again on another machine.

@nickbristow can you take a peek?

**Comment by nickbristow** [comment]
Will do.

Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by meiqimichelle** [comment]
OBE
