### ISSUE TITLE
Consider dropping Windows XP support

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#468]
As per discussion with @konklone , might no longer need to pay $600 a month that we do to keep Windows XP users in the loop. I will write a longer explanation of this issue as time permits, but wanted to bookmark it now to make sure we don't forget.

**Comment by meiqimichelle** [comment]
@konklone is this still a thing? It's been so long since I wrote this issue that we might be in an entirely different place now. Thanks for your input!

**Comment by konklone** [comment]
Now that you're on Federalist, you're under Federalist rule. :) I forget whether Federalist requires SNI by default for its CloudFront distributions? cc @dhcole

**Comment by dhcole** [comment]
Federalist does not require SNI, though I've used it on every site I've set up. You can set up Federalist with CloudFront using SNI to forgo IE on Windows XP, pay $600 / month for a custom cert on CloudFront, or set up an ELB with your custom cert and point it at a proxy server to get full SSL support. I've always found CloudFront + SNI to be the best balance of cost and ease, with the notable caveat that it doesn't support HSTS headers.

**Comment by konklone** [comment]
Well, as long as you don't choose the CloudFront custom cert option, you've saved $600/month!
