### ISSUE TITLE
As a user, I should see updated CY13/FY13 data with correct documentation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#469]
Unilateral report to include AR data (accounts receivable).

- [x] CY13 data to be updated
- [x] FY13 data to be available as a link (ie, 'looking for FY data? see here')
- [x] Judy to get description of anything new/different in this dataset (ie, what is accounts receivable)
- [x] BLM/OSM data

**Comment by meiqimichelle** [comment]
Still waiting on data from Denver.

**Comment by meiqimichelle** [comment]
In addition, Jon is to provide a description of accounts receivable.

**Comment by meiqimichelle** [comment]
Data live on development site for feedback.

**Comment by meiqimichelle** [comment]
I will push the CY13 to the live site today, pending no other issues.

**Comment by meiqimichelle** [comment]
@usEITI Are we planning to provide fiscal year downloads on the Version Next site? I'm going through old issues and checking in on this one :)

**Comment by usEITI** [comment]
We will not do FY downloads for the Unilateral data disclosure.
Disbursements are done on a FY basis and will remain FY.  Production - we
want in CY and FY, remains to be seen if we can get both from BLM and
OSMRE. Royalties are what we would also like to see in CY and FY to satisfy
the CY decision for the MSG and to satisfy the FY request of DOI.

On Fri, Oct 23, 2015 at 8:26 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> @usEITI <https://github.com/usEITI> Are we planning to provide fiscal
> year downloads on the Version Next site? I'm going through old issues and
> checking in on this one :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/469#issuecomment-150727251>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*
