### ISSUE TITLE
As a project stakeholder, I want to know about project progress at a high level

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#470]
Stakeholders are interested in project progress. We should provide tangible, high-level info for people who aren't in our project day-to-day, but still need to know that we're moving forward in the right way. Will be provided on a monthly basis.

**Comment by meiqimichelle** [comment]
Done. Provided update document to share.

**Comment by meiqimichelle** [comment]
Contextual narrative working group will give update to implementation subcommittee on March 25. Judy will provide this as an update to Paul.

**Comment by meiqimichelle** [comment]
Brainstormed 'another way' with @ultrasaurus. Resulted in @meiqmichelle testing a repo-wiki-based roadmap that tracks project hypotheses and is constantly updated with learnings and progress — [see USEITI wiki](https://github.com/18F/doi-extractives-data/wiki).

We will know we are right when: 
- we hear feedback from stakeholders (in particular ones that don't follow our progress day-to-day) that they're better able to track what's going on with our project
- we get fewer 'surprised onlookers' about the direction of site development
- when we get questions about a site development roadmap or quarterly plan, directing them to the wiki provides the answers people are looking for

**Comment by meiqimichelle** [comment]
Address roadmap concerns.

**Comment by meiqimichelle** [comment]
@coreycaitlin updated the way our wiki is organized and cleaned it up quite a bit. :tada: We're also going to be using the hypotheses/research branch more extensively over the coming months. We will check back in on this issue and its "we know we are right when"s again soon.

I think we're already hitting the last metric: `when we get questions about a site development roadmap or quarterly plan, directing them to the wiki provides the answers people are looking for`

...but before the reorg we still weren't quite hitting metrics one and two. It may be that the repo wiki is not the right solution for 'concerned onlookers', or that our content should still be kept there, but it needs to be delivered differently (actively emailed out, perhaps).

**Comment by coreycaitlin** [comment]
This also seems like something the "what's new" page can help with, to show recent progress and provide evidence of continued activity. Even if it doesn't show where we're going, at least it'll show that we're moving.

Have we had any "surprised onlookers" recently? With this kind of metric, sometimes silence is a good sign...

**Comment by meiqimichelle** [comment]
For right now, we'll take `silence is a good sign`. If this becomes an active issue again, we will revisit.
