### ISSUE TITLE
Consider defining "extractive industries" in  the "what" in your readme.md

### ISSUE THREAD

**Issue by HobokenMartha** [18F/doi-extractives-data#476]
I know most folks will look at the (very clear)  website, not the code. Plain language helps everywhere, though.

**Comment by meiqimichelle** [comment]
Good point! The `readme.md` could use a little more love and clarity. I made some adjustments to the 'what' section with 13c46742b7494a26ad7cb64aac28665237848a27, taking language from the site and adjusting a few other words. What do you think @HobokenMartha ?

**Comment by HobokenMartha** [comment]
I dig it, @meiqimichelle!   Nice.

**Comment by meiqimichelle** [comment]
:)
