### ISSUE TITLE
As a user, I want filtered data downloads to include all ither revenue types

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#487]
Filtered data downloads at https://useiti.doi.gov/data/ maintain rollup categories when they should be broken out. ie, Other Revenues contains Inspection Fees and Civil Penalties. The user should be able to see which category is which on the filtered data download, just like she/he can on the full dataset download.

**Comment by nickbristow** [comment]
https://github.com/18F/doi-extractives-data/pull/485
