### ISSUE TITLE
Content: county narratives are missing sidebars

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#531]
There is extra information in the county narrative write-ups in the form of pull-quotes. These need to be transitioned to the online version in an elegant way.

**Comment by meiqimichelle** [comment]
@coreycaitlin I'm not sure this is still relevant, or if you ended up addressing this elsewhere, or if the final version of the county narrative content didn't have important sidebars. Please close if this issue isn't useful.

**Comment by coreycaitlin** [comment]
- [ ] Campbell County: _mill levy_ definition
- [ ] DeSoto Parish: _millage tax_ definition
- [ ] Elko/Eureka: ton vs. metric ton clarification
- [ ] Greenlee County: ton vs. metric ton clarification
- [ ] Humboldt/Lander: ton vs. metric ton; _mineral resource potential_ definition; _proved reserves_ definition
- [ ] Kern County: U.S. oil barrel definition
- [ ] Marquette County: ton vs. metric ton clarification
- [ ] North Slope: _mill rate_ definition; _reclamation_ definition
- [ ] Pima County: ton vs. metric ton clarification
- [ ] St. Louis County: ton vs. metric ton clarification
- [ ] West Virginia: ton vs. metric ton clarification; "A commodity's sale price does not always equate to its market price."

Hey! We found some good, concise unit definitions. I'm going to pull some of these into the glossary, and will use this checklist to note when I've set up the glossary links in the case studies.

**Comment by coreycaitlin** [comment]
@Isabelle1512 I was just going to add the `millage tax` definition to the footnotes for DeSoto Parish, but I don't entirely understand it. The sidebar reads:

> A millage tax is the amount of tax payable per dollar on the assessed value of a property. Each mil is worth one-tenth of a cent, or $0.001.

And the text reads:

>The DeSoto Parish Emergency Medical Services (EMS) Department formed in 2001, funded by a four percent millage tax.

Could you help me clarify what a "mil" is, and how these two things fit together?

**Comment by coreycaitlin** [comment]
A second checklist for adding glossary links to the case studies themselves:

- [] Campbell County: _mill levy_ definition
- [ ] DeSoto Parish: _millage tax_ definition
- [] Elko/Eureka: ton vs. metric ton clarification
- [] Greenlee County: ton vs. metric ton clarification
- [] Humboldt/Lander: ton vs. metric ton; _mineral resource potential_ definition; _proved reserves_ definition
- [] Kern County: U.S. oil barrel definition
- [] Marquette County: ton vs. metric ton clarification
- [] North Slope: _mill rate_ definition; _reclamation_ definition
- [] Pima County: ton vs. metric ton clarification
- [] St. Louis County: ton vs. metric ton clarification
- [] West Virginia: ton vs. metric ton clarification; "A commodity's sale price does not always equate to its market price."

**Comment by Isabelle1512** [comment]
@coreycaitlin: a millage tax is a local government property tax. The millage tax rates are quantified in terms of "mills." One mill is 1/1000 of a dollar. If a person had $1000 of property, and the mill rate was 1 mill, then they would pay $0.1 in taxes. It's strange to say a 4% millage tax rate, but that is how the source website described it. I might assume since they converted it to a percentage, that it's the equivalent of 40 mills. Does that still not make sense?

**Comment by coreycaitlin** [comment]
Thanks @Isabelle1512! Here's what I landed on:

"A millage tax is a property tax based on the assessed value of a property. Millage tax rates are quantified in terms of mills: One mill is worth 1/1000 of a dollar, or $0.001."

**Comment by Isabelle1512** [comment]
@ coreycaitlin - love it.

**Comment by coreycaitlin** [comment]
Closing this out! the latest commits to PR #1196 should finish this out.
