### ISSUE TITLE
Move from GitHub Pages to 18F Pages

### ISSUE THREAD

**Issue by konklone** [18F/doi-extractives-data#556]
Should be easy enough to leave 18f.github.io behind with [18F Pages](https://18f.gsa.gov/2015/05/14/18Fpages/).

**Comment by meiqimichelle** [comment]
We've moved the next generation of the site to Federalist. When that launches in December, the old site will float into the mists of time, making this OBE. I am closing this issue, but feel free to re-open @konklone if there's something I'm missing here (ie, there is still something that needs to be done).

**Comment by konklone** [comment]
:+1:
