### ISSUE TITLE
'Executive summary' subpage MVP

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#560]
- create subpage where 'executive summary' will live
- content should be explanation of what *will* live there.

**Comment by gemfarmer** [comment]
'Report' changed to 'Executive Summary' and links to page with sample text.

**Comment by gemfarmer** [comment]
@meiqimichelle do you have any content for this and/or link to explanation of the Executive Summary? I understand the gist of what this is, but not sure I could wax poetic about it...

**Comment by meiqimichelle** [comment]
Text:

[This is where our executive summary will be. This page will have a few summary paragraphs explaining what to expect in the executive summary, and a link to download the executive summary as a PDF. The PDF itself will have live links in it so as people read the work on their computers or internet-enabled devices, they can click directly back to related parts of the full report at useiti.doi.gov.]

**Comment by meiqimichelle** [comment]
Closed with #584
