### ISSUE TITLE
Set up new css architecture

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#602]
We should leverage the new 18F web standards and [this structure for overrides](https://github.com/18F/offsite/tree/18f-pages/_sass).

**Comment by meiqimichelle** [comment]
Set up living styleguide. See FEC example.

**Comment by gemfarmer** [comment]
@meiqimichelle I have started to play around with adding the Design Standards into the site. Not as straightforward as I was hoping. I'm waiting for Eric's redesigns to come  though before making any major changes

**Comment by gemfarmer** [comment]
@meiqimichelle, are you imagining that the styleguide would be a separate app, or exist at `/styleguide` like it currently does? It seems like a `/styleguide` would be much more straightforward to implement,

**Comment by gemfarmer** [comment]
Broke living styleguide off into #626

**Comment by gemfarmer** [comment]
Goals/Stategies:
* add us web design standards as a base set of styles
* minimize overrides
* remove dead stylistic code
* narrow content width/change grid
* create new styleguide
* refactor eiti-specific typography
* refactor eiti-specific scss variables
What I have done:
* added us web design standards
* started creating styleguide
* removed unnecessary directories
What still needs to be done: 
* [ ] remov

**Comment by gemfarmer** [comment]
Closed with #649
