### ISSUE TITLE
Homepage layout improvements

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#611]
- [x] We designed the entire site a bit too large. Bring it down a notch or two.
- [ ] Re-think how we enter the map/chart visualization to make sub-categories clearer, and also make the many ways to enter clearer as to what you get after the jump
- [ ] Think of how to surface the Cool Stuff you get after clicking in? ie, a call to action that isn't an explicit call to action?
- [ ] Make the page more easily scannable, so users understand how the site is organized
- [x] Reconsider the application of color as a resource marker (test this?)
- [ ] Take a look at typography sizing, with an eye to streamlining the amount of styles and minimizing style overrides

**Comment by ericronne** [comment]
How do people feel about this?
Something we can use for hallway testing?
Thoughts/Suggestions?
![eiti-home-101415](https://cloud.githubusercontent.com/assets/9259185/10496531/ee0a2520-7286-11e5-9034-2bf9c2aa0c0b.png)

**Comment by gemfarmer** [comment]
@ericronne Looks great! Would it be helpful if the entire background was gray below/after the "How do federal revenues break...." section? The could remain white and would still pop.

**Comment by ericronne** [comment]
Thanky!
The bottom cards are screen captures from the dev site. I'm planning to revisit their design. I considered keeping the gray background and blowing it out to the full width of the page, but i think that might look funky on wider screens. Plus my hope is to unify the page as much as possible, and my gray-bg approach wouldn't help me there. :/

**Comment by meiqimichelle** [comment]
We've done a first-next version of this. We will now break out improvements (and tests) to separate sections of the homepage in separate issues. Closing.
