### ISSUE TITLE
[EPIC] Refine information architecture

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#622]

**Comment by ericronne** [comment]
https://github.com/18F/doi-extractives-data/wiki/Information-Architecture

Two nav variants ("Interactive Data" vs "Explore") based on above structure...
![image](https://cloud.githubusercontent.com/assets/9259185/10407228/c045e7a0-6ead-11e5-9189-e80098335d04.png)

**Comment by ericronne** [comment]
Perhaps we should A-B hallway test these two options.
(Note: the architecture reflected in the wiki is not yet set in stone)

**Comment by usEITI** [comment]
I agree, testing in the "hallways" would be useful.  This is also an area where the Advisory Workgroup might provide some insight?

**Comment by meiqimichelle** [comment]
Yes! We'll talk about getting testing que'd up for this this week, and @usEITI I agree with your note -- the Advisory Workgroup can help here. This will be a good thing to ask for specific feedback on from that group.

**Comment by meiqimichelle** [comment]
- Confirm with Judy that we've covered everything (stamp of approval on the wiki IA)
- Testing

**Comment by gemfarmer** [comment]
@ericronne @meiqimichelle 
I started a folder for new user research. Some positive, some negative. https://drive.google.com/drive/folders/0B4b900J0no9nVGlkeF9jRW40RVE

Takeaways that might be pertinent to #622, Natural Resources and Interactive Data were generally confusing to people

**Comment by meiqimichelle** [comment]
Testing has gone well. We are still refining global nav, and we still want to triple-check with @Isabelle1512 that our content reflects the executive summary content.

**Comment by meiqimichelle** [comment]
@ericronne As per the latest research results, I would like to test another version of the global nav (along with whatever else you have in your latest mocks -- perhaps the new glossary icon?) with these options:

- Home
- About USEITI _or_ About the initiative
- How it works
- Explore data
- Local impact
- Downloads

Mockup plz?

**Comment by ericronne** [comment]
Here you go. Feels a little cumbersome to me. Just riffing here, but I wonder if the content of Local Impact could be moved elsewhere? It's a pretty thin section, and seems like a bit of an over promise to me, since we don't really have much "impact" info. Also, the local info is already in other parts of the site, where you can drill down to county data. So i wonder if some people might miss those sections because they figure info about what's going on near them is housed under Local Impact.(?)

![0 home copy 16](https://cloud.githubusercontent.com/assets/9259185/10731081/9239199c-7bc1-11e5-9189-68d3edd2acc9.png)
![0 home copy 17](https://cloud.githubusercontent.com/assets/9259185/10731080/923786e0-7bc1-11e5-88d0-414880c605e7.png)

**Comment by Isabelle1512** [comment]
@ericronne on local impact, we've got 12 county case studies, each about 4 pages of text. It's a shame they are so narrative, can improve on that in year 2. Just wanted you to know the extent of the content. Also, if state impact is local impact, next year individual states (three or so) will be joining the EITI, and we will need a place to talk about the states...not sure where that goes...

**Comment by ericronne** [comment]
Not the end of the world if we keep the category, just not ideal, shrug

**Comment by Isabelle1512** [comment]
i'm not attached to it - just wanted everyone to have all the facts! also shrug

**Comment by ericronne** [comment]
We could also group the glossary and download links into a "utility link zone"...
![0 home copy 17](https://cloud.githubusercontent.com/assets/9259185/10732572/b1776d52-7bc8-11e5-8a20-859bc1af11f1.png)

**Comment by meiqimichelle** [comment]
We could also go back to calling that section 'case studies' if all that's there is our 12 county narratives.

**Comment by ericronne** [comment]
Here's that as an(other) alt...
![0 home copy 17](https://cloud.githubusercontent.com/assets/9259185/10732771/9359733c-7bc9-11e5-8443-df1896a7fe56.png)

**Comment by meiqimichelle** [comment]
@ericronne while we're thinking about global utilities, we should also think about where 'search' will live. @shawnbot has proposed that added a normal site search would not be a big lift. We could have that functionality plus curated search that surfaces related information from other government sites.

**Comment by ericronne** [comment]
That would be a great addition. Up in the corner where it used to be seems like the best spot for it, i'll integrate.

**Comment by meiqimichelle** [comment]
Great! @ericronne I also started an issue for [designing search results](https://github.com/18F/doi-extractives-data/issues/675) for later.

**Comment by meiqimichelle** [comment]
This is OBE and the work in many smaller tasks. Closing.
