### ISSUE TITLE
Set up regular testing sessions -- "Testing Tuesday" or similar

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#624]
To make sure we're getting using feedback, let's set up a regular testing hour/hours once a week. If we need more time, we can take it, but at least we'll have a set minimum.

**Comment by meiqimichelle** [comment]
It doesn't seem feasible to have a set time, as it is better to work around interviewees schedules. Closing.

**Comment by usEITI** [comment]
I was talking with someone last night who lives in Alexandria, Va and would love to be an interviewee for testing the site/providing user feedback.

**Comment by meiqimichelle** [comment]
@usEITI Great! You can email me that person's contact info and I'll be in touch to schedule a time.
