### ISSUE TITLE
Create Living Styleguide

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#626]
From #602 

Start a style guide that demonstrates the UI options for styles and elements.
Because the site will be heavily leveraging [US Web Design Standards](https://playbook.cio.gov/designstandards), I don't think it is 100% necessary to delve into every permutation, but instead emphasize common use cases that appear in the site

Mockups from @ericronne 

Styles:
* [ ] Typography
* [ ] Grid
* [ ] Buttons/Links
* [ ] Forms
* [ ] Colors

Elements:
* [ ] Map
* [ ] Charts

HTML/CSS

Styles:
* [ ] Typography
* [ ] Grid
* [ ] Buttons/Links
* [ ] Forms
* [ ] Colors

Elements:
* [ ] Map
* [ ] Charts

**Comment by meiqimichelle** [comment]
(continuing the convo from #602)

@gemfarmer I'm hoping this is *not* a separate app, but I haven't tried to implement before so I'm not sure if that's easier or harder. I just like having all the things in one place, if possible.

**Comment by usEITI** [comment]
Argh, I dialed in late I have an update, the hard minerals production data
issues re: the Trade Secrets Act have been settled internally and the data
sets will be sent to you early next week.

On Tue, Oct 13, 2015 at 1:32 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> (continuing the convo from #602
> <https://github.com/18F/doi-extractives-data/issues/602>)
>
> @gemfarmer <https://github.com/gemfarmer> I'm hoping this is *not* a
> separate app, but I haven't tried to implement before so I'm not sure if
> that's easier or harder. I just like having all the things in one place, if
> possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/626#issuecomment-147785941>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by ericronne** [comment]
Here's an updated version @gemfarmer, lmk if you need the sketch file...
![style guide 102215](https://cloud.githubusercontent.com/assets/9259185/10679441/2a4ef26a-78de-11e5-97c0-2d0c32253cff.png)

and two pointer svg files (thick for small applications, thin for large)...

https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaTDdhNnFsT3NMaTQ/view?usp=sharing

https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaN1pnYjc2bHh3Y2c/view?usp=sharing

**Comment by usEITI** [comment]
thumbs up
