### ISSUE TITLE
Fine-tune glossary appearance

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#637]
Apply to site
* [x] Book icon/image 
* [x] x icon/image
* [x] Add book icon link to header
* [x] inline term reference (dotted underline)

**Comment by ericronne** [comment]
@gemfarmer 
Here are three versions of the book icon. I assume you will only need one, though, which you can resize and recolor as needed. Reference ...
![glossary icon specs](https://cloud.githubusercontent.com/assets/9259185/10614350/5ea057cc-771f-11e5-9135-e9ead8601b95.png)

Main nav book:
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaMzBHMkpYZndHNmM/view?usp=sharing

Link book:
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaXzhmZjRZMTlmWTQ/view?usp=sharing

Expanded glossary book:
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaY2xjVXJDcklrcU0/view?usp=sharing

Close X icon:
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaekkxeFNISVM3UXM/view?usp=sharing

**Comment by ericronne** [comment]
Some points for possible usability testing...
* [ ] When clicking to expand one word in a list, is it more usable to keep the other words visible, or to hide/filter them out?
* [ ] What is a clear call to action for the filter field?
 - (@gemfarmer's current wording)
 - "Enter a term to narrow the list"
 - _____________ (Greg?)

**Comment by gboone** [comment]
* "Find other terms." 
* "Search for another term"
* "Look up other terms"

I think "find" "search" and "look up" might be more useful for interactions that don't show other terms than the one expanded.

**Comment by ericronne** [comment]
Thanks, Greg. The tool only filters the list of 30 or so words, which will all be listed by default.

**Comment by gemfarmer** [comment]
Closed with  #649
