### ISSUE TITLE
document how to update the glossary text

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#638]
Add documentation for how update the text in the glossary drawer.

**Comment by gemfarmer** [comment]
@meiqimichelle will there be any glossary content that is edited after the fact? I'm thinking this ticket is no longer necessary.

**Comment by meiqimichelle** [comment]
I can see needing to update the glossary at some point, but is there anything more complicated than updating the data file that the text is in? If yes (like, you have to run a script or something), then we should document it, probably in the repo wiki.

**Comment by gemfarmer** [comment]
No, there isn't. Just updating the text and maybe the term references.

**Comment by meiqimichelle** [comment]
Then I think we can close this. There's nothing special to it.
