### ISSUE TITLE
Confirm color palette

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#642]
Eliminate red, and use this opportunity to explore a potential broader change in palette.

**Comment by ericronne** [comment]
Mural...
http://mur.al/vRJMLRMJ

**Comment by meiqimichelle** [comment]
Reminder of [accessibility testing tools](http://18f.github.io/accessibility/tools/) from #499 as we look into color options.

**Comment by ericronne** [comment]
Pastels may lend sort of a "cartological authority" to the site that the current bright/saturated colors lack. 508 issues exist, but may be surmountable. Here's one such option...

![image](https://cloud.githubusercontent.com/assets/9259185/10737497/8d0bac5e-7be0-11e5-9dbf-f05a17322c81.png)

**Comment by ericronne** [comment]
Lighter option...
![image](https://cloud.githubusercontent.com/assets/9259185/10741028/8b22fdda-7bf3-11e5-8243-ce1873e7ff98.png)

**Comment by ericronne** [comment]
Deeper page w/some of this coloring applied...
![level2recolored](https://cloud.githubusercontent.com/assets/9259185/10741386/87e8bbda-7bf5-11e5-810b-fa3de9e9e51b.png)

**Comment by usEITI** [comment]
Easier on the eyes and looks polished.

On Mon, Oct 26, 2015 at 2:24 PM, Eric Ronne <notifications@github.com>
wrote:

> Deeper page w/some of this coloring applied...
> [image: level2recolored]
> <https://cloud.githubusercontent.com/assets/9259185/10741386/87e8bbda-7bf5-11e5-810b-fa3de9e9e51b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/642#issuecomment-151273721>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
@ericronne I'm getting a bit of a Babies R Us vibe when the super pastel colors head outside the charts :grin: I like the [slightly darker options](https://github.com/18F/doi-extractives-data/issues/642#issuecomment-151226140). Was this change to try to get better accessibility contrast?

**Comment by ericronne** [comment]
Ha that was a slight concern of mine, as well. My thought was to age things up by judicious application of darker colors throughout, in addition to the pastel palette. The idea in lightening was to move closer to a traditional map color scheme, but i'm good with either. I also can work in other directions, so all should not hesitate to chime in now (or hold your peace!).

**Comment by ericronne** [comment]
If someone likes the vibe of a particular mood example on the mural, feel free to note that here. Perhaps i can explore in that direction :+1: 
http://mur.al/vRJMLRMJ

**Comment by meiqimichelle** [comment]
I sticker'd, @ericronne !

**Comment by meiqimichelle** [comment]
@ericronne If the color palette is settled now, can you plz drop an image with the info here, and we'll add it to the styleguide and wiki? Thank you!

**Comment by ericronne** [comment]
We should confirm that this represents colors found on the site :)

![eiti base palette v1](https://cloud.githubusercontent.com/assets/9259185/11964011/47dddc86-a8b0-11e5-8604-9ba5902129c2.png)

**Comment by meiqimichelle** [comment]
Loverly. Thank you! I've re-assigned to me to check the site n stuff.

**Comment by meiqimichelle** [comment]
Closing in favor of #1638
