### ISSUE TITLE
Design mobile view of global nav

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#647]
Draft showing deeper level ...
![mobile-top-copy-5](https://cloud.githubusercontent.com/assets/9259185/10700785/ad1fe60c-7985-11e5-939b-41337b08364b.jpg)

**Comment by ericronne** [comment]
Here's a crack at it ...

**Collapsed**
![nav collapsed](https://cloud.githubusercontent.com/assets/9259185/11249192/1941d358-8deb-11e5-957f-9e8db071d601.png)

**Expanded**
![nav expanded](https://cloud.githubusercontent.com/assets/9259185/11249193/194203dc-8deb-11e5-8426-7eb5cab2b01d.png)

**Comment by ericronne** [comment]
@gemfarmer (et al) lmk what you think, ty

**Comment by meiqimichelle** [comment]
@ericronne I think you said you finished this, correct? Are these the final mocks? If no, plz upload latest and then close. Thank you!

**Comment by ericronne** [comment]
Changed the background to blue, to keep it distinct from the glossary, and massaged a bit more....

**Sketch file**
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwacXBPajZKdUlGOHc/view?usp=sharing

![nav collapsed](https://cloud.githubusercontent.com/assets/9259185/11309615/750c94f2-8f8a-11e5-823c-c6f7a3aa358e.png)

![nav expanded](https://cloud.githubusercontent.com/assets/9259185/11309618/79faa95e-8f8a-11e5-9b04-d29d3dfe8402.png)

![glossary expanded](https://cloud.githubusercontent.com/assets/9259185/11309620/7e61f92a-8f8a-11e5-9e36-69fd2a8797c5.png)

**Comment by gemfarmer** [comment]
Beautiful!

**Comment by usEITI** [comment]
nice

On Fri, Nov 20, 2015 at 2:27 PM, Eric Ronne <notifications@github.com>
wrote:

> Changed the background to blue, to keep it distinct from the glossary, and
> massaged a bit more....
>
> *Sketch file*
>
> https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwacXBPajZKdUlGOHc/view?usp=sharing
>
> [image: nav collapsed]
> <https://cloud.githubusercontent.com/assets/9259185/11309615/750c94f2-8f8a-11e5-823c-c6f7a3aa358e.png>
>
> [image: nav expanded]
> <https://cloud.githubusercontent.com/assets/9259185/11309618/79faa95e-8f8a-11e5-9b04-d29d3dfe8402.png>
>
> [image: glossary expanded]
> <https://cloud.githubusercontent.com/assets/9259185/11309620/7e61f92a-8f8a-11e5-9e36-69fd2a8797c5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/647#issuecomment-158501382>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
Code task associated with this design is in #817 . Closing.
