### ISSUE TITLE
Select a final glossary icon

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#648]
Redesign the glossary icon, given that this design doesn't seem to be communicating well ...
![image](https://cloud.githubusercontent.com/assets/9259185/10700876/49068328-7986-11e5-8c91-2bda7a1d3672.png)

**Comment by ericronne** [comment]
Overall glossary design issue #637

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/10700961/e9443b78-7986-11e5-8380-2945a5467bbf.png)

**Comment by ericronne** [comment]
Option A (note that the smaller white areas begin to fill in, and icon will be smaller on mobile) ...
![image](https://cloud.githubusercontent.com/assets/9259185/10701110/9bb3f442-7987-11e5-96aa-0e304f66c73a.png)

Option B (simpler) ...
![image](https://cloud.githubusercontent.com/assets/9259185/10701141/c7f1e6f4-7987-11e5-9256-a4964f7c5a5b.png)

Discuss! :)

**Comment by usEITI** [comment]
the simplest solution is usually the best . . Option B

**Comment by ericronne** [comment]
Yet another slice of Occam's razor ...
![mobile top w-glossary icon](https://cloud.githubusercontent.com/assets/9259185/10736501/551696b0-7bdb-11e5-8a26-a9ecca6ec06c.png)

**Comment by ericronne** [comment]
And reversed ...
![image](https://cloud.githubusercontent.com/assets/9259185/10736798/e10f26c2-7bdc-11e5-8ce7-027d776439f4.png)

**Comment by gemfarmer** [comment]
I like B. I like the simplicity (fewer lines) and think the bookmark makes it distinctly a book and not a heart or a pair of wings.

**Comment by ericronne** [comment]
Those are good points. @meiqimichelle should we test B and C?

**Comment by usEITI** [comment]
Yes, test!

On Mon, Oct 26, 2015 at 2:28 PM, Eric Ronne <notifications@github.com>
wrote:

> Those are good points. @meiqimichelle <https://github.com/meiqimichelle>
> should we test B and C?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/648#issuecomment-151274728>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
Ok! I'll set up a test along with continuing to test the information architecture. I will track this work in #662.

**Comment by meiqimichelle** [comment]
@ericronne What's the latest version of this (plus the latest global nav) that I should be testing? I need an image of the desktop view.

**Comment by ericronne** [comment]
@meiqimichelle this do the trick?

![home-glossary-icon-a](https://cloud.githubusercontent.com/assets/9259185/10798878/beedc48a-7d77-11e5-8f5a-ba3d371c7494.png)
![home-glossary-icon-b](https://cloud.githubusercontent.com/assets/9259185/10798879/bef9b9d4-7d77-11e5-88b3-7d375a0b56c0.png)

**Comment by meiqimichelle** [comment]
@ericronne Can you delete the 'select a topic below to learn more' ? Also, I don't see the difference between A and B -- help a feeble mind?

**Comment by ericronne** [comment]
Added the about link.
And i can't help a feeble mind, but i may be able to help yours...
The main dif is that B has a bookmark.
![home-glossary-icon-a](https://cloud.githubusercontent.com/assets/9259185/10800141/559561bc-7d7e-11e5-97fc-59ea8a281d43.png)
![home-glossary-icon-b](https://cloud.githubusercontent.com/assets/9259185/10800142/55969b40-7d7e-11e5-9153-0525df4e19a7.png)

**Comment by meiqimichelle** [comment]
Poifect, thank you @ericronne ! I'll get these over to the research repo and finalize the plan for this sprint.

**Comment by meiqimichelle** [comment]
This task is blocked pending results from usability testing in #662. Testing is underway.

**Comment by meiqimichelle** [comment]
Testing is complete, and Book Icon Version A (as seen in [the test asset we used](https://github.com/18F/doi-extractives-data/blob/research/assets/img/pocketmouse/sprint-pocketmouse-img-a.png) ) had no problems. I'm un-blocking this issue, and re-assigning to @ericronne for acceptance.

Eric, close this issue if you're OK with that research confirming that we should use Version A's icon.
