### ISSUE TITLE
Wireframe: Home > Explore data intro

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#653]
Create a teaser on the homepage that links people to #688, the explore data landing page. It should:
- entice people to click
- reveal what will be 'beyond the jump'

What do we have beyond the jump?
- Several types of data (federal revenues, gdp, etc)
- Broadly speaking, data on oil, gas, coal, iron, copper, gold, renewables
- Data on maps

**Comment by meiqimichelle** [comment]
This will be with @Isabelle1512 and @meiqimichelle.

**Comment by meiqimichelle** [comment]
The idea here hopefully meets these goals:
- introduces the user to the breadth of data available to explore
- does not favor one data type over the others (it introduces shows all, and 'all roads' lead to the landing page rather than a particular dataset -- you can't jump straight to 'revenues' for example)

More on the wire:
- Placement/'design' only for illustrative purposes, naturally
- Intro sentence
- Intro to data types, maaaaybe you can click on a broad group or group title and have that take you to that part of the explore data landing page
- The map is flat (non-interactive) and serves as a teaser for what lies within
- I think a similar teaser about the six areas that USEITI is focusing on this year would be good -- hence the empty box with text
- Call to action that leads to the explore data landing page

@ericronne , @shawnbot what say you?

![explore data homepage teaser](https://cloud.githubusercontent.com/assets/4827522/11084454/b70aba08-87f8-11e5-90b9-bf7e13026185.png)

**Comment by usEITI** [comment]
wow this is really taking shape.  I like it.

On Wed, Nov 11, 2015 at 12:24 AM, Michelle Hertzfeld <
notifications@github.com> wrote:

> The idea here hopefully meets these goals:
>
>    - introduces the user to the breadth of data available to explore
>    - does not favor one data type over the others (it introduces shows
>    all, and 'all roads' lead to the landing page rather than a particular
>    dataset -- you can't jump straight to 'revenues' for example)
>
> More on the wire:
>
>    - Placement/'design' only for illustrative purposes, naturally
>    - Intro sentence
>    - Intro to data types, maaaaybe you can click on a broad group or
>    group title and have that take you to that part of the explore data landing
>    page
>    - The map is flat (non-interactive) and serves as a teaser for what
>    lies within
>    - I think a similar teaser about the six areas that USEITI is focusing
>    on this year would be good -- hence the empty box with text
>    - Call to action that leads to the explore data landing page
>
> @ericronne <https://github.com/ericronne> , @shawnbot
> <https://github.com/shawnbot> what say you?
>
> [image: explore data homepage teaser]
> <https://cloud.githubusercontent.com/assets/4827522/11084454/b70aba08-87f8-11e5-90b9-bf7e13026185.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/653#issuecomment-155670831>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by ericronne** [comment]
I like how this helps unpack the contents of the data section. Would love it if we could integrate some more data highlights into this, perhaps in place of the sub-page listings like "All lands and waters" etc. Those eight links feel footer-level to me. Might there be one especially interesting bit of data we could show for each of the three main subcats? (Production/Revenue/Impact)

**Comment by ericronne** [comment]
I'm sure finding numbers to show is the sticky wicket here, but assuming we could resolve that, something like this....?
![image](https://cloud.githubusercontent.com/assets/9259185/11133511/cd13b160-895b-11e5-9a33-a1fd983b576b.png)

**Comment by meiqimichelle** [comment]
I like! Maybe we can come up with data highlights that help show the options available after the jump.
What do you think about incorporating the commodity options somehow, @ericronne ? Perhaps another section with our lovely icons? Or.... _thinking_ -- maybe introducing the commodity icons is better served in the 'How it works' intro box instead.

**Comment by ericronne** [comment]
Smells like a hangout-able topic @meiqimichelle

**Comment by meiqimichelle** [comment]
The latest noodling after the last videochat.
![screenshot 2015-11-23 14 53 14](https://cloud.githubusercontent.com/assets/4827522/11351105/f7e2240a-91f1-11e5-86af-f4a710cea150.png)
