### ISSUE TITLE
Get Beckley backend set up

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#657]
- Talk to Ozzy.

**Comment by meiqimichelle** [comment]
More info: Ozzy said that he can get Beckley set up pretty quickly because it was one of his test apps when we were launching our cloud platform. I'm not sure how this interacts with our new Federalist setup however.

This issue does not cover any of the frontend work.

**Comment by gemfarmer** [comment]
Talked to ozzy. He said that we deploy [this app](https://github.com/18F/beckley/tree/cf-beckley), pointing at the yml that describes our search resources and back it with an elasticsearch service in CF.

Then we’d front the beckley API with data.gov. @shawnbot, @meiqimichelle do we have an existing data.gov API endpoint that we used in the previous version of the project?

**Comment by meiqimichelle** [comment]
`Then we’d front the beckley API with data.gov` -- I don't know what this means :( What do we need data.gov to do? Or -- wait -- oooohhhhh, I think we're talking [api.data.gov](https://github.com/18F/api.data.gov). I'll check.

**Comment by meiqimichelle** [comment]
Reassigning this to me to get the old API key info.

**Comment by gemfarmer** [comment]
@meiqimichelle I have been talking with Ozzy and Nick M and I now have an API key on data.gov. The data.gov API allows us to specify a backend and front end host. Basically it sounds like there is going to be a bunch of proxying, so I'm glad Ozzy exists.
As it stands, he is planning on making an instance of Beckley that exists on CF. When that is done I am going to make the data.gov api to point to the url for Beckley that he gives me and add the curated search yml file to our repo. @ozzyjohnson is this accurate?

**Comment by meiqimichelle** [comment]
Beautiful! Back to you then. I didn't see this note before I signed up for a new API key -- so we have a spare, haha. Thank you!

**Comment by meiqimichelle** [comment]
Update: Federalist can run Beckley on their end. Perhaps the next step is to reserve some time on @dhcole 's calendar to get things set up. Or... ?

**Comment by meiqimichelle** [comment]
- [ ] See how far we got transferring the search js over to our dev branch

Tasks, in order :)

- [ ] Update [api endpoint](https://github.com/18F/doi-extractives-data/blob/gh-pages/static/js/search.js#L27) to `https://api.data.gov/beckley-federalist/v0/resources/eiti/?q=`

- [ ] Test

- [ ] Update `_search.yml` with latest info

- [ ] Have @dhcole restart/reindex

- [ ] Test

**Comment by meiqimichelle** [comment]
We're in business! Dave Cole is also going to see about refactoring some of the code to make things run a bit more smoothly. Check in with him after next Tuesday.
