### ISSUE TITLE
Questions for data to address (important to CSO)

### ISSUE THREAD

**Issue by Isabelle1512** [18F/doi-extractives-data#663]
In the executive summary, pages 53 - 55 are the charts that CSO like. The questions they get at:

1 Which states/communities are the most economically dependent on extractive industries? (EITI was originally designed to address the resource curse....) 

2 Which states/communities collect the most revenues from extractive industries? (gets at local legal and fiscal policy, since revenue isn't just a function of resources produced, but also of the laws, regulations, and land types in place)

3 Which states/communities have the most employment from extractive industries compared to other industries? (gets at relative resource dependence again given the diversity of some economies vs. others, but also the capital intensive nature of some extractive industries)

**Comment by meiqimichelle** [comment]
We've added an overview/landing page for the explore data section, design being tracked in #688. We hope this will start to speak to many of these concerns. We will also design usability tests to understand if we're meeting these outcomes or not.

**Comment by meiqimichelle** [comment]
Task: move these concerns to the new 'future testing' page on the research branch.

**Comment by meiqimichelle** [comment]
Done: https://github.com/18F/doi-extractives-data/blob/research/research/future-topics.md
