### ISSUE TITLE
Content: Match exec summary content blocks to Info Arch and track final content from IA

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#664]
This issue will be to track matching the content as per @Isabelle1512 that is intended for the website, to our information architecture to make sure we're all on the same page. We will check off the content as we receive final version from Team Deloitte; transfer to website/edit; have Isabelle review our transfer; complete.

**Comment by meiqimichelle** [comment]
@nicoleslaw Did you open another issue for this work? I can't remember -- if yes, we can close one or the other.

**Comment by nicoleslaw** [comment]
Nope, this is good! (The other issue was for copy changes.) I am working on this today. :tada:

**Comment by nicoleslaw** [comment]
Everything is tasked up from the report now.
