### ISSUE TITLE
Visual design: Explore data landing page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#688]
This task for the visual design based on the wireframes in #655. It is blocked until that task is complete.

**Comment by ericronne** [comment]
Here's a draft of the MOBILE view, based on the wires.
@meiqimichelle should we split out desktop layouts into their own issues, blerg?
![explore-rev-default-110215](https://cloud.githubusercontent.com/assets/9259185/10891794/a2100c82-8165-11e5-8abb-c8bd9e565b72.png)

**Comment by ericronne** [comment]
Should #655 be closed?

**Comment by ericronne** [comment]
Based upon these wires ...
![image](https://cloud.githubusercontent.com/assets/9259185/10892085/28d677f0-8167-11e5-9002-7ba5ca541825.png)

**Comment by ericronne** [comment]
Would the sub-regions (states, in this case) be expandable?

**Comment by ericronne** [comment]
Colors are placeholder, btw

**Comment by ericronne** [comment]
@shawnbot & @meiqimichelle lmk if any red flags appear for you re this layout.

(note: if the subregions/states aren't expandable, i'll likely remove the rules separating them)

**Comment by meiqimichelle** [comment]
@ericronne I think this work should be is #678, no? This issue was supposed to track a landing page -- this mocks are for the 'revenues' view, correct?

**Comment by ericronne** [comment]
ugh mea culpa, fixing...

**Comment by ericronne** [comment]
Mobile view, hopefully enough here to get a rough version for 11.6 demo...

Default...
![explore-default](https://cloud.githubusercontent.com/assets/9259185/10977324/06b73d7a-83b6-11e5-8bac-72a66bdae959.png)

Accordion expanded...
![explore-section expanded](https://cloud.githubusercontent.com/assets/9259185/10977325/06bb3c4a-83b6-11e5-89a1-df55ad07a175.png)


[Sketch file](https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwad0x4cHhtdlJtODQ/view?usp=sharing)

@gemfarmer

**Comment by ericronne** [comment]
About to take it on the road for today, but i wanted to show y'all the progress on a desktop view for this. I'm leaning toward putting all paragraph-style text in the left column, along with the filter. The filter, text below it, and the year selector would all be sticky. Please lmk your thoughts, and/or we can also do a hangout to discuss it. But tomorrow (fri) is insane with meetings, sigh.

Default...
![image](https://cloud.githubusercontent.com/assets/9259185/10983890/23587618-83db-11e5-9197-b95056ce6a19.png)

Scrolled...
![image](https://cloud.githubusercontent.com/assets/9259185/10983897/35813e2e-83db-11e5-89c5-5d65fd90054a.png)

**Comment by ericronne** [comment]
Draft for desktop, let's chat on it! Happy Armistice Day!
![explore - landing](https://cloud.githubusercontent.com/assets/9259185/11079371/7b6cd214-87d1-11e5-9a4c-57dd3eb054f3.png)
