### ISSUE TITLE
Wireframes: footer

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#692]
This issue (correct me if the scope should be broadened or narrowed) is about determining links in the footer, determining what pages they should be linked to, and making new pages if they don't exist.

@meiqimichelle, @nicoleslaw, @Isabelle1512 could you take a look?

I started making a list of potentials drawing inspiration from  https://app.mural.ly/t/gsa6/m/gsa6/1446213832100

Stub out URLs for questions pages in footer

From Mural.ly:
* What do companies pay?
* Where does the money go?
* Natural resources in US
* How is natural resource extraction governed in indian land? (Tribal)
* How can the public learn more about specific leases to extract natural resources from federal lands and waters?
* What are federal laws, regulations, and reforms governing natural resource extaction in the United States?
* How does the US government award rights to extract natural resources from federal lands and waters?
* Who owns land, ocean waters, and natural resources in the United States?
* What roles do federal government agencies play in natural resource fiscal management in the United States? 
* What is the scope of revenue payment data reconciliation?
* What roles do extractive industries play in the US national economy?
* What natural resources are extracted in the United States? Where is the extraction and exploration taking place?

From Footer: 
* What resources do we have in the U.S.?
* Where is extraction taking place?
* How much do these resources contribute to our economy?
* What do revenues help fund?
* What companies work in these industries? What revenues do they pay?
* How do extractive industries impact communities like mine?
* How do natural resources result in federal revenues?
* How are natural resources governed on federal lands?
* How are natural resources governed on tribal lands?
* How are natural resources governed on state lands?

TO-DOs
* [ ] Determine footer language/ questions from above potentials
* [ ] Determine page to link to, add link
* [ ] Make new page if necessary, add link

**Comment by meiqimichelle** [comment]
Ok! Let's see -- I'd like to see if we can keep our global nav sections in the footer, only with sub-sections spelled out. I've half a mind to start building this out here based on our info architecture wiki -- but I know @nicoleslaw is working on some of that organization now and might have an update tomorrow. So I will be patient :) My comment for now is -- headings in footer == :+1:

**Comment by nicoleslaw** [comment]
@meiqimichelle Are you saying that you'd rather have the global nav links in the footer than FAQs? I agree if so—much easier to read and maintain. (Though we could have a link to common questions/topics in the Questions? module.)

**Comment by meiqimichelle** [comment]
@nicoleslaw Yes on the footer re-wording and re-org-ing! The 'FAQ' setup matched an earlier info architecture, but is now out of date and should be re-written to match whatever we come up with. So, we don't have to keep those questions -- the footer should basically be a sitemap to match the latest.

**Comment by nicoleslaw** [comment]
I think we're all set on this for now.

**Comment by meiqimichelle** [comment]
Reopening because we never made a visual wire for @ericronne . Coming right up, also with USEITI social links, etc.

**Comment by ericronne** [comment]
ty!

**Comment by meiqimichelle** [comment]
Ok! Really terrible version one: delivered:

![screenshot 2015-11-18 11 12 28](https://cloud.githubusercontent.com/assets/4827522/11249629/58d686f4-8de5-11e5-9dc6-59c937a3d41d.png)

**Comment by ericronne** [comment]
ok i'm onnit...
