### ISSUE TITLE
Launch banner -- what's new, what's coming

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#693]
We'd like a notice for what's new in this 2015, first online USEITI report, and some words as to the content that's still on its way. "And in the meantime, see our exec summary."

**Comment by nicoleslaw** [comment]
For my own reference: language from the Executive Summary (pg 10):

> The MSG is committed to continuously improving USEITI implementation in subsequent years to provide US citizens with greater transparency and accountability regarding natural resource management and revenue.

**Comment by nicoleslaw** [comment]
@meiqimichelle @ericronne Do you have a preference on how we present the banner (e.g., as a short alert at the top of the site or as a [homepage feature like FEC](https://beta.fec.gov/))? Happy to write it both ways and we can test it out.

**Comment by ericronne** [comment]
A narrow band across the top seems sufficient for our purposes, to me

**Comment by meiqimichelle** [comment]
Narrow band sounds good to me. This also reminds me that we don't have the 'official gov website' banner on top (you can see this on the FEC beta page). Do we want/need that? If yes, it tends to have a 'this site is in X phase' link. Should we re-purpose that?

**Comment by ericronne** [comment]
Yep. Some examples ....
http://mrl.li/Yyp0139V

**Comment by nicoleslaw** [comment]
@meiqimichelle and I talked about having a more detailed page in the About section that covers highlights from the executive summary, what's new on the site, and what's new data wise, etc. Would either of these combos work for you? Thinking we could link to that "What's new" page instead of the 18F site, but I am not sure how you feel about that.

* An official website of the U.S. Government

* This site is in development. [Learn more](link).
* This site is in development. [See what’s new](link).

**Comment by meiqimichelle** [comment]
I think linking to the 'whats new' page is a great idea, esp. since the stage labels that we're using at 18F are in flux (ie, linking to the 18F page wouldn't provide much value).

My favorite so far is:

| Left | Right  |
| :------------ | ---------:|
| :us: An official website of the U.S. Government | This site is in development. [See what’s new.]() |

**Comment by meiqimichelle** [comment]
This is likely good enough for v1. We should prioritize it along with all the other design tasks.

**Comment by ericronne** [comment]
This work? @meiqimichelle @nicoleslaw 
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaODAxSkZGRy03UVk/view?usp=sharing

![header w-official banner](https://cloud.githubusercontent.com/assets/9259185/11072686/8c25e606-87ac-11e5-9c08-dc5046adc461.png)

**Comment by nicoleslaw** [comment]
Looks good to me! 🇺🇸

**Comment by meiqimichelle** [comment]
Yup! Over to @gemfarmer for implementation.

**Comment by ericronne** [comment]
Something yet for me to do on this?

**Comment by gemfarmer** [comment]
Just to review the PR #773. I know you are busy though and @shawnbot and @meiqimichelle are reviewing it already
