### ISSUE TITLE
Squash visual bugs

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#695]
@ericronne. For now this can serve as a dumping ground for visual bugs. 

Current status: https://federalist.18f.gov/preview/18F/doi-extractives-data/stylistic-bug-squash/

Header:
* [x] Add glossary, Downloads, search
* [x] remove sticky glossary
* [x] remove glossary sub item
* [x] correct sizing on nav items
* [x] active nav items
* [x] align nav items with EITI logo baseline

Homepage

* [x] Remove/comment out navigation chicklets, add filler text

Site-wide:
* [x] dotted underline is only for glossary terms.
* [x] standard link blue underscore, blue no-underscore on hover
* [x] glossary term links should be dotted underline
<br>See this [reference image]
(https://cloud.githubusercontent.com/assets/9259185/10919948/1fbf3644-8233-11e5-886d-c427d8c2a5b7.png)
* [x] EITI logo doesn't link to homepage
* [x] Try [this icon](https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwadHdILTA2Rk5HN2c/view?usp=sharing) for the downloads indicator (will have to recolor, lmk if you want me to do that in the file)
[blue download icon](https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwac3pxV3EwU2V3NEU/view?usp=sharing)
Communities Pages
* [x] Make communities sticky nav look like [this](https://files.slack.com/files-pri/T025AQGAN-F0DMH7Y80/pasted_image_at_2015_11_02_03_10_pm.png) 
* [x] Check links around site 

Resource to Revenues
* [x] Active nav tabs
* [x] DYK header should be same size as DYK content, left aligned, and bold
* [x] Links in tabs should be gray, and receive a gray underscore on hover
* [x] The thin rule along the top border of the gray should run the entire width of the window
* [x] Remove "< Back to revenues overview" and instead use this [breadcrumb approach](https://cloud.githubusercontent.com/assets/9259185/10952114/bde9eec6-8306-11e5-86f7-0ab4bfa15429.png) (Global change)
* [x] Reformat the "managed and regulated by..." callouts [along these lines](https://cloud.githubusercontent.com/assets/9259185/10952360/ed14314c-8307-11e5-88e8-889fe005c29d.png)
* [x] Reformat involved. Left section get h1, right section header gets h2

[Layout for reference](https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaWDg2WE1YSmdoWW8/view?usp=sharing)

**Comment by gemfarmer** [comment]
kill was feeling too aggressive for me

**Comment by meiqimichelle** [comment]
:skull: :skull: :skull: vs :boot: :bug: ?

**Comment by gemfarmer** [comment]
:bug:s are still winning :(

**Comment by gemfarmer** [comment]
Closing with #704

**Comment by ericronne** [comment]
I'll note some fine-point fixes in an issue later, but we're way farther along here. :)
