### ISSUE TITLE
Resource to Revenues Content Bugs

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#698]
In the PR #691, I updated the content on the resource to revenues page following the recent release in [USEITI Online Only Content_FINAL for 18F_110215.dox](https://drive.google.com/open?id=0B2CjDILjK8_jVklvWHQwY1MzbVE).

I updated all the sections except for the "Get involved" sections, which required more code changes than were in the scope of that change set.

What I did change:
* Did you know?
* Steps sections
* Revenue collected stats section
* Subpage intro content

@Isabelle1512, when you get a chance could you review the new content? You can find the links here.

* [Coal](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/coal/)
* [Offshore Oil & Gas](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/offshore_oil_gas/)
* [Onshore Oil & Gas](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/onshore_oil_gas/)
* [Offshore Renewables](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/offshore_renewables/)
* [Onshore Oil & Gas](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/onshore_renewables/)
* [Non-Energy Minerals](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/minerals/)

@nicoleslaw, we were hoping that you could review the above content and make edits/additions that align the submitted content with this media format.

**Comment by Isabelle1512** [comment]
Trying to get a federalist account so I can take a peak...

**Comment by nicoleslaw** [comment]
Working off of a branch here for reference: https://github.com/18F/doi-extractives-data/tree/content-bugs

**Comment by meiqimichelle** [comment]
@Isabelle1512 I think we have to add you on our end. I'll see if we can do that.

**Comment by nicoleslaw** [comment]
Opened a pr for my initial edits: https://github.com/18F/doi-extractives-data/pull/702

**Comment by nicoleslaw** [comment]
Two open questions, making a note on #710 and closing this out

- [ ] Recheck [waters verbiage](https://github.com/18F/doi-extractives-data/commit/bb4b5d22d4ce7f0c6e22a544a79d919005272f69)
- [ ] Ping Isabelle about [offshore_oil_and_gas comment](https://github.com/18F/doi-extractives-data/commit/3e655b56dbcaab4ebc395239d6e268b07400ae84)
