### ISSUE TITLE
Update Resource to Revenues involved section

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#703]
Update the Resource to Revenues involved section based on this content : https://drive.google.com/open?id=0B2CjDILjK8_jVklvWHQwY1MzbVE

Footnotes section needs to be added

**Comment by meiqimichelle** [comment]
See also [this convo](https://github.com/18F/doi-extractives-data/commit/88a06f6f20f384ff13a6078ecaec1b2ac30e7d2a#commitcomment-14190430) in a commit note.

**Comment by nicoleslaw** [comment]
Happy to make the Get involved body copy changes if that’s easier for you.

**Comment by gemfarmer** [comment]
all yours! Thanks :)

**Comment by nicoleslaw** [comment]
@Isabelle1512 The renewable section mentions BOEM's [events page](http://www.boem.gov/Upcoming-Events/), but it's not mentioned in the other sections that refer to BOEM. Should we include it in general, or do you think it's covered by the Twitter/Newsletter/etc. links?

**Comment by meiqimichelle** [comment]
Closing in favor of #710.

**Comment by nicoleslaw** [comment]
@coreycaitlin One other open question for Isabelle here about the events page in the Get involved section. Just copying you in case she comments here.

**Comment by Isabelle1512** [comment]
@coreycaitlin and @nicoleslaw - sorry for the delay - good catch on the calendar. I think it's helpful and could be added to all the BOEM get involved sections.
