### ISSUE TITLE
Add ellipses to 'Did You Know' text

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#715]

**Comment by gemfarmer** [comment]
This issue was fixed with #704 Stylistic Bug Squash

**Comment by nicoleslaw** [comment]
This may be a different task, but I am wondering if the more+ link could also show an ellipses… and then continue the text.

**Comment by gemfarmer** [comment]
@ericronne thoughts on ellipses?

**Comment by meiqimichelle** [comment]
@gemfarmer I think the question is whether there can be ellipses at the end of the 'tagline' sentence, and then when you hit more they disappear to reveal a long paragraph. The 'more+' would remain the same.

@nicoleslaw I'm guessing Brian will say that anything is technically possible, but I'd then say that we've got a lot on our plate to release and so I wouldn't put this particular feature super high up on the list, unless it can be done very quickly.

**Comment by ericronne** [comment]
ellipses would be a nice way to keep these all about the same length — and the boxes the same size — in their collapsed state.

**Comment by gemfarmer** [comment]
@nicoleslaw this shouldn't be a huge fix. That being said, I agree it is probably low priority. Since the DYK collapse is working, I'm going to change the name of this ticket to reflect the desire to add ellipsis .

**Comment by meiqimichelle** [comment]
Can this be a separate sentence for now? What I mean is -- write it in say, two paragraphs:

`Interesting teaser text of a few words here.` [more+]
[paragraph space]
`The loooong original text here`

**Comment by meiqimichelle** [comment]
*My point is that I don't want to hold up finalizing the content on that page while waiting for a code fix.

**Comment by nicoleslaw** [comment]
This should be fixed content-wise, but the paragraph wrapping is a little weird.

**Comment by meiqimichelle** [comment]
@gemfarmer the more expand doesn't work for me in Ffx

**Comment by gemfarmer** [comment]
@meiqimichelle I just made an issue and PR #775 #776

**Comment by meiqimichelle** [comment]
Overtaken by events.
