### ISSUE TITLE
Convert SVGs into eiti webfont

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#718]
This was started with .icon-download. 

Preview link here : https://federalist.18f.gov/preview/18F/doi-extractives-data/webfont/

Making webfonts with this service : http://www.glyphter.com

**Comment by gemfarmer** [comment]
Update: I have started converting some of our existing icons to webfonts from SVGs. Some have been more successful than others. Here is a catalog of what has been done and what needs to be done.

Done: :heavy_check_mark: 
* downloads
* book (glossary)
* us map
* coal
* renewables

TODO: need better svgs
* [ ] close-x
* [ ] hardrock

TODO: need to convert to SVGs, then to webfont
* [ ] angle-down (chevron)
* [ ] copper
* [ ] gas
* [ ] gold
* [ ] oil
* [ ] copper
* [ ] search

**Comment by meiqimichelle** [comment]
@ericronne probably has the icons you need in svg

**Comment by ericronne** [comment]
Gdrive is CRAWLING for me, so i'll drag the resource icon svgs into slack...

**Comment by ericronne** [comment]
Resource icons on gdrive now fyi...
https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaTEJVbnMwZXJEdzg&usp=sharing

**Comment by ericronne** [comment]
@gemfarmer Here's the interface icons (still need to supply you with search)...
https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaOVdIdTFxZTNNLWM&usp=sharing

**Comment by ericronne** [comment]
@gemfarmer Search: https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwab1VwYUNhQlM5Q28/view?usp=sharing

**Comment by ericronne** [comment]
@gemfarmer fixed the iron svg
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaMWpKRllHY3lMMlk/view?usp=sharing

**Comment by ericronne** [comment]
@gemfarmer Try this X icon. I changed the name for consistency with other icons, but of course feel free to rename to "close-X.svg" (the old name)...
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaODZVYmk1WnI3ZHM/view?usp=sharing

**Comment by gemfarmer** [comment]
@ericronne the iron icon is working, but the close-x is still not showing up. Actually no clue why. Some of the others were giving error messages that were helpful, but this one is giving no feedback :(

**Comment by ericronne** [comment]
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaenAzWDJ2MUI4ak0/view?usp=sharing
