### ISSUE TITLE
Content: Update glossary with final text

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#723]

**Comment by nicoleslaw** [comment]
Opened a pr here: https://github.com/18F/doi-extractives-data/pull/726

**Comment by meiqimichelle** [comment]
@nicoleslaw I merged that PR so this is ready for your final pass!

**Comment by nicoleslaw** [comment]
I can't see my changes yet (caching/lag issue?), so I will check back in on this later today or first thing tomorrow.
