### ISSUE TITLE
BUG Glossary book icon alignment

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#724]
The alignment is currently
![screenshot 2015-11-09 08 42 45](https://cloud.githubusercontent.com/assets/4827522/11038029/3252429e-86be-11e5-8da3-7d82523c3909.png)

It should be
![screenshot 2015-11-09 08 44 08](https://cloud.githubusercontent.com/assets/4827522/11038042/4032174a-86be-11e5-98c8-0a7d15e104b6.png)

**Comment by gemfarmer** [comment]
@meiqimichelle I may have ended up addressing this afterall. 
Current state of icon: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/

<img width="693" alt="screen shot 2015-11-10 at 3 33 59 pm" src="https://cloud.githubusercontent.com/assets/4803473/11076469/8632626a-87c0-11e5-86cf-bd5f7441145b.png">
<img width="304" alt="screen shot 2015-11-10 at 3 35 05 pm" src="https://cloud.githubusercontent.com/assets/4803473/11076495/a546af94-87c0-11e5-8b4a-eabb04bc51d1.png">

**Comment by meiqimichelle** [comment]
Great! Now over to @ericronne for final :+1: :-1: . We'll see what he says about having the book icon underlined along with the word -- maybe it is better to explicitly show what you can click on this way (I was wondering about that before). Also, the underline dots are tinier than his original -- is that a showstopper, @ericronne , or can we issue for later given all the other issues in the cue?

**Comment by gemfarmer** [comment]
@meiqimichelle jeez sometimes my attention to detail is really not where it needs to be :sigh. What do you think @ericronne ??

**Comment by ericronne** [comment]
The thinner underscore should be ok, and perhaps we can let usability rule the day and leave the book underlined.
