### ISSUE TITLE
Wireframe: 'How it works' landing page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#728]
Right now, our `How it works` landing page is our old `Resources to revenues` landing page. Our deeper understanding of the entire scope of site content and usability testing on the site information architecture has moved our thinking forward, so now this landing page will include links to all of the governance/process information listed under `How it works` in our [information architecture](https://github.com/18F/doi-extractives-data/wiki/Information-Architecture). We need an updated landing page with sections that reflect this new content.

**Comment by meiqimichelle** [comment]
Ok! I used [this mural](http://mur.al/mBypx4jg) to gather my thoughts around organizing a landing page with all this info (there's quite a bit!). I suggest we create something similar to the `Explore Data` landing page, with overview charts/graphics leading to each narrative block.

I'm not 100% sure yet on the 'diving graphics' bit, which I've placed here under 'extractives process'. That section has an intro in the exec summary, which means that the structure at this point has an 'overview' option and then direct links to each type of resource. Not sure I love that.

@nicoleslaw I want to go over this and the mural and the suggested changes I made in the info architecture to make sure it matches what you're seeing in the final content drop.

Of course, input welcome and invited from all! +1, -1, meh?

![how it works](https://cloud.githubusercontent.com/assets/4827522/11083783/a3f51650-87f0-11e5-8a36-60d3d9ce9536.png)

**Comment by meiqimichelle** [comment]
Potential intro charts/graphics for each section:

### Ownership
![screenshot 2015-11-10 20 43 21](https://cloud.githubusercontent.com/assets/4827522/11083890/cd53aaf6-87f1-11e5-8ced-60dc9a0cc1a4.png)

### Production
![screenshot 2015-11-10 21 27 32](https://cloud.githubusercontent.com/assets/4827522/11083895/e33c6b82-87f1-11e5-8ea5-c87bfebf5b75.png)

### Revenues
![screenshot 2015-11-10 21 28 17](https://cloud.githubusercontent.com/assets/4827522/11083904/fcb81a20-87f1-11e5-8acb-37030138bd04.png)
(teaser of pie chart interaction, which will be in this section)

### Process, overview
![screenshot 2015-11-10 21 29 52](https://cloud.githubusercontent.com/assets/4827522/11083930/335acf00-87f2-11e5-83f3-e15e62fae916.png)
(teaser with process overview -- maybe just the 5 steps)

### Process, individual resources
(teasers with parts of the diving graphic illustrations)

### Federal
(?)

### State
![screenshot 2015-11-10 21 31 14](https://cloud.githubusercontent.com/assets/4827522/11083951/6c0ec630-87f2-11e5-839c-1b79e3de4ccd.png)

### Tribal
(map of tribal lands?)

**Comment by meiqimichelle** [comment]
Forgot to alert @shawnbot and @ericronne . PING for review/notes ^^.

**Comment by ericronne** [comment]
@meiqimichelle i like how the content is chunked, similar to the explore data landing page. Assuming everyone is on board with [that page's layout](https://cloud.githubusercontent.com/assets/9259185/11079371/7b6cd214-87d1-11e5-9a4c-57dd3eb054f3.png), i'll start to flow this content into that structure.

Note: we're amassing a lot of charts/teasers, could be labor intensive. jus sayin

**Comment by ericronne** [comment]
Also...
![image](https://cloud.githubusercontent.com/assets/9259185/11124032/69efe9b0-8928-11e5-9696-a2f225f127a2.png)

**Comment by ericronne** [comment]
A rough layout in #729

**Comment by meiqimichelle** [comment]
Now that the visuals have started, @ericronne please close this issue if you've got what you need from it :) Noted on the amassing of little charts/visuals. Good point.
