### ISSUE TITLE
Visual design: 'How it works' landing page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#729]

**Comment by ericronne** [comment]
first crack ...
![how it works - landing](https://cloud.githubusercontent.com/assets/9259185/11129655/315a7e08-8946-11e5-9473-38874bf02ae1.png)

**Comment by gemfarmer** [comment]
@ericronne I really like the extractive processes section. How set is this design? Should I start coding it?

**Comment by ericronne** [comment]
Good q! It's based on the explore landing page, and i haven't heard feedback on that design. But i think we're pretty safe to code. I'm working on other things for much of today, so i can't do much in the way of prep. But here's the sketch file...

https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaS3dBa2liZXBPc0k/view?usp=sharing

**Note**: Feel free to tweak type sizes here (a little :) to keep them in line with styles. They may be a little off in places.

**Comment by gemfarmer** [comment]
@ericronne Ok. I'll get going on it then!

**Comment by ericronne** [comment]
@gemfarmer &co, i modified the extraction section here ....
![image](https://cloud.githubusercontent.com/assets/9259185/11196956/e7f16ae6-8c7f-11e5-8803-427fea492b05.png)

**Comment by ericronne** [comment]
Sketch file...
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaLTdtd25lNWcyYnc/view?usp=sharing

**Comment by usEITI** [comment]
No red truck, the mining association will not like red associated with
mining.

On Mon, Nov 16, 2015 at 5:34 PM, Eric Ronne <notifications@github.com>
wrote:

> @gemfarmer <https://github.com/gemfarmer> &co, i modified the extraction
> section here ....
> [image: image]
> <https://cloud.githubusercontent.com/assets/9259185/11196956/e7f16ae6-8c7f-11e5-8803-427fea492b05.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/729#issuecomment-157192961>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
@ericronne updated it to match your latest mock: https://federalist.18f.gov/preview/18F/doi-extractives-data/how-it-works-landing/how-it-works/

**Comment by ericronne** [comment]
Good catch re the "vestigial red," @usEITI.
Revising all of those icons to gray, to avoid this issue, and to put user focus on the resources themselves, as opposed to the various apparatus which extract them.

**Comment by ericronne** [comment]
Here's what i was describing in standup...

![image](https://cloud.githubusercontent.com/assets/9259185/11221636/c91e1b76-8d2b-11e5-97d7-685781ef52d5.png)

**Comment by usEITI** [comment]
Thank you

On Tue, Nov 17, 2015 at 1:30 PM, Eric Ronne <notifications@github.com>
wrote:

> Good catch re the "vestigial red," @usEITI <https://github.com/usEITI>.
> Revising all of those icons to gray, to avoid this issue, and to put user
> focus on the resources themselves, as opposed to the various apparatus
> which extract them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/729#issuecomment-157461237>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by usEITI** [comment]
I like it!

On Tue, Nov 17, 2015 at 2:05 PM, Eric Ronne <notifications@github.com>
wrote:

> Here's what i was describing in standup...
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9259185/11221636/c91e1b76-8d2b-11e5-97d7-685781ef52d5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/729#issuecomment-157472343>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by ericronne** [comment]
Thx! Here's a slight tweak, with some modified colors. Palette may be starting to take better shape :)

![image](https://cloud.githubusercontent.com/assets/9259185/11246436/41a2adda-8ddd-11e5-868a-977d6a57f479.png)

**Comment by ericronne** [comment]
@gemfarmer here are the five images at 2x size, to eliminate the softness.

Also colors are updated again :))

https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaa25iVmxvVEZxRUU&usp=sharing

**Comment by meiqimichelle** [comment]
Closing this in favor of a separate bug issue, #850 , for the last comment.
