### ISSUE TITLE
Content: Explore data landing page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#734]
The landing page current has filler text for an intro to each dataset interaction. These need words.

**Comment by nicoleslaw** [comment]
All set on this for now.

**Comment by nicoleslaw** [comment]
Wrong issue! :)

**Comment by nicoleslaw** [comment]
@meiqimichelle @shawnbot Do we have any documentation or info about these data sets? 
- Federal revenue by location
- Federal revenue by company
- Company-reported federal revenue (Is this related to reconciliation? We should make the heading clearer as it sounds too much like the previous.)

**Comment by coreycaitlin** [comment]
This page has content now, so I'm closing this out. This wound up being easiest to refine in parallel with the explore data detail pages. (See #959 and #997.)
