### ISSUE TITLE
State pages: disbursements, visual design

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#735]
This will be based on work in #1461 and #660.

**Comment by ericronne** [comment]
@meiqimichelle 
Made a big CIRCLES chart to add interest to this page. If this looks good, someone should proof it based on the original chart, [which is here] (http://18f.github.io/doi-extractives-data/).

And [here is the png] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaUUNNN0pNbnNQa2s/view?usp=sharing).

![fund disbursements](https://cloud.githubusercontent.com/assets/9259185/11755181/1c8fca64-a016-11e5-8c61-10305b6719c6.png)

**Comment by meiqimichelle** [comment]
Proofed! Looks good, sending back my way for implementation. :boom:

**Comment by usEITI** [comment]
tiny bubbles🎵🎶 ... I am dating myself!

On Fri, Dec 11, 2015 at 3:48 PM, Eric Ronne <notifications@github.com>
wrote:

> @meiqimichelle <https://github.com/meiqimichelle>
> Made a big CIRCLES chart to add interest to this page. If this looks good,
> someone should proof it based on the original chart, which is here
> <http://18f.github.io/doi-extractives-data/>.
>
> And here is the png
> <https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaUUNNN0pNbnNQa2s/view?usp=sharing>
> .
>
> [image: fund disbursements]
> <https://cloud.githubusercontent.com/assets/9259185/11755181/1c8fca64-a016-11e5-8c61-10305b6719c6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/735#issuecomment-164044008>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by dmsnell** [comment]
For what it's worth, the text in the bubble chart looks fuzzy on my external monitor.

On the rMBP screen things are crisp, but on my UltraSharp there's something vague about the definition of the letters. It appears to be related to sub-pixel smoothing. Here's a closeup of the differences: note that these are direct screenshots, both from Chrome, so what you are seeing actually represents the pixels on the display.

<img width="926" alt="screen shot 2016-07-15 at 1 22 52 pm" src="https://cloud.githubusercontent.com/assets/5431237/16887537/7d4e1ecc-4a8f-11e6-8fe5-4facbcac9cf7.png">

On inspection, I discovered that the image was being set to 100% width, translating to 550.56 pixels, though the source image is actually 978px wide. When I reset the width to be 489px (one half of the original width) then it displayed just fine with crisp text. This seems to confirm that the browser is smoothing out the crisp edges when scaling to non-integer multiples of the source resolution.

The problem exists in Safari and Chrome on my Mac but Firefox seems to handle it much better. Not surprisingly, Firefox has experimental support for [control over scaling algorithms in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).

*Possible Solution*
 - Make the asset 2x in size to allow Retina displays to see it in full and to allow other displays to scale it down in integer multiples.
 - Add a `srcset` with multiple source assets to help prevent blurred rescales

**Comment by gemfarmer** [comment]
@dmsnell We could also make it an svg when we pull in the new data. @ericronne thoughts on this?

**Comment by meiqimichelle** [comment]
@gemfarmer @dmsnell We've got newer design work on disbursements happening elsewhere, not sure if we're going to re-use this chart or not. If we do, we will export as SVG and replace, as we're slowly doing with images throughout the site, so it will scale.

**Comment by meiqimichelle** [comment]
I think this is OBE and we no longer have this image or something like it on the site. Closing for now, can re-open as needed.

**Comment by ericronne** [comment]
We should update the home-page card, issued that here #2034
