### ISSUE TITLE
Tweak card design on homepage

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#741]
- [x] content list of cards on homepage
- [x] @ericronne to tweak design based on ^^

**Comment by nicoleslaw** [comment]
@coreycaitlin Something to start thinking about, but we can talk about this on our call. I think the homepage needs will be a bit more clear in a few days once the other content is up.

**Comment by coreycaitlin** [comment]
I took at stab at this (see PR) — attempted plain-language questions and answers to get people into the deeper parts of the site. Let me know if/how they work.

**Comment by nicoleslaw** [comment]
Looks good, @coreycaitlin! A few minor things...do you want me to copyedit in line, or leave you comments here/Slack?

**Comment by coreycaitlin** [comment]
Either! Probably easiest to copyedit in line for minor stuff — also happy to brainstorm for bigger stuff. Not wedded to this content at all.

**Comment by coreycaitlin** [comment]
@ericronne, feel free to toss this back to me if you want me to spend some more time on the content!

**Comment by ericronne** [comment]
@coreycaitlin where's the doc again? Can you link me?

**Comment by coreycaitlin** [comment]
Just the homepage — I think my work so far is all merged up.

**Comment by ericronne** [comment]
@coreycaitlin cool, let's chat a bit

**Comment by ericronne** [comment]
@gemfarmer sounds like you've jumped on this already! (cc @meiqimichelle @coreycaitlin)
so here's the WIP design, with narrower cards...

![image](https://cloud.githubusercontent.com/assets/9259185/11664950/39f6c40e-9daa-11e5-98ca-3ef509eb8c10.png)

**Comment by meiqimichelle** [comment]
@ericronne is the idea that we should pick one card design or the other, or that we'd include both? ie, have an alternating design? I think you mean pick one, and these are here for feedback -- in which case, I'm still fond of the 'top-cap' illustration like we have now.

**Comment by ericronne** [comment]
yep, and top wfm

**Comment by meiqimichelle** [comment]
Done with #1104
