### ISSUE TITLE
Visual bugs: case studies

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#749]

**Comment by ericronne** [comment]
Here are some tweak suggestions for the case study layout. These should also inform other pp to a certain degree. I marked the changes directly on the image, as you can see. Less trackable, i suppose, but easier to see. LMK if this technique doesn't float your boat, @gemfarmer, thx!

![visual bugs - case study](https://cloud.githubusercontent.com/assets/9259185/11074052/2f75cbe0-87b3-11e5-86f6-73629ca4a604.png)

**Comment by ericronne** [comment]
@gemfarmer
And a couple for the home-page intro block :dancer: 
![image](https://cloud.githubusercontent.com/assets/9259185/11076338/ce8111fc-87bf-11e5-8ad8-1975a8987b80.png)

**Comment by meiqimichelle** [comment]
@ericronne The latest version of the homepage is on [staging](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/doi-extractives-data/) -- it is much closer to your mock, but could still use your notes. Can you make a new issue for each one of these images so that it is easier to track which ones are complete?

**Comment by usEITI** [comment]
Thank you for the visual mock, it was help for me to understand the tweaks.  They look good.

**Comment by nicoleslaw** [comment]
Related note for this [Overview page](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/communities/), some of the headings are a bit funky. I wonder if we could simplify the page a bit by removing the second set of case study nav, etc.

**Comment by meiqimichelle** [comment]
@nicoleslaw Did your note on the overview page get resolved? If not, can you explain more (or screenshot) what you mean? I'm not following :-/

**Comment by nicoleslaw** [comment]
Not yet; I can show you during our chat, but there are two sections of nav for the case studies (the drop-down menu and the `Choose a community to get started` section) and I find the "six commodities" part to be a bit confusing.

**Comment by meiqimichelle** [comment]
@nicoleslaw Got it. Yes, @ericronne mentioned something about the funky nav there as well. I'm going to open a new issue on case study nav refinement so we can prioritize -- #796

**Comment by meiqimichelle** [comment]
The case study visual bug fixes are ready for review on [dev](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/case-studies/).

**Comment by usEITI** [comment]
Yeah again.  What is the box and icon under Employment for Boone, Logan,
and Mingo Counties?

On Thu, Nov 19, 2015 at 8:13 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> The case study visual bug fixes are ready for review on dev
> <https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/case-studies/>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/749#issuecomment-158248933>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by ericronne** [comment]
Better-quality map and key art, @meiqimichelle ...

**Map**
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaTFNWYW56YUs5M2c/view?usp=sharing

**Key**
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaVnNVS3E5T0xDdjQ/view?usp=sharing
