### ISSUE TITLE
Content: Add tax expenditures info

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#751]
- [x] Find a place for the content under pg 27-32 of the online only report
- [x] Ask @gemfarmer to stub out the page
- [x] Port over the content from the document

**Comment by nicoleslaw** [comment]
@gemfarmer Do you mind stubbing out a page for tax-expenditures under the How it works section?

**Comment by gemfarmer** [comment]
@nicoleslaw added here:  https://github.com/18F/doi-extractives-data/pull/771
