### ISSUE TITLE
Content: Add state legal and fiscal information

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#752]
- [x] Find a place for the content on pg 34-43 of the online only report
- [x] Ask @gemfarmer to help stub out the page
- [x] Put the content into HTML and copyedit as needed

**Comment by nicoleslaw** [comment]
This one can be in the same subsection: [How it works > Governance](https://github.com/18F/doi-extractives-data/wiki/Information-Architecture) > State legal and fiscal information

**Comment by gemfarmer** [comment]
@nicoleslaw I made the initial stub. Let me know if you want me to add anything else!

**Comment by meiqimichelle** [comment]
@gemfarmer @nicoleslaw See my note in Slack -- I don't think there is a page for 'governance'

**Comment by nicoleslaw** [comment]
@gemfarmer Passing this to you to check the styling. ✌️
