### ISSUE TITLE
Sign up for Ethnio

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#755]
There is a bit of paperwork we need to do to use Ethnio on our site. Ethnio will let us get feedback from people using the site, and then if they're willing, reach other later for a chat.

- [x] Sign up
- [x] Create Ethnio 'project' (decide what the comment form will look like, add JS to site)
- [x] Add href to footer (as per #975 )

**Comment by usEITI** [comment]
Is there someone at 18F that has experience with the paperwork that can facilitate the process for us?

**Comment by NoahKunin** [comment]
@usEITI Yup - actually, as long as we are the system owners, we have to do all of it. We're already using Ethnio on other assets, so it should just be a matter of making the same justifications.

**Comment by usEITI** [comment]
Excellent, thank you.

**Comment by meiqimichelle** [comment]
@usEITI Yep, we're already underway. This is a small amount of paperwork for me fill out -- more like prep work, less like 'official paperwork' :D Thanks for the fast response @NoahKunin !

**Comment by meiqimichelle** [comment]
Here's the [link to our documentation on our share drive](https://docs.google.com/document/d/14YwXV9BoY4EUEGc7kMITFQ-9tFjBipTaj7dsGFIJnNc/edit?pli=1#).

**Comment by NoahKunin** [comment]
Just reviewed the previous approval. This is a-ok by me as the AO. :+1:

**Comment by meiqimichelle** [comment]
I have access now, and will be creating a project for EITI -- and hooking it up to the site.

**Comment by meiqimichelle** [comment]
This should be live on dev as soon as Federalist builds (it is having some issues this morning).

**Comment by meiqimichelle** [comment]
Done.
