### ISSUE TITLE
Content: Add case studies

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#758]
- [x] Stub out pages for the [12 case studies](https://github.com/18F/doi-extractives-data/wiki/Information-Architecture) (under communities?)

- [x] Nicole will add the content and copyedit it if needed
  - [x] North Slope Borough, Alaska
  - [x] Greenlee County, Arizona
  - [x] Pima County, Arizona
  - [x] Kern County, California
  - [x] DeSoto Parish, Louisiana
  - [x] Marquette County, Michigan
  - [x] St. Louis County, Minnesota
  - [x] Elko and Eureka Counties, Nevada
  - [x] Humboldt and Lander Counties, Nevada
  - [x] Tarrant and Johnson Counties, Texas
  - [x] Campbell County, Wyoming
  - [x] Boone, Logan, and Mingo Counties, West Virginia

- [x] Make the footnote link formatting consistent once the case studies are up
- [x] Update header link to Case Studies
- [x] Proofread in the browser
- [x] Update the overview text

**Comment by nicoleslaw** [comment]
Oop, just a note to say that I found the _communities files for North Slope (_communities/nor.md) and Tarrant/Johnson (_communities/tar.md).

**Comment by meiqimichelle** [comment]
@gemfarmer you can (probably should) change the names of those urls to something human-readable. That was not a good choice on my part. Perhaps the full name of the area instead?

**Comment by gemfarmer** [comment]
@meiqimichelle will do!

**Comment by gemfarmer** [comment]
@meiqimichelle @nicoleslaw are we thinking that `/communities/north-slope-borough/` is too long?

**Comment by gemfarmer** [comment]
I think I'm going to leave the county, borough, parish out of the url

**Comment by meiqimichelle** [comment]
@gemfarmer Yeah, that was a good choice -- I was just going for something more human-readable, so what you decided works perfectly!

**Comment by gemfarmer** [comment]
woops! I forgot to add the images. Should we close this issue and make a new one to add images?

**Comment by nicoleslaw** [comment]
I need to proofread these in the browser anyway, but if you want to do a separate issue for the images, that's fine with me!
