### ISSUE TITLE
Content: tax expenditures / big tables

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#785]
I divided these tables up, but they could use some visual/style help to be legible: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/governance/taxes/

**Comment by meiqimichelle** [comment]
@Isabelle1512 do you know if you talked to Nicole about this content at all? I'm trying to figure out where it should live, I think it fell through the cracks. We have a section on tax expenditures on [this page](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/revenues/) so maybe this table was supposed to be a part of that?

**Comment by Isabelle1512** [comment]
@meiqimichelle nicole and I never chatted about it specifically. The table is a longer version of the three bullets (fossil fuels, nonenergy, and renewables) - it definitely expands on the tax expenditures content on that page, and if there was an elegant way to include it there, that would make sense.

**Comment by meiqimichelle** [comment]
@coreycaitlin What do you think of this one? (since you're checking to make sure we haven't missed anything across the site). Should we add the content of this page to the content on how-it-works/revenues/ ?

**Comment by coreycaitlin** [comment]
@meiqimichelle Those tables are enormous, so I'm not sure we can work them into the revenues page itself. What would you think of keeping it as a separate page and linking from /how-it-works/revenues/, so the information is available but doesn't make that page too overwhelming? (Also, those tables kind of need a wider column.)

**Comment by meiqimichelle** [comment]
That sounds like a plan! We can update the breadcrumb on that page, too, so it nests properly.
Yes on the table layouts -- all of the tables on the site are default styling at the moment. I've got that on my list for today to make less terrible.

**Comment by coreycaitlin** [comment]
One thing to revisit: should the breadcrumb on this page have another level (i.e. Revenues)?

**Comment by meiqimichelle** [comment]
@coreycaitlin do you know where we are on this issue? Maybe done?

**Comment by coreycaitlin** [comment]
My only question was about the breadcrumb — do we have any 2-level breadcrumbs?

**Comment by meiqimichelle** [comment]
Ah! We don't have any yet, but if we need them, we could do that.
