### ISSUE TITLE
Visual Bugs: home intro block

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#788]
- [x]  Add 40 or 50 more pixels space above the text block ("The United States...") to push it down
 - [x] Make that same intro sentence H2
 - [x] Add "USEITI" before "was created" (Ok, @nicoleslaw? I changed this to a complete sentence since we can't control the break of the intro line.)
 - [x] Increase the padding(?) on the right side of that text block (by 10 or 20)

*Note: We may still need to adjust the size of the "USEITI was created ..." text, but let's see how it all looks with the above changes applied.*

Thx!

**Comment by nicoleslaw** [comment]
@gemfarmer Holler at me when you want me to look at the copy. Happy to clean it up. :pencil2:

**Comment by meiqimichelle** [comment]
Live on [dev(https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/) for review.
