### ISSUE TITLE
Visual Bugs: Explore Data Landing

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#789]
* [x] Section heders h1 --> h3
* [x] Section subheaders: blue, 400 weight h5
* [x] bottom ribbon: reduce font size, 
* [x] top section: increase spacing after hero banner

Blocked by #730, PR #783

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer 
Tweaked design with charts removed and vertical spacing adjusted. If this is good, let's also use it on the landing pg for how it works ...
![explore - landing - no charts](https://cloud.githubusercontent.com/assets/9259185/11541201/99829c30-98f6-11e5-9a46-2de2cb2232fd.png)
