### ISSUE TITLE
Content: Update About page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#790]
- [x] Update `About > History and principles` sections (p. 5-8, Exec Summary)
- [x] Recheck info for `What does EITI look like in the U.S.?` section (p. 9-11, Exec Summary)
- [x] Copyedit new content
- [x] Ask @gemfarmer to add the remaining images for the federal agencies

**Comment by gemfarmer** [comment]
Schweeet. I'll get to it in the morning :)
