### ISSUE TITLE
Content: Update Executive Summary page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#791]
Update `About > Report` section
- [x] Summary / intro of the report
- [x] Links to other downloads?
- [x] Link to `whats_new`?

**Comment by nicoleslaw** [comment]
Per Isabelle, we can defer adding the reconciliation content til 2016 when we post the interactive data (p. 11-13; 84-91, Exec Summary)

**Comment by nicoleslaw** [comment]
@coreycaitlin This is another task that can wait until the remaining content is up and organized. The report is being finalized, but we'll need to add some intro text to this page.

**Comment by meiqimichelle** [comment]
I put the final pdf on the exec summary page, woo! I just dropped it in as a download button but didn't try to organize anything else on that page yet. You can get it there yay!

I also updated the about page intro to Eric's latest mocks, it looks like this now:
![screenshot 2015-12-03 10 48 10](https://cloud.githubusercontent.com/assets/4827522/11569609/0fbfb6d0-99b0-11e5-8c02-c961305a60d7.png)

So as you can see, there's some room there (the box on the right) for little interesting tidbits if we have them.

**Comment by coreycaitlin** [comment]
@Isabelle1512 Does this (#969) seem like a fair description of what the Executive Summary is?

My goal is for this page to help people figure out whether this document is what they're looking for — and to avoid implying that this doc is the same content as the site.

**Comment by Isabelle1512** [comment]
@coreycaitlin : looking good - one way to distinguish the two is to make the executive summary more about fulfilling the EITI Standard (vs. meeting public needs/engagement). Could say something like The Executive Summary includes an overview of the contextual narrative and reporting and reconciliation process for the EITI Standard in the US. (The Standard has two parts: contextual narrative and reporting/reconciliation). I'm guessing the primary audience for the written report will be EITI stakeholders...

**Comment by coreycaitlin** [comment]
@Isabelle1512 how do you feel about capitalizing "Independent Administrator", "Multi-Stakeholder Group", and "Executive Summary"? Can any of those _not_ be capitalized?

**Comment by Isabelle1512** [comment]
@coreycaitlin: we capitalized all of them in our content. Interestingly enough, the EITI doesn't capitalize multi-stakeholder group. However, the EITI has many mutli-stakeholder groups, and we just have the one. None of them cannot be capitalized.

**Comment by coreycaitlin** [comment]
:+1: thanks for the confirmation!

**Comment by coreycaitlin** [comment]
Decided not to link to "What's New," since these pages are pretty similar except for a difference in focus and potentially audience.

**Comment by coreycaitlin** [comment]
Closing this out, as it sounds like this looks good for now!
