### ISSUE TITLE
Update URLs and file refs

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#794]
* [x] URL path should be `/case-studies/` not `/communities/`. Directories, and all files throughout the site should also follow suit.
* [x] All directories or files (js, css, html) should be changed to `how it works` from `revenues`. (DONE with the exception of css classes. `how-it-works-` is more cumbersome than `.revenues-`. If the name becomes problematic, we can address it then.

**Comment by meiqimichelle** [comment]
I added many urls to the [info architecture](https://github.com/18F/doi-extractives-data/wiki/Information-Architecture) so we can come to closure on where everything will live by the end of the week. @nicoleslaw , I wasn't 100% sure on all the section names and if I got all the individual pages, can you review? And @gemfarmer take a look as well and see if there's anything surprising.

**Comment by nicoleslaw** [comment]
Looks good. I added the /about links as well.

The only other thing I noticed is the Oil & gas + Renewables diving graphics both go to Offshore first, so I corrected that for Renewables.
