### ISSUE TITLE
Nav refinement on case studies page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#796]
There are two sections of nav for the case studies (the drop-down menu and the `Choose a community to get started` section). The the "six commodities" part is also a bit confusing. The design should be refined to address these issues.

**Comment by ericronne** [comment]
Here's a rough-ish tweak and a county layout notion ...

**Main Case Studies Pg**
![content-level page copy 7](https://cloud.githubusercontent.com/assets/9259185/11446545/152a7f30-94fe-11e5-9b88-16845960dd67.png)

**County Selected**
![content-level page copy 8](https://cloud.githubusercontent.com/assets/9259185/11446552/30074838-94fe-11e5-9177-3a5c24f5efc8.png)

**Comment by meiqimichelle** [comment]
@gemfarmer I started work on this in #910 but stopped before touching the sticky nav. See note in that PR.

**Comment by gemfarmer** [comment]
@meiqimichelle @ericronne What is the status on the individual state images for this issue?

**Comment by meiqimichelle** [comment]
@gemfarmer We don't have them yet. I wasn't sure if we'd have time to implement the state-switching so didn't prioritize getting the images. We can see about getting that moved up if you think this isn't too bad tho!

**Comment by meiqimichelle** [comment]
Done.
