### ISSUE TITLE
Content: Add Ownership section

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#800]
Add Ownership content (p. 22-24, Exec Summary) `_how_it_works > ownership`
- [x] Who owns land, ocean waters, and natural resources in the U.S.?
- [ ] Ask @gemfarmer to add image from intro (% production on federal vs non-federal lands)

**Comment by nicoleslaw** [comment]
@meiqimichelle The IA has a note about including the `% production on federal vs non-federal lands` image on this page. Do you know where that one is?

@gemfarmer This will need a bit of styling so the copy doesn’t go full-width.

**Comment by meiqimichelle** [comment]
Let's move these into separate issues. I just opened #846 to track collecting all those images into one place, and opened #848 for the long narrative page text block width.

Since content has been added, and those issues are tracked elsewhere, @nicoleslaw -- can we close this issue?

**Comment by nicoleslaw** [comment]
Sounds good to me! Closing this.
