### ISSUE TITLE
Visual Bugs: How it works (and global nav)

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#805]
Thanks @gemfarmer ! :D

![image](https://cloud.githubusercontent.com/assets/9259185/11226383/1a4a81a6-8d45-11e5-89c3-5601b0534e82.png)

**Comment by meiqimichelle** [comment]
Orange checkmark = fixes implemented with #816:
![visual-bug-hunt](https://cloud.githubusercontent.com/assets/4827522/11277550/3d8a4ae2-8ea4-11e5-821e-c07a0c925654.png)
