### ISSUE TITLE
Visual Bug: Items hitting edge of browser window

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#810]
I noticed that when the browser window isn't wide enough, the EITI logo and the footer hit the edge. Can we add a buffer of some kind to avoid this? (Not sure if the problem exists elsewhere as well)

![image](https://cloud.githubusercontent.com/assets/9259185/11249503/dc41646c-8dec-11e5-8aad-9fc336546cdd.png)

![image](https://cloud.githubusercontent.com/assets/9259185/11249506/e11af4da-8dec-11e5-8226-3454fbb77396.png)

**Comment by gemfarmer** [comment]
Hmm. I'll look into it. I think I know what is causing this.

**Comment by meiqimichelle** [comment]
I'll take this one. I'm planning on doing some small-screen-size style cleaning soon anyways.

**Comment by meiqimichelle** [comment]
I spot-checked an hopefully got the remaining issues here. Could use another review tho.

**Comment by meiqimichelle** [comment]
I believe this is resolved. We should re-issue specific bugs for specific pages if not.
