### ISSUE TITLE
Content: Proofread process pages

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#813]
- [x] Recheck to make sure we're not over-defining acronyms in the process (diving graphics) pages: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/

- [x] Proof the 12 case studies: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/communities/

**Comment by coreycaitlin** [comment]
@nicoleslaw: We do repeat the full BLM and ONRR titles in the "forms" section just above the footer. Keep them spelled out there, or use acronyms? I don't have a strong sense either way, except that the full names make the heading long.

**Comment by coreycaitlin** [comment]
When an acronym is used in both the intro and the "Managed and regulated by" box, which do we want to treat as first use? A user might start either place. My inclination is to leave the full title in both places, and shorter on subsequent uses.

**Comment by nicoleslaw** [comment]
I think we can treat the `Managed and regulated by` box as a definition / first use. For the `Revenue collected` section, maybe it's worth editing that in Inspect Element or similar and making a decision? It does seem a bit long! 

I noticed there are a few places we say "OCS" for "Outer Continental Shelf" — but Isabelle has a note to always spell it out so people don't think it's a federal agency. Do you mind checking for those as well?

**Comment by coreycaitlin** [comment]
Sounds good! And I'll keep an eye out for "OCS", too.

**Comment by coreycaitlin** [comment]
Okay, I'm going to leave both first uses — without the full names, that first paragraph can look like alphabet soup.

For the 'Revenue collected' sections, leaving the full names there, too. Seems likely that folks may be skimming or have forgotten the acronym by this point in the page, and the full names make it work better on its own.

**Comment by nicoleslaw** [comment]
Sounds good! :+1:

**Comment by coreycaitlin** [comment]
Hyphen or no: `Nonenergy` or `Non-energy`? We seem to have each in a few places.

**Comment by coreycaitlin** [comment]
Okay, I wrapped up this edit pass (see #828). I've got a few outstanding style questions I'll sort out tomorrow.

**Comment by coreycaitlin** [comment]
Created a new issue for the case studies.

**Comment by usEITI** [comment]
No hyphen.  It is not hyphenated in the Executive Summary with the
exception of one link.

On Thu, Nov 19, 2015 at 6:47 PM, Corey Mahoney <notifications@github.com>
wrote:

> Hyphen or no: Nonenergy or Non-energy? We seem to have each in a few
> places.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/813#issuecomment-158236315>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by coreycaitlin** [comment]
Great! Thanks, @usEITI — I will keep an eye out for hyphens and standardize when I spot them.

**Comment by coreycaitlin** [comment]
Closing this issue — I found two stray hyphens and fixed them!
