### ISSUE TITLE
Enhancement: where to click to close the glossary drawer

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#819]
- [x] clicking outside the glossary drawer should close the glossary

**Comment by coreycaitlin** [comment]
I keep clicking outside the glossary to close it — can we make it close if the user clicks outside the overlay?

**Comment by ericronne** [comment]
Currently clicking a second time on a word collapses the definition, regardless of whether the glossary itself is opened or closed.

**Comment by meiqimichelle** [comment]
This came up in [usability testing](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-splashysunfish/sprint-splashysunfish_results.md).
