### ISSUE TITLE
Content: How do we want to denote PDF links?

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#826]
In some of our lists of links, one or more of the links points to a PDF. My understanding is that it's best to warn users in the link text, both for general predictability and for accessibility (because opening PDFs can change screenreader behavior/navigation, which can be disorienting if the user isn't expecting it).

In the past, I've simply added `(pdf)` or `(PDF)` to the end of the link text, but I've also seen more styled treatments work well. Thoughts?

**Comment by meiqimichelle** [comment]
For now, I think `(pdf)` or `(PDF)` is good. No need to complicate things at this point.

**Comment by coreycaitlin** [comment]
:+1: 

I'll go with the all-caps version, per a related conversation with the content guild from a while back. If it winds up looking cluttered, we can revisit later.
