### ISSUE TITLE
Content: Proof case studies

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#829]
Proof the 12 case studies: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/communities/

- [x] Overview page
- [x] Boone, Logan, Mingo Counties
- [x] Campbell County
- [x] Greenlee County
- [x] Pima County
- [x] Elko and Eureka Counties
- [x] Humboldt and Lander Counties
- [x] Marquette County
- [x] St. Louis County
- [x] DeSoto Parish
- [x] Tarrant & Johnson Counties
- [x] Kern County
- [x] North Slope Borough

**Comment by nicoleslaw** [comment]
Relates to #890

**Comment by coreycaitlin** [comment]
I think these are pretty good for now! Closing the issue.
