### ISSUE TITLE
Checking BLS links in county narratives

### ISSUE THREAD

**Issue by Isabelle1512** [18F/doi-extractives-data#831]
Some folks have had trouble opening BLS websites from the footnotes in the county narratives. If this persists once they are up online, consider replacing with more general links.

For data from 2012 - present, use this link which takes you to an easy to use search: http://www.bls.gov/cew/apps/data_views/data_views.htm#tab=Tables

For data from before 2012, including 10 year trend data, use this link which takes you to Excel files for download: http://www.bls.gov/cew/datatoc.htm

**Comment by coreycaitlin** [comment]
I can't seem to replicate the issue — could you or @usEITI post a bit more detail about what's happening when you have a chance?
