### ISSUE TITLE
Visual bug: diving graphic preview images on 'how it works' landing page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#850]
- [x] Update images (see below)
- [x] Images aren't positioned properly -- see #729 -- the text falls 'on top of' the white space in the left part of the image, rather than the image coming after the text entirely.

From #729 (see that issue for visuals):

@gemfarmer here are the five images at 2x size, to eliminate the softness.

Also colors are updated again :))

https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaa25iVmxvVEZxRUU&usp=sharing

**Comment by gemfarmer** [comment]
The images that Eric linked will need to be cropped to work with the current css

**Comment by ericronne** [comment]
@meiqimichelle pls check in w/me before implementing, to ensure you have the latest version

**Comment by meiqimichelle** [comment]
Ready for review here: https://federalist.18f.gov/preview/18F/doi-extractives-data/fix-diving-preview-imgs/how-it-works/

If the images aren't the latest, they are easy to swap out. Lemme know :)

**Comment by ericronne** [comment]
all good (other preview site has old images)
