### ISSUE TITLE
Images for How it works section

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#851]
A few of the pages under How it works are missing images:

- [ ] `production` should have the rankings and bar chart from p. 9 + p. 11, Exec Summary
- [ ] `process_overview` should have the image on p. 40, Exec Summary
- [ ] `revenue` should have the images and charts as noted inline in the md file
- [ ] `state-laws-and-regulations` should have the map on p. 56

**Comment by meiqimichelle** [comment]
OBE by other, separate issues for images. #971, #972, #973, #974
