### ISSUE TITLE
Code: emulate case studies on 'State Legal and Fiscal Info' section page

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#861]
Currently blocked by #910 . Waiting for new sticky-nav.js script

For 'State Legal and Fiscal Info', extend the template for case studies to work for this page. Nav items should be styled.

There is an issue with design details somewhere, but I can't seem to find it. @ericronne.

https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/state-legal-fiscal-info/

**Comment by gemfarmer** [comment]
@ericronne I can't seem to find the issue where we were talking about the different options, but if I remember correctly, we decided to go with a right-aligned selector. Do you have the mocks for that?

**Comment by ericronne** [comment]
#796 ?
