### ISSUE TITLE
Content: Explore data > Production

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#863]
Add Production text to `explore` section (p. 68-69, Exec Summary)
- [x] All lands and waters explore/all-lands-production/
- [x] Federal lands and waters explore/federal-production/

**Comment by nicoleslaw** [comment]
Note to self: https://github.com/18F/doi-extractives-data/wiki/Data-Types

**Comment by nicoleslaw** [comment]
@meiqimichelle We talked about me [adding this content](https://federalist.18f.gov/preview/18F/doi-extractives-data/explore-production-copy/explore/all-lands-production/), but the [Data Types](https://github.com/18F/doi-extractives-data/wiki/Data-Types) doc says we have 2004–2013 data, not just 2013 like the report. Should I do a pr on this until @shawnbot gets the data up, or did I misinterpret what we talked about?

We seem to be set on federal production.

**Comment by meiqimichelle** [comment]
Talked to @nicoleslaw . Since we have more years of this data in interactive form, we probably don't need this table/info on the site. Review once all current data interactions are live.
