### ISSUE TITLE
Visual design: Home > 'how it works' intro box

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#866]
The bit on the right needs to be finalized. We will not likely have time for animation.
![screenshot 2015-11-23 11 24 57](https://cloud.githubusercontent.com/assets/4827522/11345537/f76e6eb0-91d4-11e5-8fc8-9e20e54021f7.png)

**Comment by ericronne** [comment]
Already implemented, we just need to debug the alignment. Will note in another issue if need be.

![image](https://cloud.githubusercontent.com/assets/9259185/11541318/4cdcdc8c-98f7-11e5-975e-f727da88d4a3.png)
