### ISSUE TITLE
Visual Bug: Lato light appears too light on Safari

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#875]
I think @msecret may have dealt with this issue on Peace Corps.

Also may be light on other browsers, but i only tested on safari. (Fine on chrome)

**Comment by ericronne** [comment]
after googling, fyi...
http://stackoverflow.com/questions/21278020/font-weight-turns-lighter-on-mac-safari

**Comment by gemfarmer** [comment]
or http://stackoverflow.com/questions/15413969/lato-font-rendering-odd-in-safari-not-in-chrome-or-firefox

**Comment by msecret** [comment]
See you're using Lato again huh @ericronne? Is it like the new Helvetica for you? 

I think I played around with `-webkit-font-smoothing`. I also think I ensured we were downloading the write font weight from Google fonts and then playing around with `font-weight` values from 100 to 900 in increments of 100.

**Comment by ericronne** [comment]
@gemfarmer any progress on this sucker? Interesting: when i copy some light-weight text from the site and paste it into sketch, it pastes as Lato Hairline.

**Comment by meiqimichelle** [comment]
@ericronne this one isn't in this sprint so no progress. We shall get there :)

**Comment by meiqimichelle** [comment]
@ericronne I implemented a fix for this. Can you review and see if things look better to you? @coreycaitlin can you check as well? I know you were having trouble reading the long content because our text was too light. See if things are better now, or if it can use more adjustment still.

**Comment by ericronne** [comment]
It's better, but a little fuzzy (left is safari, right is chrome). Ok for now?
![image](https://cloud.githubusercontent.com/assets/9259185/11600131/513d3296-9a90-11e5-9d68-01f899d380e9.png)

**Comment by ericronne** [comment]
Let's take another look, shall we?

**Comment by gemfarmer** [comment]
@ericronne what is the status of this?

**Comment by ericronne** [comment]
If we feel safari is worth supporting, we should keep this open. #2294 shows one option (Roboto), but the change is pretty stark. Kind of heavy. So, for now … i think we keep this open and see whether time allows further investigation.
