### ISSUE TITLE
Content: Reconciliation results

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#876]
Add reconciliation results (p. 7-8 from Executive Summary Reporting and Reconciliation .doc)

**Comment by coreycaitlin** [comment]
See updated content in drive (> Content > Executive Summary).

**Comment by nicoleslaw** [comment]
(Not sure where this goes. We originally mapped it under the report page under About.)

**Comment by meiqimichelle** [comment]
This can go here: /explore/company-reported-federal-revenue/

(and maybe we change the url one more time and just call it reconciliation) (I give up)

Note the new intro to this page on the explore data landing page:
`As a part of USEITI, companies report payments to government (taxes, royalties, etc) and the government reports what it has received. These two sets of figures are compiled and reconciled by an independent administrator and published. In the future, this dataset will be interactive. For now, learn about the 2015 USEITI reconciliation process and download the dataset →`

(Of course, edit as you see fit -- hopefully this gets closer to the gist, and why this content might work well on that page)
