### ISSUE TITLE
Content: Documentation > Reconciliation

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#877]
Add reconciliation info (p. 1-7 from Executive Summary Reporting and Reconciliation .docx)
- [x] What is the scope of the revenue payment data reconciliation?
- [x] How did the Independent Administrator perform the reconciliation?

**Comment by coreycaitlin** [comment]
Okay to close this out, or do we want to pretty up the tables this week?

**Comment by meiqimichelle** [comment]
The content it there, so close! I think there's another issue for making tables across the site better.
