### ISSUE TITLE
Conduct accessibility/508 audit

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#888]
- [x] Img alt tags
- [ ] `<h>` order
- [ ] is everything tab-able
- [x] confirm form HTML
- [x] confirm method for `title` on buttons (accordions)

See #1296 for more.

**Comment by meiqimichelle** [comment]
For accordions:

title +

on the button
`aria-controls='id_of_panel_being_controled`
`expanded='true/false`
`role='tab'`

on the panel
`role='tabpanel'`
`aria-labeledby='id_of_control'`
`aria-hidden='true/false'`

Heres an example. http://www.oaa-accessibility.org/examplep/accordian1/

**Comment by gemfarmer** [comment]
Closed in favor of #1342
