### ISSUE TITLE
Record of 'meaty bits' from data

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#891]
This is where we can keep track of and discuss the bits of each dataset that we think are meaty and interesting, and could be pulled out to the the homepage (and other data summary areas). This initial list was made in cooperation with @mentastc .

## Production
* All-lands: _TODO_ Perhaps pull out a blip in the data, once we have it. Like, did the Dakota boom could a sharp increase in oil/gas production over a few years?
* Federal lands: Federal versus non-federal production. Initial map that loads on that page that shows where production is happening.

## Revenue
* by location: chart of top states
* by company: chart of top companies
* reconciliation: _TODO_ Perhaps reconciliation results graphic datapoints. Graphic is on Drive: EITI > Content > Exec Summary > Exec summary and....docx > page 7
* tax: pull out one line of the table on that page?
* disbursement: there are many interesting things in this data. Perhaps: the fact that there are various funds that get money; some of the things that funds (parks, history); the differrence between what gets disbursed and what gets appropriated.

## Economic impact
* GDP: top states in count versus percent
* Jobs: top states in count versus percent
* Exports: part of the summary chart

**Comment by usEITI** [comment]
don't you have the production data?

On Wed, Nov 25, 2015 at 2:48 PM, Michelle Hertzfeld <
notifications@github.com> wrote:

> This is where we can keep track of and discuss the bits of each dataset
> that we think are meaty and interesting, and could be pulled out to the the
> homepage (and other data summary areas). This initial list was made in
> cooperation with @mentastc <https://github.com/mentastc> .
> Production
>
>    - All-lands: *TODO* Perhaps pull out a blip in the data, once we have
>    it. Like, did the Dakota boom could a sharp increase in oil/gas production
>    over a few years?
>    - Federal lands: Federal versus non-federal production. Initial map
>    that loads on that page that shows where production is happening.
>
> Revenue
>
>    - by location: chart of top states
>    - by company: chart of top companies
>    - reconciliation: *TODO* Perhaps reconciliation results graphic
>    datapoints. Graphic is on Drive: EITI > Content > Exec Summary > Exec
>    summary and....docx > page 7
>    - tax: pull out one line of the table on that page?
>    - disbursement: there are many interesting things in this data.
>    Perhaps: the fact that there are various funds that get money; some of the
>    things that funds (parks, history); the differrence between what gets
>    disbursed and what gets appropriated.
>
> Economic impact
>
>    - GDP: top states in count versus percent
>    - Jobs: top states in count versus percent
>    - Exports: part of the summary chart
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/891>.
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by meiqimichelle** [comment]
@usEITI I'm not sure I understand your question. This issue is to track what info point in the data we might pull out to get people interested. We have the production data, we just haven't decided what the little info bit might be.

**Comment by meiqimichelle** [comment]
OBE - Corey has this in her work in other issues.
