### ISSUE TITLE
Content: Evaluate / add sidebars

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#905]
### Add these
- [x] p.24 crosslink to state laws and regulations
- [x] p.46 revenue sidebars
- [x] p.73 annual average of solar/wind/etc. jobs
- [x] p.75 soc definition
- [x] p.83 foia list

### Evaluate these
- [x] ~~p.7 data sets~~
- [x] p.8 public comments
- [x] ~~p.14 U.S. Energy Mapping System~~
- [x] ~~p.16 Addition info about shale gas link~~
- [x] ~~p.22 definition, unnecessary with our clearer glossary terms?~~
- [x] ~~p.33 osage legislation link~~
- [ ] p.41 coal lease sales info and GAO report
- [x] p.50 payment claims
- [x] p.67 GDP definition --> glossary
- [x] p.68 definitions, repetitive with the rest of the site?
- [ ] p.69 links to DOI and OSMRE data, should this be included?
- [x] ~~p.72 classifications, extraneous?~~
- [ ] p.74 bea schedule c info
- [x] ~~p.80 revenue sidebar~~
- [x] ~~p.81 colorado sidebar~~

**Comment by nicoleslaw** [comment]
@meiqimichelle I incorporated the sidebars that made sense and fit well into the text, either as added paragraphs or links, or terms in the glossary. (I did quite a few of these as I went through migrating the content, but added a few more just now.)

There are several on the second list above that I am not sure about (some may be covered by data documentation, and several seem to be extraneous based on the site content). Worth discussing, or should I leave that up to you?

**Comment by nicoleslaw** [comment]
@coreycaitlin In a later sprint, will you follow up with @Isabelle1512 on this?

**Comment by coreycaitlin** [comment]
:zap:

**Comment by coreycaitlin** [comment]
Almost there! A few things to chat about Monday.

**Comment by meiqimichelle** [comment]
So close!

**Comment by meiqimichelle** [comment]
I think @coreycaitlin you said that you were going to make separate issues for the remaining sidebars because they didn't fit neatly anywhere on the site. Can this original issue be closed then?

**Comment by coreycaitlin** [comment]
Yes! I'll create those issues and close this out today.
