### ISSUE TITLE
Content: Glossary links

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#908]
Add glossary links to pages:

- [x] Homepage
- [x] About USEITI
- [x] How it works section
- [x] Explore data pages
- [x] Case studies

(May need to split this into more issues later.)

@gemfarmer: is the HTML around "renewable energy" on the homepage a good template for all glossary references?

**Comment by gemfarmer** [comment]
@coreycaitlin yes that is a good example. `class="term-p"` also accomplishes the same thing, but formats differently and is going to generally be better in paragraphs. Just make sure that the `data-term` attribute matches the term you are looking to reference in `_data/terms.yml`.

**Comment by gemfarmer** [comment]
For quick reference: `<span class="term" data-term="renewable energy" title="Click to define" tabindex="0">renewable energy<i class="icon-book"></i></span>`

**Comment by coreycaitlin** [comment]
:100: I'll start adding them, and check back as I hit questions!

**Comment by gemfarmer** [comment]
:cool:

**Comment by coreycaitlin** [comment]
General notes for how/where I'm going to add glossary links:

- for unusual terms (or unusual usage) with only a few mentions, I'll add to all
- I'm going to be more liberal about definitions in "How it works" and other overview sections
- **not** going to add glossary links to every mention of every term in the glossary

**Comment by gemfarmer** [comment]
Federal Production and All Lands production have some units that should be defined for a variety of products.
* tons (also short tons)
* barrels (any certain number of barrels e.g. bbl, thousand barrels could fall under this)
* cubic feet (will be either Mcf or MMcf. thousand and million, respectively)
* kilowatt hours
* gallons (any variation on)? too basic?
* pounds? too basics?
* tickets (to measure quartz crystal)

**Comment by coreycaitlin** [comment]
More words to add:

- [ ] Independent Administrator (should be able to pull from Exec Summ)

**Comment by coreycaitlin** [comment]
Moved new terms lists to #1127 so I can close this out.

**Comment by meiqimichelle** [comment]
Closed with #1126 and remaining issues moved to #1127
