### ISSUE TITLE
Visual Bug: Bread crumb formatting consistency

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#914]
Breadcrumbs should follow the general format used on this page re font, color, leading, etc. (gray, light font, no extra space below it) ...

https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/state-legal-fiscal-info/

NOTE: if it's quick, could we use a lighter gray for the slashes?

One page in need or reformatting, eg...
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/state-legal-fiscal-info/

thx!

**Comment by gemfarmer** [comment]
@ericronne It shouldn't be very costly to make the slashes a lighter gray. 
Which gray? 
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/styleguide/section-colors.html

**Comment by ericronne** [comment]
oooh ... mid-gray?

**Comment by gemfarmer** [comment]
@meiqimichelle got this. closing
