### ISSUE TITLE
Visual bugs: Mobile global nav

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#916]
- [ ] Mobile nav should appear when viewing on mobile, doesn't show when i viewed on iphone 6. Does appear when i resize the window on desktop.

##Collapsed##
![image](https://cloud.githubusercontent.com/assets/9259185/11475023/ca1e92ca-9740-11e5-99ac-96fa99b28c6d.png)
 - [x] Logo should be about 75 px wide
 - [x] Hamburger should be: 30 px w, 3 px thick rules, 4 px space between (aligned with the top of the logo like you have is good)

##Expanded##
**Typography**
Can we match this sizing?
![image](https://cloud.githubusercontent.com/assets/9259185/11475591/cf3698f4-9743-11e5-988d-886fbb02c9ab.png)

**Other**
![image](https://cloud.githubusercontent.com/assets/9259185/11475665/1cfdaa96-9744-11e5-852a-2352b2233e47.png)
 - [x] Match the X size/weight more closely if possible (bigger/thin)
 - [x] Add search icon (lmk if you need)
 - [x] Use lighter gray for help text (match glossary)
 - [x] We may not need to bother with a “you are here” underline @meiqimichelle ?

**Comment by ericronne** [comment]
Also the panel seems to extend too far into the window, leaving a wide, blank strip of vertical space ...
![image](https://cloud.githubusercontent.com/assets/9259185/11484275/cb1d1f2a-9772-11e5-82ae-9efc6dba6013.png)

**Comment by gemfarmer** [comment]
All of these changes seem reasonable and small.

**Comment by gemfarmer** [comment]
After looking at this a little closer 75px for the logo seems quite small for many of the screen sizes. Do you want it to increase in size at breakpoints, or as a % of screen width? @ericronne

**Comment by gemfarmer** [comment]
Also, I'm not able to reproduce the white vertical space bug. What browser and screen sizes were you at while experiencing that?

**Comment by ericronne** [comment]
Whoops 75 was a typo, the logo should be about 195 px wide on mobile, sry...
![image](https://cloud.githubusercontent.com/assets/9259185/11506940/685f72e8-9817-11e5-9d28-0a4860fbacf8.png)

**Comment by ericronne** [comment]
Right-side spacing bug, in Chrome and Safari (the only two browsers i checked) ...
![image](https://cloud.githubusercontent.com/assets/9259185/11507121/28bbd28e-9818-11e5-9677-bdff29ab57ed.png)

**Comment by gemfarmer** [comment]
I'm sorry to do this to you, @ericronne, but I'm not seeing it in Chrome, Safari, or Firefox. I suggest we skip it for now. And resubmit if we are seeing it again.

**Comment by ericronne** [comment]
Split out the menu-gap problem into its own issue—#938, to deal with as time permits.

**Comment by ericronne** [comment]
Try this for the burger icon ...
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaZXZkbTdac1NGakU/view?usp=sharing

**Comment by gemfarmer** [comment]
@ericronne I'm merging this. The two outstanding bugs are in #938, and a more general bug for the site not displaying properly on mobile #949
