### ISSUE TITLE
Content: Revisit homepage content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#951]
- [x] Draft/revise content for top area of the homepage
- [x] Draft content for "Explore Data" section of the homepage

**Comment by coreycaitlin** [comment]
![screen shot 2015-12-07 at 4 36 00 pm](https://cloud.githubusercontent.com/assets/1450354/11644405/9f245c60-9d00-11e5-8813-be6441c14270.png)

Possible content to discuss.

**Comment by coreycaitlin** [comment]
Next step here is building out the "Explore Data" section; as soon as that's editable, I'll come up with some content.

**Comment by meiqimichelle** [comment]
'Tis editable now! There are a few bugs left with the tabs, but the sections are all there for you to edit :dancer:
