### ISSUE TITLE
Visual Design Redux: Adjustments to explore data landing

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#956]
Making a new issue to avoid clutter/confusion. @meiqimichelle @gemfarmer 
Tweaked design with charts removed and vertical spacing adjusted....
![explore - landing - no charts](https://cloud.githubusercontent.com/assets/9259185/11541201/99829c30-98f6-11e5-9a46-2de2cb2232fd.png)

**Comment by ericronne** [comment]
And let's flop the order of production and revenue, like so ...

![explore - landing - no charts](https://cloud.githubusercontent.com/assets/9259185/11542539/7d51fa86-98fd-11e5-8b08-7b5fc0dc1bf3.png)

**Comment by ericronne** [comment]
I've added 10 pixels of vertical space between subsections, for the sake of consistency with the how it works landing page (#957, where the graphics made it necessary imo).

![explore - landing - no charts](https://cloud.githubusercontent.com/assets/9259185/11543641/7167b3b8-9903-11e5-9228-4e0a82e02814.png)

**Comment by meiqimichelle** [comment]
Ready for review here: https://federalist.18f.gov/preview/18F/doi-extractives-data/fix-diving-preview-imgs/explore/

**Comment by ericronne** [comment]
YAY!!!! thx
