### ISSUE TITLE
Visual Design Redux: Adjustments to how it works landing

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#957]
@meiqimichelle @gemfarmer
Tweaked design with charts removed and vertical spacing adjusted (similar to changes noted in #956) ....
![how it works - landing - no charts](https://cloud.githubusercontent.com/assets/9259185/11543757/0e6cf6a0-9904-11e5-9106-a49513ee5819.png)

**Comment by meiqimichelle** [comment]
Ready for review here: https://federalist.18f.gov/preview/18F/doi-extractives-data/fix-diving-preview-imgs/how-it-works/

**Comment by meiqimichelle** [comment]
Done.
