### ISSUE TITLE
Content: Edit downloads page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#960]
Edit and clarify 'Downloads' content.

**Comment by coreycaitlin** [comment]
@meiqimichelle You've been tackling this — do you want me to take another pass through this page?

**Comment by meiqimichelle** [comment]
@coreycaitlin Up to you!

**Comment by coreycaitlin** [comment]
Closing this out — will create a new issue if user research/feedback indicates we should revisit this page.
