### ISSUE TITLE
Explore > Federal Production: product count in selector doesn't match totals below

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#961]
Right now, we have 28 product choices on the federal production interaction. This is not wholly accurate, as Geothermal is really one product with several sub-choices.

![screenshot 2015-12-03 09 29 57](https://cloud.githubusercontent.com/assets/4827522/11566625/70afb61c-99a0-11e5-9a0f-d8e8f02530f4.png)

Change the total number of products to 21, with Geothermal as a category and the various options underneath:

Geothermal
-- Direct Use, Millions of Gallons
-- Direct Utilization, Hundreds of Gallons
-- etc ...

/cc @mentastc

**Comment by gemfarmer** [comment]
This would also need to be implemented on All Lands Production

**Comment by meiqimichelle** [comment]
Also, I noticed that we are already doing this for product totals in the table because we already get a total of 21 with no filters applied there. Looks like:

![screenshot 2015-12-04 11 44 39](https://cloud.githubusercontent.com/assets/4827522/11598010/85ba6fde-9a7c-11e5-830f-bdeb62361a8c.png)

**Comment by meiqimichelle** [comment]
Overtaken by events. We've completely restructured the way the explore data section looks and works.
