### ISSUE TITLE
Content: Data documentation

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#967]
- [x] stub out pages for documentation to live on
- [x] Federal lands and waters docs
- [x] Federal revenue by location docs
- [x] Federal revenue by company docs
- [x] Reconciliation docs (see issue #877)
- [x] Disbursements docs

**Comment by coreycaitlin** [comment]
@meiqimichelle: When do we expect to get the documentation for Federal revenue by location?

**Comment by meiqimichelle** [comment]
It is here! https://useiti.doi.gov/documentation/#location
Just needs to be moved over, and I want to double-triple check that everything is still accurate.

**Comment by coreycaitlin** [comment]
Anything need another pass here, @meiqimichelle?
