### ISSUE TITLE
Visual design: charts/images for How it works pages

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#971]
These are the charts/images we need for the `how it works` section

## Production
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/production/

Global rank table. This is on page 6 of the [final pdf report](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/about/report/)
![screenshot 2015-12-03 19 35 41](https://cloud.githubusercontent.com/assets/4827522/11580488/29967702-99f5-11e5-8e27-4a8b904a8f30.png)

## Revenues
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/revenues/

Huge revenues chart -- perhaps should mostly be HTML. This is on page 46 of the [final pdf report](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/about/report/)
![screenshot 2015-12-03 19 38 30](https://cloud.githubusercontent.com/assets/4827522/11580528/7bf2044e-99f5-11e5-82d8-3b2eb9001fc9.png)

Federal budget process
![screenshot 2015-12-03 19 41 25](https://cloud.githubusercontent.com/assets/4827522/11580562/df1536e0-99f5-11e5-8cd7-1f85dd993cf9.png)

## States
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/state-laws-and-regulations/

Map of 18 prioritized states. This is on page 56 of the [final pdf report](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/about/report/)
![screenshot 2015-12-03 19 46 32](https://cloud.githubusercontent.com/assets/4827522/11580634/96815b2e-99f6-11e5-935f-e39ef8595ae6.png)

**Comment by ericronne** [comment]
Here's a tweaked design for global rank, lmk if you want the sketch file...
![natural resources ranking chart](https://cloud.githubusercontent.com/assets/9259185/11642047/6ee709ac-9d01-11e5-9114-737a28b6fa83.png)

**Comment by ericronne** [comment]
Tweaked rank chart, final!(?)

![natural resources ranking chart final](https://cloud.githubusercontent.com/assets/9259185/11691062/01045c82-9e5f-11e5-87d6-e95e2640cdd4.png)

**Comment by ericronne** [comment]
@meiqimichelle here is a [png of the ranking chart] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaa085UkZRV3Y1QVU/view?usp=sharing)

**Comment by ericronne** [comment]
@meiqimichelle here's the [revenue streams chart png] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaQ2tUS1hnSlVOcUE/view?usp=sharing).
![revenue streams chart](https://cloud.githubusercontent.com/assets/9259185/11695729/58a6729c-9e76-11e5-9b25-82c6415853aa.png)

**Comment by ericronne** [comment]
@meiqimichelle if you like this, lmk how you want the art. Guessing individual pngs, so you can set the text in html. But i'd love to preserve the vertical spacing here, if possible :)

![federal budget process](https://cloud.githubusercontent.com/assets/9259185/11697621/031a6612-9e80-11e5-8b7d-af84edf5292b.png)

**Comment by meiqimichelle** [comment]
@ericronne how about creating separate pngs, as well as an overall png -- I'll drop in the overall png for now, and then loop back and create the text separately as time allows. Either way, we can preserve the spacing :)

**Comment by ericronne** [comment]
[Bill stack pngs] (https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaamJINktLUXBFRFU&usp=sharing)

Close-able issue???

**Comment by ericronne** [comment]
@meiqimichelle ^^

**Comment by meiqimichelle** [comment]
Yep! I've got a PR in progress, closing. :tada:
