### ISSUE TITLE
Visual design: images for about page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#972]
These are the charts/images we need for the `about` section

These images were originally from the [international EITI site](eiti.org), tho I can't find them there now :(

These images will go here:
https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/about/

## MSG
`To increase transparency and accountability, the EITI relies on a cross-sector partnership between government (agencies that oversee extraction in the U.S.), industry (companies operating in the extractive industries), and civil society (individuals and organizations that represent community and citizen interests). Together, all three sectors make up the Multi-stakeholder Group (MSG) responsible for overseeing the EITI.`
![screenshot 2015-12-03 19 50 24](https://cloud.githubusercontent.com/assets/4827522/11580697/20c9cdca-99f7-11e5-9157-9ece5fc1bed2.png)

## EITI Report process

`Government, industry, and civil society collaborate in a disclosure process regarding natural resource revenue, called reconciliation. Government and industry share with the IA the total amount of revenue the government received and industry paid in the year under review. The IA reconciles the reported revenue and investigates any discrepancies. The public can see the results for their respective country in an annual report, which includes a contextual narrative of the country’s legal and fiscal regime. `
![screenshot 2015-12-03 19 52 49](https://cloud.githubusercontent.com/assets/4827522/11580724/71b2942e-99f7-11e5-9861-06ac86df1d12.png)

**Comment by ericronne** [comment]
Did someone page @rtwell ?????

**Comment by rtwell** [comment]
durp!

**Comment by ericronne** [comment]
## WIP Color Palette ##

![color palette - wip](https://cloud.githubusercontent.com/assets/9259185/11639692/ee12963c-9cf3-11e5-9c9f-6143b8091758.png)

**Comment by ericronne** [comment]
Some visual reference...
![image](https://cloud.githubusercontent.com/assets/9259185/11639732/289e3b3a-9cf4-11e5-9e67-a3ee1f12644e.png)

**Comment by rtwell** [comment]
Hellos! 
**Multi-Stakeholder Group + EITI Report process illustrations updated.**
I might suggest re-thinking these 2 illustrations and combining them into 1 _**process**_ illustration. As they are, they are only defining the parties involved, although not all of them—the IA and Validator are excluded. One single illustration could demonstrate both parties _and_ process. Just my 2¢.

![whos_involved](https://cloud.githubusercontent.com/assets/12564977/11691443/8a93769e-9e60-11e5-96c7-0db6f27a7bb7.png)

**Comment by meiqimichelle** [comment]
@rtwell Let's see. You are right that these separate illustrations don't show the entire process.

Right now we have, 
- one illustration that describes the MSG
- one illustration that attempts to describe the 'checking on the numbers' process

We could also have:
- An additional illustration that describes the output of the two above == 'EITI report' with numbers and narrative

Perhaps the microcopy can be adjusted, or a third illustration, or a combo illustration to get at this. Thoughts? Does this make sense?

Or we call it done for now and improve on it later :)

**Comment by rtwell** [comment]
@meiqimichelle I'm not sure what kind of time you / I have available right now, so I'd lean towards the later.
Once we do improve, the illustration should have parity with its narrative for clear communication. The current microcopy describes a process so it would be helpful if the illustration demonstrated the process in a follow-the-money approach, introducing parties involved along the way to becoming a EITI Report.

**Comment by meiqimichelle** [comment]
Ok, sounds good! We have a lot to finish up this week, and what you have here is already much better than what was there before. Which means #winning :) Care to drop your artwork in our share drive [here](https://drive.google.com/drive/folders/0BwWYNZcEDfwaRzAtT3ZtaC1VVk0) ? Folder them however you like.

**Comment by ericronne** [comment]
@meiqimichelle lmk if you need me to svg-ize

**Comment by meiqimichelle** [comment]
Perfect, thank you @rtwell ! :tada: :smile_cat:

**Comment by meiqimichelle** [comment]
This will be live when #1035 merges. We will still nead some refinements to padding and mobile placement, but the visual task is complete. Thank you @rtwell !! Closing.
