### ISSUE TITLE
'Share your feedback' button in footer needs href

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#975]
Add link to Ethnio when it arrives. 

<img width="350" alt="screen shot 2015-12-03 at 10 14 18 pm" src="https://cloud.githubusercontent.com/assets/4803473/11581765/3e37a1a2-9a0b-11e5-9531-d43e0c654fd9.png">

**Comment by meiqimichelle** [comment]
This will be a link to Ethnio, not Github issues. Its not there yet because Ethnio isn't quite setup yet (soon!).

**Comment by gemfarmer** [comment]
Got it!

**Comment by meiqimichelle** [comment]
Closing in favor of #755 . This is now a task on that issue.
