### ISSUE TITLE
Bug: Explore map description displaying poorly in certain instances

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#976]
Spillover from #966.

As @meiqimichelle mentioned, this could be fixed by making the background white when the filters are hidden.
If not, we will probably need to move the description content into the filter block itself.
![](https://cloud.githubusercontent.com/assets/113896/11577680/71a854d2-99d4-11e5-801f-b482db55a2ce.png)

**Comment by meiqimichelle** [comment]
Thank you for issuing! Yeah, your suggestion #2 is probably the way to go (the way I have is suuuuper brittle if the # of lines of text changes) but I didn't know how to make something inside the filter wrapper not show/hide along with the rest.

**Comment by meiqimichelle** [comment]
Done with #985
