### ISSUE TITLE
Explore > Revenue by Company: show total in revenue type chart

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#991]
There should be a 'total' line in the revenue type chart. Quick link to updated description [in this comment](https://github.com/18F/doi-extractives-data/issues/991#issuecomment-234407503) ...after all the GitTracks of us not doing this 😁

**Comment by gemfarmer** [comment]
A bar for "Total" needs to be added to this chart on the [explore/federal-revenue-by-company](https://useiti.doi.gov/explore/federal-revenue-by-company/2015/) page

<img width="698" alt="screen shot 2016-07-21 at 5 47 23 pm" src="https://cloud.githubusercontent.com/assets/4803473/17041362/43bb9b54-4f6b-11e6-8a8e-012c161602b2.png">

**Comment by ericronne** [comment]
Moot, @meiqimichelle?

**Comment by meiqimichelle** [comment]
Moot.
