### ISSUE TITLE
Explore > all-lands production. Break out coal by county?

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#993]
We could display coal by county because we have that level of data. However, none of the other commodities from EIA are available at that level. Should we show the one commodity (coal) at more detail?

/cc @mentastc 

* from ONRR feedback

**Comment by meiqimichelle** [comment]
@gemfarmer What do you think about this one? I don't remember if we actively decided not to do counties for coal for this iteration (we may have, since none of the others have it). Remind me?

**Comment by gemfarmer** [comment]
From slack conversation with Michelle for visibility:
'I recall reading/hearing that we should exclude coal county data because it was the only one, but I’m not finding any evidence of that being communicated'

**Comment by meiqimichelle** [comment]
This will be done when #1036 merges.
