### ISSUE TITLE
Explore > Revenues by company: revenue types need adjustment

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#994]
For the “Federal revenue by company” filter box, Civil Penalties is listed twice since you don’t differentiate between who they were paid to.  The “Civil Penalties including Late Charges” were paid to OSMRE while the other “Civil Penalties” were paid to ONRR. You may want to consider naming the Revenue Types exactly how they are shown in the downloadable dataset as they show ONRR, ONRR/BLM, BLM, and OSMRE.

/cc @mentastc 

* From ONRR feedback

**Comment by meiqimichelle** [comment]
Chris -- can we combine the civil penalties into one category?

**Comment by mentastc** [comment]
No I would like that we add the agency

**Comment by meiqimichelle** [comment]
@mentastc Can you send me updated words for the data dictionary on our documentation page? We only have one civil penalties category listed [here](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/downloads/federal-revenue-by-company/).

**Comment by meiqimichelle** [comment]
Note to self: change the data line in input data, and send to @shawnbot for reload when its ready.

**Comment by meiqimichelle** [comment]
Ok! I've made a version of this data with agencies added for the two confusing civil penalties lines. @mentastc, in the long term if we want to add agency names back to all of them we should change how the line is written in the dataset overall, but I didn't want to get into that now.

@shawnbot there's a google sheets version of the data [here](https://docs.google.com/spreadsheets/d/1KtjW-i0S_2cdyJFTgrup_G2P67OCpZQOokn1KIwvJWI/edit#gid=4300028), which is in [this drive folder](https://drive.google.com/drive/folders/0B2CjDILjK8_jaWthalAzeXZvRWM) with its original excel if that's better for you. Reload away!
