### ISSUE TITLE
Content: Edit Explore Data pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#997]
Edit data viz content for usability and to respond to feedback. @meiqimichelle, pls add specifics here, or I can make notes when we talk!

Pages that need attention to summaries, titles, and microcopy:

- [x] Federal revenue by location
- [x] Federal revenue by company
- [x] Reconciliation
- [x] Corporate income tax
- [x] Disbursements
- [x] All lands and waters
- [x] Federal lands and waters
- [x] Gross Domestic Product
- [x] Exports
- [x] Jobs

**Comment by coreycaitlin** [comment]
For /explore-data/federal-revenue-by-location/, if you click into a state, often the whole state is gray if we don't have county-level info, which is confusing (see Alabama Coal). Do we want to fix this interaction, or try to write some content explaining?

**Comment by coreycaitlin** [comment]
^^ I added a brief line of copy to help clarify that for now, and issue #1021 to discuss further if need be.

Other questions/notes for @meiqimichelle:

- All land production uses the word "products" instead of "commodities" — is this intentional, and do we want to consider standardizing to one or the other?
- We should take another look at the info hierarchy for the bar graphs — do we have another issue for this already?

<img width="660" alt="screen shot 2015-12-08 at 8 56 35 pm" src="https://cloud.githubusercontent.com/assets/1450354/11677784/720352da-9df6-11e5-9d58-b5976c65198e.png">

**Comment by coreycaitlin** [comment]
First pass on several of the pages is done — I'm going to need to come back and take another look at those summary-fact paragraphs, as I can't get the math to work right now, and need a bit more time with it.

**Comment by meiqimichelle** [comment]
I believe this is closed with #1102.
