### ISSUE TITLE
Replace Diving Graphic images

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#998]
The diving graphic backgrounds need to be replaced with gray images.

**Comment by gemfarmer** [comment]
@ericronne per our slack conversation, if the only difference in all the graphics is a color change in the top image, I think the easiest approach would be grabbing the top graphic and modifying it directly so that the dimensions stay the same(edited)

e.g. Coal – https://github.com/18F/doi-extractives-data/blob/dev/img/how-it-works/coal-top.png


If that isn’t the case, then I guess I could give the ‘full’ new image the same treatment as I did before.

**Comment by meiqimichelle** [comment]
@ericronne Here's the folder with all the pngs for that section. The ones Brian is talking about are all called 'blah-top'.

**Comment by ericronne** [comment]
New PNGs are [here for downloading] (https://drive.google.com/a/gsa.gov/folderview?id=0BwWYNZcEDfwaZ3QyZGdtUWgzTjQ&usp=sharing).

Note...
- I didn't make any changes to the renewables; i think they are already aok
- Some of the chopped-up pieces don't seem to match what i have. Were they stretched/otherwise changed, or is my art wrong? If they don't work, let's chat!

**Comment by ericronne** [comment]
Reference (no red!) ...
![coal-wide](https://cloud.githubusercontent.com/assets/9259185/11735862/1b5e99e8-9f8c-11e5-9705-3bcab905533a.png)

![minerals-wide](https://cloud.githubusercontent.com/assets/9259185/11735864/1b619a3a-9f8c-11e5-8124-f8755b474710.png)

![offshore-oil-wide](https://cloud.githubusercontent.com/assets/9259185/11735861/1b5e9d3a-9f8c-11e5-90a5-882a13db996f.png)

![onshore-oil-wide](https://cloud.githubusercontent.com/assets/9259185/11735863/1b6135b8-9f8c-11e5-831e-bc16f89f0a6e.png)

**Comment by gemfarmer** [comment]
@meiqimichelle reference https://github.com/18F/doi-extractives-data/issues/998#issuecomment-162632622

**Comment by gemfarmer** [comment]
These are the images that need to be modified. I'm guessing that cropping those images to match the dimensions and scale should work
 https://github.com/18F/doi-extractives-data/blob/dev/img/how-it-works/coal-top.png
